### ISSUE TITLE
Table auto formatting does not work properly when "|" exists in content

### ISSUE THREAD

**Issue by windowdong11** [yzhang-gh/vscode-markdown#1000]
## Problem

![화면 기록 2021-08-19 오전 11 38 15](https://user-images.githubusercontent.com/16981721/129999509-de77bae2-ed6c-447f-a41c-f6dad4933bd5.gif)

When `|` exists, formatter expects it as separator.  
After formatting, it removes `|` at the end.  

## How to reproduce

Capture `|` except `\|`

## Configuration

Default

## Environment

version: 3.4.0
vscode: apple

**Comment by Lemmingh** [comment]
Thanks for the report.

Probably you would like to try the dev build.

This issue was discussed in
<https://github.com/yzhang-gh/vscode-markdown/issues/24#issuecomment-743995063>
