### ISSUE TITLE
Support auto-completion for markdown-links to headers

### ISSUE THREAD

**Issue by klausj1** [yzhang-gh/vscode-markdown#1002]
Hi,

it would be great if auto-completion for markdown-links would not only work for files, but also for headers in a file.

So e.g. test.md:
```
# Title 1

## 2

### tit 3

See [here](./test.md/#
```
Code completion after the '#' at the end would suggest #title-1, #2 and #tit-3

Or is this already working and I missed something?

Thanks,
Klaus

**Comment by Lemmingh** [comment]
Duplicate of #894?

**Comment by yzhang-gh** [comment]
Agree. Let's track this in #894.
