### ISSUE TITLE
Markdown All In One breaks Math block syntax highlighting

### ISSUE THREAD

**Issue by baohuynhlam** [yzhang-gh/vscode-markdown#1008]
## Problem

After I installed the "Markdown all in one" extension in VsCode, the enclosing highlighting of math block is not working correctly any more. Removing the extension and the highlighting works again, so I figured I would make an issue here.

![image](https://user-images.githubusercontent.com/55563202/132041860-ae3af4e3-e5fc-4c53-aaaa-0f98884e23f7.png)

As seen in the image, the "$$" signs at the end of the Math block is understood as something different. Therefore, subsequent markdown is not highlighted correctly, even though they are rendered correctly.

Other features of Markdown All in one still works, including Latex autocomplete/Intellisense inside the math block.

## Configuration

No other extension (such as Markdown+math) were installed. I tried turning off the "math.enabled" option, but it didn't resolve the issue. Assigning the value to `true` also did not resolve the issue.
```jsonc
"markdown.extension.math.enabled": false
```

## Environment

Lubuntu 20.04
Markdown all in one 3.4.0 (should be the newest version because I just installed it through VsCode Market 5 min ago)
VsCode 1.60.0

## Diagnostic data

There seems to be nothing in the Debug Console

**Comment by Lemmingh** [comment]
Conflict with VS Code's built-in **Markdown Math** (`vscode.markdown-math`) extension.

We both inject TM grammar for the same (at least similar) thing:
<https://github.com/microsoft/vscode/blob/4e37c907d238758879047c4218756ff5d99dae82/extensions/markdown-math/package.json#L33-L59>
<https://github.com/yzhang-gh/vscode-markdown/blob/f67fa7765c0044873ab70b7602a04f69e8de6637/package.json#L500-L519>

The merge result is unpredictable.

---

[`contributes.grammars`](https://code.visualstudio.com/api/references/contribution-points#contributes.grammars) is a ["declarative"](https://code.visualstudio.com/api/language-extensions/overview) thing in VS Code's world. The only way to remove it is disabling the corresponding extension.

I'm sorry that **you have to disable one of them**.

**Comment by yzhang-gh** [comment]
A tip about how to disable the `vscode-math`

> <img src="https://user-images.githubusercontent.com/7588612/125751139-a882fcf1-0fe6-4f04-85fc-aaabf0c3ad45.png" width="365" alt="disable markdown-math">
>
> https://github.com/yzhang-gh/vscode-markdown/issues/986#issuecomment-880481916

**Comment by baohuynhlam** [comment]
Thanks. Disabling the builtin Markdown Math (as shown by @yzhang-gh) did work. Now the math blocks gets separated correctly. I think this is something that should be stated in the documentation.

**Comment by Lemmingh** [comment]
<https://markdown-all-in-one.github.io/docs/guide/compatibility.html>
Done.

**Comment by YangLinzhuo** [comment]
Today I ran into this problem too. 
![image](https://user-images.githubusercontent.com/18740976/133927266-b51399bd-13e8-4568-a0a7-221cc9a50c9e.png)


The method here works fine but need to disable the builtin markdown-math plugin. I accidently find another solution. Here it is:

```
$$f(n) = \begin{cases}
0, & n = 0; \\
1, & n = 1; \\
f(n-1) + f(n-2), & n > 1
\end{cases}$$
```

just not add newline after open `$$` and before closing `$$`. Then highlight works fine.

![image](https://user-images.githubusercontent.com/18740976/133927247-b98aee94-445b-434a-90bf-3c78ffef5254.png)

While this method may looks ugly... Just for a record here.
Anyway, I will disable the builtin one.

**Comment by yfzhao20** [comment]
我觉着可以给出一个选项，单独关闭 markdown all in one 的数学高亮。两个插件的数学高亮还是有区别的，比如行内公式，markdown all in one 无法识别$号前有空格的情况：
![image](https://user-images.githubusercontent.com/80528249/136012861-1f9fc967-9514-4ff9-b577-ca33a04f6f0e.png)
而内置插件可以：
![image](https://user-images.githubusercontent.com/80528249/136012908-dbd73cc7-8027-48f8-8a69-3ff0b1488e99.png)

或者是调整一下识别行内公式的方法。

**Comment by Lemmingh** [comment]
> 单独关闭 Markdown All in One 的数学高亮

不可能单独关闭，文档已经解释了。

<https://github.com/yzhang-gh/vscode-markdown/issues/1008#issuecomment-912735309>

---

> 两个插件的数学高亮还是有区别的

我们用的语法其实不一样。

<https://github.com/yzhang-gh/vscode-markdown/issues/955#issuecomment-863985378>

---

> 调整一下识别行内公式的方法

我也想逃出 TextMate grammar 的框框。但现阶段很难。😢

<https://github.com/yzhang-gh/vscode-markdown/issues/846#issuecomment-922833544>

**Comment by Firestar-Reimu** [comment]
我也遇到相同的问题

我没有使用Markdown-math插件，这个是已经内置了吗？

`"markdown.extension.math.enabled": false` 是可以解决的，增加这一行后，所有的`$$`都不高亮了

**Comment by Lemmingh** [comment]
是的。这里讨论的 Markdown Math 就是 VS Code 内置的 [`vscode.markdown-math`](https://github.com/microsoft/vscode/tree/main/extensions/markdown-math)。

Yes. The "Markdown Math" in this thread refers to the VS Code's built-in [`vscode.markdown-math`](https://github.com/microsoft/vscode/tree/main/extensions/markdown-math).
