### ISSUE TITLE
在打开预览的情况下编辑 HTML block，编辑器会乱滚乱跳

### ISSUE THREAD

**Issue by abecd** [yzhang-gh/vscode-markdown#1013]
## Problem

在开头用html书写表格，在超出一页的地方为表格td添加内容时，编辑器会自动跳到头部但光标位置不变，经测试，只有当markdown文件和预览视图同时显示时才出现这种情况。

## How to reproduce

![bug](https://user-images.githubusercontent.com/37531408/133750487-2cd98697-f7b4-41c9-b5fa-a76f0b4e81a6.gif)

## Configuration

默认配置

## Environment

系统: win10
vscode: 1.60.1
插件: v3.4.0

**Comment by yzhang-gh** [comment]
请见 https://github.com/yzhang-gh/vscode-markdown/issues/961#issuecomment-856878088

**Comment by Lemmingh** [comment]
The problem here is **exactly** caused by VS Code's **source map** mechanism.

#961 involves other factors.

**Comment by abecd** [comment]
Thank you very much.  You can close this issue.

**Comment by Lemmingh** [comment]
可以讲汉语。我那会儿只是手头的机器没法打字。

---

VS Code 在 editor 和 preview 之间分段线性映射，实现 scroll sync。但是在一些情况下，锚点太稀疏，所以会出现跳很远的问题。

如果点足够多，可以改善到几行内的抖动。完全不抖恐怕有些难，毕竟 `scroll` event 太容易发生，而且运算的精度问题可能在反馈中被放大。
