### ISSUE TITLE
怎样修改预览窗口中的中文注释字体?

### ISSUE THREAD

**Issue by IsThereAnyNameUnused** [yzhang-gh/vscode-markdown#1014]
##Problem
![qvq1](https://user-images.githubusercontent.com/18085297/134460899-f8dd0cdf-793e-4193-a0a7-7f4baaac219b.png)
代码块中的意大利体中文非常难读, 请问能否修改?

**Comment by Lemmingh** [comment]
理论上可以加 CSS 来改，但我也不清楚你需要做什么。相关文档：

<https://github.com/highlightjs/highlight.js>

<https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css>

<https://code.visualstudio.com/api/extension-guides/webview#inspecting-and-debugging-webviews>

**Comment by Lemmingh** [comment]
另外，现在 preview 里的 `<code>` 继承 `editor.fontFamily` 设置（通过 CSS variable `--vscode-editor-font-family`）。所以，你也可以改 editor 的字体。

**Comment by IsThereAnyNameUnused** [comment]
就是简单的想取消斜体, 正常显示而已, 比如这种中文注释
![qvq2](https://user-images.githubusercontent.com/18085297/134476575-35facc0d-f063-45c7-89f0-ff43be8d2078.png)

**Comment by Lemmingh** [comment]
> 取消斜体

你需要在上面叠一层 CSS，覆盖掉 Highlight.js 的默认值。

```css
code * {
    font-style: normal !important;
}
```

---

比起这么折腾，恐怕换字体更省事。

Source Han Mono 思源等宽
<https://github.com/adobe-fonts/source-han-mono>

Sarasa Mono 等距更纱黑体
<https://github.com/be5invis/Sarasa-Gothic>

**Comment by IsThereAnyNameUnused** [comment]
谢谢大佬, 在回复指引下找到插件的位置 修改了这里:

![3](https://user-images.githubusercontent.com/18085297/134479956-5692e50f-06f7-4e89-a8d5-4171b959cd7d.png)

然后就正常显示了:

![4](https://user-images.githubusercontent.com/18085297/134479976-49fdbb1d-88dd-4781-a85c-d4d2bf61e77a.png)


这样修改也可以吧? 以后插件升级了这个位置会被覆盖掉吗

**Comment by Lemmingh** [comment]
> 会被覆盖掉吗

```
"C:\Program Files\Microsoft VS Code\resources\app\extensions\markdown-language-features\media\highlight.css"
```

这个？会。

VS Code 每次更新都会覆写整个安装目录。

**Comment by IsThereAnyNameUnused** [comment]
> VS Code 每次更新都会覆写整个安装目录。

这就麻烦了...我按你给的文档再琢磨琢磨吧, 不怎么会修改插件内的东西

非常感谢lol

**Comment by Lemmingh** [comment]
<https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css>

用 `markdown.styles` 来挂自定义 CSS。不过，由于 VS Code 的安全限制，你需要在每一个 workspace 里都设置一遍：放个 CSS 文件，并修改其 `settings.json`。

---

我看你最初说[伪斜 (artificial italic, synthetic italic) 的 SimSun 很辣眼](https://github.com/yzhang-gh/vscode-markdown/issues/1014#issue-1005046654)，所以[推荐换字体](https://github.com/yzhang-gh/vscode-markdown/issues/1014#issuecomment-925616357)。
