### ISSUE TITLE
Restrict key binding context to reduce Tab key conflict

### ISSUE THREAD

**Issue by OldStarchy** [yzhang-gh/vscode-markdown#1015]
## Proposal

Currently, both this extension and Markdown Table have keybindings for `tab`. The behaviour of each is not incompatible, but the keybinding for this extension is suppressing the one from Markdown Table.

The `tab` keybinding provided by the other extension allows easier navigation through tables, and should not conflict with the indentation helper provided by this extension. Is it possible to allow both keybindings to run, or is there a way to fallback to the Markdown Table's `markdowntable.nextCell` command if this extension's tab key would otherwise have no effect?

## References

An issue has already been raised https://github.com/takumisoft68/vscode-markdown-table/issues/18

**Comment by Lemmingh** [comment]
> fallback

Not possible for now.

VS Code sorts key bindings and dynamically chooses only one to dispatch.

If there were a fallback or hook mechanism, we probably wouldn't have to write so many ugly `when` clauses.

See:

* <https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts>

* <https://github.com/microsoft/vscode/issues/39888>

**Comment by veonua** [comment]
The extension hijacks tab so other extensions that use the tab to accept auto-complete/auto-correct would not run.

It is very annoying to see a completed/corrected version of a word or phrase but clicking tab just inserts spaces in a word.

**Comment by Lemmingh** [comment]
> use the tab to accept auto-complete/auto-correct

Do you mean "Inline Suggestion"?
#1011

**Comment by veonua** [comment]
yes, including CoPilot. But there are many spelling extensions and a tab is a popular keystroke to accept suggestions.

**Comment by Lemmingh** [comment]
> many spelling extensions

May I know which ones?

You can also follow [VS Code's guide](https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts) to trace the key binding resolution.

---

I'm a bit confused here. "Inline Suggestion" is still a proposed feature. VS Code and its partners can ship extensions that invoke proposed APIs, whilst others may call them only during debug.

**Comment by imthenachoman** [comment]
What exactly do these two do?

- `markdown.extension.onTabKey`
- `markdown.extension.onShiftTabKey`

Removing the keybinding for them fixes the issue but I'm unsure what that breaks with **Markdown All in One**.

I want to update it's default `when` condition so that **Markdown Table**'s `tab` still works in tables.

**Comment by imthenachoman** [comment]
Is there some `when` condition we can use to check if we are in a list? That way the `tab` will work for both extensions.

**Comment by imthenachoman** [comment]
Rock on. Thanks!

**Comment by yzhang-gh** [comment]
It has been available in the [pre-release version](https://code.visualstudio.com/updates/v1_63#_pre-release-extensions).
