### ISSUE TITLE
Markdown all in one recognizes the []() structure in the code block as a link

### ISSUE THREAD

**Issue by Longgererer** [yzhang-gh/vscode-markdown#1018]
## Problem

Markdown all in one recognizes the []() structure in the code block as a link.

## How to reproduce

Open VSCode and type below content in md file.

  
![1632884524(1)](https://user-images.githubusercontent.com/40834209/135195926-1292dd21-196f-4adf-a1d2-3405af70ee37.jpg)

You'll notice that the underline appears under "instance".

## Environment

windows10  VSCode v1.60.2

**Comment by yzhang-gh** [comment]
Can you check whether it still happens after you disable this extension?

**Comment by Longgererer** [comment]
Oh, it's my fault! It looks like a vscode problem.
