### ISSUE TITLE
LaTeX not autocompleting in between `$$ $$`

### ISSUE THREAD

**Issue by 0lelouch** [yzhang-gh/vscode-markdown#1028]
I added `"markdown.extension.math.enabled": false,` in the settings file since I am using Markdown + Math also. LaTeX not autocompleting as shown in the below video.

https://user-images.githubusercontent.com/92218586/138568693-a70b2ec6-f3be-4d76-8031-a49043a8ad11.mp4

**Comment by LittleYe233** [comment]
It reproduced suddenly on my computer - just a few minutes ago the auto completion for math blocks worked well. I don't know what causes this problem.

- OS: Manjaro
- VS Code: 1.68.0
- Extension: 3.4.3
