### ISSUE TITLE
行间 latex 导致后续高亮失效

### ISSUE THREAD

**Issue by Real-king-Ph** [yzhang-gh/vscode-markdown#1029]
## Problem

当插入行间 latex 后续所有的 markdown 高亮都失效了。

![image](https://user-images.githubusercontent.com/72426701/138706042-9219d171-a3b6-4462-b280-9052ef7ddfdf.png)

所有的配置都未经过改动，无任何其他有关 markdown 和 latex 插件

**Comment by Lemmingh** [comment]
> 是否可以支持一下呢

难。

API 迟早会有的。但是，我们目前采用 pandoc 风格，而 Jupyter Notebook 那一套无论是语法还是语义，差别很大。我都怀疑 VS Code 的 `markdown-math` 是否正确处理了所有边界情况。
