### ISSUE TITLE
关于使用该插件导致后面代码无法高亮

### ISSUE THREAD

**Issue by xjtusjtu** [yzhang-gh/vscode-markdown#1032]
插入行间公式之后，该公式后面的斜体、粗体、行内公式代码在编辑器全部无法高亮；该公式之前的斜体、粗体、行内公式正常高亮

![image](https://user-images.githubusercontent.com/57665402/140478834-b869d31e-2aa7-419e-91b1-0672f7485bad.png)

我尝试一些办法修正，发现
- 起始 `$$` 和 结束 `$$` 不换行，就可以正常高亮（如下面这张图）
- 关闭 markdown all in one 插件，可以正常高亮
- 不使用 `$$ $$`使用 ` ```math ``` `符号，可以正常高亮

上一张图片中的写法是我的常用写法，下面这张图片当中行间公式不换行看上去非常难受
![image](https://user-images.githubusercontent.com/57665402/140479287-25b08aed-deb9-4267-9b32-03fb81a76a38.png)

*ps*: 个人还装有 markdown preview enhanced 但应该不是该插件的问题

**Comment by yzhang-gh** [comment]
感谢反馈，请参考 #1008。

**Comment by xjtusjtu** [comment]
非常感谢！！！
