### ISSUE TITLE
crashing extenstions host

### ISSUE THREAD

**Issue by abodsakah** [yzhang-gh/vscode-markdown#1033]
Issue Type: <b>Bug</b>

Just started vs code and the extenstions host crashed

Extension version: 3.4.0
VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:18:44.904Z)
OS version: Linux x64 5.13.0-7620-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx (8 x 3165)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 1|
|Memory (System)|13.59GB (2.79GB free)|
|Process Argv|/home/abodsakka/Dokument/Git/school-planner --crash-reporter-id afafc095-3fef-4b10-a8d4-981feb6680aa|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627cf:30244335
pythontb:30283811
pythonvspyt551:30345470
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30384386
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593:30376534
vssld246cf:30386378

```

</details>

**Comment by Lemmingh** [comment]
Could you provide more information to help us diagnose? Thank you.

<https://markdown-all-in-one.github.io/docs/contributing/diagnostic-data.html>

<https://github.com/microsoft/vscode/wiki/Native-Crash-Issues>

**Comment by clouedoc** [comment]
@abodsakah, were you also using another Markdown linting extension?

I believe the bug might be caused by a conflict between two extensions (see #1037)
