### ISSUE TITLE
need config for background color in Markdown Preview

### ISSUE THREAD

**Issue by enihcam** [yzhang-gh/vscode-markdown#1034]
## Proposal

i'm using dark theme for my VSCode, however the Markdown Preview also set dark in background. i need a config to explicitly specify the color.

**Comment by yzhang-gh** [comment]
Please see https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview

In short, you can install extensions that provide Markdown preview styles (e.g. Markdown Preview GitHub) or write your own CSS styles.
