### ISSUE TITLE
Feature request: replace table of content numbers with number emojis :one: :two:

### ISSUE THREAD

**Issue by Gynko** [yzhang-gh/vscode-markdown#1035]
## Proposal
Replacing numbers with icons in the table of content

From this
1 Introduction
2 Chapter
2.1 Sub-Chapter

To this
:one: Introduction
:two: Chapter
:two::one: Sub-Chapter

Possible issues: 

These existing "numbering emojis" are stopping at number 10.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

That's an interesting but rarely seen feature request. I will link this to #403.
However, as you can see, there isn't a good solution now. Probably we will rethink it in the future.

**Comment by Gynko** [comment]
Thanks to you for the great extension and all the hard work!
I can currently just use the normal system, and maybe use "replace all" to change all "1." into ":one:"
Just have to be careful with it...
