### ISSUE TITLE
Markdown-all-in-one causes 100% CPU usage usage when starting a Jest puppeteer test

### ISSUE THREAD

**Issue by clouedoc** [yzhang-gh/vscode-markdown#1037]
Issue Type: <b>Bug</b>

I did not identify the reproduction steps yet; this issue is in a draft state.

**Investigation**

It might be due to another conflicting extension: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint.

**Side notes**

I have to say that I'm very impressed by the Bisect tool. If only I had known this earlier!

**System informations**

Extension version: 3.4.0
VS Code version: Code 1.62.0 (b3318bc0524af3d74034b8bb8a64df0ccf35549a, 2021-11-03T15:23:13.307Z)
OS version: Darwin arm64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.38GB free)|
|Process Argv|--crash-reporter-id 6525dafe-3e95-4eff-aba9-c883d1cd57cf|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscorecescf:30384386
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
vsccppwtct:30382698
bridge0708:30335490
pygetstartedt3:30385195
dockerwalkthru:30377721
bridge0723:30353136
pythonrunftest32:30373476
pythonf5test824:30373475
javagetstartedt:30391933
pythonvspyt187:30373474
vsqsis300:30386381
vsaa593cf:30376535
vssld246:30386377

```

</details>

**Comment by yzhang-gh** [comment]
Closing as it has been inactive for a long time. Feel free to reopen if you find some new information.
