### ISSUE TITLE
hotkey conflict with GitHub Copilot

### ISSUE THREAD

**Issue by Pablion** [yzhang-gh/vscode-markdown#1039]
## Problem

I noticed thi misbehavior when I use GitHub copilot, the tab key acts like programmed and blocking the GitHub copilot to insert the prediction. I also opened a discussion about copilot [here](https://github.com/github/feedback/discussions/7526). 

## How to reproduce

1. Activate GitHub copilot
2. Open an existed/ create a new file
3. Enter something until the copilot starts to predict.
4. Hit tab. 
5. The prediction should be inserted, but instead, a `tab` char is inserted.
6. 

## Configuration

```jsonc

```

## Diagnostic data

```log

```

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Please see #1011.

**Comment by Pablion** [comment]
Sorry, I just searched "hotkey" and saw no answer.
