### ISSUE TITLE
Settings editor twitches and input cursor randomly jumps between fields

### ISSUE THREAD

**Issue by WebMechanic** [yzhang-gh/vscode-markdown#1041]
Issue Type: <b>Bug</b>

Hello, I am reporting this as the result of a VSCode Extensions bisect.

It appears that if your extension is enabled, the settings editor becomes virtually unusable and I have to resort editing the settings.json file instead.

In the editor GUI the input cursor randomly, but consistently starts to jump between fields and the main and side panel and trying to scroll is virtually impossible as the settings view itself keeps moving up and down.

I write a lot of Markdown and there are other extensions installed to transform .md files, so maybe there is "cross contamination" with one of them. However, Code now behaves properly with your extension disabled.

Other Markdown related extensions installed and active:
- yzane.markdown-pdf 
- shd101wyy.markdown-preview-enhanced 
- davidanson.vscode-markdownlint

Extension version: 3.4.0
VS Code version: Code 1.62.1 (f4af3cbf5a99787542e2a30fe1fd37cd644cc31f, 2021-11-05T10:57:55.946Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by Lemmingh** [comment]
Could you elaborate on "the settings editor"? I'm pretty confused.

A VS Code extension cannot interact with the [Settings UI](https://code.visualstudio.com/docs/getstarted/settings). Recent changes in VS Code also seems irrelevant:

* [1.62: Settings editor accessibility](https://code.visualstudio.com/updates/v1_62#_settings-editor-accessibility)
* [1.61: Settings editor extension categories](https://code.visualstudio.com/updates/v1_61#_settings-editor-extension-categories)
* [1.60: Settings editor syntax highlighting](https://code.visualstudio.com/updates/v1_60#_syntax-highlighting-of-codeblocks-in-the-settings-editor)
* [1.59: Settings editor validation; `additionalProperties`; `editPresentation`](https://code.visualstudio.com/updates/v1_59#_settings-editor)
* [1.58: multiple checkboxes and enumeration dropdowns](https://code.visualstudio.com/updates/v1_58#_settings-editor)

Our version 3.4.0 was released one year ago. It's hard for me to figure out why it suddenly breaks the Settings on your device.

---

As for the legacy Settings Editor (#847), I'm not sure where it is nowadays.

**Comment by WebMechanic** [comment]
Hi,
the settings editor is the one I get when I press `Ctrl+,` where all extension settings are available. I don't know what else to call it.

As I wrote above, this is the result of VSCode's "Extension Bisect" and it came up with your extension as the "culprit", and indeed: the editor is usable again, now that your extension is disabled. It's still installed tho.

At some point I noticed the input cursor jumping around between fields and the left and right panels of said editor (you can tell by the blue outline the areas get when they have focus). It was impossible to make any edits. I initially thought it'S my mouse and didn't consider an extension. 
I couldn't tell now when I installed your extension and when I saw the settings editor misbehave. I often jump right into `settings.json` and don't use the editor that often.

I eventually re-installed VSCode, cleared all extensions and workspace data, then reinstalled everything from scratch, but the problem reappeared. I then ran Code _with all extensions disabled_ and the editor worked, so I launched Code's bisect feature and yours is what it came up with. Sorry 🙏🏻

This could be a Windows10 issue, some interference with another extension, I don't know and I can't tell. 
Things work again as they should with your extension sadly gone.

Maybe it's some "focus polling", window "scroll position" queries, or whatever your extension does that coincidentally interferes with the extension editor in particular.

If you can think of something I can do to narrow this down, please let me know. I know it's a bizarre "bug", hard to track.

Thanks.

**Comment by WebMechanic** [comment]
ok, so I withdraw and close this 'cos there seems to be a deeper issue in VSCode 1.62+

- https://github.com/microsoft/vscode/issues/134001
- https://github.com/microsoft/vscode/issues/136509
- https://github.com/microsoft/vscode/issues/137293

I knew this was weird, but bisect eventually came up with your extension and things went better.. for a while. 
Bizzarly enough, settings of the **integrated terminal** seem to be the root cause.

Sorry for the "blame"! **I happily reinstalled your extension** :D

Have a nice weekend!
