### ISSUE TITLE
alt + c could not check the task list

### ISSUE THREAD

**Issue by DukeHouse** [yzhang-gh/vscode-markdown#1042]
## Problem

alt + c could not check the task list ，and I remove all alt +c key shortcut map
## Configuration

```jsonc

```

## Diagnostic data

```log

```

**Comment by DukeHouse** [comment]
just alt c could produce this problem，windows 10 vscode 1.62.2

**Comment by DukeHouse** [comment]
error operation！

**Comment by Lemmingh** [comment]
Please follow [VS Code's troubleshooting guide](https://code.visualstudio.com/docs/getstarted/keybindings#_detecting-keybinding-conflicts).

See also:
<https://markdown-all-in-one.github.io/docs/guide/compatibility.html#key-binding>

**Comment by gy-mate** [comment]
I've just had the same issue. Changing the *When* value manually to `true` solved it!

<img width="609" alt="Screenshot 2024-08-01 at 20 39 27" src="https://github.com/user-attachments/assets/c82c6992-28b1-4127-90a8-0c0ac5825a27">

**Comment by DukeHouse** [comment]
thanks ，but the latest version works for me

**Comment by andij** [comment]
I had this issue and resolved it as @gy-mate [mentions above](https://github.com/yzhang-gh/vscode-markdown/issues/1042#issuecomment-2263726523). Thank you!

This is the change to `keybindings.json`:

```json
[
  {
    "key": "alt+c",
    "command": "markdown.extension.checkTaskList",
    "when": "true"
  },
  {
    "key": "alt+c",
    "command": "-markdown.extension.checkTaskList",
    "when": "false"
  }
]
```
