### ISSUE TITLE
found: Error: command 'markdown.showPreviewToSide' not found

### ISSUE THREAD

**Issue by jialin43** [yzhang-gh/vscode-markdown#1043]
## Problem

 ERR command 'markdown.showPreviewToSide' not found: Error: command 'markdown.showPreviewToSide' not found
    at h._tryExecuteCommand (vscode-file://vscode-app/c:/Users/Johnny/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1501:3364)
    at vscode-file://vscode-app/c:/Users/Johnny/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:1501:3245
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

## Configuration

```jsonc

```

## Diagnostic data

```log

```

**Comment by yzhang-gh** [comment]
这个命令可能在某个版本移除了。不太了解你是怎么触发这个问题的，需要更详细的重现过程。

**Comment by jialin43** [comment]
之前用的好好的，突然预览的按钮就不见了，重新安装过vscode，并删除配置文件也不行，没有任何markdown的预览功能了。
![image](https://user-images.githubusercontent.com/15903995/141886528-a42ac8ae-aaac-42c2-b5c8-32d3e6e6f614.png)

重现过程就是安装好vscode，然后安装 markdown all in one 插件，正常应该有个预览按钮，但是我的没有，按ctrl+shift+v，就提示下面这个错误。
![image](https://user-images.githubusercontent.com/15903995/141886425-f56eb36b-c430-42d1-aa34-b49b434f7ea4.png)

**Comment by yzhang-gh** [comment]
> 预览的按钮就不见了

这个是由 [VS Code 自带的插件](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview)提供的，大概率是损坏了

<img src="https://user-images.githubusercontent.com/7588612/141887954-808df0cd-ff31-4340-8fa9-af00d95c73d8.png" width="296">

> 重现过程就是安装好 vscode，然后安装 markdown all in one 插件，正常应该有个预览按钮，但是我的没有，按 ctrl+shift+v，就提示下面这个错误。

从上面看来，不安装本插件也不能预览，应该是 VS Code 安装有问题

**Comment by jialin43** [comment]
解决了，自带的插件居然被关闭了，打开就一切正常了，多谢大佬
