### ISSUE TITLE
Incorrect preview of nested bulleted list

### ISSUE THREAD

**Issue by thdoan** [yzhang-gh/vscode-markdown#1044]
## Problem

Nested list indented by three spaces looks fine in the extension preview, but it wraps to one line in Bitbucket README.md.

## How to reproduce

1. Create a dummy repo with this `README.md` file in Bitbucket:

```
1. Level one
   - Level two
   - Level two
2. Level one
3. Level one
```

2. Toggle the extension's Markdown: Open Preview to the Side.
3. Observe that the preview looks fine in VS Code.
4. Commit the changes and push to the repo.
5. Go to the repo index in Bitbucket.

ISSUE: The "Level two" bullets are on the same line as the first "Level one" bullet. It seems Bitbucket requires four spaces to nest lists. According to https://commonmark.org/help/tutorial/10-nestedLists.html you can have as little as two spaces to indicate a nested list, so can we conclude that Bitbucket's MD implementation is non-standard? If this is a case, feel free to close this ticket.

## Configuration

Default

## Environment

Extension v3.4.0

VS Code
Version: 1.62.1
Commit: f4af3cbf5a99787542e2a30fe1fd37cd644cc31f
Date: 2021-11-05T09:23:14.144Z
Electron: 13.5.2
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0
## Diagnostic data

N/A

**Comment by yzhang-gh** [comment]
<img src="https://user-images.githubusercontent.com/7588612/142520102-a56c7332-5990-405b-97c3-cac8b7f5783d.png" width="181">

Looks just fine in the GitHub comment.

**Comment by thdoan** [comment]
@yzhang-gh my bad, it was in Bitbucket, not GitHub. I have updated the issue details.

**Comment by Lemmingh** [comment]
Bitbucket uses [Python-Markdown](https://pypi.org/project/Markdown/) not CommonMark. Python-Markdown requires "4 spaces" indentation:

* <https://support.atlassian.com/bitbucket-cloud/docs/readme-content/>
* <https://bitbucket.org/tutorials/markdowndemo/src/master/#markdown-header-lists>
* <https://python-markdown.github.io/#differences>

Please set the following in your Settings.

```json
{
    "[markdown]": {
        "editor.detectIndentation": false,
        "editor.insertSpaces": true,
        "editor.tabSize": 4
    },
    "markdown.extension.list.indentationSize": "inherit"
}
```

**Comment by B3DTech** [comment]
This should be added as a setting inside the settings UI rather than a manual edit to the settings json file to make it easier on users to find.

**Comment by Lemmingh** [comment]
Aren't they present in the Settings (UI)?

Or, are you talking about

* <https://github.com/microsoft/vscode/issues/58995>
* <https://github.com/microsoft/vscode/issues/131707>

**Comment by B3DTech** [comment]
The settings weren't showing until I manually added them to the settings.json.  Then they showed up.  Strange glitch maybe.
