### ISSUE TITLE
Embedding GIF

### ISSUE THREAD

**Issue by QuelloLargo83** [yzhang-gh/vscode-markdown#1046]
## Proposal

Include animated GIF inside PDF

## References

Now animated GIFs in markdows are exported in pdf as still frame.
It would be helpful if the GIF would be alive in the pdf as well as is it in the HTML
Thanks!

**Comment by yzhang-gh** [comment]
I haven't seen a PDF that supports GIF 😅 and to my knowledge it is not feasible.

**Comment by QuelloLargo83** [comment]
Ok thanks for your answer :-)

**Comment by Lemmingh** [comment]
Some PDF formats allow attachments of arbitrary types. But I doubt whether there is any software other than Adobe Acrobat that can produces such files.

Anyway, this is out of our control.
