### ISSUE TITLE
Ctrl/Cmd + ` should surround the selected text with backticks (for code)

### ISSUE THREAD

**Issue by BlackDragonBE** [yzhang-gh/vscode-markdown#1047]
## Proposal

Being able to toggle a piece of text with backticks (`) should be added, similarly to being able to toggle text with bold and italic tags.

## References

A backtick is used to denote a piece of text or a word as code:
https://www.markdownguide.org/basic-syntax/#code

**Comment by BlackDragonBE** [comment]
I just realized simply pressing the backtick works for doing this. Still, I think it makes sense that Ctrl + ` would also work.

**Comment by Lemmingh** [comment]
We have a quite **naive** "Toggle code span" (`markdown.extension.editing.toggleCodeSpan`) command. You can assign a key binding. #628

As for defining default key bindings, my answer is: **No, too dangerous**. Users criticize us every few months. [Almost all existing key bindings have been reported.](https://markdown-all-in-one.github.io/docs/guide/compatibility.html#key-binding)

---

> simply pressing the backtick works for doing this

That's [Auto-surrounding](https://code.visualstudio.com/api/language-extensions/language-configuration-guide) (`editor.autoSurround`).

Please see the `surroundingPairs` in <https://github.com/microsoft/vscode/blob/main/extensions/markdown-basics/language-configuration.json>

**Comment by BlackDragonBE** [comment]
@Lemmingh Thanks for your detailed answer! I guess it makes sense not to do that to avoid conflicts. I'll just assign a key binding to the **Toggle code span** command.
Cheers!

**Comment by yzhang-gh** [comment]
The <code>ctrl+`</code> has been used for toggling integrated terminal. So I agree it would be better to assign your own key binding.
