### ISSUE TITLE
Possibility to render citations in the markdown preview window

### ISSUE THREAD

**Issue by mihaiconstantin** [yzhang-gh/vscode-markdown#1053]
## Proposal

Assuming that there is a `.bib` file provided, I think it would be handy to see the citations in the `.md` file rendered in the markdown preview window.

## Demonstration

Let's say I have a note like the following:

```markdown
---
bibliography: /Users/mihai/OneDrive/Library/Literature/Library.bib
---

# Note

This is a test note with some citations, e.g., @hastieElementsStatisticalLearning2009.
The references will be generated below under the *References* heading.

## References
```

Then, I would like in the markdown preview window to see:

<img width="615" alt="image" src="https://user-images.githubusercontent.com/20051042/143572675-e22ecd17-a350-42f9-a831-d9df06bb80bb.png">

The preview above was generated with the extension [vscode-R](https://github.com/REditorSupport/vscode-R), by running a `pandoc` command like this:

```bash
pandoc \
    +RTS -K512m -RTS note.md \
    --to html4 \
    --from markdown+autolink_bare_uris+tex_math_single_backslash \
    --output note.html \
    --self-contained \
    --standalone \
    --section-divs \
    --no-highlight \
    --citeproc
```

## Ideas for the contributed settings

In terms of user settings, I think the following would be relevant:

- `markdown.extension.citations.enabled`: `bool` indicating whether to render the citations
- `markdown.extension.pandoc`: `string` indicating the path for the `pandoc` executable
- `markdown.extension.citations.defaultBib`: `string` indicating the default `.bib` file (i.e., for users who rely on a single `.bib` file and do not want to specify `bibliography: file.bib` in the header of each markdown file)

Do you think this would fit with *Markdown All in One*? What are your thoughts?

**Comment by yzhang-gh** [comment]
Thanks.

That is interesting. To me it is a syntax extension of Markdown, just like [Markdown Footnotes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes). If there is a corresponding `markdown-it` plugin, you can use it with Markdown All in One.

Please see https://github.com/yzhang-gh/vscode-markdown#q-which-markdown-syntax-is-supported

**Comment by Lemmingh** [comment]
This is quite complicated. Can [MPE](https://shd101wyy.github.io/markdown-preview-enhanced/#/pandoc-bibliographies-and-citations) solve your problem now?

**Comment by mihaiconstantin** [comment]
@yzhang-gh, there is a `markdown-it` plugin for `pandoc` [here](https://github.com/mb21/markdown-it-pandoc), but I am still wrapping my head around how it works.

@Lemmingh, taking a closer look, it does indeed seem complicated. I was not aware of *Markdown Preview Enhanced* (MPE), thanks for mentioning it! It does what I was looking for, using `pandoc` with `--citeproc` behind the scenes:

<img width="1532" alt="image" src="https://user-images.githubusercontent.com/20051042/145690283-63801d7f-1dd5-4694-9816-d31c353b31df.png">

I am wondering whether it still makes sense to bring this functionality to *Markdown All in One* since it is already covered by *MPE*. What are your thoughts?

**Comment by yzhang-gh** [comment]
The extension was named _Markdown All in One_ 5 years ago while it isn't the case now 😂

We do not aim to include all the functionalities (which is infeasible), but we always listen to the voice of the community.

**Comment by mihaiconstantin** [comment]
@yzhang-gh makes sense not to include everything and I appreciate taking a look at this. I think we can close this issue. *MPE* seems quite flexible in allowing to use `pandoc` and specifying options.

But I am confused about your comment:

> The extension was named Markdown All in One 5 years ago while it isn't the case now 😂

This is how it shows up for me!

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/20051042/145705113-5476583c-99cf-4d32-8a0c-9d1357030170.png">

**Comment by yzhang-gh** [comment]
Thanks.

I meant the aim of this extension is no longer "all the functionalities" but for the historical reason we still use this name (changing the name may cause other troubles).
