### ISSUE TITLE
Wrong documentation for keyboard shortcut

### ISSUE THREAD

**Issue by memeplex** [yzhang-gh/vscode-markdown#1055]
The README states:

```
Ctrl/Cmd + Shift + ]   Toggle heading (uplevel)
Ctrl/Cmd + Shift + [   Toggle heading (downlevel)
```

But even in macOS the right modifier is Ctrl, not Cmd (Cmd+Shift+[/] are already taken by vscode).

**Comment by yzhang-gh** [comment]
Thanks. You are right (#71). It has been fixed now.
