### ISSUE TITLE
与 ahk 冲突

### ISSUE THREAD

**Issue by franklee095** [yzhang-gh/vscode-markdown#1056]
## 复现

以下是我使用的 ahk 文件摘要：

    #Hotstring EndChars -()[]{}:;'"/\,.?!`n`t
    :*:188  ::18812345678

正常情况下，输入 `188  ` （188及两个空格），就会自动扩展成 18812345678

在启用 vscode markdown all in one 插件后，在编辑 markdown 文件时就不能正常扩展了，会扩展成 18818812345。

禁用此插件后，功能恢复正常。

期望能够解决，谢谢。

**Comment by Lemmingh** [comment]
Duplicate of #200
