### ISSUE TITLE
Rendering frequency

### ISSUE THREAD

**Issue by ghost** [yzhang-gh/vscode-markdown#1058]
Reporting also here https://github.com/microsoft/vscode/issues/138669, which I expect to to get the standard bot close-and-ignore treatment similarly to the earlier https://github.com/microsoft/vscode/issues/104649. Basically the (slow) rendering of the markdown preview is way too frequent, even more frequent than the rendering speed of larger documents. The only workaround, to avoid getting a headache from really nasty document jumping on larger documents and with math, is to disable `markdown.preview.scrollPreviewWithEditor`. According to https://github.com/microsoft/vscode/issues/104649#issuecomment-864488948 the rendering frequency is hard-coded in vscode to 300ms, but perhaps there would be some sort of way for this extension to try to tune the frequency? Ideally the rendering should not happen until typing has stopped; some time after the last keystroke, not some time after every keystroke.

**Comment by yzhang-gh** [comment]
Thanks for the information.

This extension does not provide a standalone Markdown preview but contributes to the VS Code's

```js
md.use(require("markdown-it-task-lists"));
md.use(require("@neilsustc/markdown-it-katex"), katexOptions);
```

So I don't think it is possible for an extension to change the code of VS Code (as noted in https://github.com/microsoft/vscode/issues/104649#issuecomment-864488948)

Obviously this is misunderstood by mjbvz, I will reply to him.
