### ISSUE TITLE
Add keyboard shortcuts for code blocks, and for fenced code blocks

### ISSUE THREAD

**Issue by andreap-bh** [yzhang-gh/vscode-markdown#1060]
## Proposal

It would be very useful to have a keyboard shortcut for inline code block, and one for fenced code block.

**Comment by Lemmingh** [comment]
<https://github.com/yzhang-gh/vscode-markdown/issues?q=is%3Aissue+label%3A%22Area%3A+Input%22+in%3Atitle+code>

**Comment by yzhang-gh** [comment]
Please see https://github.com/yzhang-gh/vscode-markdown/issues/628
