### ISSUE TITLE
Cannot select brackets in link title

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [yzhang-gh/vscode-markdown#1063]
# Cannot select brackets in link title

When creating a link, the brackets surrounding the link title do not seem to be recognized well.
Similarly, the same symptom occurs when pasting an image.

I often use `editor.action.selectToBracket` to select inside brackets, but currently I can't select inside brackets with this command.

```markdown
[Example Domain](http://example.com/)
```

This behavior is the same when the link is created as follows:

```markdown
[Example Domain][link]

[link]: http://example.com/
```

Example of running: 
I want to select link title `Example Domain`, but the URL is selected.

![Animation](https://user-images.githubusercontent.com/75878492/145832721-0e8b96e8-366d-434c-9f9e-ef93d4139813.gif)

Also, `"editor.bracketPairColorization.enabled": true` is set, but brackets are not highlighted.

Sample image:

![link-syntax](https://user-images.githubusercontent.com/75878492/145832741-3a606815-7f6e-495a-8df8-670635ed2502.png)

Thanks for your work on this very handy extension!

## Version info.

- Markdown All in One: ver.3.4.0
- Visual Studio Code: ver.1.62.1

**Comment by yzhang-gh** [comment]
Thanks for the detailed feedback.

Could you check whether this issue still exists if this extension is disabled?

**Comment by Yarakashi-Kikohshi** [comment]
Even if I disabled `Markdown All in One`, I still couldn't select the link title.

**Comment by yzhang-gh** [comment]
I guess so as this extension doesn't seem to change that command. You might report it to the VS Code team (if this command is provide by them).

**Comment by Yarakashi-Kikohshi** [comment]
The command `editor.action.selectToBracket` is provided by VS Code, so I'll report it to the VS Code team.
Thank you for your cooperation.:smile:
