### ISSUE TITLE
Setting tableFormatter.enabled is ignored

### ISSUE THREAD

**Issue by dialex** [yzhang-gh/vscode-markdown#1068]
## Problem

The setting ´markdown.extension.tableFormatter.enabled´ is being ignored.

## How to reproduce

1. Edit `settings.json`
2. Add "markdown.extension.tableFormatter.enabled": false
3. Edit a file with a table, press Ctrl+S to save (this will trigger auto-formatting the file)

I expected the table not to be formatted/changed.
But actually the table was formatted (lots of ´---´where added to align ´|´ with the content)

## Configuration

Default plus 

```jsonc
`"markdown.extension.tableFormatter.enabled": false,´
```

## Environment

- Markdown All in One v3.4.0
- VS Code v1.63.2
- MacOS 12.1

**Comment by dialex** [comment]
Actually, Prettier was the one responsible for the changes on save 😮 
I wish I knew how to disabled it... but it's not your fault, so I'll close this issue!

**Comment by yzhang-gh** [comment]
No worries 😂
