### ISSUE TITLE
表格格式化的时候，是否可以增加最大宽度限制？

### ISSUE THREAD

**Issue by NingerJohn** [yzhang-gh/vscode-markdown#1072]
当某个单元格内容文字过多的时候，格式化之后，预览没任何问题，但是编辑代码区域已经不方便查看修改了，例如下面。建议增加可视区域宽度作为最终格式化的宽度限制。当然直接的解决方法就是取消word wrap (View -> Word Wrap)

##### 参数

| 参数名                 | 类型   | 必填 | 说明                               |
| ---------------------- | ------ | ---- | ---------------------------------- |
| id                     | int | `是` | 主键id                             |
| frequency              | int | `是` | 频率。（1：每周一次；2：每周两次；3：每周三次；4：每周四次；5：每周五次；6：每周六次；7：每天一次；8：两周一次；9：每月一次；10：每十天一次）|

![image](https://user-images.githubusercontent.com/10202203/149716978-30495579-359f-4705-998b-2a45d1166dca.png)

**Comment by NingerJohn** [comment]
这种方案，取消word wrap (View -> Word Wrap)

**Comment by yzhang-gh** [comment]
这是一个可以考虑的特性，见 #455
