### ISSUE TITLE
command 'markdown.extension.onXXXKey' not found when used with "Markdown Notes"

### ISSUE THREAD

**Issue by geekscrapy** [yzhang-gh/vscode-markdown#1073]
When using another extension, "Markdown Notes", I get the error `command 'markdown.extension.onXXXKey' not found`

**Comment by yzhang-gh** [comment]
Markdown Notes has been found to have some performance issues (https://github.com/yzhang-gh/vscode-markdown/issues/855#issuecomment-773376295). That may be a reason (that affects the keybindings of this extension).

I cannot give any practical suggestions as you provided too limited information. It may be helpful if you can find a way to reliably reproduce this issue (i.e., [minimal working example](https://en.wikipedia.org/wiki/Minimal_working_example)).

**Comment by rs0h** [comment]
@geekscrapy I have similar issue but for me it was caused by the **Spell Right** extension. I've disabled it and no error messages popped up anymore.

**Comment by geekscrapy** [comment]
> @geekscrapy I have similar issue but for me it was caused by the [**Spell Right**](https://github.com/bartosz-antosik/vscode-spellright/issues) extension. I've disabled it and no error messages popped up anymore.

I was going to post back today, with spell right disabled, it works as expected!

**Comment by yzhang-gh** [comment]
Thanks for the information. Spell Right has also been found to cause some trouble here (#423).
