### ISSUE TITLE
Links with relative paths get converted into absolute ones when exporting as a PDF

### ISSUE THREAD

**Issue by Elynvalur** [yzhang-gh/vscode-markdown#1074]
Hi,
 
first of all thanks for this useful vscode extension, overall it's really great work! :)

When exporting a markdown file as .html, contained links with relative paths (e.g. `[link](./document.txt)`) will be kept relative, which is just fine.

However, I noticed that this is not the case when exporting the same markdown file to PDF (via `> Markdown PDF: export (pdf)`). In this case, relative links will get converted into absolute paths. So after exporting a .md-File, which is located under `C:\Users\User\Documents`, the same relative link as above is being converted into an absolute one ( `C:\Users\User\Documents\document.txt`).

Thus, after moving the exported .pdf and .html files to let's say the Desktop, the link `[link](./document.pdf)` still references to `C:\Users\User\Documents\document.txt` in the .pdf, while the link contained in the .html file references as expected to `C:\Users\User\Desktop\document.txt`.

After browsing through the extension's settings, It seems that currently it's not possible to prevent relative links from being converted when exporting as a .pdf file.

**Comment by Lemmingh** [comment]
Exporting as PDF is currently out of scope. We haven't support it.

Please consult the program that you used to generate PDF files.

**Comment by yzhang-gh** [comment]
The PDF is exported by extension [Markdown PDF](https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf) and obviously it is out of our control.

Not sure whether it can solve this issue, I usually use Edge/Chrome to export/print an HTML file as PDF.
