### ISSUE TITLE
Bold and Italic can't be used at same time when `markdown.extension.italic.indicator = '_'`

### ISSUE THREAD

**Issue by chencyu** [yzhang-gh/vscode-markdown#1076]
## Problem

first, `markdown.extension.italic.indicator = '_'`
second, use bold and Italic on same part like this:
`longlongword**_boldwithitalic_**longlongword`
will render like: 
longlongword**_boldwithitalic_**longlongword

vice versa:
`longlongword_**boldwithitalic**_longlongword`:
render like:
longlongword_**boldwithitalic**_longlongword

expected result:
longlongword***boldwithitalic***longlongword

## Configuration

```jsonc
"markdown.extension.italic.indicator": "_"
```

## Environment

```
Markdown All in One: v3.4.0
VSCode             : v1.63.2 on Win11
```

**Comment by Lemmingh** [comment]
<https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis>

Please read the definitions of "delimiter run" carefully.

**Comment by chencyu** [comment]
> https://spec.commonmark.org/0.30/#emphasis-and-strong-emphasis
> 
> Please read the definitions of "delimiter run" carefully.

I see, thanks for providing information.
