### ISSUE TITLE
Update links when updating section numbers

### ISSUE THREAD

**Issue by ebw44** [yzhang-gh/vscode-markdown#1079]
## Proposal

When updating section numbers, it would be great if the links to sections could also be updated. Here is an example:
Before:
```markdown
[Intro](#introduction)  
[Conclusion](#conclusion)  

# Introduction

# Conclusion
```

Version after 'add/update section numbers' with extensionv3.4.0  :
``` markdown
[Intro](#introduction)  
[Conclusion](#conclusion)  

# 1. Introduction

# 2. Conclusion
```

Would like:
``` markdown
[Intro](#1-introduction)  
[Conclusion](#2-conclusion)  

# 1. Introduction

# 2. Conclusion
```

**Comment by yzhang-gh** [comment]
If the TOC is created by this extension, you can just use the "Update TOC" command. And by default the TOC will be updated automatically on file save (`markdown.extension.toc.updateOnSave`)

**Comment by frudolph77** [comment]
Hey, 
the update on safe is not working, at least in my setup. Even with explicit setting of `markdown.extension.toc.updateOnSave: true`.

The extension recognizes that the TOC is outdated, and shows it right above, but when I safe the file the TOC stays unchanged. 

Nothing is logged in the 'debug' console.

Kind regards
Frank

**Comment by yzhang-gh** [comment]
Do you have any other (Markdown) formatter installed? And also could you check what is the result if you manually execute the "update table of contents" command in the command palette (<kbd>ctrl+shift+p</kbd>)?

**Comment by frudolph77** [comment]
Update TOC via command palette works fine, forget to mention.

Thanks for the hint with other extensions. I've removed them all, except **Markdown All in One**, then the update of the TOC onSafe works like a charm. Now I'll add one by one to see which extensions breaks the safe, and let you know.

@ebw44 sorry for hijacking this issue.

**Comment by frudolph77** [comment]
Just found it. 
It's https://marketplace.visualstudio.com/items?itemName=madeindjs.notable
This extensions works with the FrontMatter of the md file and can update it onSave.

The behavior is really strange.
Having MAiO installed and then installing Notable they work fine, side by side.
Also when I deactivate it, restart code and activate it again.

When I deactivate MAiO restart code and activate MAiO they still don't work together

So as soon as both are installed and code is restarted, only Notable updates the content of the md file.
When I deactivate the update of the FrontMatter in Notable, the update of the TOC works fine.

So it seems that the onSave hook of Notable runs first and then the one from  MAiO 
Is there any chance to have more than one onSave Hook for the same file.

**Comment by Lemmingh** [comment]
This thread looks like a duplicate of

* #591
* #712

**Comment by ebw44** [comment]
I did a pretty bad job at searching for duplicate before posting that issue. As #591 is exactly what I had in mind.
Sorry
