### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by ZacksAmber** [yzhang-gh/vscode-markdown#1082]
- Issue Type: `Bug`
- Extension Name: `markdown-all-in-one`
- Extension Version: `3.4.0`
- OS Version: `Darwin x64 21.3.0`
- VS Code version: `1.64.2`

Extremely slow response time: 
- Acitivation: 49ms
- Profile: 1185.66ms

**Comment by yzhang-gh** [comment]
This doesn't contain any useful information. Please add more descriptions (what is the problem, how to reproduce).
