### ISSUE TITLE
synch

### ISSUE THREAD

**Issue by Reissner** [yzhang-gh/vscode-markdown#1083]
## Configuration

```jsonc

```

## Diagnostic data

```log

```

**Comment by Reissner** [comment]
Problem: 
I use this extension with the outline and with the previewer. 
Whereas I made the experience that scrolling the preview the source is synchronized perfectly 
so that i always have source and preview side by side. 
I observe that the preview has a bar at the left indicating the section. 
It would be nice if the source had an according bar which moves with the bar at the preview. 
Also highlighting the overview containing the headlines would be a nice feature. 

Contrary, I if i browse in the source, the preview frequently gets stuck. 
It is ok when using the slider. 
Also it would be fine if moving the source also the navigation would synchronize. 
If clicking to a headline in the navigation always updates the source but update of preview is not reliable at all. 

Please keep me informed. I can give you an example md.

**Comment by yzhang-gh** [comment]
The synchronization is provided by [VS Code itself](https://code.visualstudio.com/docs/languages/markdown#_editor-and-preview-synchronization). Probably you need to report it to the VS Code team.
