### ISSUE TITLE
Default keyboard shortcut for markdown.extension.onTabKey should change when expression to allow Github Copilot suggestions

### ISSUE THREAD

**Issue by NagisaVon** [yzhang-gh/vscode-markdown#1085]
## Problem

Default keyboard shortcut for markdown.extension.onTabKey should add !inlineSuggestionVisible expression to allow Github Copilot suggestions.

The full when expression after change should be: 
editorTextFocus && !editorReadonly && !editorTabMovesFocus && !hasOtherSuggestions && !hasSnippetCompletions && !inSnippetMode && !suggestWidgetVisible && !inlineSuggestionVisible && editorLangId == 'markdown'

## Configuration

```jsonc

```

## Diagnostic data

```log

```

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Please see #1011
