### ISSUE TITLE
Inline LaTex equetions does not accept spaces next to delimieters $ x^2 $ 

### ISSUE THREAD

**Issue by dvd101x** [yzhang-gh/vscode-markdown#1086]
## Problem

When writing Markdown with equations:
* This works: `$$ x^2 $$`
* This does not work: `$ x^2 $`
* If we remove spaces like so `$x^2$` it now works

## How to reproduce

Type `$ x^2 $` and notice how the preview doesn't show the renderd LaTex
Disable this extension and test that the preview now works for `$ x^2 $` 

## Configuration

Default.

## Environment

* v3.4.0
* Version: 1.65.1 (user setup)
  Commit: 8908a9ca0f221f36507231afb39d2d8d1e182702
  Date: 2022-03-08T02:06:27.846Z
  Electron: 13.5.2
  Chromium: 91.0.4472.164
  Node.js: 14.16.0
  V8: 9.1.269.39-electron.0
  OS: Windows_NT x64 10.0.19044

## Diagnostic data

N/A

**Comment by Lemmingh** [comment]
#955

**Comment by Lemmingh** [comment]
For math spans, we follow pandoc-style as much as possible. But VS Code's built-in `vscode.markdown-math` extension does not.

**Comment by dvd101x** [comment]
I tought it was a bug, thank you for the review and the response.

I found it by doing tests with the first example of https://github.com/susam/texme#get-started

I did validate that indeed pandoc states how inline equations works https://pandoc.org/MANUAL.html#extension-tex_math_dollars

> The opening $ must have a non-space character immediately to its right, while the closing $ must have a non-space character immediately to its left, and must not be followed immediately by a digit. Thus, $20,000 and $30,000 won’t parse as math

I wasn't aware of the different styles

I stand corrected, thank you

**Comment by Lemmingh** [comment]
Markdown is not a single rigorous language, but a collection of various [flavors](https://markdown-all-in-one.github.io/docs/guide/markdown-syntax-and-flavors.html) (aka "dialect", "variant") that **disagree with each other**.

Feel free to ask questions about its dark side.
