### ISSUE TITLE
[FeatReq] Enable toggleStrikethrough

### ISSUE THREAD

**Issue by PabloLION** [yzhang-gh/vscode-markdown#1088]
## Problem

I see the `when` field of my `markdown.extension.editing.toggleStrikethrough` is set to `false`. And this is a quite old issue.

https://github.com/yzhang-gh/vscode-markdown/issues/35
https://github.com/yzhang-gh/vscode-markdown/issues/91

May I ask why is it changed?

**Comment by Lemmingh** [comment]
Please check your [`keybindings.json`](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization) file to learn why and when you modified it.

**Comment by PabloLION** [comment]
I've manually changed the when field to `editorTextFocus && !editorReadonly && editorLangId == 'markdown'`
```json
{
  "key": "alt+s",
  "command": "markdown.extension.editing.toggleStrikethrough",
  "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown'"
}
```
I want to know why is it changed back to `false`?

**Comment by Lemmingh** [comment]
Our default value is **not** `false`; it is

<https://github.com/yzhang-gh/vscode-markdown/blob/c50fe848fae507597c2b1252c4dbe0708f16bd24/package.json#L104-L108>

**Comment by PabloLION** [comment]
Ok. I see why... Because I'm using Mac, and VSCode somehow renders it to `false`. Thanks for the clarification.😂

**Comment by PabloLION** [comment]
Thanks

**Comment by Lemmingh** [comment]
Key bindings beginning with the `Option` key may conflict with [Alt Code Shortcuts](https://www.webnots.com/option-or-alt-key-shortcuts-to-insert-symbols-in-mac-os-x/) on macOS: #404

I'd recommend that you delete the default binding, and assign a new one.
