### ISSUE TITLE
Enter, backspace, shift and other keys are not registered correctly

### ISSUE THREAD

**Issue by jedi-river-pdl** [yzhang-gh/vscode-markdown#1093]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Install
go to markdown page
hit enter

Error:
command 'markdown.extension.onEnterKey' not found

Extension version: 3.4.0
VS Code version: Code 1.60.1 (83bd43bc519d15e50c4272c6cf5c1479df196a4d, 2021-09-10T17:09:14.403Z)
OS version: Darwin x64 19.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.07GB free)|
|Process Argv|-psn_0_135201 --enable-proposed-api genuitecllc.codetogether --crash-reporter-id 2304264f-0048-4a1b-8497-01f9a8375051|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392:30443607
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
wslgetstarted:30449410
dsvsc008:30440022
pythonvspyt640:30450904
vscscmwlcmt:30438805
vscgsvid1:30447480
vscaac:30438847
pynewfile477:30450038

```

</details>

**Comment by yzhang-gh** [comment]
Please refer to https://github.com/yzhang-gh/vscode-markdown#q-error-command-markdownextensiononxxxkey-not-found

Also you may check whether you have these extensions installed
- Markdown Notes
- Spell Right
- and other Markdown extensions

There might be some unexpected conflicts causing this issue.

**Comment by jedi-river-pdl** [comment]
I just made sure 2 Markdown Extensions and Spell right were disabled.  Do they need to be uninstalled?

**Comment by jedi-river-pdl** [comment]
not sure which did it, but an uninstall and restart of vs code seemed to have worked

**Comment by yzhang-gh** [comment]
You don't have to uninstall all of them. Normally they should work well together. But if you see the same issue next time, you can test which one of them causes it.

Let's close this thread for now (related #855, #922)

**Comment by rcdailey** [comment]
@yzhang-gh This issue is back:

> command 'markdown.extension.onEnterKey' not found

I'm getting this on v3.5.0 which was released a few days ago. If I roll back to 3.4.3, the issue goes away.

**Comment by yzhang-gh** [comment]
As always, it is 95% because of conflicts between extensions.

Please check it with all other extensions disabled (enable only this one)

![image](https://user-images.githubusercontent.com/7588612/204078710-78f98a65-91c0-4add-a870-766be9ccaddf.png)

**Comment by rcdailey** [comment]
I'm happy to test that, but it's hard to ignore that it worked in the previous release. To me, this means something changed in 3.5.0 to *cause it* to interfere with other extensions (if that's indeed the issue). To me, this still smells like a bug.

I already rolled back the extension and it appears to be working fine. I don't have much incentive to upgrade again, which disrupts my daily workflow. If I have time to get back to debugging this for you I'll post my results here.

**Comment by yzhang-gh** [comment]
Thanks.

I need to mention that it never worked in the previous releases, to be specific, worked for all users at the same time. (Check #922 and ever #52 in _2017_), although I have never seen this issue on my machine (probably because I only use a small set of VS Code extensions).

For years we were investigating why many users had this issue and found some extensions did not work well along with this one (e.g. Spell Right, Markdown Notes). However, we have no control over the VS Code extension activation rules, and even the installation order of extensions may lead to different results. If you get time to find the reason in the future, I won't be surprised if it is because of another "Markdown XXX" extension.

**Comment by rcdailey** [comment]
Saying "it worked" was probably incorrect; what I really mean is "I had no issue". My list of extensions has remained the same. The only delta in that scenario is the code between `3.4.3...3.5.0`.

Here's my list of markdown-specific extensions. I'm providing it here just in case you can immediately red-flag any of them.

![image](https://user-images.githubusercontent.com/1768054/204103635-9c77cdd4-ac49-44cd-9e46-a17d205339a9.png)

**Comment by yzhang-gh** [comment]
Thanks for the additional information. For these extensions, I haven't seen conflict reports so there might be other reasons. And that's why I also mentioned "the order of installation of extensions" (or some unknown VS Code mechanisms). This may sound strange, but I did remember some users found it might matter.
