### ISSUE TITLE
unorderedList.marker

### ISSUE THREAD

**Issue by c581698** [yzhang-gh/vscode-markdown#1097]
请问这个配置参数是这里用的吗？

https://github.com/yzhang-gh/vscode-markdown/blob/fe80c74e8aa2ad5e6f1b03aaac29f209cb4fbebb/src/formatting.ts#L238

**Comment by yzhang-gh** [comment]
https://github.com/yzhang-gh/vscode-markdown/blob/fe80c74e8aa2ad5e6f1b03aaac29f209cb4fbebb/src/toc.ts#L427

**Comment by c581698** [comment]
感谢回复！

我理解错了，以为这个命令"markdown.extension.editing.toggleList"的默认列表符号是这个参数"markdown.extension.toc.unorderedList.marker"配置的。
