### ISSUE TITLE
markdown.extension.toggle preview not found

### ISSUE THREAD

**Issue by Nikodior** [yzhang-gh/vscode-markdown#1098]
markdown.extension.toggle preview not found 
This pops out when i do CTRL+SHIFT+V they keybind set for this option.

**Comment by yzhang-gh** [comment]
The `togglePreview` has been removed for a while.

You might have edited your `keybindings.json` file before. Please open it with the command `preference: open keyboard shortcuts (json)` and delete anything relevant.

**Comment by Nikodior** [comment]
Okey
