### ISSUE TITLE
Add a command to generate an hyperlink

### ISSUE THREAD

**Issue by AndreaPi** [yzhang-gh/vscode-markdown#1105]
## Proposal

Add a command (and related keyboard shortcut) to create a Markdown hyperlink. Currently, there's no [ Markdown: All in One command](https://github.com/yzhang-gh/vscode-markdown#available-commands) to create a hyperlink, and thus no shortcut. It would be useful to have a shortcut (such as for example <kbd>Cmd</kbd>+<kbd>K</kbd>, same as in GitHub-flavored Markdown) working the same as in GitHub:
- I select some `text` in a .md file
- the selected `text` gets surrounded by square brackets `[text]`, and the text `(url)` is added to the right of the square brackets and highlighted ⟹ `[text](**url**)`

If highlighting `url` is too complicated, just surround the selected text with square brackets and add `(url)` ⟹ `[text](url)`.

## References

Markdown hyperlinks: https://commonmark.org/help/tutorial/07-links.html
GitHub Markdown shortcuts: https://docs.github.com/en/get-started/using-github/keyboard-shortcuts

**Comment by yzhang-gh** [comment]
There is a feature that you can directly paste a link "onto" the selected text 😉

Please see the GIF here https://github.com/yzhang-gh/vscode-markdown#others
