### ISSUE TITLE
word highlight with `==word==`

### ISSUE THREAD

**Issue by alberto-lanfranco** [yzhang-gh/vscode-markdown#1106]
## Proposal

I'd like for this extension to support for the syntax `==word==` to highlight a word.
This is a quite common syntax, supported by many editors (as discussed [here](https://stackoverflow.com/a/66231157)).

## References

https://www.markdownguide.org/extended-syntax/#highlight

**Comment by yzhang-gh** [comment]
Thanks for the suggestion.

This is a common syntax and I also use it myself. However, as there are too many Markdown variants, this extension chooses not to include all of them but to be compatible with other Markdown extensions installed.
Please see https://github.com/yzhang-gh/vscode-markdown#q-which-markdown-syntax-is-supported for some examples.

In your case, you will need a VS Code extension that adds [`markdown-it-mark`](https://github.com/markdown-it/markdown-it-mark) support. This is super easy ([a line of code](https://github.com/mjbvz/vscode-markdown-emoji/blob/ef5fab704e76afb2a3280cb405f572e27d0050ea/src/index.ts#L7)). Hope there is someone has done it or you can create one by yourself.

**Comment by dacodekid** [comment]
@yzhang-gh , I've tried several extensions but none of them worked for me.  I can see the 'marked' highlights on the preview, but I rather see them in the code like we do with bold & italic.  Is there any way we can include the "==" in the settings itself (just like we currently have for both Bold & Italic) ?

**Comment by dacodekid** [comment]
I've ended up creating my own [vscode extension](https://github.com/dacodekid/vscode-mark-highlighter) to highlight the text in code editor.

**Comment by yzhang-gh** [comment]
Thanks for the information. Your extension looks pretty good.
