### ISSUE TITLE
Preview speed is low when the document is long

### ISSUE THREAD

**Issue by dualer** [yzhang-gh/vscode-markdown#1113]
## Problem
我发现当文档写得比较长时，markdown预览加载速度会很慢，例如：
![aec6j-igt1n](https://user-images.githubusercontent.com/85242539/163917424-16dc43e8-4346-404e-a984-eb73a1f0edd8.gif)

请问这是什么原因？另外, 补全的加载速度也很慢, 补全加载速度经常跟不上我码字的速度.

## Configuration

```jsonc

```

## Diagnostic data

```log

```

**Comment by yzhang-gh** [comment]
首先可以禁用其它无关插件测试一下。如果问题仍然存在建议提供供复现问题的 Markdown 文档。

**Comment by dualer** [comment]
> 首先可以禁用其它无关插件测试一下。如果问题仍然存在建议提供供复现问题的 Markdown 文档。

已经将其他插件禁用了(只剩你们这个插件), 仍然存在这个问题, 就是文档比较长就会有问题, 例如将百度百科词条"物理学"的内容多复制几遍(例如八遍), 后面预览速度以及补全加载速度就会很慢, 应该存在性能优化的问题.

**Comment by yzhang-gh** [comment]
在我本地测试没有问题。想起来可能是和 vscode 自带的 math 环境冲突了，可尝试如 https://github.com/yzhang-gh/vscode-markdown/issues/1102#issuecomment-1089029416 禁用

**Comment by dualer** [comment]
> 在我本地测试没有问题。想起来可能是和 vscode 自带的 math 环境冲突了，可尝试如 [#1102 (comment)](https://github.com/yzhang-gh/vscode-markdown/issues/1102#issuecomment-1089029416) 禁用

已经禁用了(那个问题就我问的...)

**Comment by yzhang-gh** [comment]
那最好还是提供一个 Markdown 文件供复现

**Comment by dualer** [comment]
> 那最好还是提供一个 Markdown 文件供复现

这个随便什么文件就行, 只要长度够就行, 比如下面这个吧 https://www.jianguoyun.com/p/DdlpIgcQ0vejChiqhrkEIAA

**Comment by yzhang-gh** [comment]
https://user-images.githubusercontent.com/7588612/164151181-afb3d4bc-f44f-42c5-9404-7e446fb660d1.mp4

还是不能复现（行内公式也测试了），所以还是得靠你自己探究究竟什么时候会产生迟钝
