### ISSUE TITLE
Support rendering inline mermaid diagrams

### ISSUE THREAD

**Issue by DanielLidstromTicket** [yzhang-gh/vscode-markdown#1121]
## Proposal

Now that GitHub has support for [rendering inline mermaid diagrams](https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/) I think it would be immensely useful if this extension also rendered mermaid diagrams in the preview window.

In GitHub I am able to iterate on the diagram using Preview as long as I am editing a story text, or pr description, etc. But I want to commit markdown files in my repo with mermaid diagrams and preferrably iterate on those (with preview) before pushing to GitHub.

**Comment by yzhang-gh** [comment]
Thanks.

Please see https://github.com/yzhang-gh/vscode-markdown#q-which-markdown-syntax-is-supported, and you can install [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) which can work along with this extension.
