### ISSUE TITLE
Extra space not very UI friendly when previewing unordered list

### ISSUE THREAD

**Issue by fdebbabi** [yzhang-gh/vscode-markdown#1122]
Hi,
first of all, thank you for your amazing markdown tool :) 

I have a markdown document that contain the exact following content:
```text
### A

- **B1**
  - C1
  - C2
  - C3
  - C4
  - C5
  - C6
  - C7
  - C8

- **B2**
  - D1
  - D2
  - D3
  - D4
  - D5
```

The problem I have is that when doing the markdown document preview, I have an extra space, as if C1->C8 belongs to B2 and not B1

This is really weird.

![Screenshot from 2022-04-27 23-40-56](https://user-images.githubusercontent.com/94532372/165636662-d13064e0-65be-4914-9387-02b89683ab67.jpeg)

## Environment

Markdown All in One extension v3.4.3
VScode: 1.66.2
OS: Linux x64 5.13.0-40-generic

**Comment by yzhang-gh** [comment]
Thanks.

Please see the [example 314](https://spec.commonmark.org/0.30/#example-313) which is called a loose list (the B list in your example). So just removing the blank line between B1 and B2 will solve this issue.

```
- a
- b
```

- a
- b

```
- a

- b
```

- a

- b

**Comment by yzhang-gh** [comment]
Thanks.

Please see the [example 314](https://spec.commonmark.org/0.30/#example-313) which is called a loose list (the B list in your example). So just removing the blank line between B1 and B2 will solve this issue.

```
- a
- b
```

- a
- b

```
- a

- b
```

- a

- b

**Comment by fdebbabi** [comment]
Yes, this is actually correct, good to know.
I am closing the issue :) thank you.
