### ISSUE TITLE
Ordered List Lint Error on First and Second List Item

### ISSUE THREAD

**Issue by koremp** [yzhang-gh/vscode-markdown#1123]
## Problem

While using ordered list, If some text was existed between ordered list's item, last ordered list's item was focused to lint with MD029/ol-prefix: Ordered list item prefix [Expected: 1; Actual: 2; Style: 1/1/1]markdownlint[MD029](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md029)

## How to reproduce

```md
# asdf

1. asdf

asdf
asdf

2. asdf 

<!-- above **2.** text was focus to lint that part--> 
```
![image](https://user-images.githubusercontent.com/18482476/166193590-adf323ac-b2e6-482a-8f72-2a324a5f03d6.png)

## Configuration

```jsonc
{
    "workbench.colorTheme": "Default Dark+",
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "editor.tabSize": 2,
    "terminal.integrated.shell.windows": "C:\\Program Files\\Git\\bin\\bash.exe",
    "editor.fontFamily": "'D2Coding'",
    "terminal.integrated.fontFamily": "monospace",
    "code-runner.executorMap": {
        "python": "C:/Python/Python38/python.exe -u $fullFileName",
    },
    "code-runner.runInTerminal": true,
    "explorer.confirmDelete": false,
    "emmet.includeLanguages": {
        "javascript": "javascriptreact",
        "typescript": "typescriptreact"
    },
    "terminal.external.windowsExec": "",
    "editor.formatOnSave": true,
    "editor.codeActionsOnSave": {
        "source.fixAll.eslint": true
    },
    "extensions.ignoreRecommendations": true,
    "javascript.updateImportsOnFileMove.enabled": "always",
    "files.eol": "\n",
    "tabnine.experimentalAutoImports": true,
    "[javascript]": {
        "editor.defaultFormatter": "esbenp.prettier-vscode"
    },
    "cmake.configureOnOpen": false,
    "bracketPairColorizer.depreciation-notice": false,
    "bracket-pair-colorizer-2.depreciation-notice": false,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "liveServer.settings.donotShowInfoMsg": true,
    "workbench.startupEditor": "none",
    "editor.inlineSuggest.enabled": true,
    "github.copilot.enable": {
        "*": true,
        "yaml": false,
        "plaintext": false,
        "markdown": false
    },
}
```

## Environment

![image](https://user-images.githubusercontent.com/18482476/166193720-71a4fe9a-a8ec-4224-aeb7-20071c2ee1f2.png)
last updated date: 24/04/2022, 23:08:29

```md
# 3.4.3 (2022.4.24)
Fixes
[Math] mhchem support ([#1116](https://github.com/yzhang-gh/vscode-markdown/issues/1116)).
VS Code freezes because of the new word pattern ([#1117](https://github.com/yzhang-gh/vscode-markdown/issues/1117)).
```
![image](https://user-images.githubusercontent.com/18482476/166194081-bfcaa431-3915-4504-86ba-941f9dcf3750.png)

## Diagnostic data

```log
MD029/ol-prefix: Ordered list item prefix [Expected: 1; Actual: 2; Style: 1/1/1]
```

`

**Comment by Lemmingh** [comment]
That message comes from **markdownlint,** not ours. And it is correct.

What do you expect?

**Comment by yzhang-gh** [comment]
The reason is already in your problem description [MD029](https://github.com/DavidAnson/markdownlint/blob/v0.25.1/doc/Rules.md#md029), which comes from the [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) extension.

> ## MD029 - Ordered list item prefix
>
> ...
>
> Note: This rule will report violations for cases like the following where an
> improperly-indented code block (or similar) appears between two list items and
> "breaks" the list in two:
>
> ~~~markdown
> 1. First list
>
> ```text
> Code block
> ```
>
> 1. Second list
> ~~~
>
> The fix is to indent the code block so it becomes part of the preceding list
> item as intended:
>
> ~~~markdown
> 1. First list
> 
>    ```text
>    Code block
>    ```
>
> 2. Still first list
> ~~~
>
> Rationale: Consistent formatting makes it easier to understand a document.

**Comment by koremp** [comment]
Sorry for my mistake about this issue. I am not used to making an issue to some repository. I misunderstood the MD029 rule and made this issue to the wrong repository. Thank you for your kind responses. I will read these kinds of documents in detail and do more checks before making an issue. Again, I really appreciate your kind responses.
