### ISSUE TITLE
Support LaTeX completion in square bracket

### ISSUE THREAD

**Issue by jwrh** [yzhang-gh/vscode-markdown#1125]
## Problem

Hi, the problem is that the auto-completion for LaTeX would not work inside square brackets `\[\]`. But for inline math with LaTeX (`$$`), the autocompletion works well. 

## How to reproduce
Try inputting `\[`, the autocompletion would not help you complete the other `\]`. And inside the `\[\]`,when inserting a `\` command, no suggestion would pop up.

## Configuration
Default

## Environment
v3.4.3

VsCode:
Version: 1.67.2
Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
Date: 2022-05-17T18:20:04.972Z (1 day ago)
Electron: 17.4.1
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 21.5.0

## Diagnostic data

```log

```

**Comment by Lemmingh** [comment]
Please see

* #552

---

Note that we definitely cannot support `\[ \]`, because it violates the CommonMark spec. But `\\[ \\]` might be OK.
