### ISSUE TITLE
code and strikethrough toggle commands do not work well

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [yzhang-gh/vscode-markdown#1130]
Disabling other extensions will still cause this problem.

The following two toggle commands do not work well.

- `markdown.extension.editing.toggleCodeSpan`
- `markdown.extension.editing.toggleStrikethrough`

Expected behavior: none → markup in code/strikethrough → none (loop)

~~I don't know the cause, but it started occurring after updating the VS Code version from 1.66.2 to 1.67.2.~~

### Demonstrations

Each command execution is repeated 5 times.

- code

    ![toggleCodeSpan](https://user-images.githubusercontent.com/75878492/170735051-f59a63b5-1910-4a56-8499-82ca80e8847a.gif)

- strikethrough

    ![toggleStrikethrough](https://user-images.githubusercontent.com/75878492/170735044-c625a0b6-9623-47c5-b2bc-89df77547fe3.gif)

## Version

- Markdown All in One: 3.4.3
- VS Code

    ```
     Version: 1.67.2 (user setup)
      Commit: c3511e6c69bb39013c4a4b7b9566ec1ca73fc4d5
        Date: 2022-05-17T18:15:52.058Z
    Electron: 17.4.1
    Chromium: 98.0.4758.141
     Node.js: 16.13.0
          V8: 9.8.177.13-electron.0
          OS: Windows_NT x64 10.0.19043
    ```

**Comment by yzhang-gh** [comment]
Thanks. It seems to be an issue after the change of word pattern in #1092
