### ISSUE TITLE
Automatically adjust the formula width

### ISSUE THREAD

**Issue by dualer** [yzhang-gh/vscode-markdown#1131]
## Proposal

markdown中是否能够像latex中使用`\begin{adjustwidth}\end{adjustwidth}`将公式自动换行, 并调整其宽度? 如果能自动换行也行, 我在markdown中没找到对应的语法, 一个公式太长, 例如一页多, 用`\begin{aligned}\end{aligned}`一行行的调整还是太麻烦了.

**Comment by yzhang-gh** [comment]
数学环境是由 KaTeX 实现的，所以这取决于 [KaTeX](https://github.com/KaTeX/KaTeX) 能否支持了
