### ISSUE TITLE
Can't preview picture in the quicksuggestion

### ISSUE THREAD

**Issue by GBEYOND0613** [yzhang-gh/vscode-markdown#1132]
## Problem

Can't preview picture in the quicksuggestion when insert a img link

## How to reproduce

insert an img link and type the path manually

## Configuration

```jsonc
 {
   "markdown.extension.list.indentationSize": "inherit",
    "markdown.extension.print.absoluteImgPath": false,
    "markdown.extension.print.imgToBase64": true,
    "markdown.extension.tableFormatter.normalizeIndentation": true,
}
```

## Environment

Markdown All in One v3.4.3

## Diagnostic data

```log

```

**Comment by GBEYOND0613** [comment]
![image](https://user-images.githubusercontent.com/57569566/173075994-ee6ebbb0-dfe6-4b59-942d-8ef684e41c00.png)

**Comment by yzhang-gh** [comment]
Thanks for the report.

Let's track this issue in #797, which can be easily fixed after we move to VS Code 1.63 (#1119).

**Comment by GBEYOND0613** [comment]
> Thanks for the report.
> 
> Let's track this issue in #797, which can be easily fixed after we move to VS Code 1.63 (#1119).

My version is 1.68.0 which is newer than 1.63 but the bug still exists :cry:

```
Version: 1.68.0 (user setup)
Commit: 4af164ea3a06f701fe3e89a2bcbb421d2026b68f
Date: 2022-06-08T11:44:16.822Z
Electron: 17.4.7
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.19044
```

**Comment by yzhang-gh** [comment]
This has not been fixed yet. I mean we need to use a new API that was introduced after VS Code 1.63.

**Comment by GBEYOND0613** [comment]
Thank you for your reply
looking forward to the new version of the update :eyes:
