### ISSUE TITLE
tableFormatter.enabled to false disables global formatting

### ISSUE THREAD

**Issue by QuentiumYT** [yzhang-gh/vscode-markdown#1143]
## Problem

When the setting `markdown.extension.tableFormatter.enabled` is false, I can't format my markdown file using "Format Document" command.
The extension kinda disable the formatting part

## How to reproduce

I want my table to stay as it is (short version without spaces), disabling this option makes the formatter no longer work (even disable the Format Document with command).

```
There is no formatter for 'markdown' files installed.
```

---

Example table:

|Tables|Are|Cool|
| :----------- | :-------------------------------: | ----: |
| col one is   |           left-aligned            | $1600 |
| col two is   |             centered              |   $12 |
| col three is |           right-aligned           |    $1 |
| col four is  | ver very very very very very long |    $1 |

## Configuration

Tested on a clean VSCode install

```jsonc
{
    "markdown.extension.tableFormatter.enabled": false
}
```

## Environment

OS: Linux Mint 20.3 Una

VSCode: 1.68.0

Extensions: Markdown All in One, Python, Pylance

## Diagnostic data

None

**Comment by yzhang-gh** [comment]
There is no built-in Markdown formatter from VS Code, so you need to install other extensions that provide Markdown formatters, e.g. https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode or https://marketplace.visualstudio.com/items?itemName=mervin.markdown-formatter

**Comment by QuentiumYT** [comment]
Thanks for your reply

I know there is no formatter from VS Code, your extension has a formatter right?

I wonder why this extension appears as a formatter.
![image](https://user-images.githubusercontent.com/35229942/176941171-002d0241-a5e3-4ac5-a1ff-cff1da3b2700.png)

Also why it doesn't when this option is disabled.
![image](https://user-images.githubusercontent.com/35229942/176941497-cfa83480-ba01-468b-ab7c-f17ec305ff2d.png)

**Comment by yzhang-gh** [comment]
When you have two or more formatters, VS Code will ask you which one to use. If you disable the one from this extension, then VS Code will use the remaining one (Prettier) automatically. I have tested it on my machine and it works as expected.

**Comment by QuentiumYT** [comment]
Yes I'm aware of that, but this option does disable the whole formatter features and not only the table formatting

**Comment by yzhang-gh** [comment]
I don't understand why you keep saying the option from this extension disables the formatter from other extensions.

https://user-images.githubusercontent.com/7588612/177022467-145fe82e-f5e6-4a07-97dd-1092a876d8f5.mp4

If you do not see any difference after you format the document, it is an issue of the other formatter you have installed. For example, https://github.com/prettier/prettier-vscode/issues/2512

**Comment by QuentiumYT** [comment]
I'm sorry, wasn't clearly explaining and kinda confusing.

You're right, a video is more appropriated :)

Extensions enabled: Only Markdown All in One (no more prettier as I don't plan to use it for formatting markdown)

https://user-images.githubusercontent.com/35229942/177034317-1dc6090f-fe85-4c34-9452-688cd6530bcf.mp4

**Comment by yzhang-gh** [comment]
This extension only provides ONE formatter which is the "GFM table formatter". If you disable it, then there is no available formatter unless you install other extensions...

**Comment by QuentiumYT** [comment]
Ohhhh that's what I didn't understood, thanks for the clarification! I thought it format also other sections.
Thanks you for your time and help, I'll close this issue as it's now clear to me :)
