### ISSUE TITLE
Print documents to HTML does not convert all the files in the folder

### ISSUE THREAD

**Issue by mimmori** [yzhang-gh/vscode-markdown#1144]
## Problem

Not all files in a folder are converted to HTML by starting batch printing.

Which and how many files are processed is not always fixed at each execution.

## How to reproduce

Start the html export to a folder full of markdown files. In my case there are 250 files and check if the number of html files generated corresponds to the number of md files.

## Configuration

```json
{
    "markdown.extension.print.absoluteImgPath": false,
    "markdown.extension.print.imgToBase64": true,
    "markdown.extension.syntax.decorationFileSizeLimit": 50000000,
    "markdown.extension.katex.macros": {
    }
}
```

## Environment

- Markdown All in One v3.4.3
- Vscode 1.68.1
- OS: Windows_NT is32 10.0.19044
- Electron: 17.4.7
- Chromium: 98.0.4758.141
- Node.js: 16.13.0

## Diagnostic data

[Console.log](https://github.com/yzhang-gh/vscode-markdown/files/9029000/Console.log)

**Comment by yzhang-gh** [comment]
Thanks for the report.

It would be helpful if you could provide such a folder (with dummy Markdown files) for issue reproduction.

**Comment by mimmori** [comment]
Attached are the test files created to reproduce the issue.

Inside the archive there are two folders:

1. bug: contains 250 md files to convert the batch;
2. out: the export folder created to check for the bug.

Further information: the bug is present only on the machine that uses windows, trying on Mac OS and Linux everything works correctly.

[test_files.zip](https://github.com/yzhang-gh/vscode-markdown/files/9036807/test_files.zip)

**Comment by yzhang-gh** [comment]
Thanks for the test files. I can confirm this bug on Windows.

**Comment by mimmori** [comment]
Is there any update?

**Comment by yzhang-gh** [comment]
Thanks for the reminder.

I just checked it on my Windows machine and it seems to work well now.

Version: 1.75.1 (user setup)
Commit: 441438abd1ac652551dbe4d408dfcec8a499b8bf
Date: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 10.0.22621
Sandboxed: No

**Comment by mimmori** [comment]
Perfect thank you very much!
