### ISSUE TITLE
lack some katex function auto completion

### ISSUE THREAD

**Issue by Vincent0706** [yzhang-gh/vscode-markdown#1149]
## Proposal

I found the auto completion lack some Katex function, such as `\pmb` .
Whether can add some Katex funtion ?

 [Katex Supported Functions](https://katex.org/docs/supported.html)

**Comment by yzhang-gh** [comment]
Thanks for the report.

The KaTeX functions are stored here

https://github.com/yzhang-gh/vscode-markdown/blob/ff0e18ff018c88e99c38a2686c63536f0df9d4a4/src/completion.ts#L23-L37

We update it from the KaTeX website from time to time.

**Comment by yzhang-gh** [comment]
Please check out the [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/2854872575).
