### ISSUE TITLE
Keyboard Shortcut for Hyperlinking

### ISSUE THREAD

**Issue by TrekkieByDay** [yzhang-gh/vscode-markdown#1151]
Is this on the roadmap? In Caret, for example, Ctrl+K automatically wraps the the selection in a hypterlink notation.

**Comment by yzhang-gh** [comment]
You can easily paste a link "onto" the selected text

Please see https://github.com/yzhang-gh/vscode-markdown#others

**Comment by ulivz** [comment]
`Paste link on selected text` does not work on my Mac, and I cannot found the shortcut setting.
