### ISSUE TITLE
Image size extension not working in export to PDF, works with HTML

### ISSUE THREAD

**Issue by ChristopheBronner** [yzhang-gh/vscode-markdown#1154]
## Problem

When exporting to HTML, the image links are correctly transformed into images with the proper size but the PDF export renders the links as text.

## How to reproduce

With the following markdown: `![icon](../resources/icons/java.svg =x24)` using the [image size extension](https://github.com/mjbvz/vscode-markdown-image-size).

The HTML outputs `<img src="file:///absolute\path\to\the\resources\icons\java.svg" alt="icon" height="24">` but the pdf outputs this:

![image](https://user-images.githubusercontent.com/108481932/182222187-06251524-cca6-490e-86aa-553dae193d6c.png)

### Workspace

```jsonc
{
    "markdown.extension.toc.levels": "2..6",
    "markdownlint.config": {
        "MD024": {
            "siblings_only": true
        }
    }
}
```

The rest is Default.

## Environment

Version: 1.70.0-insider (user setup)
Commit: 12b08be500f8a307f30e92cbc3ee39ba115eab69
Date: 2022-07-29T10:47:14.408Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.22000

## Diagnostic data

None.

**Comment by yzhang-gh** [comment]
This extension hasn't yet provided the "export to PDF" feature as we are not satisfied with the solution. So the PDF must have been generated by other extensions.

**Comment by ChristopheBronner** [comment]
Ah then you may consider this a request for an export to PDF feature because so far you're the only extension providing correct behavior!

**Comment by yzhang-gh** [comment]
Thanks for the suggestion. This is an important feature request although we do not find a good solution so far.

Let's merge this into #270, #875.
