### ISSUE TITLE
Incorrect second-level list renumbering on line delete

### ISSUE THREAD

**Issue by Smiley43210** [yzhang-gh/vscode-markdown#1155]
## Problem
An issue occurs with the automatic renumbering feature of ordered lists. When removing an entire line containing a top level list item, the automatic renumbering does not restart numbering between second level lists, and incorrectly "continues" the numbering instead.

At first glance, #668 appears as a related issue; however, I believe this is a separate issue.

## How to reproduce
Start with this markdown:
```md
1. Item to be deleted
2. First level 1
	1. Second level 1
	2. Second level 2
3. First level 2
	1. Second level 1
	2. Second level 2
3. First level 3
	1. Second level 1
	2. Second level 2
```
Then, delete the entire line containing `Item to be deleted`. Observe that the items within `First level 2` and `First level 3` are incorrectly numbered.
**Expected output:**
```md
1. First level 1
	1. Second level 1
	2. Second level 2
2. First level 2
	1. Second level 1
	2. Second level 2
3. First level 3
	1. Second level 1
	2. Second level 2
```
**Actual output:**
```md
1. First level 1
	1. Second level 1
	2. Second level 2
2. First level 2
	3. Second level 1
	4. Second level 2
3. First level 3
	5. Second level 1
	6. Second level 2
```
### GIF Demonstration
![Export](https://user-images.githubusercontent.com/1026173/183322305-98d66091-fae8-44e5-80f9-3d6c7c06191d.gif)

## Configuration
Default. (Tested on fresh install of VS Code with only this extension installed)

## Environment
- Markdown All in One: 3.4.3
- VS Code: 1.70.0 (user setup)
- OS: Windows 10 Pro, Version 21H2, Build 19044.1826, 64-bit

## Diagnostic data
No relevant messages in the developer console log.

**Comment by yzhang-gh** [comment]
You are right. That is a bug.

**Comment by yzhang-gh** [comment]
Please try our the [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/2852193722).

**Comment by Naitreey** [comment]
Hi @yzhang-gh , it looks like with the latest release (3.5.0) the bug is partially fixed. While the second-level numbered list renumbering works fine by now, the more deeply nested ones still break.

![CleanShot 2023-03-05 at 17 56 56](https://user-images.githubusercontent.com/10528297/222953689-bda699bd-f42e-4fa6-9a2c-f640c925713b.gif)

**Comment by yzhang-gh** [comment]
Thanks. Please try out the latest dev build.
