### ISSUE TITLE
Auto change comma have problem.

### ISSUE THREAD

**Issue by Vincent0706** [yzhang-gh/vscode-markdown#1157]
## Problem
Auto change comma have problem.

## How to reproduce

In Chinese mode, if you input the Chinese comma between numbers, vscode will auto change it to English number. But when I enable the Markdown All in One, that function will have some error.

You can try this input sequence in Chinese input mode: `1` , `，`(Chinese comma), `2` 
Disable the Markdown All in One, it will show like this: `1,2`. 
But if enable the Markdown All in One, it will show like this:  `1，,` (the first comma is Chinese comma, and the second comma is English comma)

## Configuration

Default

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Do you have more information about the "auto change comma" feature? (VS Code's changelog or an issue link)

**Comment by Vincent0706** [comment]
I find that this is related to the Chinese input software. If I close the Intelligent adjustment of digital post punctuation function of input software, and input `1` , `，` (Chinese comma) and `2` , it will show `1，2` .
I guess is this function have conflict with Markdown All in One.

This is the introduction of SougoInput.
![image](https://user-images.githubusercontent.com/82581024/184064589-4ea3e12d-f1e1-4f88-b5ce-8668818c6d99.png)

**Comment by yzhang-gh** [comment]
Then it makes sense. The input method probably deletes some characters in this case (and then adds other characters), which may conflict with the `onBackspaceKey` function in this extension. There are other input methods are known to have the similar issue. You can choose to delete that keybinding https://github.com/yzhang-gh/vscode-markdown/issues/617#issuecomment-585629661. Please see #200 for more information.
