### ISSUE TITLE
launch error "Cannot read properties of undefined (reading 'document')"

### ISSUE THREAD

**Issue by mrking646** [yzhang-gh/vscode-markdown#1158]
Hi after installed, I can not open this extension. Here is the error screenshot:
![image](https://user-images.githubusercontent.com/18710733/184172481-6e81e126-6b6b-4359-9ef4-a3008850a8f1.png)

<img width="506" alt="markdownErr" src="https://user-images.githubusercontent.com/18710733/184171994-f5eacfe3-547b-48d7-bb98-b4e27e9fde4d.png">

## Configuration

```jsonc

```

## Diagnostic data

```log

```

**Comment by yzhang-gh** [comment]
I have no idea what is the cause. You can try to reinstall this extension (uninstall, restart VS Code, and install).

**Comment by mrking646** [comment]
i have tried reinstall the extension, reinstall vscode, and uninstall the extension then restart the vscode and reinstall the extension, all failed



---Original---
From: "Yu ***@***.***&gt;
Date: Fri, Aug 12, 2022 00:47 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [yzhang-gh/vscode-markdown] launch error "Cannot read propertiesof undefined (reading 'document')" (Issue #1158)




 
I have no idea what is the cause. You can try to reinstall this extension (uninstall, restart VS Code, and install).

**Comment by yzhang-gh** [comment]
When will this happen? everytime you open a Markdown file? or when you execute a command?

Also, can you try to disable all other extensions temporarily (to make sure you have a clean install)?

**Comment by mrking646** [comment]
thanks, solved by reboot my laptop.

**Comment by GrahamLimber** [comment]
> When will this happen? everytime you open a Markdown file? or when you execute a command?
> 
> Also, can you try to disable all other extensions temporarily (to make sure you have a clean install)?

It happens for me (on a Mac) when I run the command with a markdown preview view open at the same time. I close the preview view and then it all works fine.
