### ISSUE TITLE
UTF-8 Characters are removed from Table of Contents IDs

### ISSUE THREAD

**Issue by nbouvrette** [yzhang-gh/vscode-markdown#1159]
## Problem

When a header contains UTF-8 characters, they are removed from the "Table of Contents" creation functionality

Seems related to https://github.com/yzhang-gh/vscode-markdown/issues/78

## How to reproduce

Create a header called `## Project structure 🏗️` then try to generate the table of content and it will create:

`  - [Project structure 🏗️](#project-structure-️)`

<img width="415" alt="image" src="https://user-images.githubusercontent.com/6453322/184673744-f8326457-3f89-4fae-9420-36194f1ffc94.png">

## Configuration

Default

## Environment

Latest version

## Diagnostic data

Not applicable

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Did you select `github` as the slugify style? It is as expected as GitHub some remove the emoji from the anchor. If you change the slugify mode to `vscode`, you can get a different output.

**Comment by nbouvrette** [comment]
Oh actually I didn't know Github did this - this works perfectly for what I need! sorry for opening this ticket and thank for the great plugin
