### ISSUE TITLE
Reduce extension package size

### ISSUE THREAD

**Issue by kidonng** [yzhang-gh/vscode-markdown#1161]
## Proposal

I noticed in the latest version (3.4.3) there are some files which should be excluded from the extension package:

```shellsession
$ du -sh ~/.vscode/extensions/yzhang.markdown-all-in-one-*/* | sort -h | tail -n5
320K	/Users/kid/.vscode/extensions/yzhang.markdown-all-in-one-3.4.3/node_modules
1.1M	/Users/kid/.vscode/extensions/yzhang.markdown-all-in-one-3.4.3/tmp
1.4M	/Users/kid/.vscode/extensions/yzhang.markdown-all-in-one-3.4.3/dist
1.6M	/Users/kid/.vscode/extensions/yzhang.markdown-all-in-one-3.4.3/images
4.6M	total
```

- `tmp`: contains cache and logs dates back to `20201213T213910`. Curious to know how it makes into the package.
- `images`: contains images not required by the extension itself. Excluding them doesn't prevent them from showing in VSCode or marketplace.

**Comment by yzhang-gh** [comment]
Thanks for the suggestion. I have excluded the `images` folder and the `.vsix` is 700+ kb now (used to be ~2 mb).

The `tmp` folder is not part of the extension and may be created by VS Code at runtime.

The change has been shipped with the pre-release version.
