### ISSUE TITLE
Numbered lists with incorrect numbers

### ISSUE THREAD

**Issue by Sleepdealr** [yzhang-gh/vscode-markdown#1162]
## Problem

Numbered lists in preview do not have the same numbers as in code.

## How to reproduce
File:
```md
1. foo
2. bar
4. baz
```

Output:
```
1. foo
2. bar
3. baz
 ```
Expected:
```
1. foo
2. bar
4. baz
```
## Configuration

Default

## Environment

MD All in One ver 3.4.3 

## Diagnostic data

N/A

**Comment by yzhang-gh** [comment]
This is the Markdown syntax (https://spec.commonmark.org/0.30/#ordered-list).

You can paste your test snippet in the GitHub comment box and click "preview"

**Comment by Sleepdealr** [comment]
Gotcha, what would be the correct way of using arbitrary list numbers, if it's possible?

**Comment by yzhang-gh** [comment]
You need to use raw HTML (probably with extra CSS). IMHO, it doesn't worth it.

**Comment by Sleepdealr** [comment]
Ah alright, thanks!
