### ISSUE TITLE
Suggestion: pressing `~` with selected content should strikethrough

### ISSUE THREAD

**Issue by zardoy** [yzhang-gh/vscode-markdown#1165]
## Proposal

Hey! I've literally run of available shortcuts on my keyboard, so I can't really use command for this one.

Also it seems to be logical, since builtin markdown-basics ext also does wrap selection on pressing `*`!

For example: `test` (press `*`) -> `*test*`
I want: `test` (press `~`) -> `~~test~~`

**Comment by zardoy** [comment]
it seems there is no way to do this since `surroundingPairs` are [hardcoded](https://github.com/microsoft/vscode/blob/bf18ad0634b0a07defa3edd732f16384cbef6a0a/extensions/markdown-basics/language-configuration.json#L38) in vscode and `onDidChangeTextDocument` requires too much hacks such as storing previous editor content in some var.

Is it worth do implement it?

**Comment by talks2much** [comment]
Thanks for mentioning. You wont believe me, but Im actually using this shorcut, but with `markdown.extension.editing.toggleStrikethrough`. Its from here: https://github.com/yzhang-gh/vscode-markdown/issues/35#issuecomment-329934709 but adding `editorHasSelection` was really good idea

**Comment by yzhang-gh** [comment]
Hi all, thanks for the input. I agree that `markdown.extension.editing.toggleStrikethrough` may be the better choice.
