### ISSUE TITLE
Print to HTML: style configuration and TOC on Sidebar

### ISSUE THREAD

**Issue by pablobato** [yzhang-gh/vscode-markdown#1167]
## Proposal

Hi! It would be really usefull if the format of the printed HTML could be modified.
Another useful feature is the TOC on a SideBar.
Thanks

**Comment by yzhang-gh** [comment]
Thanks.

> It would be really usefull if the format of the printed HTML could be modified

I don't quite understand. Did you mean CSS? It can be set with the option `markdown.styles` (provided by VS Code itself).

> Another useful feature is the TOC on a SideBar

I believe it has also been provided by VS Code. https://code.visualstudio.com/docs/languages/markdown#_document-outline

**Comment by yzhang-gh** [comment]
Alright, I kind of understand your second point now, a TOC in the exported HTML. It can be achieved with extra scripts, e.g. toc.js

**Comment by pablobato** [comment]
I see, thanks. I am pretty new to all this, could you recomend me a source to look it up?
Thanks, and sorry for the inconvinience

**Comment by yzhang-gh** [comment]
No worries. You can start with the VS Code's official tutorial https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview.

**Comment by pablobato** [comment]
thanks!! :)
