### ISSUE TITLE
Table of Contents turns automatically.

### ISSUE THREAD

**Issue by lzaquine** [yzhang-gh/vscode-markdown#1168]
## Problem

Table of Contents (out of date) - whenever I save my file, it becomes (up to date), but it turns everything into the same category even though they aren't.

## How to reproduce

What it was supposed to be
(out of date) 
- [Consultancy :man_office_worker:](#consultancy-man_office_worker-broad-dizzy)
  - [Broad :dizzy:](#consultancy-man_office_worker-broad-dizzy)
- [Developer Tools :hammer_and_wrench:](#developer-tools-hammer_and_wrench)

becomes
(up to date)
- [Tech Companies in Portugal :portugal:](#tech-companies-in-portugal-portugal)
    - [Categories](#categories)
    - [Consultancy :man_office_worker:](#consultancy-man_office_worker-broad-dizzy)
    - [Broad :dizzy:](#consultancy-man_office_worker-broad-dizzy)
    - [Developer Tools :hammer_and_wrench:](#developer-tools-hammer_and_wrench)

**Comment by yzhang-gh** [comment]
It might be a bug. Could you provide a minimal example document for reproduction?
