### ISSUE TITLE
Add better code completion for code blocks

### ISSUE THREAD

**Issue by igorwojda** [yzhang-gh/vscode-markdown#1171]
## Proposal

Typing 3 backtick characters should add closing backticks and allow selecting the code block type.

## References

![Hint](https://user-images.githubusercontent.com/530122/190124964-50dc6b40-cdde-407b-80c1-4149340179c4.gif)

Actions in the above:
1. Type backtick 3 times in  `InteliJ` (IDE adds closing backticks and allows to a selection of the type of the code block)
2. Press enter to select the type of code block (code reformat happens)

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

VS Code provides built-in snippets for common Markdown blocks (command `Snippets: Insert Snippet`)

![image](https://user-images.githubusercontent.com/7588612/190192935-3a7809b4-d126-4f6a-bb8e-164f4797688e.png)

You can also assign a keybinding to a certain snippet https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets

**Comment by igorwojda** [comment]
Thx this will work as well, but note that the initial proposal is much more convenient. 
I guess what we need to do here is to run `fenced codeblock` snippset after typing 3d `` ` `` character

**Comment by yzhang-gh** [comment]
You can simply add

```json
{
	"fenced code": {
		"prefix": "```",
		"body": "```${1|python,kotlin,markdown,...|}\n$0\n```"
	}
}
```

to your user snippets.

https://user-images.githubusercontent.com/7588612/191244203-a9f438bf-6ab3-407a-b845-3b785c13f946.mp4

You may find https://code.visualstudio.com/docs/editor/userdefinedsnippets helpful.
