### ISSUE TITLE
Custom task list check box options (e.g., bullet journal)

### ISSUE THREAD

**Issue by doylejg** [yzhang-gh/vscode-markdown#1173]
## Proposal

Introduce an option for various "check box" entries. e.g., 
```
- [ ] Incomplete Task
- [x] Completed Task
- [>] Deferred Task (or Migrated)
- [<] Scheduled Task 
- [-] Abandoned Task
- ~~[ ] Abandoned Task~~
```

These are just example ideas using bullet journal, but option to customize would be nice. The abandoned task seems possibly consistent with the feature request in Issue #992. 

If this is outside the scope of the extension, `mihaiconstantin.bujo` is an option for the BJ functionality. 

## References

[Example list paradigm](https://diaryofajournalplanner.com/wp-content/uploads/2018/11/bullet-journal-key-original.jpg.webp)

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

However, this feature requires changing the Markdown syntax, which goes beyond the scope of this extension. You can find more information from https://github.com/yzhang-gh/vscode-markdown#q-which-markdown-syntax-is-supported.

**Comment by doylejg** [comment]
I understand. Thank you for your response.
