### ISSUE TITLE
"omit in toc" appears in HTML title

### ISSUE THREAD

**Issue by NeoFantom** [yzhang-gh/vscode-markdown#1175]
## Problem
 
When using the extension's command `print current document to HTML`, the output HTML file's title in `<title></title>` tag contains the comment `<!-- omit in toc -->`, which is not intended by the user.

Notice that the HTML page looks clean in the browser, except when you hover your mouse over the tab and see the page's title.

## Reproduce

Just use this simple MWE.

```markdown
# Notes <!-- omit in toc -->

- [Chapter 1](#chapter-1)

# Chapter 1

France is a European nation.
```

**Comment by yzhang-gh** [comment]
Thanks for your report. It has been fixed now and is available in the [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/3145372818).
