### ISSUE TITLE
Duplication of various VS Code UI elements

### ISSUE THREAD

**Issue by traits** [yzhang-gh/vscode-markdown#1179]
Type: <b>Bug</b>

See  https://github.com/microsoft/vscode/issues/162615

Extension version: 3.4.3
VS Code version: Code 1.72.0 (64bbfbf67ada9953918d72e1df2f4d8e537d340e, 2022-10-04T23:20:39.912Z)
OS version: Windows_NT x64 10.0.19044
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.27GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yzhang-gh** [comment]
I do not quite believe this is caused (at least solely) by this extension as this one does nothing related (as you may already notice).

The VS Code's Bisect tool is nice. However, it doesn't seem that it always gives a meaningful result

https://github.com/yzhang-gh/vscode-markdown/issues/1160#issuecomment-1218072575
https://github.com/yzhang-gh/vscode-markdown/issues/1142#issuecomment-1170828383
https://github.com/yzhang-gh/vscode-markdown/issues/1041#issuecomment-974789844
https://github.com/yzhang-gh/vscode-markdown/issues/1037#issue-1048963912

For your issue, I would suggest doing more checks, e.g. I would disable all extensions except for this one (I don't think the reported issue will appear at this time), and then enable other extensions in a similar Bisect fashion until you reproduce the issue again.

**Comment by traits** [comment]
The effect is reproducible without any usage of bisect by simply disabling markdown-all. It requires a restart of vscode afterwards, but then all the formerly duplicated menu entries are no longer there (duplicates and original ones). Re-enabling in this new session is bringing them all back, but again as duplicates, as stated in the bug report.

**Comment by traits** [comment]
If your extension is the only one, a lot menu items are not there from the beginning, including the buggy ones from the context menu. So, while your guess regarding some more general issue seems to have some credit, I simply don't have time and knowledge (I'm not even a JavaScript programmer) to investigate the issue in more detail. I can simply help with some sparse information fragments. 

For me it seems now, the UI elements in question are originally provided by some language-related extension (my code is Python, so for something like reference finding pylance would be a candidate?) and it _could_ be possible, they are colliding with your and perhaps other extensions. But this is something, I cannot answer. The other possibility, that markdown-all causes this alone as soon as such menu entries appear remains open, IMHO. The owner of the linked parallel vscode issue should know other ways to nail down the culprit.

I would suggest leaving this topic open until the content of our discussion has been incorporated by the aforementioned vscode's own bug assignees. Perhaps it will provide them with minimal additional input.

**Comment by yzhang-gh** [comment]
> I simply don't have time and knowledge (I'm not even a JavaScript programmer) to investigate the issue in more detail

No worries, let's leave this open to see whether there is more information from other users.

**Comment by realqpat** [comment]
I had the same issue as reported here https://github.com/microsoft/vscode/issues/162615

It turns out that I have 2 `Reference Search View`
I disabled the one from microsoft and that fixed my issue 

![image](https://github.com/yzhang-gh/vscode-markdown/assets/92816716/7ff14e15-a7c9-4be1-8089-4d91f0c96dba)

**Comment by yzhang-gh** [comment]
Thanks for the update!
