### ISSUE TITLE
Unresponsive in Developers: Show Running Extensions (slow response)

### ISSUE THREAD

**Issue by ZacksAmber** [yzhang-gh/vscode-markdown#1180]
- Issue Type: `Bug`
- Extension Name: `markdown-all-in-one`
- Extension Version: `3.4.3`
- OS Version: `Darwin x64 21.6.0`
- VS Code version: `1.71.2`

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 50,
		"activateCallTime": 15,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "yzhang.markdown-all-in-one",
				"_lower": "yzhang.markdown-all-in-one"
			},
			"activationEvent": "onLanguage:markdown"
		}
	},
	"runtimeErrors": [],
	"runningLocation": {
		"affinity": 0,
		"kind": 1
	}
}
```

**Comment by yzhang-gh** [comment]
Thanks for the report.

However, this doesn't contain enough information, e.g. what files you are working on, what commands you execute, etc. (in other words, how I can reproduce the issue.)

**Comment by ZacksAmber** [comment]
Thanks for responding.
Every .md files (even a new empty .md file) is extremely slow when I enable
Markdown All in One, especially when I try to make a new line or delete
words.



The following is a screenshot in Developers: Show Running Extensions.

[image: Screen Shot 2022-10-07 at 8.46.43 AM.png]

The following is my machine info:

```sh
Software:

    System Software Overview:

      System Version: macOS 12.6 (21G115)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Zacks' MBP 16
      User Name: Zacks Shen (zacks)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 2 days 20:27

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,1
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2.4 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 64 GB
      System Firmware Version: 1731.140.2.0.0 (iBridge: 19.16.16067.0.0,0)
      OS Loader Version: 540.120.3~22
```

**Comment by yzhang-gh** [comment]
Already, your screenshot happens to have the information I need 😂. Please disable "Code Spell Checker" to check whether the performance issue still exists.

related #423

**Comment by ZacksAmber** [comment]
@yzhang-gh Seems like it works. Thank you so much! I cannot work without Markdown All in One. 😂
