### ISSUE TITLE
Allow Markdown All in One to be activated inmediately when a user opens a folder that does not contain `.md` files but do have files of md variants

### ISSUE THREAD

**Issue by CLRafaelR** [yzhang-gh/vscode-markdown#1182]
### Proposal

Currently, Markdown All in One will not be activated when a user opens a folder that does not contain `.md` files. As shown in a figure below, we can tell that from observing the "Runtime Status" tab in the extention tab that appears in such a folder. 

![image](https://user-images.githubusercontent.com/42314553/194848323-ab26d3ad-9b9c-4433-b2ce-09e7f103ec4a.png)

However, it is very convenient that Markdown All in One is activated even when a user opens a folder that has no `.md` files but files of md variants (i.e. [R Markdown](https://rmarkdown.rstudio.com/) files with `.Rmd` or `.rmd` extentions). Or, is it possible to manually activate Markdown All in One in a folder in which there is no `.md` files?

### Other information

Markdown All in One is usable and useful when a user edits files of md variants, as well as pure `.md` files. For example, 
I overwrite key binding settings so that I can use Markdown All in One's functionalities (e.g. <kbd>Ctrl/Cmd</kbd> + <kbd>b</kbd> to make letters bold, and <kbd>Ctrl/Cmd</kbd> + <kbd>i</kbd> to italicise letters):

```json
[
  {
    "key": "ctrl+i",
    "command": "markdown.extension.editing.toggleItalic",
    "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown' || editorTextFocus && !editorReadonly && editorLangId == 'rmd'"
  },
  {
    "key": "ctrl+b",
    "command": "markdown.extension.editing.toggleBold",
    "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown' || editorTextFocus && !editorReadonly && editorLangId == 'rmd'"
  },
  {
    "key": "ctrl+m",
    "command": "markdown.extension.editing.toggleMath",
    "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown' || editorTextFocus && !editorReadonly && editorLangId == 'rmd'"
  },
  {
    "key": "",
    "command": "markdown.extension.editing.toggleList",
    "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown' || editorTextFocus && !editorReadonly && editorLangId == 'rmd'"
  },
  {
  "key": "alt+enter",
  "command": "r.runSelectionRetainCursor",
  "when": "editorTextFocus && editorLangId == 'rmd'"
},
{
  "key": "ctrl+shift+alt+enter",
  "command": "r.runAllChunks",
  "when": "editorTextFocus && editorLangId == 'rmd'"
}
]
```

**Comment by yzhang-gh** [comment]
Thanks for your feedback.

I planned to add such an option in the next release https://github.com/yzhang-gh/vscode-markdown/issues/618#issuecomment-1135311605, although didn't get the time to do it, probably this weekend.

**Comment by yzhang-gh** [comment]
Let's merge this into #618

**Comment by CLRafaelR** [comment]
@yzhang-gh Thank you for your arrangement and resolving the issue. I checked out #618 .
