### ISSUE TITLE
should not delete block quote marker followed by an empty line

### ISSUE THREAD

**Issue by lutts** [yzhang-gh/vscode-markdown#1183]
when type a block quote marker with nothing followed, then press Enter, the block quote marker will be automatically deleted, this is not expected and incorrect. 

current Markdown All In One behavior:

1. input the following:
```markdown
      > block quote paragraph one
```
2. then input a single block quote mark followed with nothing, then press Enter
```markdown
      >
```
Oops!  this block quote mark will automatically removed

In Markdown, block quote should always preceded by block quote marker, including empty line

for  example: 

```markdown
> block quote paragraph one
>
> block quote paragraph two
```

will rendered to HTML:

```html
<blockquote>
<p>block quote paragraph one</p>
<p>block quote paragraph two</p>
</blockquote>
```

if the second block quote marker is missing

```markdown
> block quote paragraph one

> block quote paragraph two
```

this will be rendered to two blockquote blocks:

```html
<blockquote>
<p>block quote paragraph one</p>
</blockquote>
<blockquote>
<p>block quote paragraph two</p>
</blockquote>
```

**Comment by yzhang-gh** [comment]
Thanks for the feedback. If I recall, it has been fixed in the preview version. You can install it from VS Code's extension page.

**Comment by lutts** [comment]
yes, fixed in the preview version, close this issue, thanks
