### ISSUE TITLE
Unable to display second-level selection menu of `\begin{...}` environment

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [yzhang-gh/vscode-markdown#1185]
### What's the problem

After typing `\begin{}` in math equations, the extension shows a list of available math environments, but is unable to suggest as I continue to type. Normally, if I continue to type `al` in `{}`, the extension should suggest `align`, `aligned`, etc, but it does not show this second-level menu. This problem has existed for a long time (several months) on my machine; but I am not sure whether this is due to an upper level bug in VS Code. 

### GIF demonstration

![bug](https://user-images.githubusercontent.com/43436192/195828954-9c02a770-b046-45f9-a514-c112e2e0f0e8.gif)

### Version

Markdown-all-in-one: 3.5.0-7cda0ac941c125d75a075ac1d21bfbd71b19b17a
VS Code: 1.72.1, commit 129500ee4c8ab7263461ffe327268ba56b9f210d
OS: macOS 12.6 (Darwin arm64 21.6.0)

**Comment by yzhang-gh** [comment]
Thanks for the report.

I also see the suggestions disappear on typing `a`, although they appear again after `al`. To me it is more likely a VS Code bug as I just provide the snippets. Can you try these settings?

```
    "[markdown]": {
        "editor.quickSuggestions": {
            "comments": "on",
            "strings": "on",
            "other": "on"
        }
    },
```

**Comment by yzhang-gh** [comment]
Can you try to add some user-defined snippets and check whether they work well? https://code.visualstudio.com/docs/editor/userdefinedsnippets#_choice

**Comment by yzhang-gh** [comment]
Then you can check whether it is because of other extensions, e.g. disable all extensions, and then half of them, and so on. (https://code.visualstudio.com/blogs/2021/02/16/extension-bisect, although its result is not always correct)
