### ISSUE TITLE
using lots of cpu

### ISSUE THREAD

**Issue by phelma** [yzhang-gh/vscode-markdown#1186]
Type: <b>Bug</b>

doing anything in vscode seems to using 100-200% cpu with this extension enabled

Extension version: 3.4.3
VS Code version: Code 1.72.2 (d045a5eda657f4d7b676dedbfa7aab8207f8a075, 2022-10-12T22:16:30.254Z)
OS version: Darwin x64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 7, 7|
|Memory (System)|16.00GB (2.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yzhang-gh** [comment]
I guess you have other extensions installed, e.g. some Spell Checkers or other Markdown extensions.
