### ISSUE TITLE
checkbox inline code outline wrong selection

### ISSUE THREAD

**Issue by ziloen** [yzhang-gh/vscode-markdown#1187]
### What's the problem

checkbox inline code outline wrong selection
![image](https://user-images.githubusercontent.com/34268416/196854773-3dd8e10b-1ea8-4290-af37-b5aef6089784.png)

### What's the expected result

`a` and back tic has outline

### How to reproduce

1.  write a checkbox 
2.  write inline code

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should already been fixed in the Preview version of this extension. Could you check it? (The preview version can be installed in the VS Code extension page).

#1178

**Comment by ziloen** [comment]
![image](https://user-images.githubusercontent.com/34268416/197097618-10b9a2f0-3f4f-4b37-9daa-0a8223d16d0b.png)
Thanks for your reply, but it looks still there, version 3.4.4

**Comment by yzhang-gh** [comment]
Thanks for the verification. Will take a look later.

**Comment by yzhang-gh** [comment]
Please check out the [latest dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/3306551326) (in the Artifacts section).

**Comment by ziloen** [comment]
![image](https://user-images.githubusercontent.com/34268416/197391673-cfb6b1a3-ba82-441a-ab5c-8c5bcec406cb.png)
Backtick outline range correct now, great job, thank you a lot!
