### ISSUE TITLE
Executing `markdown.extension.editing.toggleList` will remove the indentation from the indented texts

### ISSUE THREAD

**Issue by Yarakashi-Kikohshi** [yzhang-gh/vscode-markdown#1203]
Executing `markdown.extension.editing.toggleList` will remove the indentation from the indented texts.

Disabling other extensions will still cause this problem.

## To reproduce

1. Create indented texts as below
    ```markdown
    list 1
    list 2
        list 2-1
        list 2-2
    list 3
    ```
1. Select all rows
1. Excute `markdown.extension.editing.toggleList`
1. Indentation is removed...
    ```markdown
    - list 1
    - list 2
    - list 2-1
    - list 2-2
    - list 3
    ```

![toggleList](https://user-images.githubusercontent.com/75878492/204099809-a76ec6f7-cb3a-4030-8ded-696142fd106e.gif)

Expected behavior:

```markdown
- list 1
- list 2
    - list 2-1
    - list 2-2
- list 3
```

## Version

- Markdown All in One: 3.5.0
- VS Code
    ```
    Version  : 1.73.0 (user setup)
    Commit   : 8fa188b2b301d36553cbc9ce1b0a146ccb93351f
    Date     : 2022-11-01T15: 34: 06.111Z
    Electron : 19.0.17
    Chromium : 102.0.5005.167
    Node.js  : 16.14.2
    V8       : 10.2.154.15-electron.0
    OS       : Windows_NT x64 10.0.22000
    Sandboxed: No
    ```

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

I am not surprised as this feature was only designed to deal with the one-line case when introduced.

**Comment by Yarakashi-Kikohshi** [comment]
> I am not surprised as this feature was only designed to deal with the one-line case when introduced.

Previous versions behaved as expected, so I thought this was the intended usage.

### Additional report:

Previous versions did not remove indentation when `toggleList` was executed for multiple rows. It doesn't remove indentation, even when done for single row.

|     previous version (3.4.3)      |
| :-------------------------------: |
| ![previous version toggleList][1] |

[1]: https://user-images.githubusercontent.com/75878492/204118886-9f2e4bff-9fc3-47cc-8967-386e95193caf.gif

On the other hand, the current version removes indentation even on single row.

|      current version (3.5)       |
| :------------------------------: |
| ![current version toggleList][2] |

[2]: https://user-images.githubusercontent.com/75878492/204118887-0024aa78-234a-4ce5-88bd-a844e28caf83.gif

**Comment by yzhang-gh** [comment]
😱

**Comment by yzhang-gh** [comment]
[dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by Yarakashi-Kikohshi** [comment]
I tried the dev build by installing it with VSIX. I verified that this gives the expected behavior.
Thank you :relaxed:
