### ISSUE TITLE
Use "1. " when adding a new ordered list item instead of auto incrementing number

### ISSUE THREAD

**Issue by nickvigilante** [yzhang-gh/vscode-markdown#1206]
### Proposal

Add a setting that will allow users to place `1. ` on a new line instead of auto-incrementing a list number when working with an ordered list.

### Other information

My company's standards for writing ordered lists is using `1. ` for each list item:

```
1. One item
1. Another item
1. A third item
```

Jekyll roughly matches what is effectively `^[1-9]\d*\. [^$]+` in order to determine if an item belongs to an ordered list, and it doesn't care about the sequence of numbers or the numbers themselves when it comes to the final rendering. Thus, the following:

```
3. One item
5. Another item
6. A third item
```

Would produce the following in the rendered site:

```
1. One item
2. Another item
3. A third item
```

**Comment by yzhang-gh** [comment]
You may try changing `orderedList.marker`.

**Comment by nickvigilante** [comment]
Beautiful! I must have overlooked that during my first pass of the settings. Thank you!
