### ISSUE TITLE
生成的目录中，无法正确处理数学公式

### ISSUE THREAD

**Issue by lambdaphy** [yzhang-gh/vscode-markdown#1207]
正文中标题中有数学符号，例如$\boldsymbol{x}$，生成的目录中，会把“\”变成“\\\\”导致目录中的数学符号无法正确显示。

**Comment by yzhang-gh** [comment]
谢谢反馈。这是一个已知的问题，因为底层逻辑大重构了一次，但是我自己又一直没有时间仔细看

见 #903
