### ISSUE TITLE
"omit in toc" does not work in v3.5.0

### ISSUE THREAD

**Issue by luksi1** [yzhang-gh/vscode-markdown#1208]
### What's the problem

v3.5.0 does to support `<!-- omit in toc -->`

### What's the expected result

`<!-- omit in toc -->` will ignore this line from it's table of contents menu

### How to reproduce

1. Install v3.5.0 (the latest version of the extension in VSCode)
2. Add `<!-- omit in toc -->` to the side of markdown title, i e `# hello world` and then create a table of contents

This code will not work:

```yaml

# Hello <!-- omit in toc -->

# World
```

Running the extension will still produce "Hello" in the TOC.

**Comment by luksi1** [comment]
We reproduced it locally with a project we were working on, but after you were unable to reproduce it, we tried doing it with a bare-bones project and were unable to reproduce it on our end. Closing this.

**Comment by yuntan** [comment]
I've reproduced the issue by v3.6.2.

Once I've run "Update Table Of Contents", the extension removes header marked as "omit in toc", but I've saved file it adds the header. It happens nevertheless when `toc.updateOnSave: false`.

Should I create new issue?

**Comment by yzhang-gh** [comment]
@yuntan It seems that there are other extensions changing the TOC on file save. I would suggest checking this first.

**Comment by yuntan** [comment]
@yzhang-gh Thank you for your reply. The cause of this problem is Markdown Preview Enhanced changes TOC on save. I'll check how to switch off TOC generation feature of MPE.
