### ISSUE TITLE
`'markdown.extension.syntax.decorations' has been deprecated.` notification will show every time i open vscode

### ISSUE THREAD

**Issue by ks4na** [yzhang-gh/vscode-markdown#1216]
### What's the problem

`'markdown.extension.syntax.decorations' has been deprecated.` notification will show every time i open vscode:

<img width="671" alt="截屏2022-12-18 13 38 02" src="https://user-images.githubusercontent.com/28475898/208283528-d0ba1c5b-1e49-4c3b-8b27-c4bdf78648bd.png">

this option is not enabled :

<img width="922" alt="截屏2022-12-18 13 38 42" src="https://user-images.githubusercontent.com/28475898/208283586-2f237e0a-9630-41a8-9a50-5af7d6de29e4.png">

### What's the expected result

not show this notification every time i open vscode

### How to reproduce

1. ...
2. ...

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Can you open the `settings.json` with VS Code command `Preferences: Open User Settings (JSON)` and check whether there is a `markdown.extension.syntax.decorations` entry?

**Comment by ks4na** [comment]
yes, there is one line :

```
"markdown.extension.syntax.decorations": false,
```

notification will not show when this line is removed. 

thanks!
