### ISSUE TITLE
Extension host is crashing

### ISSUE THREAD

**Issue by aamironline** [yzhang-gh/vscode-markdown#1219]
Type: <b>Bug</b>

Causing extension host to crash!

Extension version: 3.5.0
VS Code version: Code 1.74.2 (e8a3071ea4344d9d48ef8a4df2c097372b0c5161, 2022-12-20T10:29:14.590Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5700G with Radeon Graphics          (16 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|27.90GB (10.70GB free)|
|Process Argv|--crash-reporter-id 9a6a2593-4ae8-46ac-b78c-e34e064d3785|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vsdfh931cf:30280410
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaac:30438847
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
vsccc:30610678
pyindex848cf:30577861
nodejswelcome1:30587005
2e4cg342:30602488
3d0df643:30613357
f6dab269:30613381
fim-prod:30623723
vscsbc:30628655

```

</details>

**Comment by aamironline** [comment]
React Native Tools by Microsoft caused the issue! The issue was fixed after it was disabled!
![image](https://user-images.githubusercontent.com/134134/209911830-6bc7139d-647b-427b-9a19-af8e4f0087f0.png)

Console!
![image](https://user-images.githubusercontent.com/134134/209911932-eb9fcbfd-4bf0-4281-9ae8-14da47a65e50.png)

**Comment by yzhang-gh** [comment]
Thanks for the information. It seems that it is not an issue of this extension.
