### ISSUE TITLE
Preview and Scrolling issues

### ISSUE THREAD

**Issue by SirClickALot** [yzhang-gh/vscode-markdown#1221]
I am using version 3.5.0 and I seem to struggle with scrolling the Preview tab.

The problem occurs when I the EDITING TAB on the LEFT and the PREVIEW tab on the RIGHT.

THE PROBLEM: When I scroll down vertically through the Preview tab, while at the same time seeing the EDIT tab move in sympathy, at a certain way down, the document seems to 'jump' back up and I lose my place.

Further experimenting shows that this only happens when I and trying to scroll QUICKLY through the Preview.

The problem happens when I use the keyboard arrows keys or the mouse wheel to scroll down through the Preview but NOT when I explicitly drag the vertical scroll bar on the Preview window.

It might seem like a minor issue but's it's actually making it usable for me.

Thanks

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

In short, it is a VS Code "feature", but does not always work as expected. Please see my old answer https://stackoverflow.com/questions/61831197/vscode-jumpiness-when-editing-markdown-and-preview-pane-is-open/62077986#62077986

**Comment by yzhang-gh** [comment]
Just a bit of [programmer humor](https://www.urbandictionary.com/define.php?term=It%27s%20not%20a%20bug%2C%20it%27s%20a%20feature) 🤣️

The bug has been there for many years https://github.com/microsoft/vscode/issues/50934, and might have not ever been (completely) solved.
