### ISSUE TITLE
Missing bottom margin while list has only one item

### ISSUE THREAD

**Issue by afxres** [yzhang-gh/vscode-markdown#1222]
### What's the problem
Missing bottom margin while list has only one item
![image](https://user-images.githubusercontent.com/28796288/211012541-977c390c-99e6-4602-844a-a53a1485a2df.png)

Missing ``<p>`` tag on printed HTML file
![image](https://user-images.githubusercontent.com/28796288/211011955-d7340679-e9de-4fc8-8392-179b8f748d11.png)

### What's the expected result
Bottom margin should shown normally

### How to reproduce
Simple markdown like this
```
- Item 1
  - Sub Item 1-1  
    Some Text

- Item 2
  - Sub Item 2-1  
    Some Text

  - Sub Item 2-2  
    Some Text

- Item 3
```

### Other information
N/A

**Comment by yzhang-gh** [comment]
This is the CommonMark spec. Please find more information here https://spec.commonmark.org/0.30/#why-is-a-spec-needed-

And an online [demo](https://markdown-it.github.io/#md3=%7B%22source%22%3A%22-%20Item%201%5Cn%20%20-%20Sub%20Item%201-1%20%20%5Cn%20%20%20%20Some%20Text%5Cn%5Cn-%20Item%202%5Cn%20%20-%20Sub%20Item%202-1%20%20%5Cn%20%20%20%20Some%20Text%5Cn%5Cn%20%20-%20Sub%20Item%202-2%20%20%5Cn%20%20%20%20Some%20Text%5Cn%5Cn-%20Item%203%22%2C%22defaults%22%3A%7B%22html%22%3Afalse%2C%22xhtmlOut%22%3Afalse%2C%22breaks%22%3Afalse%2C%22langPrefix%22%3A%22language-%22%2C%22linkify%22%3Atrue%2C%22typographer%22%3Atrue%2C%22_highlight%22%3Atrue%2C%22_strict%22%3Afalse%2C%22_view%22%3A%22html%22%7D%7D)

**Comment by afxres** [comment]
So, is this a CSS issue?
Some online editor (like [stackedit.io](https://stackedit.io/) and [markdowntohtml.com](https://markdowntohtml.com/)) has set both ``margin-top`` and ``margin-bottom`` on ``<p>`` elements.
![image](https://user-images.githubusercontent.com/28796288/211073547-fe99a6d1-6c82-4a9a-8a3d-91f54d90cc50.png)
![image](https://user-images.githubusercontent.com/28796288/211073757-38f599d0-03ce-40e4-aea8-2276987913bb.png)
But, in this plugin generated HTML file, only ``margin-bottom`` was set on ``<p>`` elements
![image](https://user-images.githubusercontent.com/28796288/211074307-6bc24ea2-7976-4774-b831-58952fa2404a.png)

**Comment by yzhang-gh** [comment]
I meant the generated HTML (`<p>` or not) is as designed (by the Markdown spec).

With CSS, you can have different looking for the same HTML. This extension simply uses the VS Code's default CSS. You can change it with your own CSS files, or other VS Code extensions[^1]. They will be included when exporting HTML using this extension.

[^1]: https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview

**Comment by afxres** [comment]
Thanks
