### ISSUE TITLE
ToC failed to parse document from a specific code block.

### ISSUE THREAD

**Issue by cwahn** [yzhang-gh/vscode-markdown#1227]
### What's the problem
The table of contents failed to parse the document properly, skipping some parts of the document as if they don't exist. 

### What's the expected result
The whole document should get parsed properly for ToC.

### How to reproduce
1. It happens on my personal [note on github](https://github.com/cwahn/notes/blob/main/haskell/cis-194/lecture-3-recursion-patterns-polymorphism-and-the-prelude.md)
2. ToC is ignoring the document from the third heading 'Numeric Typeclasses'  to the third heading 'Writing Partial Functions'.
3. It parses the document properly if one removes the first bullet with the code block; there are other bullets with code blocks right after it, but they do not cause the issue. 

### Other information
It seems the code block in the first bullet after the third heading 'Numeric Typeclasses' causes the issue, but can't find any further condition.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

I checked your file on GitHub but didn't see the above issue. Could you make a copy of it and keep only a short version that can still reproduce this issue?
