### ISSUE TITLE
ToC inserting backslashes before LaTeX commands in headings

### ISSUE THREAD

**Issue by AzureArmageddon** [yzhang-gh/vscode-markdown#1228]
### What's the problem

Using LaTeX in my headings is causing the extension to forcibly insert a backslash before the command (since I have the extension set to update ToC on save). This has the consequence of the ToC line rendering incorrectly as the command gets escaped. This goes for any LaTeX command.

#### Input Heading

```md
## $\LaTeX$ and Stuff
```

#### Output ToC Line

```md
- [$\\LaTeX$ and Stuff](latex-and-stuff)
```

#### Input Heading

```md
## $\LaTeX$ and Stuff
```

#### Output ToC line

```md
- [$\LaTeX$ and Stuff](latex-and-stuff)
```

### How to reproduce

See above.

### Other information

I'm not sure how to get my VS Code environment information.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This is a known bug due to a fundamental change in this extension. I agree with you that the LaTeX commands should not be escaped. However, I haven't got enough time to look into it so it remains until now.

Let's track this in #903.
