### ISSUE TITLE
wrong command "formateTable"

### ISSUE THREAD

**Issue by JiongBull** [yzhang-gh/vscode-markdown#1234]
### What's the problem

vscode warns me "command 'markdownExtended.formateTable" not found'  after i executed "formattable" in the console.

<img width="260" alt="image" src="https://user-images.githubusercontent.com/4413502/217733057-5086348d-da06-45b4-9c01-76e00b5b4877.png">

### Other information

Maybe the command name isn't format'**e**'Table but formatTable?

**Comment by yzhang-gh** [comment]
It is from another extension (whose name is "markdown extended" I guess).

**Comment by JiongBull** [comment]
sorry for that? by the way, how to format table with "All In One"?

**Comment by yzhang-gh** [comment]
This extension registers a "formatter" with VS Code. So just use the ["format document" command](https://code.visualstudio.com/docs/editor/codebasics#_formatting) from VS Code.
