### ISSUE TITLE
Cannot disable TOC generation in a document

### ISSUE THREAD

**Issue by johanngerell** [yzhang-gh/vscode-markdown#1236]
![Animation](https://user-images.githubusercontent.com/247305/218418830-de086083-9ac6-4575-951b-7f142f76b9ad.gif)

### What's the problem

I added a TOC to my document at some point recently. Now I don't want the TOC to be present any more, but the first bullet list in my document is auto converted to a TOC at every document save.

### What's the expected result

A bullet list further down in a document should not be treated as a TOC

**Comment by bbugh** [comment]
We're having the same issue. A README we've been regularly updating is suddenly having a list midway down the file overwritten with a TOC. We didn't originally have a TOC. Inserting a TOC at the top using the command palette now has two TOCs. 

Here is a minimal reproduction document:

```md
## Some Other Place

### Another Headline

1. [For Example](#some-other-place)
2. More information about this thing
3. Another thing about something else
4. Somewhere else [some link](#another-headline)
```

**Comment by yzhang-gh** [comment]
@bbugh Thanks for the minimal reproduction example!

It is hard to completely avoid this kind of false alarm if we want to detect the TOC automatically. We have some filtering rules, e.g., the first line of the list should match the first heading, and the overall similarity should be larger than 0.5. So a little difference like

```markdown
## Some Other Place

### Another Headline

1. [For Example](#some-other-place2)  <!-- here -->
2. More information about this thing
3. Another thing about something else
4. Somewhere else [some link](#another-headline)
```

or

```markdown
## Some Other Place

### Another Headline

1. [For Example](#some-other-place)
2. More information about this thing
3. Another thing about something else
4. Somewhere else [some link](#another-headline)
5. balabala  <!-- or here -->
```

will change the results.

You can also use `<!-- no toc -->` to explicitly suppress the TOC detection right before a list, like this

```markdown
## Some Other Place

### Another Headline

<!-- no toc -->
1. [For Example](#some-other-place)
2. More information about this thing
3. Another thing about something else
4. Somewhere else [some link](#another-headline)
```

**Comment by johanngerell** [comment]
> It is hard to completely avoid this kind of false alarm if we want to detect the TOC automatically

I want to use everything in the extension **but** automatic TOC in my doc. I *don't* want a TOC, like **ever**.

Is it possible to add an extension setting for that? I don't want to add ugly `<!-- no toc -->` to every doc.

**Comment by yzhang-gh** [comment]
You can change `toc.levels` to `2..1` so there will never be "valid" headings.

**Comment by ackvf** [comment]
Maybe choose an opposite approach, don't generate TOC at all, unless you opt-in?

```
<!-- autogenerated toc -->
```

This will become a placeholder for the autogenerated toc. Everyone reading the document will now know that this section is autogenerated and that they should not touch it.
