### ISSUE TITLE
bug in auto-completion

### ISSUE THREAD

**Issue by dualer** [yzhang-gh/vscode-markdown#1239]
### What's the problem
公式补全有时无法正常使用, 如下图所示, 需要额外按向下键, 选择才行

![gif](https://user-images.githubusercontent.com/85242539/219951259-40c4526f-79ca-4c7b-9b7f-33d3d7870fe7.gif)

### How to reproduce

1. ...
2. ...

**Comment by yzhang-gh** [comment]
我这测试没有问题，可能是你那边有其它因素影响

![completion](https://user-images.githubusercontent.com/7588612/219953049-ed9d0c89-ad82-4cf6-8287-3fc5862ab9f6.gif)

**Comment by dualer** [comment]
找到问题的解决方案了, 见 https://blog.csdn.net/qq_41786057/article/details/129055808

**Comment by yzhang-gh** [comment]
嗯，合理
