### ISSUE TITLE
Inconsistent <img> handling

### ISSUE THREAD

**Issue by jaime-olivares** [yzhang-gh/vscode-markdown#124]
When using &lt;img&gt; tags and `markdown.extension.print.absoluteImgPath` is set to `true` by default,  some of them are rendered with their absolute path (file://) while others aren't.

I found that those not having `width` or `height` attributes are rendered incorrectly (showing relative paths). See the attached screenshot.

This problem doesn't show up when setting `markdown.extension.print.absoluteImgPath` to `false`. In that case, all images are rendered with relative paths.

<img width="1282" alt="screen shot 2018-03-20 at 10 28 56" src="https://user-images.githubusercontent.com/6194083/37665703-d9f33f52-2c2b-11e8-90c1-d47252278520.png">

**Comment by neilsustc** [comment]
Thank you. And you can try [the preview version](https://github.com/neilsustc/vscode-markdown/releases/download/beta/markdown-all-in-one-1.1.0-fix124.vsix) now.
