### ISSUE TITLE
the extension interferes with text expansions

### ISSUE THREAD

**Issue by lwd27** [yzhang-gh/vscode-markdown#1243]
### What's the problem

The extension is interfering with text expansions. I have a number of text expansions using Keyboard Maestro. When this extension is enabled they don't work. For example the string ';cell' should expand into my cell phone number. Instead it comes out as ';cel12 1234' It's similar for any of the expansions I've tried: they come out garbled.
I tried changing the trigger from ';cell' to 'aaaa' but it makes no difference. Still doesn't work

### What's the expected result

The Markdown extension should not interfere with text expansions.

### How to reproduce

Can't think how you would reproduce unless you are using Keyboard Maestro as well.
I looked at the keyboard shortcuts for the extension but I don't see anything that should conflict with the text expansion.
With Keyboard Maestro:
1. make a macro to enter a text string when typing some trigger. For example you type 'aaaa' and have it expand to your phone number.
2. type the trigger and observe

### Other information

I would really like to use your extension, but this is a deal-breaker. I need my text expansions.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This is a known issue due to the implementation under the current VS Code APIs. You can find more information from #200. For a workaround, you may try something like https://github.com/yzhang-gh/vscode-markdown/issues/200#issuecomment-493770482.

Let's merge this issue into that one.

**Comment by lwd27** [comment]
Thanks for your quick reply!
