### ISSUE TITLE
Support newline character when paste link on selected text

### ISSUE THREAD

**Issue by fanlushuai** [yzhang-gh/vscode-markdown#1244]
### What's the problem
If there is a newline character at the end of the address, it is invalid when pasting. 

### What's the expected result

Want to add the feature of removing newline character 

### How to reproduce

https://github.com/yzhang-gh/vscode-markdown/blob/fc04a9c77197406a584f27a10266feda765c6982/src/formatting.ts#L341-L344

``` ts
// Maybe can fix it with the following code
 const text = await env.clipboard.readText(); 
 const textTrimed=text.trim();
 if (isSingleLink(textTrimed)) { 
     return commands.executeCommand("editor.action.insertSnippet", { "snippet": `[$TM_SELECTED_TEXT$0](${textTrimed})` }); 
 } 

```

**Comment by yzhang-gh** [comment]
Thanks for the suggestion!

Wanna open a PR 😉?
