### ISSUE TITLE
请问目前此插件是否能实现快速折叠的功能？

### ISSUE THREAD

**Issue by rusty-peilin** [yzhang-gh/vscode-markdown#1249]
如题，我想实现一键折叠一个md文件，即只显示每段带了#的标题部分，而未带#的内容部分全部被折叠。请问目前使用此插件有办法实现这个需求吗？

问了下chatgpt，说是可以使用此库实现此功能，但按照它的提示并没有达到效果，所以特地来请教下。

**Comment by yzhang-gh** [comment]
> 问了下 chatgpt，说是可以使用此库实现此功能

🤣

VS Code 自己有提供 fold level x 的命令，可以根据你的需要选择对应的层级

**Comment by rusty-peilin** [comment]
> 

感谢，已搜到，cmd 0折叠所有，cmd j恢复。
