### ISSUE TITLE
search.exclude ignored

### ISSUE THREAD

**Issue by gmccullo** [yzhang-gh/vscode-markdown#1252]
### What's the problem

Intellisense does not respect search.exclude.

### What's the expected result

Intellisense should not show excluded files.

### How to reproduce

1. Enable markdown.extension.completion.respectVscodeSearchExclude
2. Add "**/.git" to search.exclude setting
3. In a markdown file start a link: [foobar](65)
4. ctrl-space to open path completion. 
5. Assuming there are files in the git repo with "65" in the name, you should not see any of them.

### Other information

Here's my settings:

```json
	"markdown.extension.completion.respectVscodeSearchExclude": true,
	"search.exclude": {
		"**/.git": true
	},
```

With extension enabled:

![image](https://user-images.githubusercontent.com/26315643/226533320-a90bee67-7e24-46a8-810a-70df6d3bf089.png)

With extension disabled:

![image](https://user-images.githubusercontent.com/26315643/226533442-0318edee-7668-4068-8188-aacdcc12b5dd.png)

**Comment by yzhang-gh** [comment]
I've excluded the `.git` folder by default. Please try out v3.5.1.

**Comment by gmccullo** [comment]
So I don't know if it's 3.5.1 or not, but now I don't get Intellisense path completion in markdown at all, not on anything.

![image](https://user-images.githubusercontent.com/26315643/228164710-dcc13652-08c8-492c-abda-91ce106b6c70.png)

**Comment by yzhang-gh** [comment]
I have disabled the file auto-completion (except for images) in v3.5.1 because VS Code added its own support a year ago https://github.com/microsoft/vscode/issues/140602

For your special case, I guess it is not supported to link files from another folder even they are in the same workspace.

**Comment by yzhang-gh** [comment]
I have packaged a standalone version with the file completions enabled, [maio-3.5.1-enable-completion.vsix.zip](https://github.com/yzhang-gh/vscode-markdown/files/11102691/maio-3.5.1-enable-completion.vsix.zip). Not sure whether it can provide suggestions for files in other folders (although to my memory it shouldn't).

(Please note that in the long run, this feature may eventually be removed.)

**Comment by gmccullo** [comment]
Cool. What's your plan tho? Are you planning to roll this back into the main product for now? Also would you consider contributing this improvement to path completions to vscode? For people like me who use markdown as a knowledge base, this is a pain point. I feel like the result of me complaining about a relatively unimportant bug has been to reduce the quality of this outstanding extension.
