### ISSUE TITLE
\Braket command broken in the preview (upgrading KaTeX needed)

### ISSUE THREAD

**Issue by wuchichou** [yzhang-gh/vscode-markdown#1253]
### What's the problem

In the preview, the command `\Braket` is broken, which is supported by KaTeX since KaTeX 0.15.6. Current KaTeX version is 0.16.4, however, 0.15.3 is used here in vscode-markdown. It is one big version behind. Would be better if the KaTeX could be upgraded.

### What's the expected result

`\Braket` and other commands supported by KaTeX works in the preview.

### How to reproduce

1. Input `$\Braket{a|b}$` in a markdown file and preview it.

**Comment by yzhang-gh** [comment]
Thanks. Will update the KaTeX version this weekend.

**Comment by yzhang-gh** [comment]
Please use v3.5.1
