### ISSUE TITLE
String encode is wrong,How to change it?

### ISSUE THREAD

**Issue by MangoFF** [yzhang-gh/vscode-markdown#1256]
### What's the problem
It is good to use this,thanks.

But when I try to index  path in markdown that include Chinese,It work like this:

### 1.3 [更宽：Inception](./%E7%BB%8F%E5%85%B8%E5%88%86%E7%B1%BB%E7%BD%91%E7%BB%9C/%E6%9B%B4%E5%AE%BD%EF%BC%9AInception.md)

It seems that the string encode is wrong but I don't know where to change it
### How to reproduce

1. ...
2. ...

**Comment by MangoFF** [comment]
OK,when I submit it changed, ths issue is some chinese changed like this %E4%BC%98%E5%8C%96%E5%99%A8

**Comment by yzhang-gh** [comment]
（可以用中文描述）

猜测你的 `toc.slugifyMode` 是 `vscode`，改成 `github` 可以达到你想要的效果

**Comment by MangoFF** [comment]
"markdown.extension.toc.slugifyMode": "github",  我的vs设置是这样
`就是平时显示中文并不会乱码，但是在快捷输入（如提示词弹出来后按enter确认），输入中的中文是乱码的。
就像这样
[查看图片](https://github.com/MangoFF/Interview_mangoX/blob/main/test.jpg)

**Comment by yzhang-gh** [comment]
我这好像没问题

![image](https://user-images.githubusercontent.com/7588612/229348422-1188d3ec-5ed2-402b-a870-008d94f21299.png)

这个插件的 v3.5.1 去掉了文件和章节的自动补全，你现在看到的应该是 VS Code 自带的补全，与这个插件没有关系了
