### ISSUE TITLE
Path autocompletion does not work anymore as expected

### ISSUE THREAD

**Issue by A5kar** [yzhang-gh/vscode-markdown#1258]
### What's the problem

Path autocompletion does not work anymore as expected.

I have a local Jekyll instance organised as follows

_posts/<*.markdown files>
_site/<yyyy/mm/dd/*.html files>

When I am working on markdown files, the only way to create a proper link is replicating exactly all paths (e.g. writing _site/2022/03/04/test.html), instead of simply start typing the filename (test) and obtain the suggestions with the full path.

### What's the expected result

Being able to find the proper reference by writing directly the filename, instead of writing the exact path.

### How to reproduce

1. open markdown
2. start creating a reference e.g. "[test](test
3. observe that _site/2022/03/04/test.html is not being suggested, unless I navigate through each folder first

### Other information

macOS 13.3 (Ventura)
VS Code 1.77
Markdown All in One 3.5.1

**Comment by gentksb** [comment]
Hey, I'm still facing conflict of VSCode built-in and the extension. I'm at 3.5.1.
How to disable the option at latest version?

**Comment by yzhang-gh** [comment]
I don't quite understand your question. What is the conflict? The auto-completion from this extension has been disabled in v3.5.1 so you will only see suggestions from VS Code. Do you mean you can still see duplicated suggestions?

**Comment by gentksb** [comment]
sorry for unclear sentence.
Yes, I still see duplicated suggestions. Attach a capture later.

**Comment by A5kar** [comment]
In my case, I had downgraded to 3.5.0. You can do it directly in the vscode, under the extension settings. I still did not find a convenient way to work with vscode built in path completion.

**Comment by gentksb** [comment]
@yzhang-gh 
![image](https://user-images.githubusercontent.com/36843875/232272958-f9deb85f-4608-46b9-ba00-868a7b2748a9.png)

**Comment by yzhang-gh** [comment]
Thanks. That's because the image path completion was not disabled (the same for math completion).

You can check out the [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/4712666109) (download at the bottom of the page), which now disables the image path completion.

And FYI @A5kar, the latest dev build also includes a new (experimental) option `completion.enabled`. You can set it to `true` to restore the auto-completion feature of this extension.

**Comment by gentksb** [comment]
Thanks @yzhang-gh, dev build works for me!
image path completion become single suggestion per file (only vscode built-in completion).
