### ISSUE TITLE
preview error with spaces.

### ISSUE THREAD

**Issue by kawayikyubey** [yzhang-gh/vscode-markdown#1260]
### What's the problem

When there is too much text in a single line, there will be a preview error with spaces.

This problem will disappear when the width of the preview bar is increased.

The spaces are displayed too wide, I don't know if this is a bug that needs to be fixed。

### What's the expected result

correct preview

### How to reproduce

example1：
![image](https://user-images.githubusercontent.com/62306835/230428149-6eb84c24-d289-46d5-b225-b06c57712fe4.png)

example2：
![image](https://user-images.githubusercontent.com/62306835/230428277-65c3fbb2-546a-468b-ab97-48dc7abee072.png)

use text：

```
`word word word word word wordwordwordwordwordwordwordwordwordwordword word word wordword word word word`

asd sas dssd aa a aaaaaaasassssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssdasssssssss
```

**Comment by kawayikyubey** [comment]
> ![图片](https://user-images.githubusercontent.com/7588612/230456491-47b8203e-ab29-43a7-b83b-3c21b7c0e3a0.png)
> 
> 您可能使用过其他 Markdown 扩展。请参阅https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview

Well, after some troubleshooting, I was surprised to find that the problem comes from Markdown+Math.

**Comment by yzhang-gh** [comment]
Thanks for the information. However, the Markdown+Math extension/repository is not maintained by me so I cannot "transfer" this issue there. You can simply open a new issue there and paste the same text.
