### ISSUE TITLE
`markdownPreviewFocus` context don't work anymore, please change it to `activeWebviewPanelId == 'markdown.preview'``

### ISSUE THREAD

**Issue by HaujetZhao** [yzhang-gh/vscode-markdown#1263]
Type: <b>Bug</b>

The command: 

{
  "key": "ctrl+k v",
  "command": "markdown.extension.closePreview",
  "when": "markdownPreviewFocus"
}

use context `markdownPreviewFocus` that don't work now. 

Please use `activeWebviewPanelId == 'markdown.preview'` instead. 

Extension version: 3.5.1
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:02.548Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 4600H with Radeon Graphics          (12 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.37GB (8.28GB free)|
|Process Argv|--crash-reporter-id 082b1596-7408-4001-b8bf-dc4e9bc6a70e --crash-reporter-id 082b1596-7408-4001-b8bf-dc4e9bc6a70e|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263cf:30335440
vscoreces:30445986
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
pynewext54:30695312
azure-dev_surveyone:30548225
vsccc:30610678
nodejswelcome1:30587005
282f8724:30602487
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
2i9eh265:30646982
vsccsb:30705552
functionswalk:30687959
pythonms35:30701012
pythonfmttext:30710681

```

</details>

**Comment by yzhang-gh** [comment]
Thanks for the information.

Interesting to know that. Could you point me to the related documentation or vscode issue? (e.g., we need to know in which version this change was made)

And would you like to open a PR for it 😉? (and then we can remove the `markdownPreviewFocus` implemented by ourselves.)

**Comment by HaujetZhao** [comment]
没有文档，只是单纯不能用，官网参考也没有这一条，然后我用官网方法找了一个可用的。

https://code.visualstudio.com/api/references/when-clause-contexts#inspect-context-keys-utility


但是和这个 issue 有关：


https://github.com/microsoft/vscode/issues/131289#issuecomment-1205441130


https://github.com/microsoft/vscode/pull/156944

**Comment by yzhang-gh** [comment]
谢谢，想起来 `markdownPreviewFocus` 也是 VS Code 之前本身提供的，这个插件自己实现的可能是在更早的时候了

**Comment by yzhang-gh** [comment]
开发版本中应该已更新
