### ISSUE TITLE
找不到命令

### ISSUE THREAD

**Issue by 295060456** [yzhang-gh/vscode-markdown#1265]
Markdown All in One can not work
![telegram-cloud-photo-size-5-6197463583235880197-y](https://user-images.githubusercontent.com/13795605/233149985-16917644-faad-42e1-8fba-5ea26b81c1b8.jpg)

**Comment by yzhang-gh** [comment]
[TOC] 并不是这个插件提供的功能。你可以尝试完全退出 VS Code 再打开，看看能不能找到命令

**Comment by 295060456** [comment]
我的错，要点进这个md文件，指向你需要进行插入目录的地方

**Comment by 295060456** [comment]
![image](https://user-images.githubusercontent.com/13795605/235809973-d12727ff-e6f9-4077-aa80-d18ccbb003c4.png)
插件也启用了，没有找到命令

**Comment by yzhang-gh** [comment]
显然你现在打开的这个页面并不是 Markdown 页面，是某个 office 插件提供的

**Comment by 295060456** [comment]
> 

嗯？不是这么玩的么？

**Comment by yzhang-gh** [comment]
你现在的页面是这个插件 https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-office 提供的（本质上是一个网页，不再是原生编辑器范围了）。如果你使用这个模式的话就需要看看它的说明，如果想使用 VS Code 编辑器就需要修改它的设置

![image](https://user-images.githubusercontent.com/7588612/235844191-8bfd8e17-8161-47a8-9960-2fd89ee75b59.png)

**Comment by 295060456** [comment]
我也发现了这个问题。我用VS打开的时候，有些时候会莫名调起你说的那个”office“插件，有些时候又没有

**Comment by Alan-Ben** [comment]
还有可能是VSCode版本太旧
