### ISSUE TITLE
Cannot type Vietnamese

### ISSUE THREAD

**Issue by dragonlong206** [yzhang-gh/vscode-markdown#1272]
### What's the problem
When typing Vietnamese, the text is automatically converted to ANSI text, loosing Vietnamese accent marks. Please view the attached video:
https://user-images.githubusercontent.com/11483447/236594672-5127cd68-631a-4da0-bb19-94d7d39373fa.mp4

### What's the expected result
Can type Vietnamese like when the extension is disabled.

### How to reproduce

1. Install extension to VSCode.
2. Install Vietnamese keyboard tool Unikey https://www.unikey.org/en/download.html
3. Create new markdown file.
4. Start to type Vietnamese. The issue happens as the attached video.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Please refer to #200 for more information. A simple workaround is to delete the `markdown.extension.onBackspaceKey` key binding.
