### ISSUE TITLE
Ctrl + k to add hyperlink

### ISSUE THREAD

**Issue by talal-najam** [yzhang-gh/vscode-markdown#1277]
### Proposal
It is a common feature in text editors, as well as Gitlab markdown, where highlighting a text and pressing ctrl + k allows adding a link to the text e.g. highlighting 'text' and pressing ctrl + k should result in \[text\](<text focus here>). Could we add this to the extension please?

Awesome work btw! :)

**Comment by yzhang-gh** [comment]
Thanks for the suggestion.

We already have a similar feature that you can directly paste a link "onto" the selected text. Could you try and see whether it works for you?

**Comment by talal-najam** [comment]
Thanks! ah yea that seems handy. Cheers
