### ISSUE TITLE
Editing Jupyter Markdown cell opens second notebook plus Markdown preview

### ISSUE THREAD

**Issue by paul-rogers** [yzhang-gh/vscode-markdown#1282]
### What's the problem

I have both Jupyter Notebook and this extension installed. When I edit a Markdown cell in a notebook, VS Code opens a second copy of the notebook in a new tab, along with a Markdown preview of just that cell. Back on the original notebook, the cell does switch to edit mode.

I have a Markdown file open in another tab, and a preview for that file also open. I suspect that this extension is helpfully opening a preview of the Notebook markdown editor. Suggestion: exclude Markdown in notebooks from the automatic preview feature.

There is no obvious explanation for opening the second copy of the notebook.

I'm using a vertical two-pane layout: a Python and Markdown file in the left pane, my notebook and preview in the right. When I edit Markdown in the notebook, a third pane opens at the right: that is the pane that contains the "extra" notebook and the Markdown preview.

### What's the expected result

When editing a Markdown cell in a notebook, no preview pane opens: a Jupyter Notebook already has an equivalent feature built-in. Also, that second notebook tab should not open.

### How to reproduce

1. Install this extension
2. Install the Microsoft Jupyter extension. 
3. Create a Notebook
4. Create a Markdown file and preview. (You should now have a Markdown file open, a preview open and a Notebook open.)
5. In the notebook, edit a Markdown cell.
6. You should see the two "phantom" tabs open.

To verify:

1. Disable this extension.
2. Repeat steps 3-5 above.
3. No extra "phantom" tabs will open

### Workaround

Disable this extension. Rely on the built-in (?) Markdown preview instead which requires using the "Markdown: Open Preview to the Side" command to manually open a preview.

### Other information

VSCode version:

```text
Version: 1.78.2
Commit: b3e4e68a0bc097f0ae7907b217c1119af9e03435
Date: 2023-05-10T14:47:05.613Z
Electron: 22.5.2
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 5.15.0-72-generic
Sandboxed: Yes
```

* Markdown All in One v3.5.1
* Jupyter v2023.4.1011241018

**Comment by yzhang-gh** [comment]
Thanks for the detailed feedback. This is possible as the auto-preview feature relies on the VS Code's context key, which may have been changed in recent releases. Can you check out the [latest dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/5029538459) and see whether it solves this issue?

**Comment by paul-rogers** [comment]
@yzhang-gh, I tried the latest version. The behavior still occurs. Again, disabling this extension prevents the extra tabs from opening.

**Comment by yzhang-gh** [comment]
I guess it is probably because VS Code decides to make the Jupyter Markdown cell behave just like a Markdown editor.

https://github.com/yzhang-gh/vscode-markdown/blob/47b30ace626dd13f60f5f26b09b2fa5bad8671ec/src/preview.ts#L58-L60

That's strange why a Jupyter tab passes this check.

(I may not have enough time to find it out but maybe we could get more insights from other users.)

**Comment by yzhang-gh** [comment]
> Just gave a try but failed. I refer to the docs of VS Code extensions and find out the `activeNotebookEditor: NotebookEditor | undefined` API in `window` namespace, which however is new and not yet available in VS Code 1.63. To solve this issue, I suggest making these changes in `vscode-markdown/src/preview.ts` and disable the auto-preview of notebooks:
> 
> ```ts
> function triggerAutoPreview(editor: vscode.TextEditor | undefined): void {
>     // new
>     if (vscode.window.activeNotebookEditor) {
>         return;
>     }
> 
>     if (!editor || editor.document.languageId !== "markdown") {
>         return;
>     }
>     ...
> ```

Looks reasonable to me, as we probably will never need to open a Markdown preview tab for a Jupyter Notebook editor.

> I believe this will work as long as we bump the target VS Code version of the extension to the latest one. Any plan for this?

Which version is required for the new API `activeNotebookEditor`?

**Comment by yzhang-gh** [comment]
Thanks.

> why don't we just use the latest version instead?

If we specify a newer vscode engine, the users who use the older VS Code versions (it is very common, e.g. on Linux) will not receive the extension update. So we usually only update the vscode API version when there is a major feature requiring it.

For this issue, I guess there might be other [context keys](https://code.visualstudio.com/api/references/when-clause-contexts) that can be used to check whether the current editor is a notebook editor. Although it is very likely the VS Code team hasn't updated the documentation.

**Comment by yzhang-gh** [comment]
You can use command `getContext` just like

https://github.com/yzhang-gh/vscode-markdown/blob/31f4d3e7f6165ddcd426763639b7506848b3c4cf/src/editor-context-service/i-context-service.ts#L51
