### ISSUE TITLE
Alt+C shortcut overrides Brazilian ç

### ISSUE THREAD

**Issue by angelod1as** [yzhang-gh/vscode-markdown#1285]
### Proposal

The Alt+C shortcut overrides Brazilian ç.

I propose changing it to a different shortcut.

Right now, it's used like this:

```
{
  "key": "alt+c",
  "command": "markdown.extension.checkTaskList"
}
```

### Other information

In mac, we can access some special characters using Alt+letter. For instance: 
- ç is done using alt + c; 
- å = alt + a
- œ = alt + q
- and so forth

While the other examples are not applicable to Brazilian language, the ç is a very important character, and overwriting it is a problem in our language.

### Manual solution

- Remove the keyboard shortcut for `markdown.extension.checkTaskList` manually.

**Comment by yzhang-gh** [comment]
Should have been fixed in the latest [dev build](https://github.com/yzhang-gh/vscode-markdown/actions/runs/5093226731).
