### ISSUE TITLE
Options to not include (1) top README heading or (2) the Table of Contents section itself in the Table of Contents

### ISSUE THREAD

**Issue by brandonmcconnell** [yzhang-gh/vscode-markdown#1287]
It would help to have the option to exclude these sections from the Table of Contents:
* the top README heading
* the Table of Contents section itself

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

We have a few (flexible) methods to omit certain sections from the TOC. For example:

If you usually write things like this

```md
# Top Heading

## Another Heading

in short, only the top heading is level 1
```

You may choose to set **`toc.levels`** to `2..6` so the TOC will treat level-2 as the root level.

Also, you can put a **`<!-- omit from toc -->`** comment right _above_ or _behind_ a certain heading to ignore the specific one.

In the future, we may support wildcards in the current **`toc.omittedFromToc`** option (see https://github.com/yzhang-gh/vscode-markdown/issues/723#issuecomment-811923635).

**Comment by yzhang-gh** [comment]
Let's track this in the above issue.
