### ISSUE TITLE
Laggy and slow editing with Quarto extension enabled

### ISSUE THREAD

**Issue by harrysw1729** [yzhang-gh/vscode-markdown#1292]
### What's the problem

Basic editing actions on `.qmd` files, such as backspacing and typing, are extremely laggy and slow when both the extension and the quarto extension are enabled. The issue disappeared when I disabled the Markdown All in One.

### What's the expected result

Extremely laggy and slow response to keyboard typing.

### How to reproduce

1. Enable the Quarto extension for VS Code
2. Enable Markdown All in One
3. Create a `.qmd` file
4. Start typing, and the issue would occur

### Other information

I am running VS Code `1.78.2 (Universal)` on macOS `13.4`. The version of Markdown All in One is `3.5.1`, and the version of the Quarto extension is `1.86.2`. The version of Quarto on my device is `1.3.361`.

Thanks for your help!

**Comment by yzhang-gh** [comment]
I installed the Quarto extension and could not reproduce this issue on my machine. Did you have other Markdown or spell checker extensions installed? Also, did you change the `extraLangIds` option? The `qmd` support is not enabled by default.

**Comment by harrysw1729** [comment]
I can confirm that the issue no longer exists since the Quarto extension was updated to 1.87.0 a few hours ago. 🥹
