### ISSUE TITLE
Incorrect font size of nested superscripts in markdown math when exporting HTML

### ISSUE THREAD

**Issue by andyluooo** [yzhang-gh/vscode-markdown#1295]
### What's the problem
When typing math block in markdown file, the nested superscripts (or subscripts) are rendered well in the preview tab, but with incorrect font size with the HTML file opening in browser. 

### What's the expected result
Make the HTML render behavior to match the preview tab.
Markdown scripts:

```markdown
$$x^{x^x}$$

$$2^{2^2}$$
```

Preview tab screen shot:
![preview tab](https://github.com/yzhang-gh/vscode-markdown/assets/128155646/909916e5-896c-4dc2-8b81-7036e9538dd3)

Browser screen shot:
![browser](https://github.com/yzhang-gh/vscode-markdown/assets/128155646/22ce9478-2dc4-4a3e-bd8f-f4682c3af969)
Obviously, the nested superscripts here are rendered the same font size, which is undesirable. 

### How to reproduce

1. type nested superscripts in .md file;
2. export HTML;
3. open HTML in Chrome (or Edge).

### Other information
Using Markdown+Math extension, v.2.7.4; 

```json
"markdown.math.enabled": false,
"markdown.extension.math.enabled": false,
```

Both the built-in markdown math and the markdown math of this extension are disabled.

**Comment by yzhang-gh** [comment]
I do not use the Markdown+Math extension, and I just checked that the exported HTML looks alright with the math support of this extension.

![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/cc15ea76-572e-4c4c-bec4-bbf0ba333a75)

Also, you may check whether there is any online CSS not correctly loaded because of a network issue (F12 in your browser).

**Comment by yzhang-gh** [comment]
[math.zip](https://github.com/yzhang-gh/vscode-markdown/files/11642145/math.zip)

What will it look like if you open this HTML in your browser?

**Comment by yzhang-gh** [comment]
> Also, you may check whether there is any online CSS not correctly loaded because of a network issue (F12 in your browser).

And you can see https://github.com/yzhang-gh/vscode-markdown/issues/1274#issuecomment-1568664422, #1127
