### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by AvinashMahala** [yzhang-gh/vscode-markdown#1300]
- Issue Type: `Performance`
- Extension Name: `markdown-all-in-one`
- Extension Version: `3.5.1`
- OS Version: `Windows_NT x64 10.0.22621`
- VS Code version: `1.78.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/abhi/AppData/Local/Temp/yzhang.markdown-all-in-one-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by yzhang-gh** [comment]
This is most likely not an issue of this extension.

Please refer to #711, #1226 etc.
