### ISSUE TITLE
Preview image 

### ISSUE THREAD

**Issue by obar1** [yzhang-gh/vscode-markdown#1302]
### Proposal

add option
<html>
<body>

markdown.extension.preview.Img| true | Preview image 
-- | -- | --

</body>
</html>

### Other information

handy to see image right away, of course - ideally add them under the img anchor

TobiasTao.vscode-md
has something similar called instant rendering

**Comment by yzhang-gh** [comment]
Thanks for the suggestion. Let's track this at #1191.
