### ISSUE TITLE
Wrong command label "open preview to the side" when setting is set to down

### ISSUE THREAD

**Issue by matter-it-does** [yzhang-gh/vscode-markdown#1303]
### What's the problem

As it follows from https://github.com/yzhang-gh/vscode-markdown/issues/767 
When "workbench.editor.openSideBySideDirection": "down",
the command label "Open preview to the side" is slightly wrong.

### What's the expected result

"open preview in split editor" or something ?  

### How to reproduce

1. Set "workbench.editor.openSideBySideDirection": "down",
2. Set language to markdown and in command palette bring up the preview command.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Do you mean the configuration description for `autoShowPreviewToSide`? This extension does not add extra "open preview" commands to VS Code.

**Comment by matter-it-does** [comment]
My bad! the command is from vscode probably. https://code.visualstudio.com/docs/languages/markdown#_markdown-preview 



>    Tip: You can also right-click on the editor Tab and select Open Preview (⇧⌘V) or use the Command Palette (⇧⌘P) to run the Markdown: Open Preview to the Side command (⌘K V).

**Comment by yzhang-gh** [comment]
That's true 😉.
