### ISSUE TITLE
User-defined macros in md-to-html conversion

### ISSUE THREAD

**Issue by jywu20** [yzhang-gh/vscode-markdown#1304]
### Proposal

Currently, user defined macros (in the  `markdown.extension.katex.macros` option in `.vscode/settings.json`) can be rendered in preview in VSCode, but these macro definitions seem to be not included when the "Print the current document to HTML" command is invoked. My proposal is to find a way to insert user defined macros to the HTML output as well.

**Comment by yzhang-gh** [comment]
Looks like you have the same issue as #1274. Could you also provide your minimal example files in that thread?
