### ISSUE TITLE
Print Document current document to HTML

### ISSUE THREAD

**Issue by JFaulk1434** [yzhang-gh/vscode-markdown#1310]
### What's the problem
Getting all VSCode styling in HTML when setting is turned off. 

### What's the expected result
For the first style tags to be empty. Basically line 6 - 695 is all styling which does not seem to apply regardless because when I open the HTML file it looks plain. 

### How to reproduce

1. Export to HTML
2. Look at everything between first style tag.

Here is a small sample : 
``` HTML
<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Murideo Python wrapper</title>
        <style>
/* From extension vscode.github */
/*---------------------------------------------------------------------------------------------
 *  Copyright (c) Microsoft Corporation. All rights reserved.
 *  Licensed under the MIT License. See License.txt in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

.vscode-dark img[src$=\#gh-light-mode-only],
.vscode-light img[src$=\#gh-dark-mode-only] {
	display: none;
}

/* From extension zhuangtongfa.material-theme */
.vscode-dark[data-vscode-theme-name="One Dark Pro Mix"].vscode-body, .vscode-dark[data-vscode-theme-name="One Dark Pro Flat"].vscode-body, .vscode-dark[data-vscode-theme-name="One Dark Pro Darker"].vscode-body, .vscode-dark[data-vscode-theme-name="One Dark Pro"].vscode-body {
  box-sizing: border-box;
  min-width: 200px;
}
.vscode-dark[data-vscode-theme-name="One Dark Pro Mix"].vscode-body blockquote, .vscode-dark[data-vscode-theme-name="One Dark Pro Flat"].vscode-body blockquote, .vscode-dark[data-vscode-theme-name="One Dark Pro Darker"].vscode-body blockquote, .vscode-dark[data-vscode-theme-name="One Dark Pro"].vscode-body blockquote {
  background-color: initial;
}
.vscode-dark[data-vscode-theme-name="One Dark Pro Mix"].vscode-body pre, .vscode-dark[data-vscode-theme-name="One Dark Pro Flat"].vscode-body pre, .vscode-dark[data-vscode-theme-name="One Dark Pro Darker"].vscode-body pre, .vscode-dark[data-vscode-theme-name="One Dark Pro"].vscode-body pre {
  color: initial;
}
.vscode-dark[data-vscode-theme-name="One Dark Pro Mix"].vscode-body code, .vscode-dark[data-vscode-theme-name="One Dark Pro Flat"].vscode-body code, .vscode-dark[data-vscode-theme-name="One Dark Pro Darker"].vscode-body code, .vscode-dark[data-vscode-theme-name="One Dark Pro"].vscode-body code {
  color: inherit;
}
.vscode-dark[data-vscode-theme-name="One Dark Pro Mix"].vscode-body pre code, .vscode-dark[data-vscode-theme-name="One Dark Pro Flat"].vscode-body pre code, .vscode-dark[data-vscode-theme-name="One Dark Pro Darker"].vscode-body pre code, .vscode-dark[data-vscode-theme-name="One Dark Pro"].vscode-body pre code {
  color: initial;
}
.vscode-dark[data-vscode-theme-name="One Dark Pro Mix"].vscode-body code > div, .vscode-dark[data-vscode-theme-name="One Dark Pro Flat"].vscode-body code > div, .vscode-dark[data-vscode-theme-name="One Dark Pro Darker"].vscode-body code > div, .vscode-dark[data-vscode-theme-name="One Dark Pro"].vscode-body code > div {
  background: none;
}
... Removed all the other lines to save the very long scroll...
</style>
        
        
        <style>
.task-list-item {
    list-style-type: none;
}

.task-list-item-checkbox {
    margin-left: -20px;
    vertical-align: middle;
    pointer-events: none;
}
</style>
```

### Other information

The goal would be to not have 690 lines of HTML that is not needed so to copy/paste the HTML into other programs is not so big. Here is the settings I changed:  `"markdown.extension.print.includeVscodeStylesheets": false`
On a side note this is probably the best addon i've used in VSCode. Now I can't document anything outside of Markdown.

**Comment by yzhang-gh** [comment]
Thank you.

The `includeVscodeStylesheets` controls the inclusion of two VS Code's base styles

https://github.com/yzhang-gh/vscode-markdown/blob/99f85cf9475d00ed6898ce74bad05128f1efee8f/src/print.ts#L237-L238

And the ~600 lines of styles in your file are from other extensions that contribute .css files to the VS Code's Markdown preview. Their .css files are included in the exported HTML in order to retain a similar looking as in VS Code (although they may not take effect).

May I know where you want to paste the HTML? And would you think it is useful to only export only pure HTML (without any CSS)? I have seen similar feature requests before. Note that some features may not work without CSS (e.g. math).

**Comment by JFaulk1434** [comment]
Yes I paste to a few different places, Basecamp which is a project management software that uses their own editor called Trix. And Zoho CRM which doesn't support Markdown either but does support HTML. So generally I write up a report in Markdown in VSCode, Export to HTML, Zoho - Copy/paste that html into Articles. Or in Basecamp - Open the HTML in chrome and copy/paste the text not the HTML. As far as just plain HTML not really sure what that would look like. I mean I want headers to be larger and unordered lists to be the dots. I believe that is part of the CSS? As far as colors, and fonts not really concerned as they are mostly technical documents.

**Comment by yzhang-gh** [comment]
I see.

> I mean I want headers to be larger and unordered lists to be the dots.

Then HTML by itself is enough.

Will try to do it during the weekend as it is simple to add.

**Comment by JFaulk1434** [comment]
That's fantastic thank you :)

**Comment by yzhang-gh** [comment]
You can check out the dev build https://github.com/yzhang-gh/vscode-markdown/suites/14331658569/artifacts/806613865

Instruction: https://github.com/yzhang-gh/vscode-markdown#latest-development-build

**Comment by JFaulk1434** [comment]
I downloaded it and installed with the Extension from VSIX and reloaded VSCode. The dev build shows it as `markdown-all-in-one-3.5.1.vsix`, the Latest released is also 3.5.1? When exporting to HTML it looks the same using `Markdown All in One: Print current document to HTML` still holds all the VSCode style. Is there something I am missing?

**Comment by yzhang-gh** [comment]
The version number doesn't matter as long as it is not lower than the stable release.

> Is there something I am missing?

Sorry I forgot to mention that there is a new option `pureHtml` and you need to enable it.

**Comment by JFaulk1434** [comment]
Got it. That worked perfect. Thank you!
