### ISSUE TITLE
Syntax Highlighting Problem after Reading Issue 1008

### ISSUE THREAD

**Issue by ktrNozomi** [yzhang-gh/vscode-markdown#1316]
Thanks for your contribution to the awesome extension!

After carefully reading [issue #1008](https://github.com/yzhang-gh/vscode-markdown/issues/1008), I have disabled the built markdown math extension. The highlighting gets much better now. However, there's still a defect shown in the following picture:

![2023-07-30-13-17-31](https://github.com/yzhang-gh/vscode-markdown/assets/86712470/2e4d64ff-359b-4202-86c0-b75294fe99dc)

Are there any solutions?

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Although it may render correctly, it is not by design that the inline math takes multiple lines. The syntax highlighting follows the rules described in https://github.com/waylonflinn/markdown-it-katex#syntax

**Comment by ktrNozomi** [comment]
Thanks for the reply. Then I think it's a principle that KaTeX should be careful to design (and with my opinion it's outdated).

Best wishes with this extension.
