### ISSUE TITLE
 Unable to Use "Command + B" Shortcut to Apply Bold Formatting

### ISSUE THREAD

**Issue by BlackBerry009** [yzhang-gh/vscode-markdown#1319]
### What's the problem

command + b to bold is not work

 I have already checked the configuration settings, and it appears that the "Command + B" shortcut is properly configured.

<img width="979" alt="image" src="https://github.com/yzhang-gh/vscode-markdown/assets/42471741/a9a3d56b-411c-4889-9efb-89f8039be392">

**Comment by yzhang-gh** [comment]
You can use VS Code's troubleshooting to help find the reason. Please find more in https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings

**Comment by BlackBerry009** [comment]
> You can use VS Code's troubleshooting to help find the reason. Please find more in https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings

Thanks, I found the problem, it doesn't work in mdx files, it works fine in md files

**Comment by BlackBerry009** [comment]
I found the issue https://github.com/yzhang-gh/vscode-markdown/issues/758#issuecomment-907334366 to solve it .😀
