### ISSUE TITLE
URLs Ending with .md are Modified Improperly Resulting in a Broken Link

### ISSUE THREAD

**Issue by nepgituser** [yzhang-gh/vscode-markdown#1324]
Any URL that ends with ".md" is being rewritten as ".html" when the HTML file is generated.

```
https://github.com/colloqi/piSignage/blob/master/RELEASE%20NOTES.md
[Release Notes](https://testing.com/colloqi/piSignage/blob/master/RELEASE%20NOTES.md)
<a href="https://github.com/colloqi/piSignage/blob/master/RELEASE%20NOTES.md">https://github.com/colloqi/piSignage/blob/master/RELEASE%20NOTES.md</a>
```

All of the above examples are turned into the following when the HTML file is generated.

```
<a href="https://github.com/colloqi/piSignage/blob/master/RELEASE%20NOTES.html">https://github.com/colloqi/piSignage/blob/master/RELEASE%20NOTES.md</a>
```

I don't know if this is expected behavior, but at least in the case of this link, the resulting link is not valid.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It is the expected behavior (#667), but I can see that it should be `.md` in your case. I will think about it.

**Comment by nepgituser** [comment]
Here is another URL that doesn't work properly.

https://github.com/MicrosoftDocs/microsoft-365-docs/blob/public/microsoft-365/commerce/subscriptions/allowselfservicepurchase-powershell.md

**Comment by yzhang-gh** [comment]
I have added a rule that a link containing both `github.com` and `blob` will remain unchanged. You can try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by nepgituser** [comment]
That seems like a suitable fix. Downloaded the dev build and it works as expected. Thank you!
