### ISSUE TITLE
Power Query language support

### ISSUE THREAD

**Issue by UWE-BIDEV** [yzhang-gh/vscode-markdown#1327]
Hello,
Thanks for this extension, it's an awesome tool!
I'm not sure I understand how the syntax highlighting works... is there a way to support power query scripts?
Cheers

**Comment by yzhang-gh** [comment]
Thanks.

Do you mean the syntax highlight in the code block? It is rendered by [highlight.js](https://highlightjs.org/).

https://github.com/microsoft/vscode/blob/41e940f76f5deda197bc5930b044c55607ba1cbc/extensions/markdown-language-features/src/markdownEngine.ts#L397-L410

**Comment by UWE-BIDEV** [comment]
Hi @yzhang-gh
Thanks for the reply! 
I didn't realise you used highlight.js - unfortunately, it doesn't support Power Query and there is little hope it will in the future. 😕
Are syntax highlighters easily interchangeable? I'm reading that Prism.js and Shiki.js are good alternatives.
Cheers

**Comment by yzhang-gh** [comment]
As you can see from the link, the syntax highlighting is provided by VS Code itself (and many other basic features). Probably you can open an issue in the VS Code repository.

**Comment by UWE-BIDEV** [comment]
Oh I see, I'd missed that detail! 
Thanks for your help.
Cheers
