### ISSUE TITLE
some keyboard key not working in vs code

### ISSUE THREAD

**Issue by Aqib1239** [yzhang-gh/vscode-markdown#1335]
Type: <b>Bug</b>

In my system the latest version of vs code facing an error that is ' r key ' from keyboard not working, this is only in vs code 

Extension version: 3.5.1
VS Code version: Code 1.82.1 (6509174151d557a81c9d0b5f8a5a1e9274db5585, 2023-09-08T08:45:05.575Z)
OS version: Windows_NT x64 10.0.22621
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.11GB free)|
|Process Argv|--crash-reporter-id 871603f2-da46-4202-a551-7c55a84f16c3|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
pythonvs932:30410667
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
3biah626:30602489
89544117:30613380
2i9eh265:30646982
showlangstatbar:30737416
962ge761:30841074
a2ce3375:30757347
pythonfmttext:30731395
fixshowwlkth:30771522
showindicator:30805244
pythongtdpath:30769146
i26e3531:30792625
pythonnosmt12:30797651
pythonidxpt:30805730
pythonnoceb:30805159
copilotsettingc:30839828
dsvsc013:30795093
dsvsc014:30804076
diffeditorv2:30821572
dsvsc015cf:30829746

```

</details>

**Comment by yzhang-gh** [comment]
You can see [VS Code's documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings) to find out the reason.

**Comment by Aqib1239** [comment]
T

> You can see [VS Code's documentation](https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings) to find out the reason.

This is not proper solution...

**Comment by yzhang-gh** [comment]
The above link tells you how to see what happens after you press any key. If everything works well, you should see

![Code_fVh1Zcz0HS](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/f2edc3d0-18fe-45ce-8766-4936ac83d79f)

**Comment by yzhang-gh** [comment]
![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/12fda35b-5776-47d3-b373-81e53c4d0828)

<h4 align="center">Just follow its steps and see what happens inside VS Code after you press the <kbd>r</kbd> key.</h4>
<br>

**Comment by Aqib1239** [comment]
<img width="955" alt="abc" src="https://github.com/yzhang-gh/vscode-markdown/assets/114600200/78ab24a0-9001-4690-9a6f-fb4a48eb55e5">
After run the command --> Developer: Toggle Keyboard Shortcuts Troubleshooting.  
showing this

**Comment by yzhang-gh** [comment]
![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/a08cd6e4-9d32-4c4e-ab72-85f889c66db6)

Remove this keybinding from you settings.

**Comment by Aqib1239** [comment]
how to remove this keybinding...
