### ISSUE TITLE
Math block syntax  highlight problem

### ISSUE THREAD

**Issue by liquan8142** [yzhang-gh/vscode-markdown#1339]
### What's the problem
After I reinstall my Ubuntu system and VScode.My ".md" file didn't highlight the symbol "$$" as shown in picture.
![image](https://github.com/yzhang-gh/vscode-markdown/assets/147679327/7ff56393-5db0-4f3d-a763-cb3cb01c88ab)

And I want it to be like this(this is a ".tex" file)
![image](https://github.com/yzhang-gh/vscode-markdown/assets/147679327/71ac7ffb-aa26-4ba1-9342-d24654af6d8c)

what should I do?(thanks in advance and sorry for my poor English)
### Other information
Version:
ubuntu 18.04
Markdown all in one V3.5.1
VsCode 1.83.1

**Comment by yzhang-gh** [comment]
可以参考 #1008。简单来说是 VS Code 在某个时间点加入了对数学语法的高亮，所以与这个插件冲突了，可以考虑禁用 VS Code 自带的 Markdown 数学插件.

**Comment by liquan8142** [comment]
@yzhang-gh 感谢回复！根据#1008的建议，我的数学公式恢复了高亮状态如图！！
![image](https://github.com/yzhang-gh/vscode-markdown/assets/147679327/94086ee4-1222-48f2-a024-4272bba780a3)
此处还有一个小问题，我觉得图片中的高亮显示颜色有点浅，请问如何调整颜色使其类似下图？感谢！！
![image](https://github.com/yzhang-gh/vscode-markdown/assets/147679327/edba1401-776a-4301-b58e-880b42091c01)

**Comment by yzhang-gh** [comment]
语法高亮只是给不同的词赋上了对应的语义信息比如 `variable`，`operator`，具体的颜色由 VS Code 主题决定，可以切换不同的主题试试
