### ISSUE TITLE
autoShowPreviewToSide tries to open unexpected documents

### ISSUE THREAD

**Issue by alexr00** [yzhang-gh/vscode-markdown#1342]
### What's the problem
Originally found in https://github.com/microsoft/vscode-pull-request-github/issues/5267: the setting `autoShowPreviewToSide` will cause all markdown documents to try to open to the side, even when the document's uri `scheme` is not one that should be opened to the side. For example, the VS Code[ comment widget](https://code.visualstudio.com/api/references/vscode-api#comments) can use markdown as the language for the comment editor. This is a document that should never be opened to the side. A solution to this would be to check the scheme of the document uri somewhere around here to see if it matches the scheme of one of the workspace folders or is `"file"` scheme. 

https://github.com/yzhang-gh/vscode-markdown/blob/28981030384e7d87df66a0060f10f192cacae4aa/src/preview.ts#L58-L61

### What's the expected result
Comment widget editors are not opened to the side. 

### How to reproduce

1. Install an extension that provides comments as markdown.
2. Start to add or edit a comment.
3. An editor will open with an error

![Image](https://github.com/yzhang-gh/vscode-markdown/assets/38270282/12969192-f93d-4528-8068-86122ca98606)

**Comment by yzhang-gh** [comment]
Hi, thanks for the information.

It now checks `editor.document.uri.scheme === 'file'` and should work well with the comment widget.
