### ISSUE TITLE
Markdown All in One lets extension host crash

### ISSUE THREAD

**Issue by mwehking** [yzhang-gh/vscode-markdown#1344]
Type: <b>Bug</b>

Install Markdown All in One, open Angular project.

Extension version: 3.5.1
VS Code version: Code 1.83.1 (f1b07bd25dfad64b0167beb15359ae573aecd2cc, 2023-10-10T23:48:05.904Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (6 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (6.82GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|100%|
</details>

**Comment by yzhang-gh** [comment]
There are similar issues every a few months, but none of them were found to have direct relation to this extension.

Feel free to reopen this issue if you have more information on this.
