### ISSUE TITLE
Links that contain anchors and link to other files produce faulty links when generating html

### ISSUE THREAD

**Issue by tim-sagaster** [yzhang-gh/vscode-markdown#1347]
### What's the problem

When creating html from a markdown source using the >Markdown All in One: Print documents to HTML (select a source folder) command, links to other files are not correctly translated if they contain a link to an anchor.
E.g. ``[Link to anchor in other file](otherFile.md#anchor)`` produces a link to the md file instead of the html file. If using the other valid markdown syntax without the .md ``[Link to anchor in other file](otherFile#anchor)`` a link without file ending is created. Problem only occurs when using links with anchors.

### What's the expected result

``[Link to anchor in other file](otherFile.md#anchor)`` and ``[Link to anchor in other file](otherFile#anchor)`` should both produce an output in html that looks like ``<a href="otherFile.html#anchor">Link to anchor in other file</a>``

### How to reproduce

1. Link to one file to an anchor in another file
e.g. ``[Link to anchor in other file](otherFile.md#anchor)``
2. Use the >Markdown All in One: Print documents to HTML (select a source folder) command
3. Resulting html document has faulty link: ``<a href="otherFile.md#anchor">Link to anchor in other file</a>``

**Comment by yzhang-gh** [comment]
Do those links contain keywords like `github`? See also #1324.

**Comment by tim-sagaster** [comment]
No, they are just local links e.g. ``WikiFiles/glossary.md#entry``

**Comment by yzhang-gh** [comment]
Thanks. I didn't notice that. It is the `$` to blame. Should be working now.

**Comment by tim-sagaster** [comment]
Thanks, works now as expected!
