### ISSUE TITLE
Support global `\newcommand` for TeX math

### ISSUE THREAD

**Issue by cabinz** [yzhang-gh/vscode-markdown#1348]
### Proposal

So far the `\newcommand` macro is supported only inside a single math block, while **cross-block usage** hasn't been supported by our amazing vscode-markdown plug-in, which means users cannot define a new macro for frequent usage **once and for all**.

The final feature that this proposal expects is to support cross-block customized macro usage. For example, we can have a math block at the beginning of the markdown doc:
```
$$
\newcommand\vt[1]{\mathit{\boldsymbol{#1}}} % for vector symbol
\newcommand{\mt}[3]{#1_{#2 \times #3}} % matrix symbol M_(nxm)
$$
```

which can be used wherever needed aftwards without being in the same math blocks:
```
$$
\vt{x} \in R^{m}, \vt{y} \in R^{n} \\
\mt{A}{m}{n} = \vt{x}\vt{y}^T
$$
```
<img width="176" alt="Screenshot 2023-11-08 at 14 07 13" src="https://github.com/yzhang-gh/vscode-markdown/assets/60537086/20007103-d546-4b98-830c-5764f330ef23">

### Other information

The rendering in [Typora](https://typora.io/) supports this feature. Users can put a math block containing all the `\newcommand` definitions at the very beginning of the doc for the rest to use.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

We have a `markdown.extension.katex.macros` option which might be useful for you.

**Comment by cabinz** [comment]
Thx for the answer.
But how to I specify a macro with arguments? For example, how do I fill the `katex.macros` with a key-value pair for `\newcommand\vt[1]{\mathit{\boldsymbol{#1}}}`?

**Comment by yzhang-gh** [comment]
![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/0f0262b0-22aa-4ca7-8770-8167c9cc62a2)

Just try `\\vt` and `\\mathit{\\boldsymbol{#1}}`?

**Comment by cabinz** [comment]
This works perfectly. Thx you so much!
