### ISSUE TITLE
Support GFM Alerts

### ISSUE THREAD

**Issue by calumk** [yzhang-gh/vscode-markdown#1350]
### Proposal

Support GFM Alerts

```
> [!NOTE] 
> This alert uses [!NOTE]

> [!IMPORTANT] 
> This alert uses [!IMPORTANT]

> [!WARNING]
> This alert uses [!WARNING]
```

> [!NOTE] 
> This alert uses [!NOTE]

> [!IMPORTANT] 
> This alert uses [!IMPORTANT]

> [!WARNING]
> This alert uses [!WARNING]

### Other information
EG : https://github.com/orgs/community/discussions/16925

**Comment by yzhang-gh** [comment]
Thanks for the information. That's interesting.

However, I doubt that the Markdown parser [markdown-it](https://github.com/markdown-it/markdown-it) will ever add it. Then we will need a markdown-it plugin. It doesn't seem straightforward (e.g. it involves icons and colors but not plain HTML).

**Comment by calumk** [comment]
While this is not currently planned - For reference, two more styles were added 14/12/23

> Add support for [!TIP] and [!CAUTION].

> [!TIP] 
> This alert usses [!TIP] 

> [!CAUTION] 
> This alert usses [!CAUTION] 

https://github.com/orgs/community/discussions/16925

**Comment by calumk** [comment]
Now supported with `mdit-plugins` `alert`


https://mdit-plugins.github.io/alert.html
