### ISSUE TITLE
Double-byte file names do not display properly

### ISSUE THREAD

**Issue by ayatokura** [yzhang-gh/vscode-markdown#1352]
### What's the problem
File names do not load properly when calling double-byte filenames in Markdown

### What's the expected result
It would be great if Markdown could show double-byte file names when we load them up, just like in VS Code Explorer

### How to reproduce

1. Create Markdown file 
2. Drag-and-drop to embed double-byte files
3. File names do not load properly when calling double-byte filenames in Markdown

### Other information
Screenshot
<img width="842" alt="image" src="https://github.com/yzhang-gh/vscode-markdown/assets/12283147/5ecf0eae-2885-42a6-bde9-2f97779012a8">

**Comment by yzhang-gh** [comment]
Thanks for the feedback. This feature was added by VS Code itself in the [April update](https://code.visualstudio.com/updates/v1_78#_drop-selector) of this year. You may open an issue in their official repository.
