### ISSUE TITLE
Feature request: register `DocumentRangeFormattingEditProvider` for vscode selection range format

### ISSUE THREAD

**Issue by peaceshi** [yzhang-gh/vscode-markdown#1360]
### Proposal

add a `DocumentRangeFormattingEditProvider`.

![image](https://github.com/yzhang-gh/vscode-markdown/assets/10380828/9c604966-519d-43e2-b5e2-e9058f2b0f88)
![66ea95ff977eeda85f367a872ea7565e](https://github.com/yzhang-gh/vscode-markdown/assets/10380828/6f235df3-b5c8-4319-898d-bdf3e3ef70d0)

**Comment by yzhang-gh** [comment]
Thanks. It looks like you didn't make use of the `range` argument which is passed in by the range formatter. Probably you can pass it into the `detectTables` function.
