### ISSUE TITLE
Support add a space between Latin and CJK characters

### ISSUE THREAD

**Issue by weilence** [yzhang-gh/vscode-markdown#1378]
### Proposal

In Chinese content, when English words are included, unless they serve as keywords, it is usually necessary to manually add spaces, which can be a cumbersome manual task.

for example:
before
```md
开始使用、排除故障和充分利用GitHub。 新用户、开发人员、管理员和所有GitHub产品的文档。
```
after
```md
开始使用、排除故障和充分利用 GitHub。新用户、开发人员、管理员和所有 GitHub 产品的文档。
```

**Comment by yzhang-gh** [comment]
Please see #1336.
