### ISSUE TITLE
auto show preview to side triggered when editing markdown cell in jupyter notebook

### ISSUE THREAD

**Issue by yuuuxt** [yzhang-gh/vscode-markdown#1379]
### What's the problem

Auto show preview to side is triggered when editing markdown cell in jupyter notebook

### What's the expected result

Not triggering auto show preview to side as it's an ipynb file.

### How to reproduce

1. enable auto show preview to side, and create an arbitrary jupyter notebook
2. create a markdown cell and starts editing it (must create a new markdown: insert cell, and turn cell to markdown cell, and press enter to start editing)

### Other information
markdown all in one 3.5.1
vscode-jupyter v2023.11.1003402403
vscode 1.85.1

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It is a known (and fixed) issue as #1342. I'm going to publish a new version soon.
