### ISSUE TITLE
i cant copy image in preview

### ISSUE THREAD

**Issue by wch243294382** [yzhang-gh/vscode-markdown#1391]
### What's the problem

i cant copy image in preview, the image is from <img src="http://mdrs.yuanjin.tech/img/20200929172805.png" alt="image-20200929172805674" style="zoom:50%;" />

### What's the expected result

can copy it

### How to reproduce

1. ...
2. ...

**Comment by yzhang-gh** [comment]
Thanks for the feedback. However, the preview tab is provided by [VS Code itself](https://code.visualstudio.com/docs/languages/markdown#_markdown-preview). You may need to open an issue there.
