### ISSUE TITLE
If user can see the outline of a previewed markdown file . That will be so useful !

### ISSUE THREAD

**Issue by q2333gh** [yzhang-gh/vscode-markdown#1392]
When open a normal .md file . outline shows great.
![image](https://github.com/yzhang-gh/vscode-markdown/assets/32679742/32235ab4-2dc5-4f49-a903-efc52a4b5d6f)

But when rendering a .md file . outline shows nothing.
![image](https://github.com/yzhang-gh/vscode-markdown/assets/32679742/74cb6ed5-a781-4f74-8e08-8490346757dd)

**Comment by yzhang-gh** [comment]
Hi, sorry for the late reply. That's interesting. However, the outline is provided by VS Code itself. Probably you can open a feature request in the official repository.
