### ISSUE TITLE
In preview, display the Mathematica code in a more readable way

### ISSUE THREAD

**Issue by dualer** [yzhang-gh/vscode-markdown#1399]
### Proposal

当嵌入mathematica代码块时, 会存在很多类似`\[Mu]`这样的转义字符, 是否可以在预览页面直接显示为Mathematica中的显示结果? 例如`\[Mu]`显示为`μ`

**Comment by yzhang-gh** [comment]
目前的数学模块使用的是 KaTeX，所以这个问题在我们掌控之外了
