### ISSUE TITLE
GFM alerts don't look as good as expected when exporting HTML

### ISSUE THREAD

**Issue by mlaidouni** [yzhang-gh/vscode-markdown#1405]
### What's the problem

The icons and text are no longer aligned (it seems to me that it worked fine until now). Is it possible to do this?

### What's the expected result

<img src="https://github.com/yzhang-gh/vscode-markdown/assets/151235313/cd8a07c7-265b-40b3-a1f6-fbc0a057b4c5" align="center" width="400px"> <img src="https://github.com/yzhang-gh/vscode-markdown/assets/151235313/a8c6cf99-a6da-4994-b777-f53c7d6b9691" align="center"  width="400px">

### How to reproduce

By writting this:

```md
> [!NOTE]
> Useful information that users should know, even when skimming content.

> [!TIP]
> Helpful advice for doing things better or more easily.

> [!WARNING]
> Urgent info that needs immediate user attention to avoid problems.

> [!IMPORTANT]
> Key information users need to know to achieve their goal.

> [!CAUTION]
> Advises about risks or negative outcomes of certain actions.
```

### Other information

Thanks for all ❤️

**Comment by yzhang-gh** [comment]
Thanks for the feedback. However, it looks alright on my machine. Could you try to install the latest [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build)? Or it may be caused by your browser.

![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/ec857e89-4f64-4ccc-a76e-4af85d04c228)

**Comment by mlaidouni** [comment]
> Could you try to install the latest [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build)?

I've just installed it but the result is the same.

> Or it may be caused by your browser.

Which browser ?

**Comment by yzhang-gh** [comment]
Where did you open the exported HTML (e.g., Chrome)? You can also upload it to the GitHub comment (need to zip it first) and then I can see how it looks on my machine.

**Comment by mlaidouni** [comment]
After some tries, I found the source of the problem. It's the extension [**Markdown Preview Github Styling**][id1].

## Result on Chrome with Markdown Preview Github Styling

![screenshot 1][img1]

## Result on Chrome without Markdown Preview Github Styling

![screenshot 2][img2]


[id1]: https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles "Market place" 
[img1]: https://github.com/yzhang-gh/vscode-markdown/assets/151235313/2eea5462-5a4a-4820-b626-2fa2c93cb6ff
[img2]: https://github.com/yzhang-gh/vscode-markdown/assets/151235313/68df453d-b042-47e3-aeb5-ba5e4b8c7c61

# Other

Another question, is it possible to force all lines to end with two spaces `  `, so that the line break is the same as on github?

**Comment by yzhang-gh** [comment]
Thanks for the update.

> Another question, is it possible to force all lines to end with two spaces ` `, so that the line break is the same as on github?

You need to set `markdown.preview.breaks` to `true`.
