### ISSUE TITLE
Content collapsed using the <details> tag cannot use markdown syntax.

### ISSUE THREAD

**Issue by huangsijun17** [yzhang-gh/vscode-markdown#1406]
### What's the problem
```
<details> <summary>Title</summary>
* line 1
* line 2
</details>
```
The unordered list is not parsed.

### What's the expected result
show:
▼ Title
* line 1
* line 2

### How to reproduce

Copy and paste code and tests.

### Other information

版本: 1.87.2 (user setup)
提交: 863d2581ecda6849923a2118d93a088b0745d9d6
日期: 2024-03-08T15:20:17.278Z
Electron: 27.3.2
ElectronBuildId: 26836302
Chromium: 118.0.5993.159
Node.js: 18.17.1
V8: 11.8.172.18-electron.0
OS: Windows_NT x64 10.0.22631

Markdown All in One v3.6.2

**Comment by yzhang-gh** [comment]
You need to put an empty line between HTML and Markdown code, e.g.

```markdown
<details> <summary>Title</summary>

* line 1
* line 2

</details>
```
