### ISSUE TITLE
"markdown.extension.orderedList.autoRenumber" is working when setting is false

### ISSUE THREAD

**Issue by t-ueno-ruby** [yzhang-gh/vscode-markdown#1408]
When writing markdown, I want to write a list with all 1s, so I set "markdown.extension.orderedList.autoRenumber": false.
However, even if you set the setting to false, when you edit it, it will automatically recognize it as 2 when it should be 1.
The above settings are applied globally, and there are no separate settings files for each project.

If you disable the extension, the above phenomenon will not occur (but you will have to enter the list manually each time).

### What's the problem
When writing markdown, I want to write a list with all `1`, but it automatically changed `1` to automatic re-numbering.

### What's the expected result
When writing markdown, I want to write a list with all `1` when I am typing without automatic re-numbering.

#### 1. paste settings.json(my setting).

```json
    "[markdown]": {
        "editor.defaultFormatter": "DavidAnson.vscode-markdownlint",
        "editor.formatOnSave": true,
        "editor.insertSpaces": true,
        "editor.quickSuggestions": {
            "comments": "off",
            "strings": "off",
            "other": "on"
        },
    "markdown.extension.list.indentationSize": "inherit",
    "markdownlint.config": {
        "MD007": {
            "indent": 4
        },
        "MD046": false,
    },
        "editor.snippetSuggestions": "top",
        "editor.tabSize": 4,
        "editor.wordWrap": "on",
        "editor.wordBasedSuggestions": "off",
    },
    "markdown.extension.math.enabled": false,
    "markdown.extension.orderedList.autoRenumber": false,
    "markdown.extension.toc.slugifyMode": "github",
    "markdown.extension.toc.updateOnSave": false,
    "markdown-preview-enhanced.enableExtendedTableSyntax": true,
    "markdown-preview-enhanced.scrollSync": false,
```

#### 2. type list in markdown file

Below is the actual screen capture.

https://github.com/yzhang-gh/vscode-markdown/assets/138413034/5beaf40a-0d27-4bf5-a5e9-778a7e913a01

**Comment by yzhang-gh** [comment]
You need to change `markdown.extension.orderedList.marker` to `one`.

**Comment by t-ueno-ruby** [comment]
thank you!
I had overlooked it!
Now it works as expected!
