### ISSUE TITLE
Auto update TOC breaks link

### ISSUE THREAD

**Issue by RayOei** [yzhang-gh/vscode-markdown#1409]
### What's the problem
Recently the auto update of the TOC will change the existing link `[header-title](#some-link-text)` to `[header-title](#markdown-header-some-link-text)`. This renders the link inoperable. Not sure when this started happening. I just noticed.
When I remove the `markdown-header-` the auto update reinserts in. Disabling the plugin and the issue doesn't happen.

### What's the expected result
The TOC links should be untouched.

### How to reproduce

1. Document met headers. 
2. Insert TOC. 
3. Links contain the `markdown-header-` part and the link doesn't work

Or
1. Open existing MD file with TOC
2. Auto-update changes the links

### Other information
Plugin: v3.6.2
VSC: 1.87.2 Commit: 863d2581ecda6849923a2118d93a088b0745d9d6

**Comment by yzhang-gh** [comment]
That's strange. Which `markdown.extension.toc.slugifyMode` are you using?

**Comment by RayOei** [comment]
As far as I am aware I have none set. Nothing I can find in the settings(.json). I noticed a reference to `slugifyMode` in the readme, but I don't normally work with Gitlab or Github...

**Comment by yzhang-gh** [comment]
Looks like the toc style follows Bitbucket

https://github.com/yzhang-gh/vscode-markdown/blob/d2862ca363656c244ff587e6ce17e875e02457ed/src/util/slugify.ts#L78-L85

What do you see if you search `slugify` in the VS Code's settings editor?

![image](https://github.com/yzhang-gh/vscode-markdown/assets/7588612/4f8ff761-a2c4-43c3-98c1-64c6cfea7025)

**Comment by RayOei** [comment]
As I already said: there is nothing set. E.g. it doesn't exist.

**Comment by yzhang-gh** [comment]
Apparently I have no access to your machine and have no idea what is wrong. My suggestion is

- you can try to explictly set `toc.slugifyMode` to `github` (which should be the default) and any other options, and then see whether it gives different results.
- or just disable `toc.updateOnSave` so it won't modify your TOC anymore.

**Comment by RayOei** [comment]
I am not sure why it didn't work before. But I uninstalled the plugin, and reinstalled it again. Did a full reboot of my Mac. And now it works again.

**Comment by yzhang-gh** [comment]
Thanks for the update.
