### ISSUE TITLE
Problem with checkboxes alignment

### ISSUE THREAD

**Issue by mlaidouni** [yzhang-gh/vscode-markdown#1411]
### What's the problem

The checkboxes are not properly aligned with the text. I don't know whether this problem comes from your extension or from the [Markdown Checkboxes extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox).

![image](https://github.com/yzhang-gh/vscode-markdown/assets/151235313/46d72784-0634-4e95-a6c9-1dcedc07b43b)

### How to reproduce

For exemple:

```md
# To do

## Fonctionnalité

- [ ] page de connection
  - [ ] URI `/gerante` pour la gérante
- [ ] page d'accueil:
  - [ ] présentation de l’ensemble des cadeaux disponible pour elle.
- [ ] page de compte de client:
  - [ ] contient entre autre le nombre de points qu’elle a accumulé
- [ ] page de gestion des cadeaux:
  - [ ] ajout / suppression / modification
  - [ ] affichage de l’ensemble des cadeaux
  - [ ] un cadeaux est défini par: nom, prix en points + taille, couleur, ... si pertienent\*
- [ ] page achat cadeau:
  - [ ] affichage des cadeaux disponibles pour le client
  - [ ] menu déroulant pour spécifier les caractéristiques du cadeau: (taille, couleur, ...)
  - [ ] mise à jour des points à chaque ajout dans le panier
- [ ] page de gestion du panier

## Conditions à respecter

- [ ] Dans la page d'accueil, afficher seulement les cadeaux avec un nombre de point $\le$ nombre de points de la cliente.

> [!WARNING]  
> Faire attention à ce que, dans la page html, l'id de l'objet html représentant le cadeau soit le même que l'id du cadeau, pour pouvoir le supprimer de la BD
```

**Comment by yzhang-gh** [comment]
I think it is the latter. This is what I tested last week https://github.com/yzhang-gh/vscode-markdown/issues/1405#issuecomment-2016418956

**Comment by mlaidouni** [comment]
Yes, you're right ! It's the [Markdown Checkboxes extension](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-checkbox). Thanks for all !
