### ISSUE TITLE
Markdown auto deletes Links to other markdown files in some cases

### ISSUE THREAD

**Issue by RaedAddala** [yzhang-gh/vscode-markdown#1418]
### What's the problem

I have a table of contents that contains links to other markdown files as well as parts from the same markdown file. When the table of contents list started growing bit by bit, at some point Markdown started deleting all links to other markdown files from the table of contents.

**This is weird, considering that if this is not a bug, it should either exhibit this behavior from the start.**

I searched in the settings and couldn't find something relevant for this case.

### What's the expected result

It should either work like this from the start or not at all.

### How to reproduce

Here is the first example in which I noticed the bug: (the difference between the next two snapshots is that I added a link in the table of contents)

1. Here is the list before:
![image](https://github.com/yzhang-gh/vscode-markdown/assets/56173312/879d135e-0efe-4f8e-a722-96d39820e279)

2. Here is the list after:
![image](https://github.com/yzhang-gh/vscode-markdown/assets/56173312/509677cc-4f20-430b-898d-055d6812b3a8)

Note that the change was automatic and new. I worked with the extension for months and this is a first.

**Comment by RaedAddala** [comment]
Experimenting with it, I have found another example showcasing this problem.

Note that the only difference was removing an extension from a link:

1. 
![image](https://github.com/yzhang-gh/vscode-markdown/assets/56173312/2faccab4-840f-4ffd-b451-d61808ae17b0)

2.
![image](https://github.com/yzhang-gh/vscode-markdown/assets/56173312/1a6622ea-d82d-43a9-a8ca-ae11f0f4eea8)

**Comment by RaedAddala** [comment]
If this is not a bug but a normal extension behaviour, please make it so it functions this way from the start.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. This is a feature that automatically detects and updates (optional) the TOC.

In your case, the list was not recognized as a TOC as it had "links", but as you added more TOC entries it was more likely to be a TOC, and then it was updated to the "real" TOC.

You can disable the automatic update of the TOC with the option `markdown.extension.toc.updateOnSave` but you will still see the small "Table of Contents (up to date)" hint. Or you can put a `<!-- no toc -->` comment right before your manually edited TOC.

**Comment by RaedAddala** [comment]
Thanks for your reply. It is clear to me now.

I suggest that you mention this part in the documentation or something like this. Just to avoid confusion in the future.
