### ISSUE TITLE
sluggish editting

### ISSUE THREAD

**Issue by m76589** [yzhang-gh/vscode-markdown#1430]
Type: <b>Bug</b>

~2000 line MD file.
type something, then hit delete three times.
the actual deletion of characters on the screen takes 2-3 seconds.

Extension version: 3.6.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.19045
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (20.27GB free)|
|Process Argv|--file-uri file:///c%3A/mm/src/vs-code-workspaces/b-5252-mcdgen-for-vecu.code-workspace --crash-reporter-id 47c927a9-163e-4fba-966c-2fbc80447dea|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
tftest:31042121
vscoreces:30445986
vscod805cf:30301675
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialog:30910333
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pythonmypyd1:30879173
pythoncet0:30885854
2e7ec940:31000449
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
dsvsc020:30976470
pythonait:31006305
chatpanelc:31048052
dsvsc021:30996838
bdiig495:31013172
pythoncenvptcf:31049071
a69g1124:31046351
pythonprt:31047983
dwnewjupytercf:31046870
26j00206:31048877

```

</details>

**Comment by yzhang-gh** [comment]
You may find some information from #423 (workaround section). In short, disable other conflicting extensions _or_ delete the `onBackspaceKey` keybinding.

**Comment by m76589** [comment]
Thanks. It turned out to be one of the extensions,  found using the bisect feature.
