### ISSUE TITLE
Code Blocks Without Language Not Formatted in Markdown Files

### ISSUE THREAD

**Issue by sohang3112** [yzhang-gh/vscode-markdown#1446]
### What's the problem
In VS Code, when a markdown file is open, code blocks without a specified language are not getting formatted in the source code view. However, these blocks are formatted correctly in the markdown preview.

### What's the expected result
Code blocks with no specified language should be formatted in a single color (eg. green).

### How to reproduce

1. Open a markdown file in Visual Studio Code.
2. Add a code block without specifying a language.
4. The code block isn't formatted in markdown source code view (but is rendering correctly in Markdown Preview).

### Other information
Example screenshot - code without language isn't formatted, but with language (python) is:
![screenshot](https://github.com/user-attachments/assets/49f5c412-27f8-469c-8d69-0a508bad98db)

**Comment by sohang3112** [comment]
@yzhang-gh Please check if you can reproduce this issue on your machine - do you know of any solution to this issue?? If not, I would like to raise a PR to fix this issue - please confirm that you would be interested in merging such a PR.

**Comment by sohang3112** [comment]
@yzhang-gh please respond

**Comment by Buddinski88** [comment]
Maybe I can step in. I have inline code blocks and they render cleanly in the preview, but when I convert the document to HTML, no "style" is applied to it.

Example:

`- All files have numbers at the end `d1x1` means that the panel has a size of 60x60mm.`

![image](https://github.com/user-attachments/assets/eccadb57-e86d-49c2-8819-f55942ad4ea1)

As HTML:

`
<li>All files have numbers at the end <code>d1x1</code> means that the panel has a size of 60x60mm.</li>
`

![image](https://github.com/user-attachments/assets/e8966a39-ac6e-4521-ae2d-9b76aadbb988)

**Comment by sohang3112** [comment]
@Buddinski88 Yes exactly, no style is applied. Since language isn't known, it should simply pick a text color (eg. green) that's different from normal text color.
