### ISSUE TITLE
Disable Word Wrap for Tables

### ISSUE THREAD

**Issue by patrick-devlin** [yzhang-gh/vscode-markdown#1467]
# Feature Request: Disable Word Wrap for Tables

### Thank You

Thank you for this extension! It has been extremely useful and helpful, especially the tabular auto-formatting.

### Proposal

    "[markdown]": {
        "editor.wordWrap": "on",
        "editor.wordWrapColumn": 110
    }

Is it possible for the `wordWrap` configuration to apply to everything **except** tables?

### Alternative Suggestion:

If applying this change globally is not feasible, I propose adding a new setting to toggle this behavior specifically for tables:

    "[markdown]": {
        "editor.formatOnSave": true,
        "editor.wordWrap": "on",
        "editor.wordWrapTable": "off",   // New configuration to disable word wrap for tables
        "editor.wordWrapColumn": 110
    }

### Other Information

While the auto-formatting for tables is fantastic, it currently doesn't integrate well with word wrap settings. Tables are wrapped alongside regular text, which makes it difficult to edit tabular content—particularly in documents with larger tables.

**Comment by cloudyparts** [comment]
Sorry submitted this from the wrong account.  See https://github.com/yzhang-gh/vscode-markdown/issues/1468
