### ISSUE TITLE
Support for links

### ISSUE THREAD

**Issue by borekb** [yzhang-gh/vscode-markdown#20]
The ideal UX, in my opinion, is what pasting detects URL from the clipboard and does its magic. For example, before paste:

![image](https://user-images.githubusercontent.com/101152/28305441-f8c0038a-6b9b-11e7-98ae-201c2eff0edf.png)

After paste:

![image](https://user-images.githubusercontent.com/101152/28305454-03f75988-6b9c-11e7-9924-82b4f2603f08.png)

The next preferred method is a keyboard shortcut like here on GitHub. I select text, press a keyboard shortcut (Ctrl+K would be ideal but that one is taken by VSCode so probably Ctrl+L which is the second most popular shortcut for MD links in various editors) and get this:

![image](https://user-images.githubusercontent.com/101152/28305550-4d7ce208-6b9c-11e7-9f48-e0a05caf8bd0.png)

I can then paste the URL which is in my clipboard.

Thanks for this awesome extension!

**Comment by neilsustc** [comment]
Good suggestion

**Comment by neilsustc** [comment]
I find that we cannot get the text from clipboard using vscode APIs. So we cannot detect if the text is an URL.

I'm going to adopt the second method <kbd>ctrl</kbd>+<kbd>l</kbd>.
But there must be a upstream issue contributing snippets with arguments.
If you would like to try it, just add this to you Markdown keybindings (Menu>File>Preferences>Keyboard Shortcuts>advanced customizations->open `keybindings.json`),

```json
{
    "command": "editor.action.insertSnippet",
    "args": "[$TM_SELECTED_TEXT]($0)",
    "key": "ctrl+l",
    "mac": "cmd+l",
    "when": "editorTextFocus && editorLangId == markdown"
}
```

**Comment by borekb** [comment]
It gives me this palette:

![image](https://user-images.githubusercontent.com/101152/28677319-759afd12-72ed-11e7-83d4-fd2884a5295d.png)

Is this expected? When I select _Insert link_, it works as expected but I thought it would insert the link syntax straight away.

**Comment by borekb** [comment]
But thanks for the tip anyway!

**Comment by neilsustc** [comment]
Are you using vscode insider version?
I think it might be a bug of insider version because v1.14.1 (stable) inserts link syntax directly

**Comment by borekb** [comment]
I'm on 1.14.2, Windows 10.

**Comment by borekb** [comment]
This works for me:

```
    {
        "command": "editor.action.insertSnippet",
        "args": {
            "snippet": "[$TM_SELECTED_TEXT]($0)"
        },
        "key": "ctrl+l",
        "mac": "cmd+l",
        "when": "editorTextFocus && editorLangId == 'markdown'"
    }
```

**Comment by neilsustc** [comment]
Oops, my fault

This is my setting

![image](https://user-images.githubusercontent.com/7588612/28678276-8efc4844-7322-11e7-8f78-0ca347d2d46e.png)

**Comment by neilsustc** [comment]
BTW, this is the upstream issue [vscode #31372](https://github.com/Microsoft/vscode/issues/31372) preventing this extension to configure the keybinding out-of-box for you.
But it seems to have a low priority... You can vote for this.

**Comment by borekb** [comment]
Upvoted, thanks.

**Comment by borekb** [comment]
By any chance, doesn't VSCode API provide access to clipboard today, compared to last year? This would still be a great feature to have :)

I was also thinking if it would be possible to paste regardless of clipboard contents and then retrospectively look at what it was: if a URL, keep it, if something else, revert it. If this happened very quickly, maybe I wouldn't able to notice as a user? But maybe this would be problematic for larger blocks of text in the clipboard, I don't know.

**Comment by neilsustc** [comment]
Not a good news but you can find more information [here](https://github.com/neilsustc/vscode-markdown/issues/129#issuecomment-387208188).

**Comment by borekb** [comment]
Thanks, very useful!

**Comment by borekb** [comment]
The workaround doesn't seem very feasible, does it?

**Comment by borekb** [comment]
I meant [this](https://github.com/neilsustc/vscode-markdown/issues/20#issuecomment-392765487):

> I was also thinking if it would be possible to paste regardless of clipboard contents and then retrospectively look at what it was: if a URL, keep it, if something else, revert it. If this happened very quickly, maybe I wouldn't able to notice as a user? But maybe this would be problematic for larger blocks of text in the clipboard, I don't know.

**Comment by neilsustc** [comment]
In fact, we can watch for any text changes (no matter it is a pasting or normal typing) and do something. I think it is feasible. But one concern is there will be a noticeable two consecutive edits.

**Comment by yzhang-gh** [comment]
Finally we get it. Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

![paste](https://user-images.githubusercontent.com/7588612/52423701-8c8bca80-2af0-11e9-8e4c-e1a3fd4d5351.gif)

**Comment by borekb** [comment]
@yzhang-gh works like a charm! 🎉

**Comment by johnyoonh** [comment]
The feature is great, but it is not clear from the gif that you are doing the selection in the insert mode. I spent half an hour trying to see if there was other keybinding conflicts.

**Comment by yzhang-gh** [comment]
> it is not clear from the gif that you are doing the selection in the insert mode

Sorry, I don't get the point. Are you using the Vim extension?

I assumed the short text above the gif "Paste link on selected text" is enough.

**Comment by johnyoonh** [comment]
Yes I am using that vim extension. It could be just me. You happen to have syntax highlighting on previous gif for current line the same color as the selected text color, hence the confusion. Coming from vanilla vim, text selection in insert mode was a new concept for me..

**Comment by borekb** [comment]
I've updated the OP with clarification about the status of this issue as of today.

**Comment by jcrben** [comment]
Trying to figure out why this isn't working me for my Windows (inside WSL) computer but works just fine on my mac - no additional configuration steps mentioned at https://github.com/yzhang-gh/vscode-markdown#others

**Comment by yzhang-gh** [comment]
This might be helpful https://code.visualstudio.com/docs/getstarted/keybindings#_troubleshooting-keybindings

**Comment by jcrben** [comment]
thanks, that helped me figure it out!

It seems to be caused by this user-defined ctrl+v shortcut whereas on mac I was using meta+v

![image](https://user-images.githubusercontent.com/5614134/129510245-139a75c2-9176-49c1-afc8-5bd194c5fd84.png)

thanks again, I can figure it out from here... I am striving to have keyboard shortcut consistency across platforms which is why I have this shortcut which might seem redundant, but there are platform booleans for that
