### ISSUE TITLE
support footnote and corresponding hotkey

### ISSUE THREAD

**Issue by TheKiteRunning** [yzhang-gh/vscode-markdown#212]
Hi,

footnote is useful for some kinds of writing, and [markdown footnote](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes) is not easy to use since we should input ` [^ft]` ，` [^ft]:` and jump to the location of footnotes manually.
 
I hope vscode support this function:

- when we enter a hotkey, ` [^ftNum]` is created in the cursor location, 
- then jump to a corresponding ` [^ftNum]:`  in the end of the document.

Looking forward to your reply.

**Comment by neilsustc** [comment]
I note that you already found another extension [Markdown Footnotes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes). I think that is a good extension to support it. This extension only supports CommonMark and GFM now. Other Markdown dialects will be reconsidered only if there are many people request for them.

**Comment by TheKiteRunning** [comment]
Thank you for your answer.

**Comment by TheKiteRunning** [comment]
please add the markdown dialect label to #76 too

**Comment by austindrenski** [comment]
@neilsustc Using [Markdown Footnotes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes)  works fine for the VS Code preview window. 

But is there a way to hook this into __vscode-markdown__'s `Print current document to HTML` command?

**Comment by neilsustc** [comment]
A solution is to check the existence of that extension before printing, then apply corresponding markdown plugins.

I will do it later.

**Comment by dankaygit** [comment]
I was recently using Markdown All In One and also found myself wanting for some footnotes. 
Would be greatly appreciated

**Comment by yzhang-gh** [comment]
Will take a look this weekend.

**Comment by yzhang-gh** [comment]
Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
