### ISSUE TITLE
Multipoint editing doesn't work

### ISSUE THREAD

**Issue by quanzaiyu** [yzhang-gh/vscode-markdown#224]
#### What is the problem?

When using Multipoint editing, only the first selected section is valid.

#### How can I reproduce it?

![](http://oss.xiaoyulive.top/%E5%8B%98%E8%AF%AF/QQ%E6%88%AA%E5%9B%BE20180703124653.png)

It doesn't work when you type 'Ctrl+B', only the first selected section is valid.

**Comment by yzhang-gh** [comment]
Please refer to #33.
