### ISSUE TITLE
Deleting item from numbered list doesn't re-number the items

### ISSUE THREAD

**Issue by garyking** [yzhang-gh/vscode-markdown#267]
#### What is the problem?

In a numbered list, if I delete an item in the middle, then the subsequent items don't get re-numbered.

#### How can I reproduce it?

Create a list like:

```
1. a
2. b
3. c
```

Delete `2. b`. Item `3. c` should be changed to `2. c`, but it doesn't change at all.

#### Is there any error message in the console?

No

**Comment by neilsustc** [comment]
![renumber](https://user-images.githubusercontent.com/7588612/44944118-270d1280-adc9-11e8-9192-e7787a8d5bdd.gif)

I cannot reproduce

**Comment by garyking** [comment]
If you cut line 2 with cmd-x, then the lines won't re-number.

**Comment by neilsustc** [comment]
That's true

**Comment by yzhang-gh** [comment]
Let's track this at #668.
