### ISSUE TITLE
Print to HTML (printToHtml) automatically on file save

### ISSUE THREAD

**Issue by lcswillems** [yzhang-gh/vscode-markdown#294]
I would like to know if it is possible to execute markdown.extension.printToHtml everytime I save the file.
Is it also possible to modify the template used to convert md to html ?

Thank you,
Lucas

**Comment by neilsustc** [comment]
I found an extension [Save and Run Ext](https://marketplace.visualstudio.com/items?itemName=padjon.save-and-run-ext). You can have a try. The command name is `markdown.extension.printToHtml`

**Comment by neilsustc** [comment]
And for "template", actually, I don't understand your exact meaning... Do your mean the styles applied to the HTML file?

These styles are applied (in sequence)
1. VSCode preview stylesheets
2. Custom stylesheets from setting `markdown.styles`
3. Preview settings (`fontSize`, `fontFamily` etc.)

**Comment by lcswillems** [comment]
Thank you for your answer!
Why not proposing this functionality directly without requiring to install a plugin?

**Comment by neilsustc** [comment]
Personelly, I think most people only export Markdown as HTML for sharing. So this funtionality is not that frequently used.

**Comment by lcswillems** [comment]
But, I don't understand: a software is not meant to have only functionalities used 100% of the time by its users... In Word or Excel, there are a lot of functionalities that are rarely used by a lot of users, but this is because of these functionalities that these tools are so great!

**Comment by neilsustc** [comment]
Another different philosophy is to keep it simple 😉. Eclipse and PyCharm/IntelliJ are all good IDEs, with many useful features. But I prefer *lightweight* VSCode even that its Python extension is still not good enough.

A more realistic reason is we cannot make efforts to implement every features. I believe this is common for all open-source projects. Every month, VSCode team picks some of the top-voted features (and also, according to the programmers' preferences) and make their monthly iteration plan.

For me, a feature who is requested by about 3 people (in GitHub) is a "popular" one.

**Comment by lcswillems** [comment]
I don't see why adding the automatic md to html would make it more complicated to use.

However, I understand your second point!

Thank you for your time and your extension!

**Comment by Lemmingh** [comment]
"Auto exporting" has been available since version 2.3.0 (2019-04-28).

**Comment by TC74** [comment]
Can we change the exported file name to xxxx.md.html instead of .html?
