### ISSUE TITLE
"Insert a link" command

### ISSUE THREAD

**Issue by lcswillems** [yzhang-gh/vscode-markdown#295]
I would like to know if a command to insert a link exists? For example, if I do **ctrl+b** when some text is selected, it bolds it.

Is there a similar command to insert a link? I could select some text, do **ctrl+l**, for example, and it would open a dialog box asking for a link and then inserting the link.

Thank you,
Lucas

**Comment by neilsustc** [comment]
You can find more infomation in #20.

And good news is that someone seems to be working on the upstream issue now.

**Comment by yzhang-gh** [comment]
See #20.
