### ISSUE TITLE
Toggle unordered list doesn't work with multiple lines selected

### ISSUE THREAD

**Issue by timdhoffmann** [yzhang-gh/vscode-markdown#307]
#### What is the problem?
Command Markdown: Toggle Unordered List doesn't work with multiples lines selected.
Expected: Multiple lines toggle between formatting as a list and formatting as a regular paragraph.
Observed: Nothing happens.

#### How can I reproduce it?
1. Select multiple lines
2. Invoke command "Markdown: Toggle Unordered List"

#### Is there any error message in the console?
No.

**Comment by neilsustc** [comment]
The `toggleUnorderedList` command was added for switching between list markers (#145).

This is a different feature. By the way, you might like to know VSCode's [multi-cursors feature](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor).

**Comment by timdhoffmann** [comment]
Ah, then I misunderstood the feature from the command. I know the multi-cursors feature, thanks.
Then this would be indeed a feature request for toggling the state of multiple lines 
a) between ordered list on/off
b) between unordered list on/off

**Comment by timdhoffmann** [comment]
Yep, that's the functionality with asterisks (which make markdownlint complain). Unfortunately, there's no option for dashes.

**Comment by manastalukdar** [comment]
Any ETA on this feature request? Thanks.

**Comment by yzhang-gh** [comment]
Thanks for the interest. I personally don't have much time for this...

**Comment by yzhang-gh** [comment]
![togglelist](https://user-images.githubusercontent.com/7588612/59566311-50e0ae80-9056-11e9-93a5-128a744852a4.gif)

In the upcoming release
