### ISSUE TITLE
Mathematics absolute values in a table: | interpreted as end of cell

### ISSUE THREAD

**Issue by ram6ler** [yzhang-gh/vscode-markdown#318]
#### What is the problem?

When an absolute value symbol (`|`) is used in a mathematical expression in a table, the markdown parser appears to trigger the closing of a cell rather than recognise the character as part of the math expression. (Markdown appears to be parsed before an expression bound by `$` characters.)

(I notice that this is similar to the already closed [Formatting - Wrong formatting when Table contains `|`](https://github.com/neilsustc/vscode-markdown/issues/128) issue.)

#### How can I reproduce it?

A simple example:

<pre>
|Operation|`isEdge`|`listEdges`|`listVertices`|
|--:|:--:|:--:|:--:|
|Adjacency matrix|$\Theta(1)$|$\Theta(|V|^2)$|$\Theta(|V|)$|
                                      ^
                            (This | character triggers table 
                            cell completion - it is not
                            recognized as part of the math
                            expression.)
</pre>

#### Is there any error message in the console?

No.

**Comment by neilsustc** [comment]
Thank you for pointing it out. It is kind of complex to tackle. For now, you can use `\vert` in place of `|` as a workaround.

**Comment by Lemmingh** [comment]
I'm sorry to say **this behavior is required by the Spec**.

The [parsing strategy](https://spec.commonmark.org/0.29/#appendix-a-parsing-strategy) in **CommonMark Spec** says:

* Parse block structures first, then inline structures.

The [Tables](https://github.github.com/gfm/#tables-extension-) in **GFM Spec** says:

* A table is a leaf block.
* A table cell can only contains inline elements.
* Block-level elements cannot be inserted in a table.

Thus,

***Table cell parsing* must take higher precedence than *inline math area parsing*.**

---

Sorry for the inconvenience. [Please use `\vert` as described above.](https://github.com/yzhang-gh/vscode-markdown/issues/318#issuecomment-437684504)

**Comment by Lemmingh** [comment]
@yzhang-gh
There should be something wrong with our TM grammar, which leads to this misunderstanding. Would you please take a look?

**Comment by yzhang-gh** [comment]
Thanks.

But there doesn't seem to be an easy fix. The `|` doesn't have a specific color on its own (besides the general math highlight).

And it may not be worth it to create a special set of TM grammar for inline math inside a table cell.

![image](https://user-images.githubusercontent.com/7588612/102011926-566da080-3d82-11eb-812b-99db0f599699.png)
