### ISSUE TITLE
中文系统下，无法通过键入TOC命令快速创建目录

### ISSUE THREAD

**Issue by lymims** [yzhang-gh/vscode-markdown#327]
不能通过输入`>TOC`来快速创建目录：
![image](https://user-images.githubusercontent.com/9443706/48847121-c1cf2900-eddb-11e8-80a5-49c01e3a8f1a.png)

似乎因为命令的名称是中文，需要输入中文才行：
![image](https://user-images.githubusercontent.com/9443706/48847193-e6c39c00-eddb-11e8-8e37-68770cd5a755.png)

相应的， `>OLP`命令就没问题
![image](https://user-images.githubusercontent.com/9443706/48847237-03f86a80-eddc-11e8-8b5d-999a56eb8f60.png)

系统语言是中文，但是我已经把VSCode的语言设置为英文。

实际使用的时候，一般是不开输入法的，所以比较不方便，希望提供一种方式能够让中文系统也能通过输入`>TOC`来执行命令。

**Comment by neilsustc** [comment]
你是在 `locale.json` 里面把显示语言改成英文的吗？感觉这样改应该可以看到两个语音吧

**Comment by lymims** [comment]
中文系统，直接安装 VS Code，语言默认是英文，没有动其他设置，甚至 `locale.json` 文件都不存在。
所以上述的 `但是我已经把VSCode的语言设置为英文` 可能描述得不太准确，其实我没有动语言方面的设置。

**Comment by neilsustc** [comment]
你能尝试一下修改一下显示语言吗，按 [这个步骤](https://code.visualstudio.com/docs/getstarted/locales#_changing-the-display-language) 改成 `"locale": "en"`

**Comment by AndrewLauu** [comment]
可以把这个命令的快捷键改成Ctrl T O可能方便一点

**Comment by neilsustc** [comment]
改成英文之后可以搜到了吗？

快捷键的话可以参照 [这里](https://code.visualstudio.com/docs/getstarted/keybindings) 自定义

**Comment by willowj** [comment]
> 改成英文之后可以搜到了吗？
> 
> 快捷键的话可以参照 [这里](https://code.visualstudio.com/docs/getstarted/keybindings) 自定义

我的ok了。

重启 vscode 生效。

thx
