### ISSUE TITLE
Feature Request : Support for Text to UML tool(s)

### ISSUE THREAD

**Issue by DaBisounours** [yzhang-gh/vscode-markdown#328]
#### What is the problem?

Not a lot of us might need to print UML diagrams in their markdown files, but as this extension is called "All In One", I guess other people would need it as I do for my job.
Text to UML tools can produce automatically generated UML diagram from a specific language such as **_PlantUML_**, **_nomnoml_** and so on...
There are extensions that can preview it but once you try to export it, you are bound to what the exporting extension offers you.

#### How can I produce it?

Basically, the idea is to be able to embed some code directly into the markdown file as the following : 
![image](https://user-images.githubusercontent.com/9742239/48848914-7bf76e00-eda5-11e8-8416-62702b73f9a8.png)
I have a local working version that I use by modding the existing extension (5 added/modified lines of code) and I thought that I could share it here as some others might need it as well, AND of course if it goes along the lines of the project.
It parses PlantUML code using the[ **_markdown-it-plantuml_**](https://www.npmjs.com/package/markdown-it-plantuml) plug-in.

Tell me what you guys think of this.

**Comment by neilsustc** [comment]
The plan of this extension is to align with the CommonMark Spec plus some of widely recognized dialects (like GFM). There are too many dialects to support.

[Markdown Preview Enhanced](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced) goes a different way that providing you as many features as possible. You can give it a try.

If you are willing to share your build to others, you can pack it into `zip` and upload it in the comment.
I will keep this request open to collect more people's opinions.

**Comment by DaBisounours** [comment]
Thank you @neilsustc for your answer. Even though what was interesting was the fact that your extension can export markdown as html, I now understand why you cannot extend it with any dialects.

I may post tomorrow either the zip file or a quick tutorial to show how I did it so that others will be able to use their plugin of choice with your extension.

**Comment by 1354092549** [comment]
In discussion
#658

**Comment by yzhang-gh** [comment]
Closed with v3.0.0. This extension now works well with other Markdown plugins.
