### ISSUE TITLE
[Multi-cursor] cannot handle selections which are adjacent

### ISSUE THREAD

**Issue by freetonik** [yzhang-gh/vscode-markdown#33]
Hey,

if you select multiple instances of some text using multiple cursors (by pressing `super+d`) and try to toggle bold or italic, only the first instance is changed. See gif:

![](https://media.giphy.com/media/HVTbpbKtMksfK/giphy.gif)

P.S. Thank you for a great plugin!

**Comment by neilsustc** [comment]
I will fix it after vscode v1.16.0 is released.
Thank you for the feedback.

**Comment by neilsustc** [comment]
![multi-cursor-iloveimg-compressed](https://user-images.githubusercontent.com/7588612/30102116-2616a9b8-9321-11e7-979a-3c3e6894f8d9.gif)

It looks silly but it is the easiest implementation.

**Comment by freetonik** [comment]
Thanks! This is nice, but you're right, to be honest, it does look a bit silly :)

**Comment by neilsustc** [comment]
v0.9.0 released

**Comment by freetonik** [comment]
Sorry, but it doesn't work properly. See gif:

![](https://media.giphy.com/media/PDaoHqC8RKMRa/giphy.gif)

**Comment by neilsustc** [comment]
Please try [this version](https://github.com/neilsustc/vscode-markdown/releases/tag/v0.9.1)

**Comment by freetonik** [comment]
It solves the previous problem but introduces another one: if blocks are adjacent the formatting breaks and a warning message appears. See gif:

![](https://media.giphy.com/media/awJjVAg8WLgQ0/giphy.gif)

**Comment by neilsustc** [comment]
😭

It's a really hard corner case. I cannot figure out a solution now.

**Comment by ericyd** [comment]
@freetonik What is the desired behavior in your last image? Should it become
`**ababab**`
or
`**ab****ab****ab**`
or something else entirely?

**Comment by neilsustc** [comment]
Some thoughts

- If we have multiple selections, the "quick mode" doesn't take effect (because it just smartly select a word when there is no selection) → Just behave like in "normal mode", so I think it should be `**ab****ab****ab**`
- Ideally, we compute and return a `vscode.TextEdit` for each selection and apply them together (might need some more considerations here)

**Comment by freetonik** [comment]
I agree with neilsustc, it should become `**ab****ab****ab**`

**Comment by xuoutput** [comment]
按cmd+b变粗体还是没修好么, 我暂时用多选选中后按**来变粗体了

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

![multi](https://user-images.githubusercontent.com/7588612/52900493-41f40780-31ee-11e9-92d0-312b2aa48482.gif)
