### ISSUE TITLE
Choose Different Markdown Themes

### ISSUE THREAD

**Issue by muuvmuuv** [yzhang-gh/vscode-markdown#332]
It would be very cool to have an option for selecting different markdown preview themes. I think most of the developers publish to GitHub or maybe GitLab and therefore they both have there own Markdown styling. Would be nice if I could select those to see how my README, for example, looks to others when I push my changes.

**Comment by neilsustc** [comment]
I am afraid it can only be done by the vscode. Currently what an extension can do is provide `css` and `js` and let vscode apply them to the preview. You might need to file a request in the vscode repository.

**Comment by muuvmuuv** [comment]
Ah I see it is possible with `"markdown.styles"`, see: https://github.com/Microsoft/vscode/issues/48174

**Comment by neilsustc** [comment]
> `"markdown.styles"` is a list of all stylesheets to load in the preview, **not a list of selectable styles**.

I am not sure if I understood you correctly. If you are interested in **using a specific theme** but not **dynamically changing the theme**, then `"markdown.styles"` should be enough.

And [Markdown Preview Github Styling](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles) is a good extension from the vscode author.
