### ISSUE TITLE
Can't find the command to generate TOC when VS Code language is Chinese

### ISSUE THREAD

**Issue by rxliuli** [yzhang-gh/vscode-markdown#337]
I can't use the command to generate the title of the article, I don't know what happened. . .

But the title in the markdown article is still recognizable, and the latest version of VSCode is used by my generation.

![image](https://user-images.githubusercontent.com/24560368/49325976-3ba6a580-f586-11e8-8c49-97b9785066da.png)

> The first two toc commands here are the [Markdown TOC] (https://marketplace.visualstudio.com/items?itemName=AlanWalk.markdown-toc) plugin feature and are the current replacement for my generation.

My family's `User.Settings` configuration

```js
{
  // Encoding format
  "files.encoding": "utf8",
  // Automatically guess the encoding format when opening the file
  // "files.autoGuessEncoding": true,
  // font
  "editor.fontFamily": "Inconsolata",
  "editor.fontSize": 18,
  // Control the fold
  "editor.wordWrap": "wordWrapColumn",
  // Control terminal
  "terminal.integrated.fontSize": 16,
  "terminal.integrated.fontFamily": "Inconsolata",
  "terminal.integrated.cursorBlinking": true,
  // bash terminal using cmder
  "terminal.integrated.shell.windows": "D:/Program/cmder/vendor/git-for-windows/bin/bash.exe",
  // Override the default file icon
  "workbench.iconTheme": "eq-material-theme-icons",
  // Load a new empty workspace when the last session was not resumed
  "workbench.startupEditor": "newUntitledFile",
  // Automatically save the file (delay 1s)
  "files.autoSave": "afterDelay",
  "files.autoSaveDelay": 1000,
  // update
  "update.enableWindowsBackgroundUpdates": false,
  // Git executable path
  "git.path": "D:/Program/cmder/vendor/git-for-windows/bin/git.exe",
  // // Allow formatting of the specified file
  // "clang-format.executable": "/absolute/path/to/clang-format",
  // "gitlens.advanced.messages": {
  // "suppressShowKeyBindingsNotice": true
  // },
  // Prohibit markdown to automatically update the directory (the line number is always flashing and annoying...)
  "markdown-toc.updateOnSave": false,
  // "markdown-pdf.executablePath": "C://Program Files (x86)//Google//Chrome//Application//chrome.exe",
  "git.confirmSync": false,
  // markdown toc setting is compatible with github
  "markdown.extension.toc.githubCompatibility": true,
  // vscode markdown preview font
  "markdown.preview.fontFamily": "RTWS YueGothic Trial Regular",
  // Avoid the indentation of the markdown directory
  "editor.tabSize": 2,
  // "editor.detectIndentation": false,
  // Do not automatically update the directory when saving
  "markdown.extension.toc.updateOnSave": false,
  // Configure ESlint and Prettier
  "editor.formatOnSave": true,
  "eslint.autoFixOnSave": true, // fix the code in eslint format each time it is saved
  "prettier.eslintIntegration": true, // Let prettier use eslint's code format for validation
  "prettier.semi": false, // remove the semicolon at the end of the code
  "prettier.singleQuote": true, // replace single quotes with single quotes
  "javascript.format.insertSpaceBeforeFunctionParenthesis": true, // put a space between the function (name) and the following parentheses
  "vetur.format.defaultFormatter.html": "js-beautify-html", // formatted. vue html
  "vetur.format.defaultFormatter.js": "vscode-typescript", // Let js in vue be formatted in the ts format of the editor
  "vetur.format.defaultFormatterOptions": {
    "js-beautify-html": {
      "wrap_attributes": "force-expand-multiline" // attribute forcing line alignment
    }
  },
  "eslint.validate": [
    // Turn on checking for errors in .vue files
    "javascript",
    "javascriptreact",
    {
      "language": "html",
      "autoFix": true
    },
    {
      "language": "vue",
      "autoFix": true
    }
  ],
  // Control the display and operation of custom code snippets
  "editor.snippetSuggestions": "inline",
  "editor.tabCompletion": true,
  "explorer.confirmDragAndDrop": false,
  "materialTheme.autoApplyIcons": true,
  "workbench.colorTheme": "Material Theme High Contrast",
  "javascript.updateImportsOnFileMove.enabled": "always",
  "explorer.confirmDelete": false
}
```

I don't know what happened. Is the new plugin removing this feature?

**Comment by neilsustc** [comment]
Might be the same issue as #327.

**Comment by rxliuli** [comment]
However, I thought of another possibility. I used to install [Chinese (Simplified) Language Pack for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=MS-CEINTL.vscode-language-pack-zh-hans) plugin to let VSCode display Chinese, and later used native VSCode for some reason. So I wonder if this is the reason, so I tried to reinstall the Chinese language plugin.

The result, 233333, is really the reason for this!

![After installing the VSCode Chinese language plugin](https://raw.githubusercontent.com/rxliuli/img-bed/master/20181201212821.png)

Here my language is still `en`, just installed the Chinese language plugin, my generation does not understand what happened?

**Comment by rxliuli** [comment]
It should be a language problem. After installation, the Chinese command displayed under the Chinese system by default (instead of the language of VSCode), so you can't use `toc` to match the command to generate the article directory. Probably modify the initialization logic after installation. Right?

![输入 markdown 创建文章目录](https://raw.githubusercontent.com/rxliuli/img-bed/master/20181201211242.png)

**Comment by neilsustc** [comment]
I will investigate further in it.

**Comment by rxliuli** [comment]
thanks

Yu Zhang <notifications@github.com> 于2018年12月1日周六 下午10:19写道：

**Comment by Lemmingh** [comment]
🎉 是 VS Code 的 bug，他们已经修了。

在 VS Code 1.51.1 上，Command Palette 能同时显示本地化和英文的名称，搜索也正常。

---

* 2016 年，VS Code 引入了 <https://github.com/microsoft/vscode/issues/4679#issuecomment-214741754>
* 2018 年，那边出了一些问题。
* 根据
  * <https://github.com/microsoft/vscode-loc>
  * <https://github.com/microsoft/vscode/issues/54111#issuecomment-404466887>
  * <https://github.com/microsoft/vscode/issues/59392#issuecomment-425430729>

  我们的本地化资源文件是正确的。

所以，这个问题应该完全来自 VS Code，而且大概在 2019 年初彻底修正。

**Comment by yzhang-gh** [comment]
棒
