### ISSUE TITLE
Extension does not interpret smart punctation in preview

### ISSUE THREAD

**Issue by crystalfp** [yzhang-gh/vscode-markdown#345]
The preview does not interpret the “smart” typographic signs that are common in markdown:
--- → —
-- → – 
"a" → “a”
'b' → ‘b’

(Don't know if this is a bug or a feature request)

#### How can I reproduce it?
Take the preview of a markdown file containing:
```
"aaa" -- 'bbb' --- ccc
```

#### Is there any error message in the console?

No

**Comment by neilsustc** [comment]
I'm not sure whether I understand the "smart typographic signs" you mentioned.

In current [Markdown Spec](https://spec.commonmark.org/0.28/), I cannot find anything related. I guess you used to use some other Markdown editors?

Try the reference Markdown parser [here](https://spec.commonmark.org/dingus/)

![image](https://user-images.githubusercontent.com/7588612/50042685-3c4b3b80-005e-11e9-8236-edcb4d30c06c.png)

**Comment by crystalfp** [comment]
You are right. It is only a [convenience](https://pandoc.org/MANUAL.html#extension-smart) provided by Pandoc. Anyway, I'm so used to it to see when it is missing. It is also provided by [MultiMarkdown](http://fletcher.github.io/MultiMarkdown-5/typography.html), by a markdown-it [extension](https://github.com/edemaine/markdown-it-replacements) and maybe others.

So please, move it to "Feature request". In the meantime, thanks for your work. I especially appreciated the preview skipping the YAML metadata block. No other editor is doing this and renders it as a jumble of word at the beginning of the preview.

**Comment by neilsustc** [comment]
I see. Thank you for the input.

**Comment by Lemmingh** [comment]
Duplicate of #823, I guess.

The [`typographer` of **markdown-it**](https://github.com/markdown-it/markdown-it/blob/master/lib/rules_core/replacements.js) seems to turn on all these conversions, while the plugin `markdown-it-replacements` implements them with fine-grained control.

We might have to rely on <https://github.com/microsoft/vscode/issues/107328>

**Comment by crystalfp** [comment]
Yes, already covered in #823 Thanks!
