### ISSUE TITLE
Equation identifier using pandoc-eqnos breaks syntax highlighting

### ISSUE THREAD

**Issue by victoraraujo01** [yzhang-gh/vscode-markdown#346]
#### What is the problem?

Syntax highlighting stops working when using equation identifiers for Pandoc with pandoc-eqnos (https://github.com/tomduck/pandoc-eqnos) package. Example:

What I get:
<img width="281" alt="image" src="https://user-images.githubusercontent.com/507925/50120880-25fbd600-023e-11e9-9eff-73017de79ac5.png">

Expected result:
<img width="285" alt="image" src="https://user-images.githubusercontent.com/507925/50120887-314f0180-023e-11e9-894f-fcf02da2e833.png">

#### How can I reproduce it?

Just write anything on the same line of a `$$` ending a math block.

#### Is there any error message in the console?
No.

**Comment by neilsustc** [comment]
The math syntax highlight is actually contributed by the community. This is a bit hard for me.

On the other hand, it is not a normal Markdown syntax (and even not valid in LaTeX).

**Comment by victoraraujo01** [comment]
Ok, I understand this is not normal Markdown Syntax, but it is actually a wide employed pattern in Pandoc to reference parts of a document (see pandoc-crossref, pandoc-fignos or pandoc-tablenos). I've actually used the same notation to reference images and tables and markdown syntax highlighting still works just fine.

Could you give directions to which file should be modified to support this? Maybe I could take a look at it and see if I can help.

**Comment by neilsustc** [comment]
Thanks.

Here is the "entrance"

https://github.com/neilsustc/vscode-markdown/blob/fb5df65ba2aa4ab9d81e94c9b911a968b8fbe1a5/package.json#L300-L306

I suspect you only need to remove the ending `$` here 

https://github.com/neilsustc/vscode-markdown/blob/fb5df65ba2aa4ab9d81e94c9b911a968b8fbe1a5/syntaxes/math_display.markdown.tmLanguage.json#L13

And some references for TextMate Grammars
https://macromates.com/manual/en/language_grammars
http://www.apeth.com/nonblog/stories/textmatebundle.html

---

Finally, make sure no other syntax is broken

<details>
<summary>Test code<summary>

```markdown
<!-- inline math -->

Let's say $x + y = z$, ...

$\alpha$$\$$$\\$$\ $

\\$\\$\$$\alpha$

$\gdef\bar#1{#1^2} \bar{y} + \bar{y}$

$$\$$$

$$
<!-- display math -->

$$ \tag{1} x + y = z $$

$$
\begin{array}{cc}
    a & b \\
    c & d
\end{array}
$$

$$
\alpha%comment
$$

$$
\gdef\bar#1{#1^2} \bar{y} + \bar{y}
$$

<!-- functions -->

$$ \alpha, \hat{x}, \frac{x}{y} $$

<!-- character -->

$$ x \, y \; z $$

<!-- non-valid math environment -->

$20,000

$ x + y = z $

$\ $
```

</details>

**Comment by victoraraujo01** [comment]
I just made a quick test by making your suggested fix and it did, indeed, solved my problem. Thanks!

I will do some tests later with the test code you provided.

**Comment by victoraraujo01** [comment]
Here's the how the test code is highlighted without removing the `$` on the line you mentioned:

![image](https://user-images.githubusercontent.com/507925/50282282-68d5cd80-0439-11e9-8605-59a500d5a5ae.png)
_Image 1_

And here's the same code by changing the line to the following:

`			"end": "(?<![^\\\\]\\\\)(?<![^\\\\]\\$)(\\$\\$)([\\s]*)",`

![image](https://user-images.githubusercontent.com/507925/50282311-830fab80-0439-11e9-8527-83f01c1b6a50.png)
_Image 2_

You can see that line 16 shows a different output. The image below shows that the math block in lines 13-16 is not correctly rendered by the markdown preview pane (although it seems to recognize everything until the ending `$$` at line 16 as a math block):

![image](https://user-images.githubusercontent.com/507925/50282704-ccacc600-043a-11e9-90ab-0caa269b161e.png)
_Image 3_

Pandoc, however, does render it correctly:

![image](https://user-images.githubusercontent.com/507925/50283772-1519b300-043e-11e9-8e6b-16eac884d4f5.png)
_Image 4_

In my opinion, the syntax highlight showed in _Image 2_ should be the correct one, because the `$$` in the beginning of line 16 is not correctly escaped. Since, however, Pandoc supports it, maybe we could change the regular expression to the one shown below in order to support both the case I presented and mantain the expected output for the test code you provided?

`			"end": "(?<![^\\\\]\\\\)(?<![^\\\\]\\$)(\\$\\$)([\\s]*)(\\{\\#.*\\})?$",`

**Comment by neilsustc** [comment]
Sorry, I find I cannot remember why there is the line 16. Feel free to remove that line when testing.

And the math rendering of Markdown is provided by [markdown-it-katex](https://github.com/waylonflinn/markdown-it-katex), which assumes the block math delimiter `$$` to be either at the start or end of a line. That is why you get that rendering error.

Could you please open a PR when you feel it is good enough? Thanks.

**Comment by linsui** [comment]
The line 13 should be removed. The line 16 is just an ordinary test. The ending '$' just try to make the highlight behave the same as the rendering. :joy:

**Comment by danielhep** [comment]
This is an old issue, but has this been resolved yet? It still seems to be an issue.

**Comment by simjerd** [comment]
Hi, I'd like this issue to be solved, and I'd be happy to help. Is the test code you gave still up-to-date ? I can try and solve it and open a PR.

**Comment by yzhang-gh** [comment]
> Is the test code you gave still up-to-date?

I think so. (Just remove lines 13 and 16.)

**Comment by simjerd** [comment]
Okay then. So here is the updated test code, for the records:

<details><summary>Test code</summary>
<p>

```markdown
<!-- inline math -->

Let's say $x + y = z$, ...

$\alpha$$\$$$\\$$\ $

\\$\\$\$$\alpha$

$\gdef\bar#1{#1^2} \bar{y} + \bar{y}$

$$\$$$

<!-- display math -->

$$
\begin{array}{cc}
    a & b \\
    c & d
\end{array}
$$

$$
\alpha%comment
$$

$$
\gdef\bar#1{#1^2} \bar{y} + \bar{y}
$$

<!-- functions -->

$$ \alpha, \hat{x}, \frac{x}{y} $$

<!-- character -->

$$ x \, y \; z $$

<!-- non-valid math environment -->

$20,000

$ x + y = z $

$\ $
```
</p>
</details>

Just note line 11 (`$$\$$$`) is apparently not supported by pandoc, but it is by the katex preview.
So the code rendering is unchanged, with or without the final `$` in [here](https://github.com/neilsustc/vscode-markdown/blob/fb5df65ba2aa4ab9d81e94c9b911a968b8fbe1a5/syntaxes/math_display.markdown.tmLanguage.json#L13):

- With the `$`:
  ![With the `$`](https://user-images.githubusercontent.com/25692910/93710740-2a5ace80-fb49-11ea-8181-81ab9daf78f2.png)
- Without the `$`:
  ![Without the `$`](https://user-images.githubusercontent.com/25692910/93710730-1a42ef00-fb49-11ea-9b29-5a74ec29e572.png)

And, this was the point, adding text after the final `$$` of a math block is correctly supported if the `$` is removed. I just added "foo" on line 20:

- With the `$`:
  ![wdollar_foo](https://user-images.githubusercontent.com/25692910/93710806-8e7d9280-fb49-11ea-80bd-6a261102a86d.png)
- Without the `$`:
  ![ndollar_foo](https://user-images.githubusercontent.com/25692910/93710814-9c331800-fb49-11ea-83bb-f25df51d12cd.png)

Tell me if there are other things you want me to test.

**Comment by yzhang-gh** [comment]
Thanks. I've deleted the `$` as it should be the right solution in theory and also we don't see anything broken.

**Comment by simjerd** [comment]
Great, thanks !
