### ISSUE TITLE
Sync cursor and outline [edited]

### ISSUE THREAD

**Issue by ivysrono** [yzhang-gh/vscode-markdown#36]
show outline on sidebar.

**Comment by neilsustc** [comment]
Working on it

![image](https://user-images.githubusercontent.com/7588612/30780296-55487ac8-a13a-11e7-953b-8facc8914005.png)

**Comment by ivysrono** [comment]
Next release?

**Comment by neilsustc** [comment]
Not finished yet but will come soon 😉

**Comment by neilsustc** [comment]
Please check out v0.10.0

**Comment by ivysrono** [comment]
Thanks, 0.10.1 works great!
BTW, could the outline show like(beside) minimap?

**Comment by neilsustc** [comment]
Could you please provide more details about the feature (show like minimap?)

**Comment by ivysrono** [comment]
![default](https://user-images.githubusercontent.com/2649544/30788901-0f1840ac-a1d4-11e7-97f3-389979e3e7ba.png)

**Comment by neilsustc** [comment]
I guess it's already a vscode feature.

<https://code.visualstudio.com/docs/getstarted/userinterface#_minimap-outline-view>

**Comment by ivysrono** [comment]
Yes, I know "editor.minimap.enabled": false
However, there is minimap only, how could I set to show outline?

**Comment by neilsustc** [comment]
哈哈，我貌似懂了一点。
不过插件添加的 outline 只能显示在 explorer 面板里面。最接近的解决办法只能是把 explorer 放到右边（设置里面应该叫 sidebar？），然后用鼠标把 outline 拖到最上面

**Comment by ivysrono** [comment]
我也猜到可能插件权限有限。
左右无所谓，现在这样已经能用了，可以满意了。
谢谢。

**Comment by ivysrono** [comment]
用着用着又发现了一个小小的需求：
能否自动定位并展开所属outline？
还是上面的 Everedit 截图，我点击到 `### 1.3` 那一行的时候，右侧outline就会自动展开并定位到 1.3

**Comment by neilsustc** [comment]
vscode 自带的 Markdown 预览好像可以做到预览图和光标同步，
不过插件好像不能观察到鼠标点击的事件，我得找找看。
