### ISSUE TITLE
[Proposal] Omit toc and parent headers from the TOC by default

### ISSUE THREAD

**Issue by nombrekeff** [yzhang-gh/vscode-markdown#363]
## Kind of a **feature request**/**idea**/**frustration**
Hi there 👋,  
Let me explain, I've been using your plugin for a while now, and the **TOC** autogeneration is really helpful as you don't have to worry about updating it when you add new content, but I have a little frustration if you could call it that way, more so a doubt.

### Here is the thing:
I always find it kind of anoying that it adds "itself" (the **"Table Of Content"**) to the list, this is not much of a problem you add a **\** comment and its solved, but some times I declare the **TOC** header a couple of headers down, and it adds them also to the list, for example the title **h1**, I think they are not necesarly wanted in the list most of the time.

### Example
This is the current behaviour, without omiting anything:

```md
# my-app-header

## Table Of Content
- [my-app-header](#my-app-header)
  - [Table Of Content](#table-of-content)
  - [Something](#something)
    - [Something else](#something-else)

## Something
### Something else
```
Notice it adds the **"Table Of Content"** and **my-app-header**.

One solution would be to **omit** them wich can be done easy enough:
```md
# my-app-header <!-- omit in toc -->

## Table Of Content <!-- omit in toc -->
- [Something](#something)
  - [Something else](#something-else)
```

I think this is mostly not wanted,  I dont know if this is by design or by technical limitations or some other cause, but here are a couple of behaviours I've thought of:

**Behaviour 1:**  
I would maybe make it so it omits **"itself"** and any header **above** by default, and create a **include in toc** _(or similar)_ comment for telling it must be included instead.

**Behaviour 2:**  
It could also be solved by omitting any header greater that the **TOC** one, for example:
```md
# my-app-header
## Table Of Content
- [Something](#something)
  - [Something else](#something-else)

## Something
### Something else
```
* Notice it does not add itself nor his parent headers.

**Behaviour 3:** 
Maybe if setting them by default is not a wanted feature it could be done by setting some **option in vscode** to do it by default or setting a **comment at the top of the file**, something like:
```md
<!-- omit parents in toc -->
# my-app-header
```

Just some ideas, tell me what you think!
Chrees, and great plugin btw!

**Comment by yzhang-gh** [comment]
Thanks for the input.

There is an option `markdown.extension.toc.levels` you can make use of.
For example, setting it to `2..6` in your user settings (or workspace settings).

I tried avoiding too many assumptions on the user preferences.
Maybe some people would like to have `## Preface` or `## Recap` before `## Table of Contents`.

`<!-- omit in toc -->` is the simplest and straightforward way. That is the reason. (#177)

**Comment by nombrekeff** [comment]
Thanks for the quick reponse!

> There is an option markdown.extension.toc.levels you can make use of.

Ohh I see, that would solve my problem also.

> I tried avoiding too many assumptions on the user preferences.

I undertand and respect that, leaving it to the user to decide is a good way of going about it.

> Maybe some people would like to have ## Preface or ## Recap before ## Table of Contents.

True, I didn't think of that posibility. Well I think it's fine as is then, thanks! This solves my doubts!
