### ISSUE TITLE
toc causes MD007 warning, markdown.extension.toc.tabSize broken

### ISSUE THREAD

**Issue by JohnRGee** [yzhang-gh/vscode-markdown#364]
#### What is the problem?

toc indent has changed to 2 spaces with my settings, and now generates markdown lint warning MD007 as I have markdownlint settings expecting four spaces.

      "ul-indent": { "indent": 4 },

Support got added for `markdown.extension.toc.tabSize` to deal with MD007 in v1.8.0 and I was using that. 

https://github.com/yzhang-gh/vscode-markdown/commit/9a3bfd429ee9517a7aa57b39f62f6858005140e9#diff-3a050df20b3a1c2ba3272cb808d6ab8b

However, the code supporting this got removed:

https://github.com/yzhang-gh/vscode-markdown/commit/fb5df65ba2aa4ab9d81e94c9b911a968b8fbe1a5#diff-3a050df20b3a1c2ba3272cb808d6ab8b

#### How can I reproduce it?

`.editorconfig`

    [*.md]
    indent_style = space
    indent_size = 4

'.markdownlint`

    "ul-indent": { "indent": 4 },

Editor shows `Spaces: 4` in bottom bar.

Saving README.md with toc uses indent of two spaces.

**Comment by yzhang-gh** [comment]
> However, the code supporting this got removed:
>
> https://github.com/yzhang-gh/vscode-markdown/commit/fb5df65ba2aa4ab9d81e94c9b911a968b8fbe1a5#diff-3a050df20b3a1c2ba3272cb808d6ab8b

You were close to the answer. As said in the commit message,

> 🛠 #344, indentationSize: 'adaptive' or 'inherit'

Just give `markdown.extension.list.indentationSize` a try.

**Comment by JohnRGee** [comment]
Thanks for quick reply!

Ah, I did not realise new setting was defaulting to adaptive. I am warning free again after adding setting for:

    "markdown.extension.list.indentationSize": "inherit",
