### ISSUE TITLE
editor.tabSize not honored when scoped to "[markdown]"

### ISSUE THREAD

**Issue by borekb** [yzhang-gh/vscode-markdown#365]
#### What is the problem?

2.0.1 version of the extension doesn't seem to honor `editor.tabSize` settings when it's scoped to Markdown.

#### How can I reproduce it?

Put this to your `settings.json`:

```json
{
  "editor.tabSize": 2,
  "[markdown]": {
        "editor.tabSize": 4
    }
}
```

Observe in VSCode's status bar that there is "Spaces: 4".

Try to indent a list item. It will indent it with two spaces instead of four.

**Comment by yzhang-gh** [comment]
This is the new feature introduced in [v2.0.0](https://github.com/yzhang-gh/vscode-markdown/blob/master/CHANGELOG.md#200-20190119) 😉

![image](https://user-images.githubusercontent.com/7588612/51901675-1c729b80-23b0-11e9-8dbb-eb6eae491db4.png)

**Comment by borekb** [comment]
Oh, thanks, that explains it! I was trying to find this setting in VSCode but missed it (perhaps due to this: https://github.com/Microsoft/vscode/issues/67396).
