### ISSUE TITLE
Auto-complete for reference link IDs

### ISSUE THREAD

**Issue by mpaluchowski** [yzhang-gh/vscode-markdown#366]
It would be very useful to have auto-complete, when inside a link block, for the IDs of reference links, ie.

```markdown
This is [a link][<cursor here>]

[link-id]: http://www.example.org
```

When the cursor is where marked above, a popup list would suggest IDs from the list of reference links at the bottom of the document.

**Comment by yzhang-gh** [comment]
Thanks for your feedback (also in the marketplace).

You can try the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) now. (the limition is it only suggests after pressing `[`)

**Comment by mpaluchowski** [comment]
Brilliant ❤️ Tried it out, works as you described. Two possible improvements:

1. any chance the autosuggest dialog could also show the URL, next to the ID of the reference link?
2. would love if the autosuggest worked also with <key>Ctrl</key>+<key>Space</key>, when editing the reference inside `[]`, ie. if I'm editing `[some link][partial-id-<cursor kere>]` and press the key combination, I'd get suggestions starting with `partial-id-`.

**Comment by mpaluchowski** [comment]
And I confirm it does. Thank you!
