### ISSUE TITLE
The extension breaks the editor.tabCompletion setting

### ISSUE THREAD

**Issue by dschuessler** [yzhang-gh/vscode-markdown#367]
#### What is the problem?

When the extension is active, the setting `"editor.tabCompletion": "on"` does not work.

#### How can I reproduce it?

1. Copy this into your User Settings:

```
{
    "[markdown]": {
        "editor.quickSuggestions": true,
    },
    "editor.tabCompletion": "on"
}
```

2. Activate no other extension than "Markdown All In One".
3. Open a Markdown file with some content. The larger the amount of text, the better you can reproduce the problem, because more suggestions will pop up.
4. Begin typing until at least two suggestions appear in the suggestion widget.
5. Insert the first suggestion by pressing `Tab`.
6. Press `Tab` again.

Expected behavior: The second suggestion is inserted. (This actually happens when the extension is disabled.)
Actual behavior: A tab is inserted.

**Comment by yzhang-gh** [comment]
I cannot even reproduce step 5 (no extension, fresh new user settings, and your settings) (also tried only the user settings). You must have some other settings changed.

![tab](https://user-images.githubusercontent.com/7588612/52170566-94d8b400-2744-11e9-9d53-8a851f782099.gif)

**Comment by dschuessler** [comment]
It seems you did not set the markdown specific setting about `quickSuggestions` I mention in step 1.

![ohne titel cut 2019-02-04 20_00_00](https://user-images.githubusercontent.com/5774545/52231457-4e0cca80-28ba-11e9-9c59-3dda65ded366.gif)

**Comment by yzhang-gh** [comment]
Thanks for the information. I found I had some custom keybindings. Now I can confirm.

It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
