### ISSUE TITLE
中文目录自动转码了

### ISSUE THREAD

**Issue by Brain-RD** [yzhang-gh/vscode-markdown#368]
![](https://brian-1258565516.cos.ap-guangzhou.myqcloud.com/img/问题.png)

**Comment by Brain-RD** [comment]
![](https://brian-1258565516.cos.ap-guangzhou.myqcloud.com/img/问题.png)

**Comment by Brain-RD** [comment]
> #### What is the problem?
> ![](https://camo.githubusercontent.com/043047886d00adc1d2ce803be49c93cdbc52a881/68747470733a2f2f627269616e2d313235383536353531362e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f696d672f2545392539372541452545392541322539382e706e67)
> 
> #### How can I reproduce it?
> #### Is there any error message in the console?

**Comment by Brain-RD** [comment]
[](https://brian-1258565516.cos.ap-guangzhou.myqcloud.com/img/问题.png)

**Comment by yzhang-gh** [comment]
可以试试 `githubCompatibility` 选项
