### ISSUE TITLE
overrides VSCodeVim keybindings for workspace navigates

### ISSUE THREAD

**Issue by zachvalenta** [yzhang-gh/vscode-markdown#369]
#### What is the problem?

With VSCodeVim installed, can navigate 'workspace' section of the explorer using Vim shortcuts `h`, `j`, `k`, `l` instead of the typical 'find in workspace' fuzzy search.

When Markdown All-in-One is installed at the same time, the VS Code Vim 'workspace' nav reverts to fuzzy search.

#### How can I reproduce it?

Have both VSCodeVim and Markdown All-in-One installed simultaneously.

#### Is there any error message in the console?

No

**Comment by yzhang-gh** [comment]
Could you explain a little more about "workspace nav" and "fuzzy search"? I don't use Vim and am not familiar with these features.

**Comment by zachvalenta** [comment]
Sure thing!

The default behavior of VS Code is that, when I'm in the file explorer panel and enter text, VS Code performs a fuzzy search. Like the below screenshot, when I enter `pycharm`, VS Code matches with the `pycharm.md` file:

![screen shot 2019-02-10 at 12 22 08 pm](https://user-images.githubusercontent.com/11388735/52536945-ebd71e00-2d2e-11e9-8b58-4ec65149c050.png)

However, when VsCodeVim is enabled and I'm in the file explorer panel and enter text, VS Code treats my text as Vim shortcuts, so I can go down a file using `j`, go up a directory using `h`, etc.

The issue I'm facing is that when I have Markdown All-in-One installed at the same time as VsCodeVim, I can no longer use shortcuts like `j` and `h` in the file explorer panel.

**Comment by yzhang-gh** [comment]
![vim](https://user-images.githubusercontent.com/7588612/52537435-c8c46280-2d5e-11e9-99d1-195af82b83cc.gif)

Seems to work well here. (You can see both extensions are activated)

And this extension doesn't do anything with `j`, `k`. Can you test it again with only these two extension enabled? (And make sure you are using the latest versions 😉)

**Comment by zachvalenta** [comment]
I followed your advice and Markdown All in One was indeed **not** the problem. 

Thanks for helping me with this!
