### ISSUE TITLE
[Request] Support back button navigation in preview window

### ISSUE THREAD

**Issue by alshdavid** [yzhang-gh/vscode-markdown#370]
When the md preview window is open as the only tab open in the workspace, the back button on my mouse sends me to the previously opened source file.

I use a lot of hyperlinks in my documentation, it would allow for a much more ergonomic experience to allow the back button to send me to the previously opened md file preview.

**Comment by yzhang-gh** [comment]
I am afraid it is not feasible for an extension. You need to open a request in the vscode repository (they have a built-in markdown extension).

**Comment by irvnriir** [comment]
What about adding a button for this to right/tab toolbar? That won't support the "back" mouse button, but would be extremely useful.

If adding this. Please use a history which starts from opening the preview tab. So it would be not affected by other tabs.
