### ISSUE TITLE
File keeps scrolling down when preview is opened.

### ISSUE THREAD

**Issue by felipeek** [yzhang-gh/vscode-markdown#371]
#### What is the problem?
File keeps scrolling down when preview is opened.

#### How can I reproduce it?
1. Open a markdown file with a big number of lines
2. CTRL+SHIFT+P and Markdown: Open Locked Preview to the Side
3. Start typing text at the top of the text area and also hit enter sometimes
4. For some reason, VSCode will slowly start to scroll the file down until the cursor is at bottom edge of the text area

#### Is there any error message in the console?

Happening under Ubuntu

**Comment by yzhang-gh** [comment]
Actually this "scrolling" feature is provided by the vscode built-in Markdown extension. There are two options "Scroll Editor with Preview" and "Scroll Preview with Editor" you can configure.

If the problem is still there. You might need to open an issue it in the vscode repository.

**Comment by spanishgum** [comment]
For anyone in the future landing here, here is the setting:

```json
{
  "markdown.preview.scrollEditorWithPreview": false
}
```

For me, mermaid diagrams with errors we're causing the file to scroll to the bottom __every time__.
