### ISSUE TITLE
html code not parsed properly

### ISSUE THREAD

**Issue by Splike** [yzhang-gh/vscode-markdown#373]
I want to center some images, and the best way I've found to do this, is with html

This works
````
<center>

![image](image.svg)
</center>
````

This doesn't work
````
<center>
![image](image.svg)
</center>
````
If there is a better way to center images, I'd like to hear about it. If not, maybe consider letting us do it more easily without html code.

**Comment by yzhang-gh** [comment]
VSCode uses [markdown-it](https://markdown-it.github.io/) to render Markdown. As far as I know, there is no good way to center an image purely with Markdown.

If you would like to center all the images, one solution might be using externel `css` files (with setting `markdown.styles`)

**Comment by Splike** [comment]
Fair enough, but is there a way not to break the preview image, when I remove the blank lines?

**Comment by yzhang-gh** [comment]
I am afraid not. You can test it using the markdown-it website mentioned above.

**Comment by Lemmingh** [comment]
## Is there a way not to break the image, when I remove the blank lines

No. [HTML block of type 6](https://spec.commonmark.org/0.30/#html-blocks) requires:

> End condition: line is followed by a blank line.

## I want to center some images

[`<center>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center) is obsolete. It may freeze modern HTML processors and browsers. AVOID IT.

Use CSS although it might be a bit tricky.

[Image](https://spec.commonmark.org/0.30/#images) is inline structure. Hence,

```markdown
![](url)
```

gives

```html
<p><img src="url" alt=""></p>
```

This CSS rule can make that image horizontally centered:

```css
p > img:only-child {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```

However, as CSS is not aware of [text node](https://developer.mozilla.org/en-US/docs/Web/API/Text), the rule also applies to:

```markdown
Look ![](url) here.
```

```html
<p>Look <img src="url" alt=""> here.</p>
```

This cannot be solved with CommonMark now. But [some flavors support attributes](https://talk.commonmark.org/t/consistent-attribute-syntax/272):

```markdown
![](url){.horizontally-centered}
```

```html
<p><img src="url" alt="" class="horizontally-centered"></p>
```

Then, you can do a precise selection:

```css
img.horizontally-centered {
    display: block;
    margin-left: auto;
    margin-right: auto;
}
```
