### ISSUE TITLE
Sometimes list auto editing won't work properly.

### ISSUE THREAD

**Issue by Sciroccogti** [yzhang-gh/vscode-markdown#374]
#### What is the problem?

Sometimes list auto editing won't work properly. 

It's pretty weird, because as the gif shows, the function acts well at the lines written several days ago, but when I try it in a new line, problem occurs.

#### How can I reproduce it?

![md](https://user-images.githubusercontent.com/32357397/52837105-730a0480-3128-11e9-994c-46730cbf7ccd.gif)

I guess maybe the large size of `.markdown` causes this problem, because this function works quite well before, however the problem above occured after the update of Win10 along with the reboot of my PC, while I've already written over 1000 lines in this `.markdown`.

#### Is there any error message in the console?

Saddly no.

**Comment by yzhang-gh** [comment]
Could you try making a fake document which can still produce this issue?

**Comment by Sciroccogti** [comment]
Sorry I failed to reproduce this issue in a new document, so I had to upload the original document.

However, it got weirder when I pasted the content of the original document into a brand new document. This issue can be reproduced in the new document, even after I deleted all the content in it.

What's more, this issue only occurs **in some part of the document**. I 'll appreciate it even if the issue is not fixed, because all of these are so confusing.😂

[模电.txt](https://github.com/yzhang-gh/vscode-markdown/files/2871550/default.txt)

PS: uploading `.md` is not supported, so I use `.txt` instead. I have already tested that if I turn the `.txt` into a `.md`, this issue can still be reproduced **at the bottom of the document**.

**Comment by yzhang-gh** [comment]
Thanks for the document.

The reason is some of your lists have `tab` rather than `space` after list markers. Although `tab` is not mentioned in the definition of a list in the CommonMark Spec, it does behave the same as `space` in the Markdown preview. (You can set `editor.renderWhitespace` to `all` to see them)

![white](https://user-images.githubusercontent.com/7588612/52898452-27ae2f80-31d6-11e9-9861-d89be8b3342b.gif)

If you would like to use `tab` key to insert `space`, you can check the `editor.insertSpaces` option.

**Comment by Sciroccogti** [comment]
Thanks so much!

**Comment by Sciroccogti** [comment]
Sorry to bother, but I just ran into a similar problem:
![](https://user-images.githubusercontent.com/32357397/78452578-9ee6a180-76be-11ea-9687-79682ec65f8d.gif)

As you can see, it is functional above the code block, but not working below it.
***
I noticed that as long as I replace the `C++` with `Cpp`, then everything will be all right.

**Comment by yzhang-gh** [comment]
Good catch. See #593.
