### ISSUE TITLE
Number the formula and quote it outside the formula

### ISSUE THREAD

**Issue by asurance** [yzhang-gh/vscode-markdown#375]
* Question  
 I want to number the formula and quote it outside the formula.But it seems that '\label' and '\ref' is not support.Do I have an another choice?
* Example  
```Markdown
$$
（x-C_x)^2+(y-C_y)^2=R^2\label{circle}
$$
$$
(x-C_x)(x-P_x)+(y-C_y)(y-P_y) = 0\label{dot}
$$
We can get the following formula by $(\ref{circle})-(\ref{dot})​$:
.....
```

**Comment by yzhang-gh** [comment]
All the supported functions are listed [here](https://katex.org/docs/supported.html).

What you are looking for is `\tag`
