### ISSUE TITLE
formula is not supported on github

### ISSUE THREAD

**Issue by asurance** [yzhang-gh/vscode-markdown#376]
#### What is the problem?
formula is not supported on github though I set Github Compatibility true.
* In visual studio code
![image](https://user-images.githubusercontent.com/23739401/52844816-6e514a80-3140-11e9-9bbe-aa71b9fffe31.png)
* on github
![image](https://user-images.githubusercontent.com/23739401/52844915-ba03f400-3140-11e9-8a50-6d66e0abaa26.png)

#### Is there any error message in the console?
No

**Comment by yzhang-gh** [comment]
GitHub Flavored Markdown doesn't support math. The `githubCompatibility` is used to decide how we generate heading id.

**Comment by upupming** [comment]
Yes, github doesn't support external js files for security reasons.

You can convert it to html and host html on github pages.

**Comment by asurance** [comment]
Ok, I'll try

**Comment by yzhang-gh** [comment]
Thanks for the input
