### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kvnol** [yzhang-gh/vscode-markdown#377]
- Issue Type: `Performance`
- Extension Name: `markdown-all-in-one`
- Extension Version: `2.0.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/din01/yzhang.markdown-all-in-one-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by yzhang-gh** [comment]
I don't see any log file or reproducing steps.
