### ISSUE TITLE
Table side frame is invisible

### ISSUE THREAD

**Issue by donaldtone** [yzhang-gh/vscode-markdown#378]
#### What is the problem?
in a markdown file, create table like that:
|table1|table2|
|---|---|
|cell2|cell2|
|box1| box2|

in the preview window, the table frame is not completed.
![image](https://user-images.githubusercontent.com/23021576/52908521-9b3b5580-3245-11e9-9077-87499e31712d.png)

**Comment by yzhang-gh** [comment]
Markdown is rendered as HTML. The style is controlled by CSS. For example, GitHub adds its own CSS so it looks like

|table1|table2|
|---|---|
|cell2|cell2|
|box1|box2|

You can add your own CSS with option `markdown.styles` (which requires simple CSS knowledge).
Or you can search for a Markdown theme in the marketplace (like [Markdown Preview GitHub Styling](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles)).

**Tip**: You can press `alt+shift+f` to format your table.

**Comment by zhongjiajie** [comment]
@yzhang-gh 
shutcut `alt+shift+f` not exists.
![pic](http://ww1.sinaimg.cn/large/775a67e7gy1g0ifrw9ye4j20pk04tdg0.jpg)
I use ubuntu 18.04, vscode 1.31.1, markdown-all-in-one 2.1.0 (2019.02.16)

**Comment by yzhang-gh** [comment]
![default](https://user-images.githubusercontent.com/7588612/53323704-d3423880-38d6-11e9-9aa6-b10f2f209e2a.png)

The keybinding is a bit different on Ubuntu. You can type "Format Document" to find it.

**Comment by zhongjiajie** [comment]
@yzhang-gh It work! thank a lot. But should we write same txt for remind user the differene shutcut between OS system?

**Comment by yzhang-gh** [comment]
@zhongjiajie Added 👍.

**Comment by zhongjiajie** [comment]
@yzhang-gh Awesome!
