### ISSUE TITLE
Need to get in touch with you?

### ISSUE THREAD

**Issue by ahmadawais** [yzhang-gh/vscode-markdown#379]
Hey, @yzhang-gh 🙌

I'd love to get in touch with you but can't find how. Can you send me an email via [https://AhmadAwais.com/contact](https://AhmadAwais.com/contact)?

It's about including your extension in my VSCode course and more.

Peace! ✌️

**Comment by ahmadawais** [comment]
Closing this issue. Looking forward!

**Comment by yzhang-gh** [comment]
Just drop me an email at yzhang.life@outlook.com 😉

**Comment by ahmadawais** [comment]
Awesome! 💯

Just sent an email.
