### ISSUE TITLE
table format bug

### ISSUE THREAD

**Issue by ferencdg** [yzhang-gh/vscode-markdown#381]
If I have a row like |a||c| without any space between two |, and use the auto formatter then one of the | is removed and makes the table look like |a|c

I have no control over how other developers write the table, sometimes they don't leave any space between |

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by ferencdg** [comment]
thanks, when is it gonna be available on the marketplace?

**Comment by yzhang-gh** [comment]
The latest version was published 3 days ago. So probably we will wait for a while until we have more bug fixes or features.
