### ISSUE TITLE
Provide option to disable automatic Markdown link creation 📎️

### ISSUE THREAD

**Issue by fvcproductions** [yzhang-gh/vscode-markdown#382]
#### What is the problem?

Whenever I copy over a block of text with links in it, the extension creates a Markdown link automatically. Caused by #20.

No way to disable this specific feature so I have to disable entire extension in meantime.

#### How can I reproduce it?

Highlight over a body of text with a link inside of it but that you don't want to be made into a Markdown link and paste new text. 

I'm on macOS Mojave so <kbd>command</kbd> + <kbd>V</kbd> causes this instead of <kbd>ctrl</kbd> + <kbd>V</kbd>.

For example, let's say I have this block of text.

```markdown
<blockquote class="embedly-card"><h4><a href="https://twitter.com/fvcproductions/status/1098361334733946883">Frances Coronel on Twitter</a></h4><p>Excited that I was just accepted and will be attending my second International Women's Day Summit through Google's @WomenTechmakers on March 2nd! 🎉⠀ ⠀ #IWD19⠀ ⠀ https://t.co/Nhfn8KIAUR</p></blockquote>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
```

and I have this text I don't want to be made into a link

```markdown
not a link
```

it will then turn into this even though I don't actually want that

```markdown
[not a link](<blockquote class="embedly-card"><h4><a href="https://twitter.com/fvcproductions/status/1098361334733946883">Frances Coronel on Twitter</a></h4><p>Excited that I was just accepted and will be attending my second International Women's Day Summit through Google's @WomenTechmakers on March 2nd! 🎉⠀ ⠀ #IWD19⠀ ⠀ https://t.co/Nhfn8KIAUR</p></blockquote>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>
)
```

#### Is there any error message in the console?

Nope

**Comment by yzhang-gh** [comment]
Thanks for the report. This is a bug since obviously it should not be treated as a link.

But I am away from laptop now. A workaround it to delete the keybinding by yourself (left bottom corner>keyboard shortcuts>search for `cmd+v`>delete the `markdown...paste` one)

**Comment by yzhang-gh** [comment]
Should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) now 😉.

**Comment by fisker** [comment]
when this will be released ?

**Comment by yzhang-gh** [comment]
Probably this weekend
