### ISSUE TITLE
Math rendering not working in markdown lists

### ISSUE THREAD

**Issue by jmigual** [yzhang-gh/vscode-markdown#384]
#### What is the problem?

LaTeX inline should always be rendered but if I have a markdown list it does not work.

#### How can I reproduce it?
This code reproduces the issue
```markdown
- $T_i = $ period
- $C_i = $ worst-case execution time
- $D_i = $ relative deadline
- $\phi_i = $ offset
- $U_i = \frac{c_i}{\tau_i} = $ utilization
```
It gets rendered like this:
![screenshot from 2019-02-26 09-03-17](https://user-images.githubusercontent.com/6493651/53396723-7792b080-39a5-11e9-9105-33ecd5922cff.png)

#### Is there any error message in the console?

No, thhere's no error message in the console

Thank you in advance

Edit: I found out that it is related with the space at the end of the math. If I remove this space it gets rendered properly

**Comment by yzhang-gh** [comment]
> Edit: I found out that it is related with the space at the end of the math. If I remove this space it gets rendered properly

Yes, that is the reason. To avoid ambiguity with US dollar symbol, no leading or trailing space is allowed for inline math.

**Comment by jmigual** [comment]
Oh I see. It is not an issue then.
