### ISSUE TITLE
convert to html changes "=" to "%3D" html5 for image links 

### ISSUE THREAD

**Issue by ericjmartin** [yzhang-gh/vscode-markdown#385]
#### What is the problem?

image links `![]()` seem to get HTML prettied during conversion

#### How can I reproduce it?

In markdown:

    ![link](https://www.google.com/search?q=markdown)

 Result in html:

    <img src="https://www.google.com/search?q%3Dmarkdown" alt="link"></p>

#### Is there any error message in the console?

no

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
