### ISSUE TITLE
auto-format on save

### ISSUE THREAD

**Issue by ferencdg** [yzhang-gh/vscode-markdown#386]
I am not sure if this is a vs issue or extension issue: if I open an .md file inside my workspace folder, modify it and a save it, it will be autoformatted on save. However if I open a file outside of my workspace it is not autoformatted on save(in fact even manual format doesn't work)

**Comment by yzhang-gh** [comment]
I tried but cannot reproduce.

With this file structure

```
test/
├ test.md
└ subfolder/
  └ test2.md
```

open `subfolder` with VSCode and then open `test.md` within the current one. Both `test.md` and `test2.md` work well.

Note that `formatOnSave` is `false` by default. Do check your (workspace) settings.
