### ISSUE TITLE
Autocomplete does not work for math expressions

### ISSUE THREAD

**Issue by kevinmackie** [yzhang-gh/vscode-markdown#387]
#### What is the problem?
Autocomplete does not work when entering mathematical equations.
See attached animated gif.
![markdown-all-in-one-no-math-autocomplete](https://user-images.githubusercontent.com/6693248/53684074-898a9100-3cce-11e9-9ecb-d9af7fd6141b.gif)

#### How can I reproduce it?
With the latest version of Visual Studio Code (1.31.1),
and with a fresh install of Markdown-All-in-One (2.1.0),
try to enter a math expression like $\lambda$. No autocomplete is shown, even if you press Ctrl-space

#### Is there any error message in the console?
I toggled on Developer Tools and there are no error messages.

**Comment by yzhang-gh** [comment]
The cursor should be inside a valid math environment, e.g. `$\lam|$` or `$$ \lam| $$`.

**Comment by kevinmackie** [comment]
It is, the expression shown in the clip is $\lambda$ character by character.
