### ISSUE TITLE
how to stop auto-update Table of Contents

### ISSUE THREAD

**Issue by mathpaquette** [yzhang-gh/vscode-markdown#388]
#### What is the problem?
Table of contents is getting auto-generated on file save with unwanted sections on it. 

#### How can I reproduce it?
Markdown 2.1.1
Vscode 1.31.1

open a MD with an outdated table of contents. touch the file and save, the table of contents is getting regenerated

#### Is there any error message in the console?

no error.

**Comment by yzhang-gh** [comment]
See option `markdown.extension.toc.updateOnSave`

Tip: use `<!-- omit in toc -->` comment to ignore headings

**Comment by JounQin** [comment]
![image](https://user-images.githubusercontent.com/8336744/63407719-cc2c5b00-c41f-11e9-8377-b56f74c2e9a3.png)

@yzhang-gh Seems not working to me.
