### ISSUE TITLE
Print to HTML broken?

### ISSUE THREAD

**Issue by gjsjohnmurray** [yzhang-gh/vscode-markdown#389]
#### What is the problem?
Print to HTML doesn't seem to work. I am using the latest VSCode (1.32.1) on Windows. I haven't used the extension before, so perhaps I'm doing something wrong. But the Developer Tools Console otput (see below) seems to indicate a problem caused by tightened security inside VSCode.

#### How can I reproduce it?
Install extension, open a .md file, then invoke the command Markdown: Print current document to HTML

#### Is there any error message in the console?
[Embedded Page] Refused to apply inline style because it violates the following Content Security Policy directive: "style-src vscode-core-resource:". Either the 'unsafe-inline' keyword, a hash ('sha256-W9X+lnH/6u59xZ9bcuQy9nnYRXC1HxRSEIOsdCFggaM='), or a nonce ('nonce-...') is required to enable inline execution.

From webviewElement.ts:284

**Comment by yzhang-gh** [comment]
Seems to work here. Do you have any custom style in your document?
