### ISSUE TITLE
syntax.decorations: The phase of recognizing <code> tag is broken

### ISSUE THREAD

**Issue by yumetodo** [yzhang-gh/vscode-markdown#390]
#### What is the problem?

Look at this markdown below:

```md
```a`a```
```

This markdown text should be converted like below HTML

```html
<code>a`a</code>
```

```a`a```

markdown-it recognize this correctly.

![image](https://user-images.githubusercontent.com/10869046/54065881-0d61f180-426a-11e9-8521-11717016d7e6.png)

However, vscode-markdown recognize like below:

```html
``<code>a</code>`a```
```

As a result, in editor view, decoration rectangle drawing result is strange.

![img](https://i.stack.imgur.com/r1Qak.png)

#### How can I reproduce it?

1. `"markdown.extension.syntax.decorations": true`
2. create new markdown file
3. paste  

```md
```a`a```
```

#### Environment

- Windows 10 Home 1809
- Visual Studio Code 1.31.0 or later
- Markdown All in One 2.1.1

ref:
- https://stackoverflow.com/questions/54625024/who-create-this-rectangle-in-visual-studio-code-markdown-text-edit/54943197#54943197

**Comment by yzhang-gh** [comment]
Thank you for the report. Looks a bit hard to handle...

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by yumetodo** [comment]
@yzhang-gh I install build 1.0.29, then, work fine!

BTW, Another pattern cause bug found...

```markdown
`a
a`
```

This should be recognize like `<code>a a</code>`.
![image](https://user-images.githubusercontent.com/10869046/54485844-775e4480-48c3-11e9-835c-bb04f32dc7ca.png)

**Comment by yzhang-gh** [comment]
You are right. However vscode decorations cannot cover multi-lines. So this is the best we can do now.

**Comment by yumetodo** [comment]
> vscode decorations cannot cover multi-lines.

I'm not sure about vscode decorations. However, as far as I see, [Bracket Pair Colorizer](https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer) do it (`bracketPairColorizer.showVerticalScopeLine`, I don't know Bracket Pair Colorizer really use vscode decorations system to draw)
![image](https://user-images.githubusercontent.com/10869046/54526540-73611e00-49ba-11e9-8f93-397b8f0c618d.png)

---

How do you think about code tag syntax in code block syntax?

    ```
    aaa
    `a`
    a
    `````
        ```a```

![image](https://user-images.githubusercontent.com/10869046/54526674-cd61e380-49ba-11e9-9fad-9647bedd84b7.png)

**Comment by yzhang-gh** [comment]
> The multi-line thing

[This](https://github.com/Microsoft/vscode/issues/63600) is the upstream issue. _Bracket Pair Colorizer_ might have used some tricks (technically, we can fake multi-line decoration with multiple single-line decorations 😂). However, I am not a fan of this.

---

> Decorations Inside code blocks

Interesting. It is doable to disable decorations there. I can look into it this weekend.

**Comment by yzhang-gh** [comment]
I have disabled decorations in the fenced code blocks. However, I didn't touch the indented code blocks. There are many corner cases if we want to perfectly determine the indented code blocks. I don't think it is worth that effort.

**Comment by yumetodo** [comment]
Thank you for your fix!
