### ISSUE TITLE
$$\and$$ doesn't recognize

### ISSUE THREAD

**Issue by wuyudi** [yzhang-gh/vscode-markdown#392]
#### What is the problem?
I type $$\and$$,but I don't see the proper symbol.

#### How can I reproduce it?
as the problem said.

#### Is there any error message in the console?

no

**Comment by yzhang-gh** [comment]
All supported symbols are listed [here](https://katex.org/docs/supported.html). Are you looking for `\And`?

**Comment by wuyudi** [comment]
Now I know what i want is $$\land$$,thanks.
