### ISSUE TITLE
Syntax problem with LaTeX block & strikethrough

### ISSUE THREAD

**Issue by Tiger3018** [yzhang-gh/vscode-markdown#393]
#### What is the problem?

**Extesion Enabled**

![Screenshot_20190313_090349](https://user-images.githubusercontent.com/31267153/54246434-cdec1b80-456f-11e9-920d-74215af7f9d6.png)

The strikethrough (and code block) shouldn't be highlighted in latex block.

**Disabled**

![Screenshot_20190313_090419](https://user-images.githubusercontent.com/31267153/54246435-cdec1b80-456f-11e9-8fdb-2fc2e1c06796.png)

#254 & #185

**Comment by yzhang-gh** [comment]
Thanks for the report. Will have a look later

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by Tiger3018** [comment]
Fixed. Thank you.
