### ISSUE TITLE
Print to HTML does not search for markdown.styles relative to workspace folder.

### ISSUE THREAD

**Issue by TheWyo** [yzhang-gh/vscode-markdown#394]
#### What is the problem?
If you use the setting `markdown.styles` to provide a path to the css file to use, using the Print current document to HTML command will search for those files relative to the open file the command is run on, whereas VSCode's preview searches relative to the workspace root.

#### How can I reproduce it?
Folder structure:
```
workspaceRoot
├subfolder
 ├test.md
 ├test.css
```
Settings.json:
```json
"markdown.styles": ["subfolder/test.css"]
```

- Open test.md, and run Code's Open Preview command. CSS correctly applied.
- Run print to HTML command - CSS not applied because print command is looking for root/subfolder/subfolder/test.css
- Change markdown.styles to just "test.css"
- Run commands again: Preview not styled as Code is looking for root/test.css, print is styled as it's next to .md file.

#### Is there any error message in the console?

Warning:

[UriError]: Scheme is missing: {scheme: "", authority: "", path: "subfolder/test.css", query: "", fragment: ""}

**Comment by yzhang-gh** [comment]
Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by TheWyo** [comment]
Fixed in the dev build. Thanks!
