### ISSUE TITLE
Formatter must unregister when being disabled

### ISSUE THREAD

**Issue by jrieken** [yzhang-gh/vscode-markdown#395]
A formatter that is registered with VSCode must be unregistered when the formatter is being disabled. Otherwise VSCode still thinks a formatter is available, enabling formatting actions and contributing to the problem of conflicting formatters. See Microsoft/vscode#70314 for more details on the topic and feel free to reach out to us for further questions.

Thanks & #HappyCoding

**Comment by yzhang-gh** [comment]
Thanks for letting me know. Done.
