### ISSUE TITLE
Keybindings not working

### ISSUE THREAD

**Issue by DarkCreekWay** [yzhang-gh/vscode-markdown#396]
#### What is the problem?

keybindings do not work at all.

#### How can I reproduce it?
Try Ctrl+B on Windows with 

VSCode V1.32.1 
Extension 2.2.1

I suspected an issue with the When Clause for the KeyBinding of

markdown.editing.toggleBold

changed the when clause

Before:
editorTextFocus && !editorReadonly && editorLangId == 'markdown'

After:
editorTextFocus && !editorReadOnly && editorLangId == 'markdown'

notice Casing change of parameter editorReadonly vs. editorReadOnly 

After editing the clause, the key binding worked as expected.

Seems, package.json needs to be fixed.

**Comment by yzhang-gh** [comment]
Thanks for the report. It is a good catch, although `editorReadonly` should also work. The default key bindings also use it pretty often.

![vscode keybindings](https://user-images.githubusercontent.com/7588612/54317192-661eea80-45da-11e9-958b-22637d513a65.png)

Maybe there is another reason causing this problem?

**Comment by DarkCreekWay** [comment]
I tested further and found the root cause. The [Visual Studio Keymap Extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings)  interfers with the keybindings of this extension. As soon, as the other extension is deactivated, keybindings work as expected.

Editing the when clause changes the key binding from "Standard" to "User". Seems, VS Code evaluates the user defined binding first. This led me on the wrong track.

Having both extensions side by side would be great, but I am not sure, if this is feasible.

**Comment by yzhang-gh** [comment]
That makes sense then.

I am wondering what is the functionality of  `ctrl+b` in that extension. If it is not applicable for Markdown, we can open an issue there to exclude Markdown documents.
Besides that, overriding it with a user-level key binding is always a simple solution.

**Comment by DarkCreekWay** [comment]
Is there a way to control priorities of key bindings ?

I think about a prioritized approach like

Prio - Area
0 - VS Code
1 - Keymap Extension
2 - Filetype Extension
3 - User Defined

Even if this is possible, it would be cumbersome to sync with other extension author's in order to avoid conflicts.

**Comment by yzhang-gh** [comment]
As far as I know, we can't. Maybe we should open an issue in the vscode repository. But I don't think there is a good solution...

**Comment by DarkCreekWay** [comment]
I browsed the vscode issues. There are a lot of issues regarding keybindings.
This issue [Feature Request: Keybinding Overloading](https://github.com/Microsoft/vscode/issues/39888) made it to the Backlog and looks promising.

So, as we can't do much here, I close the issue.

Keep up the good work!
