### ISSUE TITLE
Wrong links(URL) recognition on paste

### ISSUE THREAD

**Issue by Ovsyanka** [yzhang-gh/vscode-markdown#397]
At least some URLs not recognizing. For example this:

```
https://github.com/gliderlabs/docker-alpine/blob/master/docs/usage.md#disabling-cache
```

I made some digging on this issue. First of all I tested  few regexps and looks like django's [regexp](https://stackoverflow.com/a/7160778/3653002) works better then others. Here is testing results, including your implementation:
* [daringfireball](https://regex101.com/r/J50kem/1)
* [yours](https://regex101.com/r/byk8OT/7)
* [some from stackowerflow](https://regex101.com/r/byk8OT/6)
* [django 1.3](https://regex101.com/r/byk8OT/8)

I used there new django [test cases](https://github.com/django/django/tree/master/tests/validators) but old django code because [actual code](https://github.com/django/django/blob/master/django/core/validators.py#L74) has to be adapted.

I think that django's test cases is more or less OK, maybe with some changes. For example you could allow trailing spaces.

So, I suggest you to make test cases based on django's and add unit tests into your code or at least textual examples to describe intended behavior. Then you could adapt new django code to use in your project.

**Comment by yzhang-gh** [comment]
Wow, thanks for the investigation. I just googled a regexp and then used it 😂.

Would you like to make a PR for the better regexp? As for the unit tests, they are nice to have, although I guess we won't change the regexp very often.

**Comment by Ovsyanka** [comment]
@yzhang-gh As I understood you are OK with the intended behavior, so yes, I could do it. I have no experience with vs code extensions development so It will take some time.

Unit tests needed at least to show what behavior is expected.

**Comment by yzhang-gh** [comment]
Thank you. The regexp change is easy and you already found the place.

The unit tests part, actually, needs to rework (#261). But you don't have to.
The simplest way (which is also not that good 😂) is to duplicate any `*.test.ts` file in the `test` folder and change the corresponding text and commands.
