### ISSUE TITLE
If YAML block ends with "..." no preview and no outline are generated

### ISSUE THREAD

**Issue by crystalfp** [yzhang-gh/vscode-markdown#398]
#### What is the problem?
If the YAML block at the beginning of the file ends with tree dots instead of three dashes (it is valid as per yaml specs) the preview is empty and the outline is not generated.

#### How can I reproduce it?
Open a markdown file containing
```
---
title: my title
...
# Title
```
The Outline in the file explorer says "no symbols found in file 'test.md'" and the preview is empty.

If the "..." is changed to "---" everything is working as expected.

#### Is there any error message in the console?
No

**Comment by yzhang-gh** [comment]
Thanks for the report. It seems to be a feature provided by the vscode built-in Markdown support. The vscode repository might be the right place for this issue.

(You can check the `README.md` for the features this extension contributes.)
