### ISSUE TITLE
Preview background configurable?

### ISSUE THREAD

**Issue by pardeike** [yzhang-gh/vscode-markdown#402]
My resulting website has white background but my preview in VSCode is dark (using dark theme). Is there a way to configure it white? My transparent graphics are hard to read in the preview.

**Comment by yzhang-gh** [comment]
You need to apply some styles to the preview, either with other extensions or your own CSS files.

Please see [VSCode docs](https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview) for more info.

**Comment by pardeike** [comment]
Perfect. Maybe a note mentioning that the preview is actually the build in one (at least for newbies like me) would point people to other extensions. 

Anyway, great extension!
Andreas
