### ISSUE TITLE
Default shortcuts not compatible with macOS

### ISSUE THREAD

**Issue by deanishe** [yzhang-gh/vscode-markdown#404]
The default keybindings on macOS assign ALT+s to "strikethrough", which interferes with text entry.

ALT+letter (and ALT+SHIFT+letter) is a core part of entering text on macOS, and as such, not appropriate for keyboard shortcuts in an application that allows text entry. When used with letter keys, ALT should always be combined with CTRL or CMD on macOS to avoid making it impossible to enter certain characters in your app.

ALT+s specifically is how you type an "ß" on an English keyboard. Therefore I can't correctly write German in vscode-markdown without deactivating/changing the default shortcuts.

**Comment by yzhang-gh** [comment]
Thanks for telling me that. I will remove the default `alt+s` keybinding for macOS.

**Comment by deanishe** [comment]
Marvellous. Thanks very much!

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by deanishe** [comment]
It works. Now I can type ß to my heart's content!

There's no keybinding for strikethrough on the Mac, though. I had to assign my own.
