### ISSUE TITLE
Toggle Code Block adds an unnecessary line break 

### ISSUE THREAD

**Issue by robertmarkbram** [yzhang-gh/vscode-markdown#407]
#### What is the problem?
Any time I use the `Toggle Code Block`, it adds an extra blank line at the end of my code.
- Whether I select every line of code (including or excluding the last line break) or just leave the cursor in the current single line of code.
- Whether I use the keyboard shortcut or invoke the function via the Command Palette.

#### How can I reproduce it?
Invoke the function.

#### Is there any error message in the console?
No

**Comment by yzhang-gh** [comment]
Thanks for the feedback. However, it (`toggle code block`) seems not to be a feature this extension is offering. Could you have a check?

**Comment by robertmarkbram** [comment]
Oops, sorry, wrong extension. This is meant for [Markdown Shortcuts](https://marketplace.visualstudio.com/items?itemName=mdickin.markdown-shortcuts)!
