### ISSUE TITLE
Table formatter misformats lines that contain `’` 

### ISSUE THREAD

**Issue by darkmattercoder** [yzhang-gh/vscode-markdown#408]
#### What is the problem?

When I try formatting a table, where one line contains one or `n` times `’`'s , the formatter adds `n` spaces less than necessary. 

#### How can I reproduce it?

Try formatting the following tables:

```
| col1    | col2     | col3   |
| ------- | -------- | ------ |
| line    | that'    | works  |
| line    | that’’ | doesnt |
| working | line     | again  |

| col1    | col2     | col3   |
| ------- | -------- | ------ |
| line    | that'    | works  |
| line    | that’ | doesnt |
| working | line     | again  |
```

#### Is there any error message in the console?
Not at all.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
