### ISSUE TITLE
User snippets don't work at all

### ISSUE THREAD

**Issue by jaacko-torus** [yzhang-gh/vscode-markdown#409]
#### What is the problem?

User snippets don't seem to work at all when the extension is enabled.

#### How can I reproduce it?

Create a new snippet for markdown like:

```json
{
	"Example_Name": {
		"description": "example",
		"prefix": "ex",
		"body": [
			"please go to [`<./${0:url}>`](./${0:url})"
		]
	}
}
```

When this extension is disabled then this works perfectly, but once it's enabled snippets don't work all of a sudden.

#### Is there any error message in the console?

no errors

**Comment by yzhang-gh** [comment]
Seems to works well here

![snippet](https://user-images.githubusercontent.com/7588612/54956075-06640000-4f47-11e9-91ab-a6d9864b254f.png)

Could you please try again with all the other extensions disabled except for this one?

**Comment by jaacko-torus** [comment]
sorry, you're right, It was another extension
