### ISSUE TITLE
Backspace on a list entry of just space should delete the space

### ISSUE THREAD

**Issue by hotohoto** [yzhang-gh/vscode-markdown#410]
#### What is the problem?
when there are spaces on a sub-list entry like below, pressing backspace doesn't delete the nearby space but it changes indent.

```
- abc
- def
  - <space><space>
```

#### How can I reproduce it?

- make list
- make sublist on a list entry
- press 2 or more spacebars
- try to delete the spaces

#### Is there any error message in the console?
N/A

**Comment by yzhang-gh** [comment]
Thanks for the feedback. I will take a look at the weekend.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
