### ISSUE TITLE
Intellisense order is wrong

### ISSUE THREAD

**Issue by linsui** [yzhang-gh/vscode-markdown#413]
#### What is the problem?
Intellisense order is wrong

#### How can I reproduce it?
For example, input \delta, the first is Delta.

这个问题我很久以前提到过，这个扩展的提示是大写优先，#233 ，也向 vscode 反馈了 https://github.com/Microsoft/vscode/issues/71062 ，他们认为是扩展的问题。vscode 那边也有几个关于智能提示排序的 issue 但似乎没有关于大小写的。

顺便说一下， 这里的 xrightarrow 写了两个。https://github.com/yzhang-gh/vscode-markdown/blob/647994b1872c542a3ab4f938d9ac64f5db99a1c1/src/completion.ts#L40

**Comment by linsui** [comment]
我怀疑有可能和提示列表的顺序有关，但唯一一个小写字母在大写字母前面的例子是我在上面引用的那个 xrightarrow ，但还是重复的，所以没法确定原因。编译也没成功 :sweat_smile:

**Comment by yzhang-gh** [comment]
> 顺便说一下， 这里的 xrightarrow 写了两个

哈哈，好眼力

> 排序问题

这个还真不知道 vscode 的机制是什么，你可以把大小写顺序改变测试一下

编译的话最近按 vscode 的推荐改用 webpack 了，但是应该不需要什么特殊的步骤，F5 调试就好
不过每次改了代码需要关掉调试窗口重新 F5，不像以前可以直接 reload

**Comment by linsui** [comment]
因为要安装好多包，但我从没用过nodejs，所以还在尝试 :sweat_smile:

**Comment by linsui** [comment]
测试了一下，似乎不是这个原因。我看了  python 扩展的源码，也没看出区别，但应该可以用这种方法解决问题。
https://github.com/Microsoft/vscode-python/blob/a86bf11f9c43dd378274dc7503b6f32ae571e1d4/src/client/providers/completionSource.ts#L102

**Comment by yzhang-gh** [comment]
这里 😉

https://github.com/yzhang-gh/vscode-markdown/blob/647994b1872c542a3ab4f938d9ac64f5db99a1c1/src/completion.ts#L53-L72

**Comment by linsui** [comment]
我测试了，可以工作，但因为有 LARGE 和 Large 这样的命令，需要交换所有字母的大小写而不仅是首字母，所以还是等你来修复吧，我力所不及 :joy:

**Comment by yzhang-gh** [comment]
嗯嗯，谢谢，周末有时间看看

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by linsui** [comment]
谢谢。工作正常 :+1:
