### ISSUE TITLE
Pictures not showing up in firefox linux

### ISSUE THREAD

**Issue by wingerse** [yzhang-gh/vscode-markdown#415]
#### What is the problem?
Images don't work when printing to html in firefox linux. I have not tested with chrome.

#### How can I reproduce it?
Have `a.md, a.png` in the same folder.
   
   $ cat a.md
   `![](a.png)`

Now print to html. The problem seems to be with the `file:///` used. (`<img src="file:///14.png" alt="">`). If I remove `file:///` it works..

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It is a bug.

However, I am busy this month. I will take a look later.

**Comment by nielsgl** [comment]
The same happens with Chrome.

**Comment by monfero** [comment]
I've notice the same behaviour after last update. By the moment I'm editing the html file by hand but I would appreciate a solution in the next version. Thank you.

**Comment by yzhang-gh** [comment]
Please try the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
