### ISSUE TITLE
GitHub does not render LaTeX in Markdown. Work around?

### ISSUE THREAD

**Issue by adam-erickson** [yzhang-gh/vscode-markdown#422]
#### What is the problem?
GitHub does not render LaTeX in Markdown. Will this package implement a workaround? I noticed that other packages have such.

#### How can I reproduce it?
Put a Markdown file containing LaTeX on GitHub.

#### Is there any error message in the console?
No.

**Comment by yzhang-gh** [comment]
To my knowledge, GitHub Flavored Markdown doesn't support math and there is no good workaround. 
(And I don't think there is any _vscode extension_ can resolve that.)

A [_browser extension_](https://chrome.google.com/webstore/detail/mathjax-plugin-for-github/ioemnmodlmafdkllaclgeombjnmnbima) might help. I haven't checked.

**Comment by adam-erickson** [comment]
The TeXify app can supposedly solve it for GitHub: https://github.com/apps/texify. There are also tools for VS Code, e.g.: https://marketplace.visualstudio.com/items?itemName=goessner.mdmath

**Comment by yzhang-gh** [comment]
If you accept HTML format, this extension also has a "print to HTML" command (then math should work well in the exported HTML).

**Comment by adam-erickson** [comment]
Thank you!
