### ISSUE TITLE
Win10 Space Bug

### ISSUE THREAD

**Issue by lotapp** [yzhang-gh/vscode-markdown#424]
#### What is the problem?

In win10, the list tab has only 3 spaces, and the non-list is normal 4 spaces.

#### How can I reproduce it?

list to tab key

![bug](https://img2018.cnblogs.com/blog/1127869/201904/1127869-20190422065126724-416737691.gif)

#### Is there any error message in the console?

no

**Comment by yzhang-gh** [comment]
You can change the indentation size with setting `list.indentationSize`.

**Comment by lotapp** [comment]
Thank you very much

**Comment by yzhang-gh** [comment]
👌
