### ISSUE TITLE
Titles cannot be created correctly.

### ISSUE THREAD

**Issue by zcc0721** [yzhang-gh/vscode-markdown#425]
#### What is the problem?

TOC cannot be created correctly when md have some symbol.

#### How can I reproduce it?

e.g. A simple symbol like this:

```
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 5.0.4 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 23223
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'
```

<img width="698" alt="Snipaste_2019-04-23_11-15-02" src="https://user-images.githubusercontent.com/17916496/56551250-71423e80-65ba-11e9-92a3-1bde3061ee07.png">
<img width="690" alt="Snipaste_2019-04-23_11-16-28" src="https://user-images.githubusercontent.com/17916496/56551255-73a49880-65ba-11e9-9a7d-00838529decb.png">
<img width="706" alt="Snipaste_2019-04-23_11-18-13" src="https://user-images.githubusercontent.com/17916496/56551261-78694c80-65ba-11e9-8247-a847ab903249.png">
<img width="675" alt="Snipaste_2019-04-23_11-19-33" src="https://user-images.githubusercontent.com/17916496/56551267-7c956a00-65ba-11e9-80fd-c60921301bf1.png">
<img width="598" alt="Snipaste_2019-04-23_11-22-27" src="https://user-images.githubusercontent.com/17916496/56551278-8028f100-65ba-11e9-8c36-1e1c45122e00.png">
<img width="644" alt="Snipaste_2019-04-23_11-23-45" src="https://user-images.githubusercontent.com/17916496/56551287-84eda500-65ba-11e9-8f1d-e660117a5791.png">

**Comment by yzhang-gh** [comment]
Thanks for the detailed report. Looks interesting. I guess the <code>\`\`\`.  \`\`\`</code> affects the code block detection. (You can see the inline code decorations which should be disabled in the code block)

I will take a look later.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by zcc0721** [comment]
Thanks a lot, I am very appreciated for your help.
