### ISSUE TITLE
`imgToBase64` option doesn't work

### ISSUE THREAD

**Issue by yzhang-gh** [yzhang-gh/vscode-markdown#429]
I get this `unableToReadFile \Figure_3.png, revertingToImagePaths` with `![图3](Figure_3.png)` on VSCode 1.33.1. Is it the same error?

_Originally posted by @linsui in https://github.com/yzhang-gh/vscode-markdown/issues/266#issuecomment-487292001_

**Comment by yzhang-gh** [comment]
@linsui Please try the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by linsui** [comment]
It works well, thanks! :+1:
