### ISSUE TITLE
Formatting does not work for single-column tables

### ISSUE THREAD

**Issue by Splike** [yzhang-gh/vscode-markdown#431]
Auto-formatting for tables first kicks in when there are 2 or more columns. It would be great if this can happen before, as some tables only contain a single column.

**Comment by yzhang-gh** [comment]
I guess it is because of the regular expression matching. Seems a bit tricky.

**Comment by Splike** [comment]
Maybe it's possible to have a separate regex for single-column tables?

**Comment by yzhang-gh** [comment]
My personal opinion is to consider using a list rather than a single column table (as a table is usually a two-dimensional "data type"). 😂

Looking for someone willing to help.

**Comment by Splike** [comment]
Wouldn't a list change the visual format of the output though?

**Comment by yzhang-gh** [comment]
I mean the list is an alternative choice to present your "single column content".

If you want the exact same visual outcome, then it is not (although we can use CSS to fake it).

**Comment by Splike** [comment]
I'm currently using single column tables to to neatly display captions below images, since markdown doesn't natively support this. A list just wouldn't have the same visual result.

Code:
```markdown
| <img src=".\Images\image.jpg" width="300"> |
| :----------------------------------------: |
|      **Figure 1.** _This is a caption_     |
```
Output:

![Caption](https://user-images.githubusercontent.com/7159527/56930321-906e2e00-6adc-11e9-862c-8f98fa8d2f48.png)

**Comment by yzhang-gh** [comment]
Interesting use case 😂
