### ISSUE TITLE
markdown.extension.print.onFileSave: false is ignored

### ISSUE THREAD

**Issue by akurani** [yzhang-gh/vscode-markdown#432]
#### What is the problem?

The new print-to-HTML feature in v2.3.0 (2019.4.28) creates the HTML file even if you set the "markdown.extension.print.onFileSave" setting to false.

#### How can I reproduce it?

1. Set "markdown.extension.print.onFileSave": false in settings.json.
2. Edit and save a markdown file.
3. Notice the HTML file is still created.

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. I'll take a look soon.

**Comment by pgolebiowski** [comment]
Thanks @yzhang-gh!

**Comment by yzhang-gh** [comment]
Published a new version. Please try it out

**Comment by akurani** [comment]
New version fixes the issue. I tested the flag both ways, and it worked as expected.
