### ISSUE TITLE
List editing does not work below code block

### ISSUE THREAD

**Issue by jeremycolby** [yzhang-gh/vscode-markdown#434]
Any list created above a code block will have the functionality, any list below will not.

When creating this list, pressing enter automatically puts a dash and allows you to continue the list
- item
- item
- item

``` python
print("Hello world.")
```

When creating this list, the dashes are not created and need to be manually entered
- item
- item
- item

**Comment by yzhang-gh** [comment]
Thanks for the feedback. With the current implementation, we cannot have space after <code>\`\`\`</code>, i.e. <code>\`\`\`python</code>
