### ISSUE TITLE
Umlauts in TOC links not working

### ISSUE THREAD

**Issue by cheeezeburgers** [yzhang-gh/vscode-markdown#440]
First of all this extension is the reason I use vscode! Thank you for your work - you are amazing!

#### What is the problem?

When there is an umlaut like ä,ö,ü in a header the TOC link is not working anymore.

#### How can I reproduce it?

Type a header like "# Überschrift" and make a TOC. The link will not work.

**Comment by yzhang-gh** [comment]
Hi, thank you for the feedback.

Have you tried the `githubCompatibility` option? It will change how the TOC links are generated.
The default links are generated in a vscode-compatible way.

**Comment by cheeezeburgers** [comment]
Sorry for late response.

YES! This fixes the issue. It now shows the native umlaut characters (ä,ö,ü) in the TOC and not the html ones.

Thank you
