### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KDF5000** [yzhang-gh/vscode-markdown#444]
- Issue Type: `Performance`
- Extension Name: `markdown-all-in-one`
- Extension Version: `2.3.1`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.33.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`/Users/xxxx/yzhang.markdown-all-in-one-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by yzhang-gh** [comment]
> ⚠️ Make sure to attach this file from your home-directory:
> ⚠️/Users/xxxx/yzhang.markdown-all-in-one-unresponsive.cpuprofile.txt

Please provide the `cpuprofile` (follow the instructions in the link you mentioned)
