### ISSUE TITLE
Katex: \boxed do not inherit theme colors

### ISSUE THREAD

**Issue by enizor** [yzhang-gh/vscode-markdown#446]
### Why this issue?

Creating this Katex-induced issue (see https://github.com/KaTeX/KaTeX/issues/1772) here so people stumbling on it know where it comes from. 

If you think it has not its place here, feel free to close it.

### What is the problem?

`\boxed` environments do not inherit the color theme: the frame is always pure black. It is generally irrelevant while exporting in HTML but is very visible while previewing in a dark theme.
```
$$
\boxed{a^n - b^n = (a-b)\sum_{i=0}^{n-1}a^{i}b^{n-i-1}}
$$
```
Currently: (`Katex 0.10.0`)
![image](https://user-images.githubusercontent.com/25256520/57788841-1672b180-7738-11e9-8239-21e95e1765c8.png)

Updating to latest `Katex 0.10.2`
![image](https://user-images.githubusercontent.com/25256520/57788736-e7f4d680-7737-11e9-9689-adfe519b9088.png)

### Solution

Bump dependencies. I do not know how this works for VS Code extensions, is it required to up the extension version?

### Temporary Workaround

You can update yourself `katex.min.css` (for example getting it from [here](https://cdn.jsdelivr.net/npm/katex@0.10.2/dist/katex.min.css)) in `VSCODE-FOLDER\extensions\yzhang.markdown-all-in-one-2.3.1\node_modules\katex\dist`.

**Comment by upupming** [comment]
@enizor I recommend you open a PR and change the current katex plugin to markdown-it-texmath, and change the package to use the latest katex always.

**Comment by yzhang-gh** [comment]
Currently, we are using my [personal fork](https://github.com/yzhang-gh/markdown-it-katex) of waylonflinn/markdown-it-katex. It is still on KaTeX v0.10.0.

waylonflinn said he would update his module recently. But we can also update my own one if needed.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
