### ISSUE TITLE
Math "\neq" in exported html is not rendered correctly.

### ISSUE THREAD

**Issue by PaperCube** [yzhang-gh/vscode-markdown#449]
#### What is the problem?

Latex math "\neq" isn't rendered correctly when an exported html is opened by Chrome 74.0.3729.157 (32-bit Windows). It looks like "/=", just like that in issue #349 . Caches have been cleared several times.
However, it is rendered correctly both in preview panel and in Edge.
![批注 2019-05-18 220025](https://user-images.githubusercontent.com/7395735/57971399-15ec4c00-79c0-11e9-9c8a-ee0cd9eb7b4c.png)

#### How can I reproduce it?

Create a markdown file with content `$\neq$`, export it to html and open the exported html file with Chrome 74.

#### Is there any error message in the console?
No.

**Comment by yzhang-gh** [comment]
Please try the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

We recently updated the KaTeX package and it seems to work well in the dev build.

**Comment by PaperCube** [comment]
It does work fine in dev build. Thank you a lot. When will a new version with the updated KaTeX package be released?

**Comment by PaperCube** [comment]
@yzhang-gh But after installing the dev package, all arrays are in a mess. I wonder if there's a syntax mistake or another bug of KaTeX?
![image](https://user-images.githubusercontent.com/7395735/57976322-7a82c780-7a0f-11e9-9e0e-fa46b861fec3.png)

**Comment by yzhang-gh** [comment]
Besides upgrading the version, we also added KaTeX macros support, which may have caused some issues.

I have made a fix. Please try out the latest dev build.

**Comment by PaperCube** [comment]
It now works. Thanks.
