### ISSUE TITLE
格式化带中文的表格，竖线不对齐

### ISSUE THREAD

**Issue by kzhui125** [yzhang-gh/vscode-markdown#456]
<img width="322" alt=" 12" src="https://user-images.githubusercontent.com/11925432/58301301-7e03bd80-7e18-11e9-9a80-57075f85e203.png">

**Comment by yzhang-gh** [comment]
这是字体的原因，见 [#293](https://github.com/yzhang-gh/vscode-markdown/issues/293#issuecomment-427635840).
