### ISSUE TITLE
[Feature Request] Option to not add the top level heading in table of contents

### ISSUE THREAD

**Issue by lackovic** [yzhang-gh/vscode-markdown#459]
The top level heading (aka # H1) has to be [the first line in the file](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md041---first-line-in-file-should-be-a-top-level-heading), so it is usually right above the table of contents, and [there can be only one](https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md#md025---multiple-top-level-headings-in-the-same-document), there is no real need to have a link to it.

Would be nice to have an option to not add it in table of contents.

**Comment by yzhang-gh** [comment]
See option `markdown.extension.toc.plaintext`

**Comment by lackovic** [comment]
@yzhang-gh thanks. Can you point out to a specific document which explains what that option does? I could not find any reference to it, and the option in VSCode only says "Just plain text".

**Comment by yzhang-gh** [comment]
This can be done with the `<!-- omit in toc -->` comment

![omit heading](https://github.com/yzhang-gh/vscode-markdown/raw/master/images/toc.png)

**Comment by kdwarn** [comment]
You can also configure it in settings: "markdown.extension.toc.levels": "2..6"
