### ISSUE TITLE
`\\` 和环境同时使用时数学渲染失败

### ISSUE THREAD

**Issue by linsui** [yzhang-gh/vscode-markdown#460]
```markdown
$$aaa\\
\begin{aligned}
    bbb
\end{aligned}$$
```

类似这样的代码会出现渲染失败，公式显示为红色代码。但这一错误并不是一直出现的，具体的触发条件我并不清楚。出现错误后所有包含换行的公式都无法渲染，在重启 vscode 后会恢复正常，但还会再次出现。

***

触发条件是环境内不完整的函数或其他原因导致错误后，无法再次渲染。在环境外不会出现这一错误。

```markdown
$$aaa\\
\begin{aligned}
    a_b
\end{aligned}$$
```

在以上代码中输入 `a_` 之后，数学渲染错误。输入 `b` 无法重新渲染。

**Comment by yzhang-gh** [comment]
在旧版本是好的，推测是因为预览版加入了宏，出错之后内部状态变了

**Comment by yzhang-gh** [comment]
如果没定义宏的话预览版应该不会有这个问题了

**Comment by linsui** [comment]
谢谢，好快 :+1: 我试了一下，定义了宏也没有问题，是完全修复了吗？

**Comment by yzhang-gh** [comment]
重启之后估计就会有问题了😂，只有激活的时候才看情况传 `macros` 参数

**Comment by linsui** [comment]
我测试了一下，只有上一个构建会出错，之前几个版本都没问题。最新的构建目前没有问题。

**Comment by yzhang-gh** [comment]
神奇，但是没问题就更好了
