### ISSUE TITLE
Headers in comment sections are added to the TOC

### ISSUE THREAD

**Issue by gdeban** [yzhang-gh/vscode-markdown#462]
Sometimes I want to comment out a whole section of a document, including headers.
This does not work for the generated TOC (table of contents). The commented out headers are still parsed.

document:
```
# Section 1
## Section 1.1
<!--
## Commented out section 1.2
-->
## Section 1.3
```

generated Table of Contents:
```
- [Section 1](#section-1)
  - [Section 1.1](#section-11)
  - [Commented out section 1.2](#commented-out-section-12)
  - [Section 1.3](#section-13)
```

**Comment by yzhang-gh** [comment]
Thanks for the feedback. A workaround is to place the `<!--` right before the heading.

```markdown
<!-- ## Commented out section 1.2
...
-->
```
