### ISSUE TITLE
[Feature Request]Local file link auto completions

### ISSUE THREAD

**Issue by linsui** [yzhang-gh/vscode-markdown#466]
Could you please provide auto completions for not only images but all local links?

**Comment by yzhang-gh** [comment]
It is technically similar to the image completions.

https://github.com/yzhang-gh/vscode-markdown/blob/e07377b8b00c5874213e6e566f1559bb3a94d610/src/completion.ts#L338-L370

A potential problem is the root path. For images, it is relative to the current document. But for Markdown documents, which are usually hosted in a server, I assume the paths should be relative to the folder root path?

**Comment by linsui** [comment]
Sorry, I didn't understand what the difference between image and file is... Will there be any problem to deal with them in the same way?  :confused:

**Comment by yzhang-gh** [comment]
I guess there is no problem when only considering writing inside VSCode.

Assume we have this file structure (_used for a Markdown-based website_),

```
. (root)
├ subfolder/
│ ├ img.png
│ ├ doc1.md
│ └ doc2.md
└ index.html
```

In `doc1.md`, we can use `![...](img.png)` to show the image. But `[...](doc2.md)` usually doesn't work _in the generated website_, depending on the server configuration (it might be `[...](/subfolder/doc2)`).

**Comment by linsui** [comment]
I got, thanks! So it depends on how the html is generated? I test it with python http server and `[...](doc2.md)` and  `[...](/subfolder/doc2.md)` both work well.

**Comment by yzhang-gh** [comment]
I think I worried too much about that. We cannot cover all the possible path resolving ways. Let's do it just like the image completion (relative path) first.

**Comment by simkimsia** [comment]
I would like this feature as well. I do prefer if the links can be from root folder.

but it's okay if you do it first as relative path.

**Comment by yzhang-gh** [comment]
@simkimsia sorry, I seemed to have missed your post. Thanks for sharing.

This is now done in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) (with the help of @linsui 👍). It supports both relative-to-current-file and relative-to-the-root path. Please feel free to tell me whether it works for you.

**Comment by simkimsia** [comment]
@yzhang-gh So how do I try this out?

**Comment by yzhang-gh** [comment]
You can download the `.vsix` and install it. (See above link for more information.)

**Comment by yzhang-gh** [comment]
@TjeuKayim Thanks for the information. I am not familiar with Zola, but I guess you may like to know the new setting `completion.root` (#526)
