### ISSUE TITLE
能否设置大纲默认展开并以位置为默认排序依据

### ISSUE THREAD

**Issue by ivysrono** [yzhang-gh/vscode-markdown#474]
![图片](https://user-images.githubusercontent.com/2649544/59611981-dfd0f200-914e-11e9-9460-32a26ad997ec.png)
现在每次都要手动调整好麻烦的。

**Comment by yzhang-gh** [comment]
这个需要到 VSCode 官方仓库反映，现在已经不是由这个插件提供了
