### ISSUE TITLE
Styling lost on line break. 

### ISSUE THREAD

**Issue by cliffordfajardo** [yzhang-gh/vscode-markdown#478]
#### What is the problem?
Some of the styles like bold and italics in the editor don't work when we split the text mid sentence.

Github flavored markdown seems to support this. I tried those examples in this very markdown editor box I'm writing in issue in and the styles get applied in all the cases above, including the preview mode.

![Screen Shot 2019-06-23 at 11 12 58 AM](https://user-images.githubusercontent.com/6743796/59980244-e2e13d80-95a7-11e9-96c9-1643c3a22ff6.png)

Example:

**Italics**:

```
*is italicized which is nice.*
*is not italizcized 
unfortunately*
```

**Bold**

```
**is bolded which is nice.**
**is not bolded 
unfortunately**
```

Aside: I also have `githubCompatibility` marked as true with this extension.

**Comment by yzhang-gh** [comment]
Thank you for the feedback. The syntax highlight is provided by vscode itself. Specifically, it is [microsoft/vscode-markdown-tm-grammar](https://github.com/microsoft/vscode-markdown-tm-grammar).
