### ISSUE TITLE
Underline words

### ISSUE THREAD

**Issue by Splike** [yzhang-gh/vscode-markdown#479]
I'd love to be able to underline words.

I suggest the keyboard shortcut should be
```
*italics* or _italics_
**bold**
__underline__
```

**Comment by yzhang-gh** [comment]
This is not a part of the CommonMark Spec. So we probably will not support it in this extension.

You can do it with vscode snippet. (Add this to the `keybindings.json`)

```
    {
        "command": "editor.action.insertSnippet",
        "args": {
            "snippet": "__$TM_SELECTED_TEXT__"
        },
        "key": "ctrl+u", // whatever you like
        "when": "editorTextFocus && editorLangId == 'markdown'"
    }
```

**Comment by Splike** [comment]
Thanks for your reply.

I've suggested underline as a feature of the CommonMark Spec. Hopefully it will be implemented one day.

**Comment by LanxinL** [comment]
> This is not a part of the CommonMark Spec. So we probably will not support it in this extension.
> 
> You can do it with vscode snippet. (Add this to the `keybindings.json`)
> 
> ```
>     {
>         "command": "editor.action.insertSnippet",
>         "args": {
>             "snippet": "__$TM_SELECTED_TEXT__"
>         },
>         "key": "ctrl+u", // whatever you like
>         "when": "editorTextFocus && editorLangId == 'markdown'"
>     }
> ```

Thanks for your advice, I supplement some results :)

-  `__$TM_SELECTED_TEXT__` didn't work for me. Should it be `__${TM_SELECTED_TEXT}__`?
- However, `__${TM_SELECTED_TEXT}__` just transfers `test` to `__test__`. it seems not a correct underline.
- Finally I try `<u>${TM_SELECTED_TEXT}</u>. It works well. 

Hope can help others who want to use underline words by Markdown in VSCode.

**Comment by yzhang-gh** [comment]
@LanxinL. Thanks for sharing.

- I don't know why, but theoretically `__$TM_SELECTED_TEXT__` should work according to the [docs](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables)
- That's because underline is not a supported syntax in most Markdown renderers (including vscode).
- HTML tag is fine for most Markdown renderers.
