### ISSUE TITLE
ToC Downcase

### ISSUE THREAD

**Issue by yedhrab** [yzhang-gh/vscode-markdown#482]
#### What is the problem?

Case-sensitive toc doesn't work everywhere.

- Fork ex: [markdown pdf][0] cant convert markdown to html right

#### How can I reproduce it?

Just add setting options like `"markdown.extension.toc.downcase": true / false` 

[0]: https://marketplace.visualstudio.com/items?itemName=yzane.markdown-pdf

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Let's track this issue at #476. I will add a new option when I get some more time.
