### ISSUE TITLE
Performance issue 2 (slow when editing large file)

### ISSUE THREAD

**Issue by yzhang-gh** [yzhang-gh/vscode-markdown#483]
I don't know if I made everything correctly, but here it is.

![Capture](https://user-images.githubusercontent.com/18548503/60319417-0416a500-997f-11e9-9208-a284762733e9.PNG)

[CPU-20190628T051951.575Z.cpuprofile.txt](https://github.com/yzhang-gh/vscode-markdown/files/3337646/CPU-20190628T051951.575Z.cpuprofile.txt)

_Originally posted by @quicktrick in https://github.com/yzhang-gh/vscode-markdown/issues/323#issuecomment-506606687_

**Comment by yzhang-gh** [comment]
Hi @quicktrick, I have made a small change. Can you try out the new build here ([v2.4.0-issue483.zip](https://github.com/yzhang-gh/vscode-markdown/files/3364813/markdown-all-in-one-2.4.0-issue483.zip)).

You can set the option `syntaxDecorations` to `false` to improve the performance.

**Comment by quicktrick** [comment]
Hi @yzhang-gh! 

Thanks a lot for your efforts!  I've tested the new build.

1. With `syntaxDecorations: true` the issue persists:

![Capture](https://user-images.githubusercontent.com/18548503/60809873-61d39a00-a194-11e9-9d05-359315a2382f.PNG)

[CPU-20190708T120524.768Z.cpuprofile.txt](https://github.com/yzhang-gh/vscode-markdown/files/3368275/CPU-20190708T120524.768Z.cpuprofile.txt)

---

2. With `syntaxDecorations: false` everything seems to be good:

![Capture1](https://user-images.githubusercontent.com/18548503/60809882-67c97b00-a194-11e9-88bd-d634f2b3663f.PNG)

[CPU-20190708T121436.066Z.cpuprofile.txt](https://github.com/yzhang-gh/vscode-markdown/files/3368283/CPU-20190708T121436.066Z.cpuprofile.txt)

**Comment by yzhang-gh** [comment]
Glad to see that

**Comment by yzhang-gh** [comment]
With version 2.4.1, this extension will automatically disable syntax decorations for large files (>128 KB). So you can reset that setting to default now.
