### ISSUE TITLE
Table of contents generate directory error

### ISSUE THREAD

**Issue by daidai21** [yzhang-gh/vscode-markdown#484]
#### What is the problem?

There is a problem with the directory generated by the plug-in.

#### How can I reproduce it?

![image](https://user-images.githubusercontent.com/36124626/60825409-3aa1ba80-a1de-11e9-8125-ec480b99b801.png)

**Comment by daidai21** [comment]
![image](https://user-images.githubusercontent.com/36124626/60826073-b3eddd00-a1df-11e9-8912-e27d2f48b7b0.png)

I think I understand this function...
So, I want to put forward a requirement.
If `#` does not appear in the file and `##` appears in the file, it is considered that `##` is the first-level title rather than a second-level heading. What's your opinion?

**Comment by yzhang-gh** [comment]
The indentation looks wired. Do you have some personal settings for the `list.indentationSize` and tab size (on the bottom right corner of vscode)?

> If `#` does not appear in the file and `##` appears in the file, it is considered that `##` is the first-level title rather than a second-level heading.

This extension does behave like this. Are you using other Markdown extensions?

![image](https://user-images.githubusercontent.com/7588612/60835595-7a0adf80-a1bb-11e9-9702-372edcd9efc3.png)

**Comment by daidai21** [comment]
list.indentationSize is set to inherit as normal. Thank you!
