### ISSUE TITLE
Math macro in suggestions

### ISSUE THREAD

**Issue by gouletjg** [yzhang-gh/vscode-markdown#485]
#### What is the problem?
Macros defined in katex are not appearing in suggestions when a math environment is entered.

#### How can I reproduce it?
Define a macro, then notice that it does not appear inside a math environment ($$ {math} $$)

#### Is there any error message in the console?
None

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

**Comment by jgoulet1994** [comment]
To anyone looking for this, I found a workaround.

If you create a user snippet in markdown.json and format the prefix as: "\\macro", then it will appear with the other math suggestions.
