### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by imageFish** [yzhang-gh/vscode-markdown#486]
[Question]How to import the vector image formations files, such as eps. Or it does not support such   formation images. if it doesn't support, will it do in the future?

**Comment by yzhang-gh** [comment]
HTML doesn't support such a format. Neither does Markdown.

See [HTML supported image formats](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#Supported_image_formats)

**Comment by yzhang-gh** [comment]
No action can be done here as it is the limit of HTML/Markdown.
