### ISSUE TITLE
打开较大的 Markdown 文件会出现问题（超过 5M）

### ISSUE THREAD

**Issue by rxliuli** [yzhang-gh/vscode-markdown#488]
## Markdown 打开大文件之后出现问题

吾辈打开比较大的 Markdown 文件后出现的问题，卸载之后下面这些问题没有了，应该是插件本身的 bug

- 删除提示 `command 'markdown.extension.onBackspaceKey' not found`
- 打开预览后左下角提示 `Activating Extendsions`，然后就没有然后了。。。

**Comment by yzhang-gh** [comment]
这个问题最常见的原因是 vscode 还没有激活这个插件（在第一次打开 Markdown 文件的时候），或者因为某种原因激活失败

有几点建议可以尝试
- 打开 Markdown 文件之后稍等几秒，看看问题是否消失
- 重新安装一下这个插件试试
- 若仍然有问题，打开控制台看看是否有报错（菜单栏>帮助>开发者工具）

**Comment by rxliuli** [comment]
> 这个问题最常见的原因是 vscode 还没有激活这个插件（在第一次打开 Markdown 文件的时候），或者因为某种原因激活失败
> 
> 有几点建议可以尝试
> 
> * 打开 Markdown 文件之后稍等几秒，看看问题是否消失
> * 重新安装一下这个插件试试
> * 若仍然有问题，打开控制台看看是否有报错（菜单栏 > 帮助 > 开发者工具）

当吾辈打开一个普通的 markdown 文件时，没有遇到什么问题。然而一旦打开 Markdown 大文件时，首先编辑器会变得很卡，之后控制台就会报以下错误（此时还未进行任何操作）

```sh
workbench.main.js:3311 Extension Host
workbench.main.js:3311 Debugger attached.
```

附：试了一下重新安装没有用呢

**Comment by yzhang-gh** [comment]
确实可以复现😂

这个文件也太大了，这个插件有些功能需要扫描整个文档（比如生成目录，添加删除线等），感觉很难解决

只能建议在打开超大文件时禁用这个插件了

**Comment by rxliuli** [comment]
> 确实可以复现😂
> 
> 这个文件也太大了，这个插件有些功能需要扫描整个文档（比如生成目录，添加删除线等），感觉很难解决
> 
> 只能建议在打开超大文件时禁用这个插件了

其实有时候打开一个正常的 Markdown 文件也会这样，虽然遇到的次数并不是很多，但重开 VSCode 就可以了，感觉有点奇怪，或许可以加个埋点 bug 报告之类的？

**Comment by yzhang-gh** [comment]
对于其它的文件的话可能是一些更细分的问题了，比如 not found 这一类是插件激活问题，一般原因在上面有提及. 除此之外一些较大的文件可能存在一些性能问题，这样就要具体问题具体分析了（#323, #483）

**Comment by yzhang-gh** [comment]
看记录在这之后加入了大文件自动禁用 decorations 的功能，不过这个 issue 已经有一段时间了，不清楚是否还存在这个问题

**Comment by rxliuli** [comment]
> 看记录在这之后加入了大文件自动禁用 decorations 的功能，不过这个 issue 已经有一段时间了，不清楚是否还存在这个问题

没有解决的话一直存在这个问题吧？

**Comment by yzhang-gh** [comment]
主要是你分享的文件过期了测试不了😂

**Comment by rxliuli** [comment]
这，吾辈也找不到这个文件了 #笑哭

Yu Zhang <notifications@github.com> 于 2020年1月21日周二 17:19写道：

**Comment by yzhang-gh** [comment]
那我们暂时关掉这个 issue 好了，这个问题也不是特别频繁，下次遇到再说吧
