### ISSUE TITLE
可否在文件较大时自动设置 syntaxDecorations 呢？

### ISSUE THREAD

**Issue by rxliuli** [yzhang-gh/vscode-markdown#489]
> 引用问题: [488](https://github.com/yzhang-gh/vscode-markdown/issues/488), [483](https://github.com/yzhang-gh/vscode-markdown/issues/483)

[这里](https://github.com/yzhang-gh/vscode-markdown/issues/483#issuecomment-508935107) 提到设置 `"markdown.extension.syntax.decorations": false` 可以提高一些性能，但它似乎是禁用了某些功能，对于 md 小文件（通常情况）无须如此。那么，为什么不自动化，根据文件大小自动选择应该如何打开呢？

可以提供一个类似于下面这样的设置

- "markdown.extension.syntax.decorations"
  - "auto"
  - "true"
  - "false"

**Comment by yzhang-gh** [comment]
我已经尝试过了，在你那个文件下仍然不行😂，所以不单是**这一个功能**的问题

而对于明显很大的文件，这个插件的那些功能也都不重要了，不如禁用掉

如果你发现某个一般大的文件仍然有性能问题，可以具体解决

**Comment by rxliuli** [comment]
> 我已经尝试过了，在你那个文件下仍然不行😂，所以不单是**这一个功能**的问题
> 
> 而对于明显很大的文件，这个插件的那些功能也都不重要了，不如禁用掉
> 
> 如果你发现某个一般大的文件仍然有性能问题，可以具体解决

好吧，删除倒是可以，格式化还是挂了，看来确实不是这一个地方的问题。。。
吾辈编辑这种大文件是因为原本是小说，需要弄成方便打印（纸质版）的版本，所以才有这种场景

**Comment by yzhang-gh** [comment]
对于这种超大文件编辑还是建议用 notepad++，sublime text 这种，光用 vscode 打开就很费事了（可以观察下 CPU 和内存占用）

**Comment by rxliuli** [comment]
其实不太行，刚测试了一下 NPP 使用 [Markdown 插件](https://github.com/nea/MarkdownViewerPlusPlus) 之后也是挂的结局。。。#笑哭
![image](https://user-images.githubusercontent.com/24560368/61321137-7de2d580-a83d-11e9-88d5-dd91b779aa71.png)

**Comment by yzhang-gh** [comment]
😂
