### ISSUE TITLE
Omit in toc does not work

### ISSUE THREAD

**Issue by ST-DDT** [yzhang-gh/vscode-markdown#490]
If try to omit a headline in the toc it still gets added:

````md
# Test

## Table of contents

- [Table of contents](#table-of-contents)
- [Additional topics](#additional-topics)
- [Foobar](#foobar)
- [Lorep](#lorep)
- [Additional topics](#additional-topics-1) <-- I don't want this

## Additional topics

* a
* b
* c
* d

## Foobar

## Lorep

## Additional topics <!-- omit in toc -->

* a
* b
* c
* d
````

The `<!-- omit in toc -->` doesn't seem to have an effect.

I use v2.4.1 with githup compatibility mode + lowercase toc.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. That was because it was removed as HTML comment (v2.4.1).

It should be fixed with v2.4.2 now.
