### ISSUE TITLE
** `Nested `** is not supported（**`不支持语法嵌套`**）

### ISSUE THREAD

**Issue by mr-dragon** [yzhang-gh/vscode-markdown#493]
#### What is the problem?

```markdown
** `Nested `** is not supported
```

Can be parsed and checked again, whether there are grammatical characters, or if the content will be rendered again.

#### How can I reproduce it?

```markdown
** `Nested `**
```

#### Is there any error message in the console?
nothing

**Comment by mr-dragon** [comment]
**`不支持语法嵌套`**

可以解析完再检查一遍，是否有语法字符，有的话将内容再渲染一遍？

MWeb支持此嵌套语法

**Comment by yzhang-gh** [comment]
我不是很理解你的问题

![image](https://user-images.githubusercontent.com/7588612/61908628-017c8080-af28-11e9-857c-145ac5ae9e0f.png)

（注意加粗部分不能以空格开头或结尾）

**Comment by mr-dragon** [comment]
> 我不是很理解你的问题
> 
> ![image](https://user-images.githubusercontent.com/7588612/61908628-017c8080-af28-11e9-857c-145ac5ae9e0f.png)
> 
> （注意加粗部分不能以空格开头或结尾）

我知道原因了，昨晚回去又试了下，有些地方需要在 前后加空格才会识别

```markdown
空格**`支持语法嵌套`**空格
```
