### ISSUE TITLE
TOC: Github compatibility feature outdated?

### ISSUE THREAD

**Issue by jakob-bebop** [yzhang-gh/vscode-markdown#494]
#### What is the problem?

when Toc: Github compatibility is checked, the TOC links no longer match the anchors generated by gitHub.

OTOH, the default setting (Toc: Downcase link = true) seems to produce a compatible TOC.

#### How can I reproduce it?

For a header with a word in italics, e.g. `##Producing _more_ files`, the default TOC setting generates the same anchor as does the Github HTML view, namely `#producing-more-files`

when Toc: Github compatibility is checked, the TOC link changes to `#producing-_more_-files`

**Comment by yzhang-gh** [comment]
Thanks for the feedback. This is a bug.

**Comment by RaisedByWolves1** [comment]
As a relative newbie to VS Code I am confounded as to what is meant by phrases like "when Toc: Github compatibility is checked". Where do you specify this setting? I only have worked with an SFTP extension and the command pallete has easy access to the setting for that extension settings in either UI or raw JSON. Is this a setting you somehow shoehorn into the actual TOC item?

**Comment by yzhang-gh** [comment]
@RaisedByWolves1 You can access VSCode settings with command palette

![image](https://user-images.githubusercontent.com/7588612/62791723-a6b95c00-bac5-11e9-922e-be92d1fa0a83.png)

And then search for "github", you will find it.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
