### ISSUE TITLE
Support <!-- omit in toc --> above headings

### ISSUE THREAD

**Issue by donaldshen** [yzhang-gh/vscode-markdown#495]
## What is the problem?
![image](https://user-images.githubusercontent.com/19591950/62111576-6b5ba800-b2e3-11e9-8829-9c927d47b837.png)
which cause every `back to top` buttons stop working

#### How can I reproduce it?
try any repo in github, omit it's `table of contents` and add a `[back to top](#table-of-contents)` in README.md, then push to github to check whether that link work

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Actually, it is GitHub that adds the `-`. What this extension can do stop at the Markdown source code level. It has no control over how the final HTML is rendered.

In this case, GitHub generates `<a ... href="##table-of-contents-">` (HTML) from `# Table of Contents <!-- omit in toc -->` (Markdown). That is probably because they don't do `trim()` on the heading text.

**Comment by donaldshen** [comment]
oh I see...
I guess  I just need to stop `update on save` my toc in README, and remove that `table of contents` manually

**Comment by donaldshen** [comment]
or maybe you could think of another way to add `<!-- omit in toc -->`, e.g., add comment above those headers, just like those eslint inline comments

**Comment by yzhang-gh** [comment]
> or maybe you could think of another way to add `<!-- omit in toc -->`, e.g., add comment above those headers, just like those eslint inline comments

Sounds good!

**Comment by AndyHuyidi** [comment]
兄弟，你好，想问一下，在使用ALL IN ONE  的CTOC生成目录的时候， 锚点后面的链接不支持中文吗？
![image](https://user-images.githubusercontent.com/48292864/63485384-b4171300-c4d5-11e9-9d03-f566d39c88ba.png)

**Comment by AndyHuyidi** [comment]
自动生成后，变成乱码字符的了

**Comment by yzhang-gh** [comment]
这是因为在 VSCode 里默认会进行 URI 编码，不喜欢的话可以尝试 githubCompatibility 设置

**Comment by AndyHuyidi** [comment]
> 这是因为在 VSCode 里默认会进行 URI 编码，不喜欢的话可以尝试 githubCompatibility 设置

1、还没有明白您这个，githubCompatibility 设置是在github里面设置吗？  我这个用的是VSCODE，是在VSCODE里面设置吗？ 能详细点吗，谢谢。
2、用CTOC生成后，在使用preview enhanced 在VSCODE里面的预览时可以在页面内跳转，但将其保存为HTML文档用browser 打开后就无法实现页面内跳转了。 

Thanks a lot!!

**Comment by donaldshen** [comment]
> > 这是因为在 VSCode 里默认会进行 URI 编码，不喜欢的话可以尝试 githubCompatibility 设置
> 
> 1、还没有明白您这个，githubCompatibility 设置是在github里面设置吗？ 我这个用的是VSCODE，是在VSCODE里面设置吗？ 能详细点吗，谢谢。
> 2、用CTOC生成后，在使用preview enhanced 在VSCODE里面的预览时可以在页面内跳转，但将其保存为HTML文档用browser 打开后就无法实现页面内跳转了。
> 
> Thanks a lot!!

1. 在 vscode 里生成 toc 那当然是在vscode里寻找githubCompatibility配置项了
2. 你的问题和我提的 omit in toc 有啥关系，应该重提issue，不然老是@到我🥺

**Comment by AndyHuyidi** [comment]
好的， 感谢。

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
