### ISSUE TITLE
Feature Request: Update the logo with white background in it.

### ISSUE THREAD

**Issue by escape0707** [yzhang-gh/vscode-markdown#498]
...or it will appears almost all grey or black in VS code with dark mode on like this:

![ext-icon](https://user-images.githubusercontent.com/11014745/62223759-0e95e580-b3e8-11e9-81ad-42c3d1ff9790.png)

> 不厚道的借用别的扩展logo，类似这样实心的图标应该会好看一点？
> 
> ![image](https://user-images.githubusercontent.com/11014745/62224153-ce833280-b3e8-11e9-88d9-bcbb179735f1.png)

**Comment by yzhang-gh** [comment]
搞定 😉
