### ISSUE TITLE
HTML file contains obsolete meta

### ISSUE THREAD

**Issue by Lemmingh** [yzhang-gh/vscode-markdown#499]
#### What is the problem?

In the `<head>` of HTML file created by the command **Markdown All in One: Print current document to HTML** (`markdown.extension.printToHtml`), there is a `<meta>` tag

```html
<meta http-equiv="Content-type" content="text/html;charset=UTF-8">
```

However, [according to MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv), `http-equiv="content-type"` is obsolete:

> **Warning**: Do not use this value, as it is obsolete. Use the `charset` attribute on the `<meta>` element.

Please replace it with

```html
<meta charset="utf-8">
```

Thanks a lot.

#### How can I reproduce it?

1. Open a Markdown file
2. Run command **Markdown All in One: Print current document to HTML** (`markdown.extension.printToHtml`)
3. Check the HTML file generated by it

#### Is there any error message in the console?
No.

**Comment by yzhang-gh** [comment]
Thank you for pointing this out. Fixed.
