### ISSUE TITLE
Markdown All in One(2.4.2) on VS Code(1.36.1)   Right-click menu don't appare.

### ISSUE THREAD

**Issue by xifarm** [yzhang-gh/vscode-markdown#500]
i download the newest VS Code（windows） and download newest Markdown All in One.

add first new *.md file.

but the Right-click menu don't appare.
this is very difficult.

because, in the MAC, the Right-click menu is ok.

#### How can I reproduce it?
![image](https://user-images.githubusercontent.com/4516600/62437653-b60f7100-b776-11e9-8fd3-72b08d73d511.png)

**Comment by yzhang-gh** [comment]
我没有很理解你的问题，猜测你是说点击右键之后不会出现上下文菜单

不过这个插件并没有对上下文菜单做改动，我怀疑是别的地方的问题

建议禁用所有其他插件（除了这一个）来检查是否是这个插件造成的.（侧边栏插件页的 ··· 菜单里可以方便地禁用所有插件）

**Comment by xifarm** [comment]
非常感谢解答。

我需要的答案，通过下载 Markdown Shortcuts 解决了。


Markdown All in One是很赞的MD插件。

**Comment by xifarm** [comment]
多谢多谢。
