### ISSUE TITLE
command 'markdown.extension.onBackspaceKey' not found

### ISSUE THREAD

**Issue by Triple-Z** [yzhang-gh/vscode-markdown#501]
#### What is the problem?

```
command 'markdown.extension.onBackspaceKey' not found
command 'markdown.extension.onEnterKey' not found
command 'markdown.extension.onTabKey' not found
```

1. wait for a few seconds after you open a Markdown file for the first time 
> Tried.
2. doesn't work? -> update vscode 
> The latest stable version.
3. doesn't work? -> reinstall this extension
> Tried
4. still doesn't work? 😵 -> please open the developer tools to see whether there is any error message,
> No error occurs.

#### How can I reproduce it?
Install this extension on 1.36.1 Visual Studio Code.

VS Code version:
![image](https://user-images.githubusercontent.com/16285716/62589277-4d9dcc80-b8fb-11e9-9da6-39719cae82ce.png)

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment]
I am using the same version of VSCode and everything works well. Can you do one more check, disabling all extensions (except for this one)? (This can be easily done as shown below)

![image](https://user-images.githubusercontent.com/7588612/62602034-a5800780-b8ea-11e9-93a7-aca06efea3fa.png)

**Comment by Triple-Z** [comment]
I have restarted VS Code several times and it works fine now. It seems the problem is caused by extension daemon, thx for your help and appreciate your great work!

Sorry to bother you, this problem is caused by my side.

**Comment by yzhang-gh** [comment]
No worries 😉

**Comment by Diego-MX** [comment]
But what caused it?  
I'm experiencing the same problem.

**Comment by yzhang-gh** [comment]
Please see https://github.com/yzhang-gh/vscode-markdown#faq.

**Comment by ackvf** [comment]
Wow, just got this for the first time ever. It seems that restarting extension host has fixed it for me.
