### ISSUE TITLE
enhancement suggestion: open [markdown] cells of python extension

### ISSUE THREAD

**Issue by YoniChechik** [yzhang-gh/vscode-markdown#502]
Currently it is not supported in the official python extension to view markdown cells (`#%% [markdown]`)  online as you type. if you enable this feature, this will help a lot of notebook writings in vscode.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Do you mean the Markdown preview? I am afraid it is impossible to change the Webview managed by Python extension from this extension.
