### ISSUE TITLE
I hope md file name autocompletes can also be added

### ISSUE THREAD

**Issue by wanjm** [yzhang-gh/vscode-markdown#504]
now it can auto complete image name ;
I hope md file name autocompletes can also be added, as we need to use md file in link.

**Comment by yzhang-gh** [comment]
This is already done in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). Please give it a try.

(Duplicate of #466)

**Comment by yzhang-gh** [comment]
Added in v2.5.0
