### ISSUE TITLE
Need to change title at HTML output

### ISSUE THREAD

**Issue by HN-Tran** [yzhang-gh/vscode-markdown#506]
Hello, please put something to change the title on the HTML output. I tried using HTML-title-tags, but it doesn't work, since everything written in the Markdown document is written in the HTML-body-section. Instead of using the first h1, can you put a rule like this?

```
---
title: Document Title
---
```

or

```
% Document Title
```

It would be great so I don't need to change the HTML output every time.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

We don't support YAML front matter or `%` comment now. So the two options you mentioned might not be that suitable here.

But I can think of a solution, supporting another "magic" comment `<!-- title: Document Title -->` which should appear as the first line. (Just like the `<!-- omit in toc -->` comment we already supported)

**Comment by HN-Tran** [comment]
> Thanks for the feedback.
> 
> We don't support YAML front matter or `%` comment now. So the two options you mentioned might not be that suitable here.
> 
> But I can think of a solution, supporting another "magic" comment `<!-- title: Document Title -->` which should appear as the first line. (Just like the `<!-- omit in toc -->` comment we already supported)

Yes, it would be great if you could do that. I would support the "magic" comment solution.

**Comment by nan-af** [comment]
Any updates regarding this?

**Comment by yzhang-gh** [comment]
I would like to request help from anyone interested.

Currently, we are using the first heading as the title

https://github.com/yzhang-gh/vscode-markdown/blob/c83296e52bee7326d1c56731f0e670289e5c3a62/src/print.ts#L58-L61

**Comment by nan-af** [comment]
I would like to help, but I already have too much work to do. Apologies.

I might do it if I get time though

**Comment by boris-gannoyingl** [comment]
Haven't tested it, but it should be as simple as...
`
let titleTemp = doc.getText().split(/\r?\n/g);
let title = titleTemp.find(lineText => lineText.startsWith('/, '$1').trim();
}
else {
     title = titleTemp.find(lineText => lineText.startsWith('#'));
     if (title) {
          title = title.replace(/^#+/, '').replace(/#+$/, '').trim();
      }
}
 `
Optionally, the `else` statement can be removed, though it allows for prior behavior.

**Comment by yzhang-gh** [comment]
@boris-gannoyingl Thanks. Yes, it is very simple from technical perspective. How about a PR? 😉

**Comment by Lemmingh** [comment]
> ```js
> let titleTemp = doc.getText().split(/\r?\n/g);
> let title = titleTemp.find(lineText => lineText.startsWith('<!-- title:'));
> ```

This means the `<!-- title: -->` comment can appear on **arbitrary** line, which sounds like a risk.

I think the [original proposal](https://github.com/yzhang-gh/vscode-markdown/issues/506#issuecomment-521560181) is

```typescript
let title: string;

const firstLineText = doc.lineAt(0).text;
if (!!(let m = /^<!-- title: (\S.*) -->/.exec(firstLineText))) {
    title = m[1].trim();
}
```

**Comment by boris-gannoyingl** [comment]
I concur with only being on the first line. Failed to notice that in the original suggestion.

**Comment by yzhang-gh** [comment]
Thanks, everyone. Please check out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
