### ISSUE TITLE
toc生成目录不完整

### ISSUE THREAD

**Issue by smallprogram** [yzhang-gh/vscode-markdown#508]
#### What is the problem?
当我撰写了10个以上的二级标题之后，使用toc生成的目录会丢失第10个二级标题之后的标题。生成的目录不完整
![image](https://user-images.githubusercontent.com/6050360/63237394-5c2da180-c274-11e9-8de5-6f68656d84f3.png)
![image](https://user-images.githubusercontent.com/6050360/63237400-60f25580-c274-11e9-8ce5-4a0078839bb8.png)

附上md文件
[02.02-组件与模板-模板语法.zip](https://github.com/yzhang-gh/vscode-markdown/files/3514098/02.02-.-.zip)

#### How can I reproduce it?
我希望生成完整的目录。

#### Is there any error message in the console?

没有错误提示

**Comment by yzhang-gh** [comment]
主要原因是从 560 行开始有了奇怪的缩进

![image](https://user-images.githubusercontent.com/7588612/63257942-ca716480-c272-11e9-9657-403966554450.png)

不过 Markdown 确实是允许 4 个空格以内的缩进，所以我也修复了一下（可在[预览版](https://github.com/yzhang-gh/vscode-markdown#latest-development-build)尝试）

**Comment by smallprogram** [comment]
> 主要原因是从 560 行开始有了奇怪的缩进
> 
> ![image](https://user-images.githubusercontent.com/7588612/63257942-ca716480-c272-11e9-9657-403966554450.png)
> 
> 不过 Markdown 确实是允许 4 个空格以内的缩进，所以我也修复了一下（可在[预览版](https://github.com/yzhang-gh/vscode-markdown#latest-development-build)尝试）

👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍

**Comment by smallprogram** [comment]
It's fixed~~
