### ISSUE TITLE
How to tweak the decoration style for the inline code?

### ISSUE THREAD

**Issue by gaochenyi** [yzhang-gh/vscode-markdown#509]
How to tweak the decoration style for the inline code `inline_code`?

For example, I want to decorate it with a light grey background rather than boxing because that makes the inline code too conspicuous.

![Screen Shot 2019-08-22 at 5 43 08 PM](https://user-images.githubusercontent.com/32761974/63504574-6c5bb000-c504-11e9-879e-5a79120eb6af.png)

**Comment by yzhang-gh** [comment]
The syntax decoration feature is originally designed for dark theme (see [here](https://github.com/yzhang-gh/vscode-markdown/issues/185#issuecomment-394168278)). The colors are hardcoded so they may look wired under light theme. What theme are you using?

**Comment by gaochenyi** [comment]
> The syntax decoration feature is originally designed for dark theme (see [here](https://github.com/yzhang-gh/vscode-markdown/issues/185#issuecomment-394168278)). The colors are hardcoded so they may look wired under light theme. What theme are you using?

Oops. I am using 'Quiet Light', which is a light theme. Then is there any way to change the style of decoration? I tried the extension [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) but could not make a regular expression matching only the inline code. Can this extension be used to tweak the default decoration style?

**Comment by yzhang-gh** [comment]
Here is the RegExp I used to match code span

https://github.com/yzhang-gh/vscode-markdown/blob/4c4950b943e563d7ad7cb70b5fda2e4d5f1b273b/src/syntaxDecorations.ts#L51-L52

You can play with it in the https://regex101.com/. However, I am not sure whether Highlight extension can override the decorations provided by this extension. One possible solution is to disable the decorations of this extension and write your own rules using Highlight extension.

**Comment by gaochenyi** [comment]
Many thanks!

After some trials, I am able to customize the decoration with your RegExp after disabling the decoration of this extension. And I am sorry for the late response because until today I don't find time to learn the regular expression.

By the way, I attach my setting in case other folks need it.

```jsonc
  "highlight.regexes": {
  	"(?<!`)(`+)(?!`)(.*?)(?<!`)(\\1)(?!`)": {
      "filterLanguageRegex": "markdown", // Apply only if current file's language matches this regex. Requires double escaping
      "filterFileRegex": ".*\\.md", // Apply only if the current file's path matches this regex. Requires double escaping
      "decorations": [ // Decoration options to apply to the capturing groups
        {}, // Decoration options to apply to the first capturing group
        {
          "rangeBehavior": 1,
          // "border": "1px dotted #454D51",
          "borderRadius": "3px",
          "backgroundColor": "#efefef",
        },  // Decoration options to apply to the second capturing group
      ]
    },
  },
```

**Comment by yzhang-gh** [comment]
👍
