### ISSUE TITLE
Inside Makefile code-block,  the tab key should insert "tab" character 

### ISSUE THREAD

**Issue by ajit555db** [yzhang-gh/vscode-markdown#511]
Feature request

#### What is the problem?

Inside embedded code of type "Makefile", the tab should insert "tab" character instead of spaces if the default tab option is set to spaces.

**Comment by yzhang-gh** [comment]
This extension simply calls the vscode default `tab` action. There is nothing I can do here.

https://github.com/yzhang-gh/vscode-markdown/blob/4c4950b943e563d7ad7cb70b5fda2e4d5f1b273b/src/listEditing.ts#L177
