### ISSUE TITLE
[Feature request] "Markdown: Toggle code block" 

### ISSUE THREAD

**Issue by haakonstorm** [yzhang-gh/vscode-markdown#512]
Hello, and thank you for a great plugin!
We have the command `toggle code span` which encapsulates in single backticks:

```
COMMAND <<InputComesFromHERE
...
...
InputComesFromHERE
```

When you select the text, then `shift`+`cmd`+`p`, 
and select `"Markdown All in One: toggle code span"` you get:
```
`COMMAND <<InputComesFromHERE
...
...
InputComesFromHERE
`
```

But how can I select the text, and end up with:

``````
```
COMMAND <<InputComesFromHERE
...
...
InputComesFromHERE
```
``````
?

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Currently, we don't have this feature. As a workaround, you can define a user keybinding

```json
{
    "command": "editor.action.insertSnippet",
    "args": {
        "snippet": "```\n$TM_SELECTED_TEXT\n```"
    },
    "key": "ctrl+l",
    "when": "editorTextFocus && editorLangId == 'markdown'"
}
```

See more information [here](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets).

**Comment by axiqia** [comment]
I add this feature in this [request,](https://github.com/yzhang-gh/vscode-markdown/pull/551) if you have time, please review it. @yzhang-gh
