### ISSUE TITLE
HTML video tag

### ISSUE THREAD

**Issue by josergdev** [yzhang-gh/vscode-markdown#514]
#### What is the problem?

html video tags don't seem to work.
It doesn't even load the alternative text.

![capture](https://i.imgur.com/EGAGtIq.png)

#### How can I reproduce it?

Just try:

```
# Video Test

<video weight="640" height="360" controls>
  <source
    src="https://i.imgur.com/3V9bfuA.mp4" 
    type="video/mp4"
  />
  Your browser does not support the video tag.
</video>
```

#### Is there any error message in the console?

No

**Comment by yzhang-gh** [comment]
There are 2 steps from Markdown to its preview:
1. parse Markdown and convert it to HTML
2. render HTML as a web page (in a browser, VSCode WebView etc.)

_This extension only intervenes in the first step_. I am not sure but I guess it can work if you export your sample file to HTML and open it in the browser. If it is the case, then that is VSCode's decision (to not render video)

**Comment by Lemmingh** [comment]
> VS Code uses a version of Electron that does not include FFmpeg.
>
> playback of many common media formats is not supported inside VS Code.
>
> There are no plans to change this.

said [Matt Bierner](https://github.com/mjbvz) at <https://stackoverflow.com/a/51735036>.
