### ISSUE TITLE
add "stop" listening to table of contents. 

### ISSUE THREAD

**Issue by WestMec200** [yzhang-gh/vscode-markdown#516]
Is there a way to stop the automatic update of the tables?

I have this markdown and I dont want exercises, etc on here just the steps.
This is my only constant issue with this extension and wish there was a way to have it stop without disabling it.

```markdown
# Exercise 01
- [Exercise 01](#exercise-01)
  - [Objectives](#objectives)
  - [Instructions](#instructions)
- [Get Docker-Compose is running – Step 1](#get-docker-compose-is-running-%e2%80%93-step-1)
- [Chrome Network Tools – Step 2](#chrome-network-tools-%e2%80%93-step-2)
- [Step 3](#step-3)
- [Step 4](#step-4)
- [Step 5](#step-5)
- [Step 6](#step-6)
- [Step 7](#step-7)
```

**Comment by yzhang-gh** [comment]
Please refer to the [Supported Settings](https://github.com/yzhang-gh/vscode-markdown#supported-settings) section. (Probably `toc.updateOnSave` is what you need)
