### ISSUE TITLE
`Value not accepted` when using an ext command in `keybindings.json`

### ISSUE THREAD

**Issue by garyking** [yzhang-gh/vscode-markdown#519]
#### What is the problem?

I've got the following in my VSC global keybindings.json file:

```json
  {
    "key": "cmd+b",
    "command": "-markdown.extension.editing.toggleBold",
    "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown'"
  },
```

So that I remove the shortcut. It works fine, but for some reason, `"-markdown.extension.editing.toggleBold"` is marked with the message: 

```json
{
	"resource": "Code/User/keybindings.json",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "1",
	"severity": 4,
	"message": "Value is not accepted. Valid values: <huge list of every possible value here>.",
	"startLineNumber": 56,
	"startColumn": 16,
	"endLineNumber": 56,
	"endColumn": 56
}
```

#### How can I reproduce it?

Add the same code to your keybindings.json file.

#### Is there any error message in the console?

Yep, the one above.

**Comment by yzhang-gh** [comment]
I see the warning

![image](https://user-images.githubusercontent.com/7588612/64901958-e7fae800-d6d1-11e9-9490-8b9e253fc5f3.png)

However, it is out of the scope of this extension. I guess you will get the same warning if you delete any extension-contributed keybinding.
I would suggest reporting this to VSCode team.
