### ISSUE TITLE
在选中文字是链接的时候，crtl+V自动生成网址格式没反应

### ISSUE THREAD

**Issue by Anyway521** [yzhang-gh/vscode-markdown#523]
如图，在生成[链接](链接)格式的文字时，crtl + V 没有反应
![QQ截图20190921010011.png](https://cdn.anyway1314.cn/imageQQ截图20190921010011.png)

**Comment by Anyway521** [comment]
就是`[www.baidu.com](www.baidu.com)`这种，

**Comment by mayeths** [comment]
无法理解你说的意思，但这个功能是先复制一个链接，然后在 md 里选中一段文字按粘贴，就会自动贴上去

**Comment by yzhang-gh** [comment]
@mayeths 说的是对的

@Anyway521 能说明一下操作步骤吗（以及和预期有什么不同）？

**Comment by linsui** [comment]
如果选中的文字是一个链接地址，复制时不会有变化。
比如我希望得到 `[https://www.baidu.com](https://github.com/)` ，首先输入 `https://www.baidu.com` ，然后选中，将一个链接地址，如 `https://github.com/` 复制到剪贴板，粘贴。得到的不是 `[https://www.baidu.com](https://github.com/)` 而是 `https://github.com/` 。不过这个是设计如此吧

**Comment by yzhang-gh** [comment]
懂了😂

确实是如此设计的（如果选中的文本本来就是链接，则使用默认的粘贴行为）
