### ISSUE TITLE
Reference link does not support Github Markdown Style

### ISSUE THREAD

**Issue by dcalvin** [yzhang-gh/vscode-markdown#524]
#### What is the problem?

When I try to add an internal reference link (to a topic within the current doc), it would not lower-case all words. For example `#COLLATION_CHARACTER_SET_APPLICABILITY-表` is available for selection, but we need `#collation_character_set_applicability-表` instead to be consistent with the parsing rule on GitHub. 

#### How can I reproduce it?

Auto-lowercase the English words when generating the anchor

Thanks for the wonderful work.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

I am not very sure I understand the issue you mentioned. Are you talking about the reference link auto-completion?

![image](https://user-images.githubusercontent.com/7588612/65602601-b8ec4c80-dfd6-11e9-84ec-c3b8c3aeb5cd.png)

They are already downcased.

Can you provide more information about the reproduction **steps**? such as a toy document, what do you type and what is expected?
