### ISSUE TITLE
[feature request] file completion from custom root path

### ISSUE THREAD

**Issue by davwheat** [yzhang-gh/vscode-markdown#526]
I have my markdown files in a subfolder called `static` in the project root. When building and deploying, this folder's contents are copied to the root directory on my web server.

Because of this, if I want to add an image, the path "autocompleter" wants to prepend every path with `/static`.

Could you add a setting so we can add a custom root folder for the path autocomplete?

**Comment by yzhang-gh** [comment]
A new option `completion.root` has been added to the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) (6c024ca).

**Comment by davwheat** [comment]
Thanks!
