### ISSUE TITLE
[feature request] is it possible to add "rich edit" support to markdown table?

### ISSUE THREAD

**Issue by fyears** [yzhang-gh/vscode-markdown#527]
#### What is the problem?

Typora has a very nice feature that it seems no vscode md plugins support yet:

When you create a table with markdown code in Typora:

```markdown
|  aaaa | bbbb |
| 123 | 456 |
```

Typora automatically change the table into "rich edit GUI" (which looks like Excel) instead of keeping it as "raw text". It's much easier to select the specific cell and enter some text in rich edit GUI.

Is it possible for this "markdown all in one" to add the similar support?

Thank you.

#### 什么问题？

Typora 有个很爽的功能，似乎没有 vscode md 插件实现过。

当输入 md 表格的时候，Typora 自动变成了一个“富文本编辑表格”，而不是纯文字。这种编辑模式比纯文字好用太多了。

请问这个“markdown all in one”插件有没有可能添加类似支持？

谢谢！

**Comment by yzhang-gh** [comment]
感谢反馈. 之前有过类似的讨论 https://github.com/yzhang-gh/vscode-markdown/issues/23#issuecomment-320110895 ，Typora 那样的表格在 VSCode 里应该是无法实现的，Caret 那种倒是有可能，只是这个功能相比其需要的工作量不是很值得 😂.
