### ISSUE TITLE
Color scheme of code block is not suitable with it's white background at HTML output

### ISSUE THREAD

**Issue by ganxy1028** [yzhang-gh/vscode-markdown#529]
Key words and notes is light colored in HTML output, which does't suit is white background.
A color scheme change will be good. Thanks

代码块在输出的HTML中的配色在白色背景下看不清，能改一改配色方案就好了。谢谢

![image](https://user-images.githubusercontent.com/26629457/66456627-b131ab00-eaa0-11e9-81c8-1cba0bece201.png)

**Comment by yzhang-gh** [comment]
目前这个样式是从 VSCode 里复制出来的，没办法改
（你可以尝试一下 VSCode 内白色主题预览时效果会不会好一点，如果是那样我可以更新一下样式）

如果你懂一点 CSS，另外一个方法是用 `markdown.styles` 设置添加一个 highlight.js 的主题文件，可以去它官网查看

**Comment by ganxy1028** [comment]
白色主题的预览效果会好一些，除了数字颜色不太好之外其他都能看清。

.hljs-number,
.hljs-class {
	color: #B8D7A3;
}

这一段的颜色能修改一下就好，可以考虑像原工作区里一样改为和注释一样的 #57A64A ，其他部分应该都挺好

**Comment by yzhang-gh** [comment]
我刚才检查了一下，现在已经是直接引用 VSCode 的样式

https://github.com/yzhang-gh/vscode-markdown/blob/6c024cadeef95392a4f35472eb1e4d1d61d4293b/src/print.ts#L247-L248

既然你有相应的 CSS，可以自己添加一个样式文件，导出 HTML 的时候会被包括进去

**Comment by ganxy1028** [comment]
当然，我可以自己添加。但是如果默认在导出HTML得时候使用Light 模式的 highlight 就更好了，在其他电脑上弄得时候会容易一些。因为从默认的设置上看，导出HTML的时候使用的始终是 Dark 模式下的配色，不论vscode本身用的是那种主题。

**Comment by yzhang-gh** [comment]
你确实帮我发现了一个问题：虽然我导入的样式和 VSCode 是一样的，但是 VSCode 内部预览的时候会添加 `.vscode-light` 来区分主题，而我导出的文件没有这些，导致这些样式没有应用上去.
这个问题修复之后应该可以达到和 VSCode 中预览相同的效果.

> 除了数字颜色不太好之外其他都能看清... 这一段的颜色能修改一下就好...

至于具体个别的样式我就不修改了，和 VSCode 保持一致，好维护一点
（你愿意的话也可以直接给 VSCode 提 PR）

**Comment by yzhang-gh** [comment]
我已经改成使用 light 主题样式了，你可以下载开发版（在 `README` 最后）尝试一下，感觉效果确实比之前好

**Comment by ganxy1028** [comment]
非常感谢

**Comment by kleach** [comment]
And how can I disable this feature? I don't want
```html
<body class="vscode-light">
```
to be default for my workspace. My project is based on using dark theme for markdown but there is no setting to choose which theme I want to use.

**Comment by ganxy1028** [comment]
![image](https://user-images.githubusercontent.com/26629457/68447816-4220b100-021c-11ea-82ce-202e3d785c19.png)
修改后的highlight文件已在VScode 1.40版本中成为默认，希望也能加入到本扩展中，谢谢。
[https://github.com/microsoft/vscode/blob/master/extensions/markdown-language-features/media/highlight.css](修改后的CSS文件)

**Comment by yzhang-gh** [comment]
It should be automatically included as we are referencing the latest CSS files. (see https://github.com/yzhang-gh/vscode-markdown/issues/529#issuecomment-540080209)

**Comment by ganxy1028** [comment]
OK. Thanks
