### ISSUE TITLE
Keybinding context variable for Markdown preview

### ISSUE THREAD

**Issue by tats-u** [yzhang-gh/vscode-markdown#530]
#### What is the problem?

https://github.com/microsoft/vscode/issues/65350

#### How can I reproduce it?

- See https://github.com/microsoft/vscode/issues/65350
- Install this extension in addition of ones written in that issue.

#### Is there any error message in the console?

Nothing

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

As the preview keybindings are so commonly used, it is natural to see the conflicts.

The good news is VSCode allows you to control all the keybindings. Just delete it if you don't need it.

![image](https://user-images.githubusercontent.com/7588612/66502391-b4a45100-eaf7-11e9-82eb-5715298672eb.png)

**Comment by tats-u** [comment]
I have already done it.

**Comment by tats-u** [comment]
These shortcut redefinition also affect to viewer of other languages like AsciiDoc, so I suppose they should be restricted to when Markdown mode.

**Comment by yzhang-gh** [comment]
This shortcut is also used to close the Markdown preview tab, which is not in Markdown text editor mode. It seems we don't have a better solution (to identify the current focused tab) now.

**Comment by tats-u** [comment]
Is it better for us to submit a feature request to VSCode body?
I think that the feature that closes the viewer not only opens it is useful, too.

**Comment by yzhang-gh** [comment]
I agree. I would suggest adding a new context variable `isInWebview` (or `webviewId`).

ref: https://code.visualstudio.com/docs/getstarted/keybindings#_when-clause-contexts

**Comment by Lemmingh** [comment]
Should have been resolved by #780
