### ISSUE TITLE
toc breaks from codeblocks

### ISSUE THREAD

**Issue by jasonkuhrt** [yzhang-gh/vscode-markdown#532]
Thanks for this extension!

Discovered that TOC will break when it finds for example:

```gql
# this is a comment
```

No idea if its a good fit internally for this project but maybe you want to do use [doctoc](https://github.com/thlorenz/doctoc) to power the toc features of this extension.

**Comment by yzhang-gh** [comment]
> Discovered that TOC will break when it finds for example:

Could you elaborate on what is the problem? It seems to work well here.

![image](https://user-images.githubusercontent.com/7588612/66692297-a741bf00-eccf-11e9-8527-39a582ecb6b0.png)

> doctoc

Thanks for the information. That is interesting. It might be useful as it provides an option for different sites.

**Comment by yzhang-gh** [comment]
Well, I can reproduce it now. (Just updated my own extension)
