### ISSUE TITLE
Add a setting to choose which style to use by default

### ISSUE THREAD

**Issue by kleach** [yzhang-gh/vscode-markdown#534]
# Problem
In the fix for #529 you made 

```html
<body class="vscode-light">
```
instead of
```html
<body>
```

Maybe it's important for those who does need right highlighting on the light background but in my project's workspace it's important to use dark theme.
Can you add an option to choose which theme to use?

# For example:
- in `settings.json`:
```json
"markdown.extension.defaultTheme": "light" | "dark",
```
- in `print.ts`:
```js
const html = `<!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>${title ? title : ''}</title>
        ${getStyles(doc.uri, hasMath)}
        ${hasMath ? '<script src="https://cdn.jsdelivr.net/npm/katex-copytex@latest/dist/katex-copytex.min.js"></script>' : ''}
    </head>
    <body${defaultTheme == "light" ? 'class="vscode-light"' : ''}>
        ${body}
    </body>
    </html>`;
```

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

May I know your use case of the exported HTML? AFAIK, people usually export Markdown to HTML for sharing (as a document), which is presumably in a light background.

**Comment by kleach** [comment]
I'm writing a _C++_ training course for children. I use dark theme to contrast a formatted explanation with the code sections. It feels more natural and authentic to look on the dark themed code because we're used to work with dark themed IDEs. And there is a fun fact that children love to work with dark themes because they feel themselves like hackers 😊

**Comment by yzhang-gh** [comment]
Added in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by kleach** [comment]
Nice. Thank you.
