### ISSUE TITLE
Math symbols are not shown properly on remote machines.

### ISSUE THREAD

**Issue by MrChenWithCapsule** [yzhang-gh/vscode-markdown#535]
#### What is the problem?

Previewing markdown files with math symbols works as expected on my local machine.

![图片](https://user-images.githubusercontent.com/30191901/66816064-00c61a00-ef6c-11e9-8cdf-44d575651c1b.png)

But with VSCode's remote development extension (connecting to either a remote machine or WSL), these symbols are not properly rendered.

![图片](https://user-images.githubusercontent.com/30191901/66816616-f6f0e680-ef6c-11e9-9b68-bfa6d7ab2d9a.png)

However, exporting to HTML seems to work fine.  

#### How can I reproduce it?

1. Create a new markdown file on a remote machine.
2. Insert some math symbols.
2. Open preview.

#### Is there any error message in the console?

Yes, see below:
[-1571130610505.log](https://github.com/yzhang-gh/vscode-markdown/files/3728369/-1571130610505.log)

**Comment by yzhang-gh** [comment]
This looks like a complicated issue. The inside VSCode preview is handled by VSCode itself, while this extension adds some plugins to it.

https://github.com/yzhang-gh/vscode-markdown/blob/e4c6e9fe8c1e46f2792dc5c9f9e279f33c11b704/src/extension.ts#L27-L33

It seems that the KaTeX plugin isn't loaded properly in remote mode. I guess the task list also doesn't work (try `- [ ] item`).

Moreover, can you test whether [Markdown Emoji](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-emoji) has the same issue? (It is an extension from the VSCode team.)

**Comment by MrChenWithCapsule** [comment]
I updated VSCode to version 1.39.2 that released today, and this bug seems to have been fixed.  :sweat_smile:

**Comment by yzhang-gh** [comment]
😄
