### ISSUE TITLE
Use of "omit in toc" also prevents use of link to header

### ISSUE THREAD

**Issue by bcjmk** [yzhang-gh/vscode-markdown#536]
Use of 

# Document Name 
[Back to Top](#document-name)

Will not work. And use of the  only works in this extension, not in the broader MarkDown applications.

Any guidance on how to implement in real world?

Thanks,
Bill

**Comment by yzhang-gh** [comment]
> `<!-- omit in toc -->` breaks the link to the heading.

Yes, this is a known issue. Currently, we don't have a solution. I will resolve it in #495.

> And use of the only works in this extension, not in the broader MarkDown applications

Markdown has so many dialects that there is no unified way to do this. This "magic comment" won't affect the content (which means you can keep it even if you are using other editors).
But if you want the same feature in other editors, you may need to use the ways they provide.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
