### ISSUE TITLE
TOC includes underscores from headers in links if Github Compatibility is enabled

### ISSUE THREAD

**Issue by vancejc** [yzhang-gh/vscode-markdown#537]
#### What is the problem?
As mentioned in https://github.com/yzhang-gh/vscode-markdown/issues/147 , if `"markdown.extension.toc.githubCompatibility": true` is set, any header with an underscore causes an incorrect TOC to be generated.  If the setting is `false` then the TOC correctly strips out underscores.

#### How can I reproduce it?
Create an italic header using underscores (`## (_Test_)` for example), set `"markdown.extension.toc.githubCompatibility": true` and create a table of contents.  You will see that underscores are included in the link which make for invalid linking in github (ironic, in that github compatibility is turned on)

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This is a known issue #494. We need to remove the styles in the headings (e.g. `_italics_` and `**bold**`).

Please subscribe to the referred issue. I am going to figure out a solution this weekend.
