### ISSUE TITLE
Cannot load css style sheets in `markdown.styles`

### ISSUE THREAD

**Issue by WyRe** [yzhang-gh/vscode-markdown#538]
#### What is the problem?
I cannot load extra css style sheet with `markdown.styles` settings; I'm getting warnings all the time

#### How can I reproduce it?
I'm get those errors when I add something to `markdown.styles` parameter. 

#### Is there any error message in the console?
```
Could not load 'markdown.styles': /home/wyre/github.css
```
```
Could not load 'markdown.styles': https://raw.githubusercontent.com/raycon/vscode-markdown-style/master/preview/github.css
```

What I'm doing wrong? thank you!

**Comment by yzhang-gh** [comment]
The `markdown.styles` setting is provided by VSCode itself. (This extension's settings are all with prefix `markdown.extension.`)

I know VSCode probably doesn't allow local files except for those in the current folder (for security concerns). The `https` one looks nothing wrong to me.
https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css

If things don't work for you, you may need to report to the VSCode team.

**Comment by WyRe** [comment]
> The `markdown.styles` setting is provided by VSCode itself. (This extension's settings are all with prefix `markdown.extension.`)

Sorry then, I've not noticed that point.

> I know VSCode probably doesn't allow local files except for those in the current folder (for security concerns). **The `https` one looks nothing wrong to me.**
> https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css

So you say [this one](https://raw.githubusercontent.com/raycon/vscode-markdown-style/master/preview/github.css) is loading for you?

**Comment by yzhang-gh** [comment]
Sorry, my previous comment is kind of misleading. (I have reordered the sentences.)

I just tried to add the `https` CSS file and got the same warning as yours. But according to the VSCode documentation, it should work. It looks like a VSCode bug.

**Comment by WyRe** [comment]
For further info ... the problem seems to be in how Github serves the raw content-type, which is `text/plain`. [More info here](https://github.com/microsoft/vscode/issues/82924)

**Comment by yzhang-gh** [comment]
Thanks for the information.
