### ISSUE TITLE
Support AsciiMath

### ISSUE THREAD

**Issue by qizaodian** [yzhang-gh/vscode-markdown#540]
AsciiMath的语法比LaTeXMath更直观友好，能否实现对AsciiMath公式输入的支持？

**Comment by yzhang-gh** [comment]
看了一下 ASCIIMath 需要使用 MathJax，所以这个需求还依赖于 #531.

**Comment by 66Leo66** [comment]
能否利用 [christianp/asciimath2tex](https://github.com/christianp/asciimath2tex) 实现 asciimath 支持？

**Comment by 66Leo66** [comment]
关于区分，可以使用自定义的标识符，如Rocket.Chat项目使用双`%`包围 asciimath 表达式；

关于兼容性，可以用一个 Command 来一次性转化所有 asciimath 为 tex（用于在其他平台发表），或只在渲染&导出时处理，提供给用户选择。

**Comment by yzhang-gh** [comment]
额，技术上什么问题都总能有解决方案。。。只是不一定值得投入这么多精力
