### ISSUE TITLE
TOC: duplicated anchors won't work

### ISSUE THREAD

**Issue by pedroprates** [yzhang-gh/vscode-markdown#541]
The table of contents successfully differentiate duplicated headers with different anchors, based on this issue [#211](https://github.com/yzhang-gh/vscode-markdown/issues/211), but the anchor created for the duplicated header, won't work neither on PDF nor HTML (the link won't connect to the header).

For example:

# Introduction
Some small introduction
# New Method
## Introduction
New method introduction

The first **Introduction** header will have a `#introduction` anchor, while the second **Introduction**, the one below the **New Method**, will have a different anchor `#introduction-1`. When exporting to PDF (or HTML), PDF readers (or browsers, when dealing with HTML) won't acknowledge the second anchor as linking to the second **Introduction** header, probably because of the additional *-1* on the end of the header name, and therefore the second **Introduction** on the Table Of Contents won't be clickable. 

Is there another way to deal with duplicate headers and anchors in a way that it won't break the link on PDF readers?

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

(First to say there is probably no universal way of dealing with the duplicated headings. It is all about compatibility/consistency.)

The `-1` incremental solution is adopted in many places.
I just checked and it works well inside VSCode and the exported HTML.
As for PDF, I only recommend using Chrome to print the HTML to PDF. And the anchors also work there.

I guess your document doesn't have enough length for jumping. Put more dummy text and try again.

**Comment by pedroprates** [comment]
Thank you for the fast reply, @yzhang-gh!

Yes, I understand that there are no *one size fits all* kind of solution for this problem, probably we would end up on a better solution for a particular case. 

I have made [a markdown example](https://gist.github.com/pedroprates/35769fb5ca70be6465e0c79882ed0aae) covering this. This issue happens when I export both on HTML or PDF: 

The second **Introduction** header link does not work, it's not clickable (on PDF) or it doesn't move to anywhere (HTML). I was thinking about why does this happen: probably because the anchor, `#introduction-1` is searching for a header like `Introduction 1`, just replacing every `-` for a blank character. For testing purposes, still on my example, I did 2 almost-equal section headers: **Another Method** and **Another Method 1**. The anchor of the latter header, `#another-method-1`, look-alike our duplicate anchor, and therefore the PDF (or HTML) looks for a header with the `1` by the end, like **Another Method 1**, also replacing the `-` for a blank character. On this second test, both PDF or HTML have worked well, so I think both files are looking exclusively replacing the `-` to a blank character. 

Do you know any way of creating anchors using the section and sub-section header? A way that I could create an anchor like: `#another-method-introduction` for my duplicated **Introduction** section? I think this would be the best solution, given that normally it's not usual to have duplicate headers that also share all its upper sections.

**Comment by yzhang-gh** [comment]
The logic is simple. Link `<a href="#whatever-id">...</a>` searchs for `<h1 id="whatever-id">...</h1>"` (the matching between `href` and `id`).

There is no doubt that Markdown `[link](#whatever-id)` generates HTML `<a href="#whatever-id">link</a>`.

Things are different from Markdown `# Heading` to HTML. Usually, it becomes `<h1 id="heading">Heading<h1>`. When there are duplicated ids, VSCode and GitHub both append a `-1` to the id.

Some other Markdown parsers may have different behaviors. What Markdown renderer are you using?

**Comment by pedroprates** [comment]
Ok, I see.. I'm using the [Markdown PDF](https://github.com/yzane/vscode-markdown-pdf) to render my PDF on VSCode, do you have any suggestions for a different renderer?

**Comment by yzhang-gh** [comment]
I also don't have a good solution (for PDF) now. That is why this extension doesn't provide such a feature (#270).

Personally, I export Markdown to HTML (using this extension) and then use Chrome to print HTML to PDF.

**Comment by pedroprates** [comment]
Ok, thank you!!
