### ISSUE TITLE
Auto open preview makes commenting on Github PR for `.md` files impossible

### ISSUE THREAD

**Issue by ProLoser** [yzhang-gh/vscode-markdown#542]
#### What is the problem?
I am using the Github PullRequests extension for VSCode. When I open a `.md` file a preview auto-opens (this is fine). However when I try to comment on the file, whenever I focus on the inline comment box, the preview pane immediately steals focus away.

Please detect when I'm typing into a PR line comment before re-rendering or stealing focus.

#### How can I reproduce it?
1. Install [Github Pull Requests](https://github.com/Microsoft/vscode-pull-request-github)
2. In the PR browser, select a `.md` file from an open PR.
3. _Markdown Preview should auto-open next to diff_
4. Click the `[+]` button on a line number in the diff to add a comment
5. Click on the textarea to begin writing the comment
6. _Markdown Preview steals focus away from the textarea_

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

It doesn't look like a problem of this extension. (The only thing this extension does is overriding the default Show Preview keybindings.)

Can you disable this extension and see whether the issue is still there?
