### ISSUE TITLE
Hide distracting pieces of Markdown syntax entirely

### ISSUE THREAD

**Issue by alper** [yzhang-gh/vscode-markdown#547]
Would it be possible and/or desired to add a setting to hide markdown syntax in certain cases, say like with the URL element as in this example by [Bear](https://bear.app/):

![Bear 2019-11-04 00-15-13](https://user-images.githubusercontent.com/72429/68093662-36d62a00-fe98-11e9-97ab-35f94c649d78.jpg)

I can think of a couple of other places where this could be interesting but I wanted to know whether something like thas can be considered at all.

**Comment by yzhang-gh** [comment]
There is an feature (#185) that I think is more suitable for VSCode. What's your opinion?

**Comment by alper** [comment]
I'll try out both the things in #185 and fiddle around to see whether something like this is at all possible in vscode.

**Comment by yzhang-gh** [comment]
In case the original post is too long to read, the visual outcome is https://github.com/yzhang-gh/vscode-markdown/issues/185#issuecomment-394168278 (enable `markdown.extension.syntax.plainTheme`)

**Comment by yzhang-gh** [comment]
Feel free to comment if you have more information.

**Comment by alper** [comment]
No, fine. I'll reopen if I have something more concrete.

**Comment by aaaron** [comment]
Hi @alper--curious if you ever got further with this? I followed the Highlight advice and links are grayed, but still find them to be distracting and of notsomuch value in edit pane. Would prefer a Bear-like icon, or full obfuscation until you edit like Org Mode or Roam.

**Comment by alper** [comment]
@aaaron Have not had any time to pursue this.
