### ISSUE TITLE
How to use completion root without relative pathing

### ISSUE THREAD

**Issue by cvharris** [yzhang-gh/vscode-markdown#548]
#### What is the problem?
Can't seem to configure the new `markdown.extension.completion.root` to what I expect. I want to set the path to match how the image will be served on the live site. Since I'm building this using Nuxt, the `static` folder is automatically configured to serve any file in there. I don't want my markdown files in the same folder because I use the Webpack Markdown loader to parse it and template the content before rendering HTML.

When I saw this new setting released I assumed it was to help with this situation. I also tried playing with the `"markdown.extension.print.absoluteImgPath"` setting in conjunction with this but couldn't get anything to change.

This is what the autocompletion looks like to me no matter what my settings:
<img width="541" alt="Screen Shot 2019-11-04 at 9 31 19 AM" src="https://user-images.githubusercontent.com/4013888/68133390-e1c10500-fee5-11e9-99fa-15607730b221.png">

#### How can I reproduce it?
In some project, create one folder that has markdown files and another `static` folder that has images. Mine looks like this:

```
content/
  guide/
    index.md
static/
  img/
    my-pic.jpg
```

Set `"markdown.extension.completion.root": "/static"` or `"static"`, neither makes any difference.

In `index.md` start creating an image `![](`, check the autocompletion path

Expected:  `/img/my-pic.jpg`

Result: `../../static/img/my-pic.jpg`

#### Is there any error message in the console?

No errors

**Comment by yzhang-gh** [comment]
`static` should be okay.

Type `/` right after `![](` and there you go 😉

**Comment by cvharris** [comment]
Ah, I see. So it does work, it just seems like it offers both the relative and rooted paths, and only the rooted paths when you type the '/'. Is it possible to make the root paths the only or default options?

**Comment by yzhang-gh** [comment]
I see the point.

**Comment by yzhang-gh** [comment]
It should be improved in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by cvharris** [comment]
I see it, that will clean up the results, thanks for adding that so quickly! It filters out relative results as soon as you type '/'.
