### ISSUE TITLE
TOC: usual list with links inside a document is replaced with one more Table of Content

### ISSUE THREAD

**Issue by AndreiLiakhavets** [yzhang-gh/vscode-markdown#549]
#### What is the problem?
Usual list inside a document is considered as one more Table of Content and it being completely rewritten on save.

#### How can I reproduce it?
In this markdown:

```
# Dummy1 <!-- omit in toc -->

- [Dummy11](#dummy11)
  - [Dummy node 113](#dummy-node-113)
  - [Dummy node 114](#dummy-node-114)

## Dummy11

Some list:

- here is some text with link to [Dummy node 113](#dummy-node-113). Event in the middle of the text
- here is link to . As well even in the middle

### Dummy node 113

### Dummy node 114
```
![image](https://user-images.githubusercontent.com/43411549/68136430-8adb2000-ff25-11e9-9c83-f0a424505b08.png)

When I insert second link to the list `Some list`, it's being considered as a second TOC:
![image](https://user-images.githubusercontent.com/43411549/68136527-b52cdd80-ff25-11e9-97d6-eb800b1e84fb.png)

After save I will get this:
![image](https://user-images.githubusercontent.com/43411549/68136558-c4ac2680-ff25-11e9-9e41-9544bad314d9.png)

#### Is there any error message in the console?
No errors

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

We need to find a new balance between wrong TOC detection and losing track of a true TOC.

For now, there is a workaround. You can install the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) and place a `<!-- no toc -->` before the list.

**Comment by AndreiLiakhavets** [comment]
Thanks for the option with .

I've read #525. There is an issue when list looks very similar to TOC.
Here is from my point of view a bit different case. Here the list contains a lot of other text. I think it might be quite common case. 
As I understood the generated list never contains a free text(means it contains only link with their description like `[description](link)`). Isn't it?
Maybe it's possible to suppress TOC detection if the list contains additional free text? Or for example with some threshold in the relation length of free text to length of links in order still detect TOC when someone incidentally typed some characters in the TOC. 

It will isolate the issue to much rare cases.

**Comment by yzhang-gh** [comment]
You are right. We have a similar sanity check for issue #304.

It seems that we can make it stricter (Unless the TOC is configured to be plaintext, it shouldn't contain text other than anchor links)

**Comment by yzhang-gh** [comment]
Please try out the latest dev build.

**Comment by AndreiLiakhavets** [comment]
There is an issue in the build. Some underscores are removed from the header texts.

e.g.
```
# Dummy1 <!-- omit in toc -->

- [Dummy11](#dummy11)
- [Dummy12](#dummy12)
- [Dummy12](#dummy12-1)
- [Dummy1_2_adafaasfasf](#dummy12adafaasfasf)

## Dummy11

## Dummy12

## Dummy_1_2

## Dummy_1_2_adafa_asfasf
```
![image](https://user-images.githubusercontent.com/43411549/68220698-790e8100-ffe8-11e9-932b-a1d432df51fe.png)

Please check.
