### ISSUE TITLE
Underscores get removed in TOC

### ISSUE THREAD

**Issue by yzhang-gh** [yzhang-gh/vscode-markdown#550]
There is an issue in the build. Some underscores are removed from the header texts.

e.g.
```
# Dummy1 <!-- omit in toc -->

- [Dummy11](#dummy11)
- [Dummy12](#dummy12)
- [Dummy12](#dummy12-1)
- [Dummy1_2_adafaasfasf](#dummy12adafaasfasf)

## Dummy11

## Dummy12

## Dummy_1_2

## Dummy_1_2_adafa_asfasf
```
![image](https://user-images.githubusercontent.com/43411549/68220698-790e8100-ffe8-11e9-932b-a1d432df51fe.png)

Please check.

_Originally posted by @AndreiLiakhavets in https://github.com/yzhang-gh/vscode-markdown/issues/549#issuecomment-549871015_

**Comment by yzhang-gh** [comment]
An opposite issue #494.

**Comment by AndreiLiakhavets** [comment]
@yzhang-gh thanks for your quick updates.

I want to clarify that I meant only text of the links(`[]` part) in the TOC, not the reference itself. I didn't check references, probably `()` part works as expected.

**Comment by yzhang-gh** [comment]
I see

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
