### ISSUE TITLE
无法换行

### ISSUE THREAD

**Issue by lyg4795** [yzhang-gh/vscode-markdown#554]
使用\<br />无法换行..
应该怎么换行,除了空一行这个方法?

**Comment by yzhang-gh** [comment]
原始的 Markdown 里面需要在句尾加两个空格（段内换行）
VSCode 还可以使用设置 `markdown.preview.breaks` 来改变这个行为

**Comment by lyg4795** [comment]
> 原始的 Markdown 里面需要在句尾加两个空格（段内换行）
> VSCode 还可以使用设置 `markdown.preview.breaks` 来改变这个行为

谢谢,我这边是因为前面的文字中有$,没有转义导致<br/>无效
