### ISSUE TITLE
[Feature Request] Outline Numbering for headings

### ISSUE THREAD

**Issue by Jerksen** [yzhang-gh/vscode-markdown#555]
This isn't an issue, but a feature request. The extension is fantastic, but the only thing missing for me is automatic numbering of headings, that can be updated on Save.

# Use Case 1 - new doc with no numbers
the following document:
```markdown
# Introduction
## Background
```

will have numbers prefixed on save or activation
```markdown
# 1 Introduction
## 1.1 Background
```

# Use Case 2 - update document with existing numbers
the following document will become:
```markdown
# 1 Introduction
## 1.1 Background
## Open Issues
## 1.2 Team Composition
```

will have new numbers added and old numbers changed on save or activation
```markdown
# 1 Introduction
## 1.1 Background
## 1.2 Open Issues
## 1.3 Team Composition
```

The numbers here should match those in the TOC

---

By @yzhang-gh:

#### TODO

- [x] make it more flexible (see https://github.com/yzhang-gh/vscode-markdown/issues/457#issuecomment-632004345)

**Comment by yzhang-gh** [comment]
This is a same feature as #457. I am going to leave this open as you provide some concrete examples.

**Comment by Jerksen** [comment]
Sorry, I did a quick search for duplicates and didn't see any. I'm hoping to find some time to try and help with this in the next few weeks, but don't have any vscode extension experience.

**Comment by ajsjunior** [comment]
This feature could be like **Markdown TOC** extension does.

**Comment by yzhang-gh** [comment]
Please see https://github.com/yzhang-gh/vscode-markdown/issues/457#issuecomment-623103838.

**Comment by dlidstrom** [comment]
This is indeed a very nice feature. However, it will number from 1.x and never reach 2.x, if one wants to follow markdown "rules" to only have a single top-level header. Perhaps, if the top-level header is omitted from toc, then the second level headers could be 1.x, 2.x, etc.

**Comment by yzhang-gh** [comment]
@dlidstrom Thanks for the feedback.

We have many ways to exclude a heading from the TOC (options `toc.levels`, `toc.omittedFromToc` and `<!-- omit in toc -->` comment). I am considering only add numbers to those valid TOC headings. I will take a look this weekend.

**Comment by Huntess** [comment]
Found a bug, when a number gets to two digits, the Add / update section numbers command adds another number. repeatedly

`## 1.9. test 4`
`## 1.10. 1.10. test 5`
`## 1.11. 1.11. test 6`

this happens at any level

`# 14. 14. test 1`
`# 15. 15. test 2`

**Comment by yzhang-gh** [comment]
@Huntess please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). (#701)

**Comment by yzhang-gh** [comment]
<img src="https://user-images.githubusercontent.com/7588612/83320909-33fcb580-a27e-11ea-8785-bce143edb700.gif" alt="numbering" width="610px">

Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by guoquan** [comment]
TOC is not updated while the headings are changed.
However, when I update TOC manually or save the file, it will be updated.
Just the inconsistency before saving makes me a bit nervous 🤣

**Comment by guoquan** [comment]
> @dlidstrom Thanks for the feedback.
> 
> We have many ways to exclude a heading from the TOC (options `toc.levels`, `toc.omittedFromToc` and `<!-- omit in toc -->` comment). I am considering only add numbers to those valid TOC headings. I will take a look this weekend.

Interesting workaround. However, decoupling the two functionality would be more preferable.

**Comment by yzhang-gh** [comment]
> TOC is not updated while the headings are changed.
> However, when I update TOC manually or save the file, it will be updated.

This is by design. They are independent commands. You can undo a single change if any one of them doesn't work as expected.

> However, decoupling the two functionality would be more preferable.

Please provide concrete examples as in this original post. Otherwise it is not very convincing 🤔.

**Comment by guoquan** [comment]
> > TOC is not updated while the headings are changed.
> > However, when I update TOC manually or save the file, it will be updated.
> 
> This is by design. They are independent commands. You can undo a single change if any one of them doesn't work as expected.
> 
> > However, decoupling the two functionality would be more preferable.
> 
> Please provide concrete examples as in this original post. Otherwise it is not very convincing 🤔.

For example, if I want a TOC with the first level title while hoping to have numbering headings from the second level and on.
Something as follows:

- [Lorem ipsum](#)
  - [1. dolor sit amet](#)
  - [2. veri quaestio laboramus](#)
    - [2.1. mea ei](#)
    - [2.2. usu soluta](#)
  - [3. melius ei](#)

**Comment by yzhang-gh** [comment]
@guoquan Thanks. Although I am not very convinced by this example (as a user may want any strange TOC #403), let's see whether other users have a similar request.

---

A common template of using Markdown to write a blog is

```markdown
# Title <!-- omit in toc -->

#### Table of Contents <!-- omit in toc -->

- 1. Real Section 1
  - 1.1. Section 1.1
  ...

## 1. Real Section 1

###  1.1. Section 1.1

...
```

The current implementation is optimized for this case.

**Comment by ozboss** [comment]
Is it possible to deactivate the last point in the numbers? So that the numbering is just like described in the first post.
(e.g. 1.1 instead of 1.1.)

**Comment by yzhang-gh** [comment]
@ozboss Please see #714.

**Comment by gerardbosch** [comment]
Hi there, is it possible somehow to define or set a specific start numbering for auto-generated section numbers?
Instead of starting by `1.`, would it somehow be possible to set it to another number, or a prefix number?

For example, something like `<!-- toc number prefix: 4 -->` and generate then `4.1`, `4.2`...?

**Comment by yzhang-gh** [comment]
@gerardbosch Thanks for the detailed description. I have created a new issue for that.
