### ISSUE TITLE
How to generate TOC ?

### ISSUE THREAD

**Issue by GreatFireWall** [yzhang-gh/vscode-markdown#557]

**Comment by yzhang-gh** [comment]
`Ctrl + Shift + P` and https://github.com/yzhang-gh/vscode-markdown#available-commands

**Comment by GreatFireWall** [comment]
Thanks.

**Comment by cstrempfer** [comment]
@yzhang-gh That shortcut isn't mentioned in the ReadMe. Or am I missing something?
