### ISSUE TITLE
建议支持插入当前时间日期

### ISSUE THREAD

**Issue by powerdong** [yzhang-gh/vscode-markdown#558]

**Comment by yzhang-gh** [comment]
这个跟 Markdown 并没什么关系，很多输入法就可以

比如 Windows 10 自带的微软拼音
![image](https://user-images.githubusercontent.com/7588612/69489286-3d146080-0eb0-11ea-9be4-2495fa16013b.png)

**Comment by powerdong** [comment]
@yzhang-gh  哈哈哈  好吧 谢谢

**Comment by EricZs1995** [comment]
> 这个跟 Markdown 并没什么关系，很多输入法就可以
> 
> 比如 Windows 10 自带的微软拼音
> ![image](https://user-images.githubusercontent.com/7588612/69489286-3d146080-0eb0-11ea-9be4-2495fa16013b.png)

厉害

**Comment by LittleMan168** [comment]
Well, thanks.
