### ISSUE TITLE
On alt + shift + right I get Running the contributed command: 'markdown-table-formatter.moveColumnLeft' failed.

### ISSUE THREAD

**Issue by A-Atrash** [yzhang-gh/vscode-markdown#559]
I am very much used to use alt+shift+right/left (Mac) to select a whole word, but recently VS stated showing this message whenever I try that:
`Running the contributed command: 'markdown-table-formatter.moveColumnRight' failed.`
I removed it and removed all its packages and installed it again, but no gain.
Any idea?

**Comment by yzhang-gh** [comment]
You probably have installed another Markdown extension.

**Comment by A-Atrash** [comment]
@yzhang-gh Correct! I removed all formatters and it works now. Will reinstall what I want. Thanks!
