### ISSUE TITLE
figures in Base64 can't be printed into HTML

### ISSUE THREAD

**Issue by ganxy1028** [yzhang-gh/vscode-markdown#560]
MD 文件中的 Base64 图片无法打印在HTML中，HTML 中的图片链接将 Base64 码识别为了MD文件夹下的图片绝对路径。

Figures in Base64 can't be printed into HTML, because the HTML recognises the Base64 code as the paths of figure under the folder of .MD file, instead of the figure itself.

sample: [test.txt](https://github.com/yzhang-gh/vscode-markdown/files/3886562/test.txt)

![image](https://user-images.githubusercontent.com/26629457/69540173-fa8e7900-0fc0-11ea-9ff0-95a5a29c3d6c.png)

**Comment by yzhang-gh** [comment]
你这个图片在我笔记本上用 VSCode 预览就没反应……（整个 Markdown 插件没动静，包括官方的）

我自己找了个图片试了下没发现问题，你也换个小点的图片试试？
（顺便告诉我下你的 print 相关的设置）

**Comment by ganxy1028** [comment]
是我自己的问题，忘了设置打印的时候转为base64。抱歉，我疏忽了

**Comment by yzhang-gh** [comment]
😅

**Comment by ganxy1028** [comment]
如果这个选项默认的选择是True的话感觉会好一点。打印成HTML之后通常都是要挪走或者发给别人的。

**Comment by yzhang-gh** [comment]
关于默认设置就见仁见智了，有的人就不喜欢. 反正设置同步也方便（VSCode 官方也马上会统一一下设置同步的功能）
