### ISSUE TITLE
Outdent only ever indents

### ISSUE THREAD

**Issue by cvharris** [yzhang-gh/vscode-markdown#561]
#### What is the problem?

Whenever I try to outdent (Shift + Tab) anywhere in a markdown file I only ever add more tabs. This only happens when this extension is installed and I'm editing a markdown file. I can't find a setting that allows me to control this behavior but it seems that the tab key's default behavior is overridden and does not check for Shift + Tab.

This looks like it's a duplicate of #230 but this doesn't work anywhere in a Markdown file, even in Fenced Code.

#### How can I reproduce it?

1. Open a *.md while Markdown All in One is installed
2. Write some content then indent it a little (Highlight, Tab, Tab...)
3. Try to outdent same content (Highlight, Shift + Tab, Shift + Tab...)
4. Now content is tabbed 4 times instead of set back to the left edge
5. Disable Markdown All in One
6. Repeat steps 2-3
7. Content is correctly set back to left edge

#### Is there any error message in the console?

No errors in the Dev Tools. Versions:

VSCode Version: 1.40.1
OS Version: Mac OS Mojave
Markdown All In One Version: 2.5.1

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) now.

**Comment by cvharris** [comment]
That makes sense. I think outdent also only ever works if the cursor is positioned before the first non-space character. Maybe that helps differentiate it between expand abbreviation

**Comment by yzhang-gh** [comment]
Fixed now.

**Comment by cvharris** [comment]
Yes! Awesome, just pulled it down and tested it. Thank you for the quick turnaround!
