### ISSUE TITLE
Math not exported to pdf

### ISSUE THREAD

**Issue by pypardo** [yzhang-gh/vscode-markdown#562]
### What is the problem?

When using math formula
$$ something $$

It works fine on preview, but math formula is not exported in pdf, just the raw value with the $$ $$

#### How can I reproduce it?

Juste type a simple formula

$$1+1=2$$

Then export pdf

#### Is there any error message in the console?

No

Regards

**Comment by yzhang-gh** [comment]
Actually, this extension doesn't provide such a feature (exporting to PDF). You probably have used another extension.
