### ISSUE TITLE
How can we place source code in tables?

### ISSUE THREAD

**Issue by DBJDBJ** [yzhang-gh/vscode-markdown#563]
#### What is the problem?
How can we place source code in tables?
MD table does not work, I have also tried HTML table but that simply does not work. 
#### How can I reproduce it?
Easy. Just try to place source code in a table. MD or HTML.
#### Is there any error message in the console?
Not that I know of.

**Comment by yzhang-gh** [comment]
What do you mean by source code?

If it is inline code, just use <code>\`code\`</code>.

If it is a multi-line code block, you can use `<pre><code>multi-line code</code></pre>` (use `<br>` for line break in Markdown tables, and real line break for HTML tables)

**Comment by DBJDBJ** [comment]
What do you mean by source code?

**Comment by yzhang-gh** [comment]
Feel free to reopen if you have more questions

**Comment by DBJDBJ** [comment]
Everybody knows what is "source code" in the context of these issues pages. So I asked you "what do you mean by source code"? 

Since it seems you do not understand the expression "source code".

I have no more questions, there is a workaround, which you have not provided.

**Comment by yzhang-gh** [comment]
Don't get me wrong. I was asking "what (specific type of) source code do you mean". Inline code? or code block? They are what we have in Markdown and obviously *they are different*. Then I also gave the two ways respectively.

I have tried being nice but I am curious why you seemed to be offended by "What do you mean by source code". Interesting.
As an open-source extension maintainer, I don't owe you anything. And your question has nothing to do with my extension (so far).

If you have found other workaround, good.

**Comment by DBJDBJ** [comment]
The solution is not very elegant but it works.

A. HTML table
B. one empty line before code block opening

For example:

![screen](https://snipboard.io/0iVBQD.jpg)

HTH

**Comment by yzhang-gh** [comment]
That makes sense. If we don't add an empty line the Markdown code block will be treated as a part of the HTML and thus won't be parsed.

**Comment by DBJDBJ** [comment]
Now. The TD widths are all over the place ...  Some CSS is "ruling" of course... is there a way, I add my own CSS, just to control the tables, not replacing the default one ? 

I know I can replace the whole CSS and set "bootstrap" for example, but that changes everything 
of course ...  I need to be able to control these tables layout ... style attribute seems not to work.

**Comment by yzhang-gh** [comment]
The `style` attribute should work (or simply `width` attribute). You can paste your code snippet so I can test. (I guess you have been using a Markdown theme other than the default one?)

![image](https://user-images.githubusercontent.com/7588612/69907788-10fc6080-1417-11ea-838f-62fea2eaa5ad.png)

![image](https://user-images.githubusercontent.com/7588612/69907804-4012d200-1417-11ea-8595-59008f33ba36.png)

**Comment by DBJDBJ** [comment]
my outcome is [this](https://github.com/DBJDBJ/dbj-valstat/blob/master/utils/markdown_sampler.md)

the point is Github's view is what matters. not the visual code view. what can be done about that?  The web site using Hugo? I am doing it [here](https://dusanjovanovic.org). 

but this has to be just a github collection of md documents. yes, I was using stackedit in the past but and of course Visual  Code + github, is far superior.

I am using default Markdown Theme. My markdown sample is attached. TD valign works but just in Visual Code ... style + width too ... but Github view is not showing right?

[markdown_sampler.zip](https://github.com/yzhang-gh/vscode-markdown/files/3908999/markdown_sampler.zip)

**Comment by yzhang-gh** [comment]
I can confirm it doesn't work on GitHub (while it does work inside VSCode).

Then I found

> The HTML is sanitized, aggressively removing things that could harm you and your kin—such as `script` tags, inline-styles, and `class` or `id` attributes.
> — https://github.com/github/markup

This is bad. It looks like there is no workaround for GitHub...
