### ISSUE TITLE
How to disable double click to exit when preview file?

### ISSUE THREAD

**Issue by ydam24** [yzhang-gh/vscode-markdown#568]
How to disable double click to exit when preview file?
Could provide any config?

**Comment by yzhang-gh** [comment]
You are probably referring to a feature provided by VSCode itself (https://code.visualstudio.com/docs/languages/markdown#_editor-and-preview-synchronization)

> Additionally, double clicking an element in the Markdown preview will automatically open the editor for the file and scroll to the line nearest the clicked element.

It can be disabled by `markdown.preview.doubleClickToSwitchToEditor`

**Comment by ydam24** [comment]
Great!Thanks a lot!Really useful!
