### ISSUE TITLE
Command 'markdown.extension.onEnterKey' not found, again

### ISSUE THREAD

**Issue by sirgru** [yzhang-gh/vscode-markdown#569]
For the problem like "command '...' not found", please try to
1. wait for a few seconds after you open a Markdown file for the first time => waited several minutes.
2. doesn't work? -> update vscode => On the latest version.
3. doesn't work? -> reinstall this extension => It is uninstalled and it still happens.
4. still doesn't work? 😵 -> please open the developer tools to see whether there is any error message, and then paste it below. => No error in the console.

Is there some kind of extension cache, which I can clear to get rid of it? In the past I've had it happen and it would fix itself after a couple of VS Code restarts.

**Comment by yzhang-gh** [comment]
I haven't seen/heard this "not found" issue for a long time. Technically, there should be a proper fix already.

I am wondering whether the extension installation is corrupted. Can you do these one more time:
- uninstall this extension
- restart (close and reopen) VSCode (**important**. VSCode only removes extension on the next start)
- install this extension (no reload is needed) and test

**Comment by sirgru** [comment]
I managed to resolve the issue on my end. 

I uninstalled the extension, and also deleted the extension folders on disk, which were still present. In there I found folders "1.7.3" and "2.3.1", so perhaps this was part of the issue. This didn't help, and in key binding there were still some `markdown.extension.onXXX` bounds somehow. I re-installed the extension again and now the folder is "2.6.0" and now it works.

**Comment by xiphiasphotography** [comment]
6 years later, still having the same issues:
command 'markdown.extension.onEnterKey' not found
command 'markdown.extension.onShiftEnterKey' not found
command 'markdown.extension.onBackspaceKey' not found
command 'markdown.extension.onShiftBackspaceKey' not found
etc...

Fixed the issue by uninstalling the yzhang.markdown-all-in-one extension. Now everything works fine.
