### ISSUE TITLE
bold/italic shortcut doesn't work

### ISSUE THREAD

**Issue by zachvalenta** [yzhang-gh/vscode-markdown#571]
#### What is the problem?

The default shortcuts for bold and italic https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts do not work for me.

I don't think it's conflicting with anything in my `keybindings.json`:

```json
[
       { "key": "cmd+r", "command": "workbench.action.gotoSymbol" },
    {
        "key": "cmd+alt+enter",
        "command": "editor.action.openLink"
    },
    {
        "key": "shift+cmd+k",
        "command": "workbench.action.terminal.kill"
    },
    {
        "key": "alt+cmd+v",
        "command": "md-shortcut.toggleLink",
        "when": "editorTextFocus && markdownShortcuts:enabled"
    },
]
```

#### How can I reproduce it?

I'm using version 1.41.0 of VS Code. I disabled all other extensions during debug.

#### Is there any error message in the console?

There was no error message in the console. I'm using version 2.6.1 of the extension. I uninstalled and reinstalled the extension in the process of debugging.

**Comment by yzhang-gh** [comment]
That's strange. Can you open the keyboard shortcuts page (at right bottom corner) and check whether the commands are listed?

![image](https://user-images.githubusercontent.com/7588612/70807148-dc65ad00-1df7-11ea-9d19-e5cc69f1cc55.png)

Try something like "toggle bold", "ctrl+b" etc.

**Comment by zachvalenta** [comment]
Good tip. I did, and this is what I saw:

![Screen Shot 2019-12-13 at 9 50 16 AM](https://user-images.githubusercontent.com/11388735/70808600-02eefe00-1d8e-11ea-9b67-545b97aab073.png)

![Screen Shot 2019-12-13 at 9 47 34 AM](https://user-images.githubusercontent.com/11388735/70808605-097d7580-1d8e-11ea-8d18-46763d1f5bc2.png)

A quick grep of the `.vscode/extensions` directory suggests the `ctrl b` shortcut comes from the [official Python extension](https://github.com/Microsoft/vscode-python).

![Screen Shot 2019-12-13 at 9 50 22 AM](https://user-images.githubusercontent.com/11388735/70808690-3893e700-1d8e-11ea-8e04-e14eae678fc0.png)

**Comment by zachvalenta** [comment]
Strangely enough, `cmd i` and `cmd b` work for italic and bold, despite not being the [stated defaults](https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts).

**Comment by yzhang-gh** [comment]
OK, I know the reason now. You are using a Mac, whose `cmd` usually acts like `ctrl` on Windows 😂 (like `cmd c` vs. `ctrl c` -- copy)

**Comment by zachvalenta** [comment]
Gotcha, knew it had to be something simple. Much appreciated.
