### ISSUE TITLE
undoing bold/italic throws error using Vim extension

### ISSUE THREAD

**Issue by zachvalenta** [yzhang-gh/vscode-markdown#572]
#### What is the problem?

Using the macOS defaults for bold/italic and then immediately undoing that action causes the [VS Code Vim](https://github.com/VSCodeVim/Vim) extension to throw an error.

Happy to move this issue to the VS Code Vim repo, I just haven't seen this error from undoing anything else and figured it might be possible that property mentioned in the error message (`.getTime`) was not being set by VSCode-Markdown.

![Screen Shot 2019-12-13 at 2 53 36 PM](https://user-images.githubusercontent.com/11388735/70828293-1bc0d900-1db9-11ea-89c5-64139e902524.png)

#### How can I reproduce it?

On macOS, bold or italicize a word (`cmd b` or `cmd i`) and then undo using VS Code Vim (`u`)

**Comment by yzhang-gh** [comment]
Thanks. However, I have no idea why this happens. Maybe you can ask for more info from the Vim repo first.

**Comment by zachvalenta** [comment]
This was indeed a VS Code Vim thing https://github.com/VSCodeVim/Vim/issues/4381
