### ISSUE TITLE
TOC is broken for headings with double quotes in them (")

### ISSUE THREAD

**Issue by dorian-marchal** [yzhang-gh/vscode-markdown#575]
## What is the problem?

Automatic TOC generation doesn't work for headings with double quotes in them.

For example, this heading:

```markdown
### Foo - "bar"
```

Generates this entry in the TOC:

```markdown
- [Foo - &quot;bar&quot;](#foo---quotbarquot)
```

While I think it should be (at least with Github compatibility mode enabled):

```markdown
- [Foo - &quot;bar&quot;](#foo---bar)
```

#### How can I reproduce it?

Add this heading to your document:

```markdown
### Foo - "bar"
```

And generates the TOC.

**Comment by yzhang-gh** [comment]
Thanks for the report. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by dorian-marchal** [comment]
Thanks!
