### ISSUE TITLE
Allow specifying headings omitted from ToC in VSCode settings

### ISSUE THREAD

**Issue by dorian-marchal** [yzhang-gh/vscode-markdown#576]
It would be nice to have a VSCode setting to ignore some headings from TOC without "polluting" the Markdown file for those who don't use this extension.

`<!-- omit in toc -->` is a good option (thank you for that. :+1:), but it doesn't scale when every team members don't use the same editor (imagine if every extension used it own set of file annotations).

It could be some list of headings (per project file), maybe like this:
```json
{
  "omittedInToc": {
    "README.md": [
      "# Project Name"
    ],
    "docs/my_doc.md": [
      "# Introduction",
      "## Summary"
    ]
  }
}
```

**Comment by yzhang-gh** [comment]
Makes sense

**Comment by dorian-marchal** [comment]
I created a PR for this, here: https://github.com/yzhang-gh/vscode-markdown/pull/580

It would be nice if you can take a look at it when you have some time. :+1:

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Let's track this in this thread https://github.com/yzhang-gh/vscode-markdown/issues/723#issuecomment-811923635
