### ISSUE TITLE
Synchronized scrolling should not move the editor side, only the preview side

### ISSUE THREAD

**Issue by jeanrajotte** [yzhang-gh/vscode-markdown#577]
#### What is the problem?
I think it's because of a large table that keeps being re-rendered in the preview pane. As I type, the editor side keeps scrolling down.

#### How can I reproduce it?

Create a large table and keep changing it.

#### Is there any error message in the console?

nope

**Comment by jeanrajotte** [comment]
p.s. I think this only happens when the rendered table is visible in the preview pane and I'm editing the table or below the table. If it's not (scrolled up above the current section or below the current editing region) the behaviour does not happen.

**Comment by yzhang-gh** [comment]
Actually, this is provided by VSCode itself.
(https://code.visualstudio.com/docs/languages/markdown#_editor-and-preview-synchronization)

As far as I know, there is an option for this feature. If you have further suggestions, feel free to report to the VSCode team.

**Comment by jeanrajotte** [comment]
Gotcha! Thanks for the quick and clear response.
