### ISSUE TITLE
extension causes VS Code to slow significantly

### ISSUE THREAD

**Issue by zachvalenta** [yzhang-gh/vscode-markdown#578]
#### What is the problem?

Editing in VS Code slows down significantly when I have Markdown All in One enabled, especially on file sizes larger than 2k LOC.

#### How can I reproduce it?

I was following an issue on perf problems in the main VS Code repo https://github.com/microsoft/vscode/issues/87021 when I thought to go through my extensions. When I disabled Markdown All in One, VS Code regained it's normal editing speed.

I checked some potentially related issues https://github.com/yzhang-gh/vscode-markdown/issues/444 but the `cpuprofile.txt` file they mention seems to have changed its file path since those tickets were opened.

**Comment by yzhang-gh** [comment]
This is possible. Some features of this extension may cause lag. Can you provide a sample file so I can pinpoint which features to blame?

**Comment by zachvalenta** [comment]
> This is possible. Some features of this extension may cause lag. Can you provide a sample file so I can pinpoint which features to blame?

Happy to oblige -> https://gist.github.com/zachvalenta/7657dfb4c60eb7fa2c5f80659cd3ca7c

**Comment by yzhang-gh** [comment]
Fun fact: We have performance optimization for large files (more than 128 KB), and your test file is 112 KB... If you keep writing and suddenly you will find VSCode get smoother 🤣.

I'm going to change the threshold to 50 KB.

**Comment by yzhang-gh** [comment]
Available in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by zachvalenta** [comment]
> Fun fact: We have performance optimization for large files (more than 128 KB), and your test file is 112 KB... If you keep writing and suddenly you will find VSCode get smoother 🤣.
> 
> I'm going to change the threshold to 50 KB.

Very cool stuff. 👍

Also, I noticed this slowdown seems particular to VS Code version 1.41 i.e. the most recent build; I have 1.40.2 on my work machine and don't see any slowdown on larger files, so the root cause may have as much or more to do with VS Code than Markdown All in One (1.41 also broke another extension I use, albeit in a different way).
