### ISSUE TITLE
drag-and-drop reordering of headings in outline

### ISSUE THREAD

**Issue by lemonkiller** [yzhang-gh/vscode-markdown#58]
![1](https://user-images.githubusercontent.com/9989574/33411501-0aff8e82-d5c1-11e7-9b13-868f30f56052.gif)

**Comment by neilsustc** [comment]
I am afraid it is not possible given current vscode APIs. (related #36)

**Comment by yzhang-gh** [comment]
Closing as it is not possible in the near future.
