### ISSUE TITLE
[Feature Request] Html Print Setting : Absolute File Links

### ISSUE THREAD

**Issue by bcompagnat** [yzhang-gh/vscode-markdown#581]
#### What is the problem?
When I create a Markdown file and link some local files (same repo) the links are broken when printing to HTML.

#### How can I reproduce it?
Insert a relative link to another markdown file that is located on the same Repo.

#### Suggestion
Absolute path should be created for files links when printing to HTML. Maybe by putting another option like absolute path for images. Also, if the printing is activated and you link another MD file, maybe the absolute path could point to another HTML.

***If its something with interest, I am ready to do it, I already have it implemented on my side. Its just a matter of what settings should look like and if it could be useful for others.***

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

May I ask whether you would like to export HTML with absolute external file links?

If you are hosting the files with a web server, then absolute paths are likely to break.

If you just want _a local document_ in the form of HTML, using absolute file paths doesn't help much.
(Images are embedded when you open the HTML, but file links are... just links.)

**Comment by bcompagnat** [comment]
Yes I kind of confuse myself with my needs.. Its probably not worth it for anyone else. I want other readers of my file to be able to access links from internal shared location. 

We can close this request.
