### ISSUE TITLE
编辑含有大量 `` 及表格的文件存在严重的性能问题

### ISSUE THREAD

**Issue by liangjiancang** [yzhang-gh/vscode-markdown#582]
其实也没多大，超过五百行就已经很明显了，按个backspace都要两三秒才能响应。怀疑是跟 `` ` ` `` 代码块以及表格有关，因为另一个七八百行但 `` ` ` `` 和表格少得多的文件却没有多大感觉。

重现：开个空白的文件，复制粘贴 `` `String s = "s";` `` 个五百次，再编辑试试看……

**Comment by liangjiancang** [comment]
关闭 `markdown.extension.syntax.decorations` 后情况有所改善，但较完全禁用插件仍有明显的卡顿。
能否增加一个选项，禁用那些涉及实时处理的功能，只保留像格式化、目录这样的基本功能；或者是增加临时禁用/开启插件所有功能的命令。

**Comment by yzhang-gh** [comment]
目前在大于 128 KB 的文件下会自动禁用 decorations（开发版为 50 KB，见 #578）

看你的说法仍然会有性能问题，这就需要具体分析了. 最好能提供一个测试文件

**Comment by liangjiancang** [comment]
> 目前在大于 128 KB 的文件下会自动禁用 decorations（开发版为 50 KB，见 #578）
> 
> 看你的说法仍然会有性能问题，这就需要具体分析了. 最好能提供一个测试文件

我描述一下具体现象吧。

1. 打开侧边预览，快速输入中文（英文不明显），可以使用粘贴一段中文的方式来重现。
2. 预览与实际内容会有一段明显的延迟。
3. 在预览刷新至与实际内容相同这段时间内，如果按 backspace，编辑器会卡住直到预览刷新完毕。
4. 刷新完毕后，编辑器才会执行 backspace 的处理，也有一定概率 backspace 会被直接吞掉。

如果关闭插件，虽然预览的延迟还在，但延迟时间内按 backspace 编辑器会马上执行处理，不会卡住。

要重新的话，把下面的内容重复即可（在我电脑上到 5000 行左右效果就很明显了）。把文件搞出来以后，在最后面按上面说的，打开侧边预览，再快速粘贴一小段中文数次，然后立即按 backspace。

```md
`文字文字文字文字文字文字文字文字文字文字文字文字`
`文字文字文字文字文字文字文字文字文字文字文字文字`
`文字文字文字文字文字文字文字文字文字文字文字文字`
`文字文字文字文字文字文字文字文字文字文字文字文字`
`文字文字文字文字文字文字文字文字文字文字文字文字`
(more)
```

**Comment by yzhang-gh** [comment]
我电脑上并不能重现（偶尔有停顿是真的停顿不是卡）

![lag](https://user-images.githubusercontent.com/7588612/71302514-aa9baa00-23e6-11ea-9658-63087e7cec52.gif)

5000 行的时候文件大小已经是 300+ KB 了，只要你切换过标签页，decoration 就会被禁用（下图是没被禁用时的效果）

<img src="https://user-images.githubusercontent.com/7588612/71302548-1aaa3000-23e7-11ea-8abb-89b199d5049d.png" alt="cecoration" width="114px">

（另外预览的延迟就和插件无关了）

**Comment by yzhang-gh** [comment]
想起来几个 VSCode 的设置，我个人是把 `markdown.preview.scrollEditorWithPreview` 和 `markdown.preview.scrollPreviewWithEditor` 禁用了的

**Comment by Lemmingh** [comment]
我认为，这个问题的关键是**文档的行数**，其他方面（文档总大小、语法装饰）都是次要的。

我进行了一组测试，如下。

## 准备

生成三个文件

* `caseSL.md` 大小 50 000 bytes，由 `1234567890` 重复 5000 次得到
* `caseML.md` 大小 50 000 bytes，由 `123456789` 重复 5000 **行**得到
* `caseE.md` 大小 5 000 bytes，由*空行*重复 5000 **行**得到

我使用 PowerShell 生成它们

```powershell
'1234567890'*5000 | Out-File 'caseSL.md' -Encoding ascii -NoNewline
"123456789`n"*5000 | Out-File 'caseML.md' -Encoding ascii -NoNewline
"`n"*5000 | Out-File 'caseE.md' -Encoding ascii -NoNewline
```
## 内容

关闭其他扩展，打开一个空的 VS Code 窗口。

将光标置于文档末尾，使用以下 3 种方式敲击 <kbd>Enter</kbd> 或 <kbd>Backspace</kbd>

* 单击
* 200 ms/次，连续 30 次，共计 6 s
* 500 ms/次，连续 20 次，共计 10 s

分别进行以下 3 种观察

1. 使用 **Windows 任务管理器** 观察
2. 使用 **Process Explorer** 观察
3. 使用 **Extension Profiler** (**Running Extensions** > **Start Extension Host Profile**) 记录

## 结果

在 `caseSL.md` 时：CPU 负载跟编辑其他小文件时没有区别 (< 5%)。

在 `caseML.md` 时：单次击键后，可见 VS Code 的 CPU 负载明显升高约 3 s。连续击键出现明显的延迟，extensionHost 消耗 CPU > 20%。此扩展占用了 profile 期间几乎所有 CPU 时间，甚至 unresponsive。

在 `caseE.md` 时：与 `caseML.md` 类似，但症状较轻。

## 环境

### VS Code

* Version: `1.41.1 (system setup)`
* Commit: `26076a4de974ead31f97692a0d32f90d735645c0`
* Date: `2019-12-18T14:58:56.166Z`
* Electron: `6.1.5`
* Chrome: `76.0.3809.146`
* Node.js: `12.4.0`
* V8: `7.6.303.31-electron.0`

### Markdown All in One

* Version: `2.6.1`

### System

* Windows: `Windows 10 Pro, Version 1909, Build 10.0.18363.535, 64-bit`
* CPU: `Intel Core i5-6300U CPU @ 2.40GHz, 2496 Mhz, 2 Core(s), 4 Logical Processor(s)`
* Total Physical Memory: `7.93 GB`
* Available Physical Memory: `2.22 GB`
* Total Virtual Memory: `17.8 GB`
* Available Virtual Memory: `9.13 GB`
* Power mode: `Best performance`

## 分析

我目前比较怀疑 `TextDocument.getText()`。

在 `onEnterKey()` 和 `onBackspaceKey()` 中，`isInFencedCodeBlock()` 和 `mathEnvCheck()` 比较显眼，而其他的东西似乎都不至于引起这种差异。

这两个函数都调用了 `getText()`，虽然目前没查到它的具体实现🤦，但我猜测，可能是把文档切成数组再连接起来。

在我的测试中，每击键一次，会调用 `getText()` 来**扫全文 3 次**。如果猜测成立，那么，**在处理行数很多的文件时，这会造成巨大的开销**，也就能解释 CPU 高消耗。

希望能有人去验证一下，若确实如此，除了这个扩展需要想办法 workaround，也有必要向 VS Code 反馈。（话说最近这段时间，VS Code 那边有关 performance 的 issue 还挺多😂）

**Comment by yzhang-gh** [comment]
感谢详细的测试.

这些极端情况可以帮助我们了解哪里可以优化. 不过正常使用中很难用到 5000 行的 Markdown 文件，所以这个性能问题暂时还不急，留待以后考虑.
