### ISSUE TITLE
Change in TOC generation behavior with `inline code`

### ISSUE THREAD

**Issue by GalenWong** [yzhang-gh/vscode-markdown#584]
#### What is the problem?

In previous version 2.5.1 of the plugin, the behavior of TOC generation with inline code was 

```md
- [`code`](#code) 

## `code`
```

With an update to 2.6.0, the behavior is

```md
- [code](#code) 

## `code`
```

Notice the TOC generated does not have the back-tick inline code marker. Since I cannot find specific discussion in the CHANGELOG and in the issues, I would like to ask if the change was intentional, or accidental. 

#### How can I reproduce it?

Install version 2.5.1 and 2.6.0 to see the difference.

**Comment by yzhang-gh** [comment]
Thanks for the report.

The change was motivated by #515, #528. I feel it might be better to keep the Markdown syntax like bold, italic and code span but remove syntax like `[text](link)` etc.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
