### ISSUE TITLE
Fixing generated HTML in table of contents

### ISSUE THREAD

**Issue by dylankb** [yzhang-gh/vscode-markdown#585]
#### What is the problem?

Perhaps this is a feature and not a bug, but recently I encountered an issue where creating a table of contents that contained ordered list items caused the table of contents to generate HTML for those ordered items in the ToC. I solved this issue by adding `"markdown.extension.toc.orderedList": true,` in my settings. Perhaps this will be useful for someone coming in from a Google search.

#### How can I reproduce it?

Create a markdown document with ordered elements.

```
# One

# 2) Two

# 3) Three
```

Then run `Markdown All In One: Create Table of Contents`. The ToC will look like this

```
- [One](#one)
  - [<ol start="2">
<li>Two</li>
</ol>](#ol-start%222%22-litwoli-ol)
  - [<ol start="2">
<li>
<ul>
<li>One</li>
</ul>
</li>
</ol>](#ol-start%222%22-li-ul-lioneli-ul-li-ol)
```

#### Is there any error message in the console?

Not that I see.

**Comment by dylankb** [comment]
If this is a known feature and/or doesn't need to be documented then feel free to close.

**Comment by dylankb** [comment]
Ok, so two things:

1) I thought I had solved this issue but I did not. It's still happening.
2) This looks like basically the same issue that was reported [here](https://github.com/yzhang-gh/vscode-markdown/issues/567). I'm running 2.6.1 of Markdown All In One and according to the changelog that should have fixed this issue.

One thing that I'll add is the table of contents that is generated always has the `Table of Contents (out of date)` note preceding it. When saving the document the ToC appends a new copy of itself below. For example, after saving twice my ToC looks like this.

```
- [One](#one)
  - [<ol start="2">
<li>Two</li>
</ol>](#ol-start%222%22-litwoli-ol)
  - [<ol start="3">
<li>Three</li>
</ol>](#ol-start%223%22-lithreeli-ol)
<li>Two</li>
</ol>](#ol-start%222%22-litwoli-ol)
  - [<ol start="3">
<li>Three</li>
</ol>](#ol-start%223%22-lithreeli-ol)
````

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This is tricky. In short, some Markdown syntax needs to be stripped in the heading text, e.g. from `[text](link)` to `text`. And it can be very complex and simple regex may not be enough. So we have used a Markdown renderer to "extract" plain text and caused new problems like this...

I have pushed a fix and this should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). Please try it out.

**Comment by dylankb** [comment]
Great, that looks like it fixed the issue!
