### ISSUE TITLE
插件自动补全功能使用户自定义的markdown自动补全代码片段失效

### ISSUE THREAD

**Issue by hoooJerry** [yzhang-gh/vscode-markdown#586]
#### What is the problem?

插件自动补全功能使用户自定义的markdown自动补全代码片段失效
this extension stops users' code snippets function.

我创建了一个markdown文件的自动补全文件markdown.json,希望添加一些个性化的补全方案,但是测试之后发现是插件阻止了我的自定义补全行为.

I created an auto-completion file markdown.json for the markdown file. I hope to add some personalized completion schemes, but after the test, I found that the plug-in blocked my custom completion behavior.

#### How can I reproduce it?

希望能在下一版本中不要使用户自定义补全与插件的自定义补全功能冲突,或许可以添加一个自定义补全功能,就像user snippets那样.
It is hoped that in the next version, the user-defined completion will not conflict with the plug-in's self-defined completion function. Perhaps a user-defined completion function can be added, just like user snippets

#### Is there any error message in the console?

no

**Comment by yzhang-gh** [comment]
> 但是测试之后发现是插件阻止了我的自定义补全行为

能详述一下禁用插件之后，你期望中的补全行为是怎样吗？我没有用 user snippets，不是很清楚你的问题是什么

**Comment by hoooJerry** [comment]
你好，对不起报告了错误的issue。后来发现这似乎是vscode的bug，我已提交官方，等收到回复再和您探讨！谢谢！

**Comment by yzhang-gh** [comment]
👌
