### ISSUE TITLE
File path completion should replace space in filename with "%20" instead of "&#32;"

### ISSUE THREAD

**Issue by uasi** [yzhang-gh/vscode-markdown#589]
#### What is the problem?

File path completion that appears in `[text](path)` replaces space in filename with `&#32;`. It's an HTML entity that represents a space character, but space in URL should be encoded as `%20`.

#### How can I reproduce it?

- in a workspace create "foo.md" and "bar baz.md"
- open "foo.md"
- type `[x]()` (suggestions appear)
- complete `[x](bar&#32;baz.md)`
- cmd+click that `bar&#32;baz.md`, nothing happens
- replace `[x](bar&#32;baz.md)` with `[x](bar%20baz.md)`
- cmd+click `bar%20baz.md` now opens "bar baz.md"

(I used Visual Studio Code 1.41.1, Markdown All in One 2.6.1, and macOS 10.14.6)

#### Is there any error message in the console?
N/A

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by uasi** [comment]
Thank you for the quick response!
