### ISSUE TITLE
List autocomplete does not work if there is a code block above

### ISSUE THREAD

**Issue by DreamerDeLy** [yzhang-gh/vscode-markdown#593]
List autocomplete does not work if there is a code block above with language mark.

Example
```
* Fixed bug
* Fixed bug <- there autocomplete working

-```
SoftwareSerial mainSerial(SERIAL_RX, SERIAL_TX); // RX TX
-```

* List item text
* List item <- there autocomplete working

-```c++
SoftwareSerial serialSensor(SERIAL_RX, SERIAL_TX, false, 512); // RX TX
-```

**.10**
* Fixes
<- there don't working
```

#### Is there any error message in the console?

There are no errors in the console.

**Comment by yzhang-gh** [comment]
Looks like it works here.

![list](https://user-images.githubusercontent.com/7588612/72494841-11827680-3860-11ea-8172-127e8b321f19.gif)

It is possible that the code blocks may affect the list continuation. But the code snippet above doesn't seem to be a minimal working example.

And just out of curiosity, what is the purpose to use <code>-```</code> for code blocks 😳

**Comment by DreamerDeLy** [comment]
> Looks like it works here.
> 
> ![list](https://user-images.githubusercontent.com/7588612/72494841-11827680-3860-11ea-8172-127e8b321f19.gif)
> 
> It is possible that the code blocks confuse the list continuation. But the code snippet above doesn't seem to be a minimal working example.
> 
> And just out of curiosity, what is the purpose to use `` -``` `` for code blocks 😳

I inserted `-` before ``` for not to finish the code block from github. In reality, I don't use `-`

**Comment by yzhang-gh** [comment]
You can use HTML `pre` tag to do this on GitHub.

```
<pre>```
some code
```</pre>
```

**Result**
<pre>```
some code
```</pre>

---

I will take a look later.

**Comment by DreamerDeLy** [comment]
Ok, thanks.

I also recently noticed that this does not happen when I use C instead of C++. Also works with others I've tried (python, r, ruby, php, java).
Maybe it depends on the plugins or themes installed?

**Comment by yzhang-gh** [comment]
That's the reason! C++ has `+` symbols and caused the fenced code check to fail.

It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
