### ISSUE TITLE
Print Markdown to HTML to a different output location

### ISSUE THREAD

**Issue by sgstokes** [yzhang-gh/vscode-markdown#594]
#### What is the problem?

This is actually a feature request.  Is it possible to add a configuration setting to specify a path for HTML output in lieu of printing to the same path as the Markdown file?  

By the way, thank you for a terrific extension!

**Comment by yzhang-gh** [comment]
Thank you.

It would be interesting to know why do you need such a setting. Can you provide an example of use case?

**Comment by sgstokes** [comment]
I have a directory with a large number of markdown files. That directory is not shared. As I only share the HTML output.

I would like to create an output path under that directory and share that to others. There are many approaches, but the pattern I described was the one I was hoping to use.

Regards,
Stephen

**Comment by sgstokes** [comment]
In addition to my previous email, it would also be useful to have the separate output path to reduce the clutter/commingling of file types.

**Comment by yzhang-gh** [comment]
I see. Let's keep this open and collect more feedback from other users.

**Comment by sgstokes** [comment]
Thank you!

**Comment by queenkjuul** [comment]
Just like to chime in and say I would also love this feature, my workflow is similar: I have a "working" dir full of markdown files and then a separate folder that is shared to my co-workers where I keep the HTML output. As of right now I have to print and then move the html files to the other folder--not the end of the world, but it'd be nice to skip that step.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

**Comment by yzhang-gh** [comment]
Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). There is a new command "Print documents to HTML" which allows you to specify the output folder.

**Comment by sgstokes** [comment]
Works great! Thank you!
