### ISSUE TITLE
Embedded Html

### ISSUE THREAD

**Issue by surpavan** [yzhang-gh/vscode-markdown#596]
The current export to html is working fine.  It would be great if we get the option to export as a single html file with all content too. Example: keeping images as base encoded within file etc.. as single HTML file for all the content that can be supported.
Yes, file size will increase, but is a good option if we want to produce html email/single page reports like outputs.

**Comment by yzhang-gh** [comment]
Have you tried `markdown.extension.print.imgToBase64` option?

**Comment by surpavan** [comment]
That option helped.  Thank you.

**Comment by surpavan** [comment]
Label as question please.
