### ISSUE TITLE
Markdown with Bootstrap as CSS

### ISSUE THREAD

**Issue by surpavan** [yzhang-gh/vscode-markdown#598]
The css theme provided by default is good. Just a thought as to why not use bootstrap names/css as default - as the style editing would be more easy/supported in web-world (stackoverflow etc.).

This will also allow some interested people to provide themes, customization etc..

**Comment by yzhang-gh** [comment]
You can use the option `markdown.styles`. Note that there are some restrictions for security concerns.
(If I remember correctly, CSS files with `https` links or within the current folder are allowed.)

**Comment by surpavan** [comment]
Any possible example on how to use markdown.styles?  I tried with the bootstrap cdn, but the tables are not getting properly displayed.

**Comment by yzhang-gh** [comment]
![image](https://user-images.githubusercontent.com/7588612/72682916-6e568900-3b0d-11ea-838e-0212eb1fea6e.png)

And it should look like this in the `settings.json`

```json
{
    "markdown.styles": [
        "https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
    ]
}
```

**Result**
![image](https://user-images.githubusercontent.com/7588612/72682890-1d469500-3b0d-11ea-8a0d-8ec5a118f2de.png)

**Comment by surpavan** [comment]
Thank you. :)
