### ISSUE TITLE
Compile to HTML and open

### ISSUE THREAD

**Issue by surpavan** [yzhang-gh/vscode-markdown#599]
Thank you for the wonderful plugin.
Question:  I use the compile to HTML a good number of times, Is there a way I can compile it to HTML and open it with default browser? instead of going to file and opening it?
How can I keep a short cut for it? or A new command where it can run the print to html and open the file in browser.

**Comment by yzhang-gh** [comment]
There is an option `markdown.extension.print.onFileSave` you can have a try.

As for live updating in the browser, I suggest [Live Server](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) extension. It is easy to use.

**Comment by surpavan** [comment]
markdown.extension.print.onFileSave is good.
I am not looking for live update, but open the html once saved.
