### ISSUE TITLE
Add collapsable table of contents option

### ISSUE THREAD

**Issue by dmey** [yzhang-gh/vscode-markdown#607]
Would there be any interest in adding an option to create collapsible table of contents (TOC) as supported by other TOC generators. For example, one could generate the TOC from something like:

```
<details>
<summary>Table of contents</summary>

- [Heading 1](#heading-1)
  - [Heading 2](#heading-2)

</details>
```

which produces

<details>
<summary>Table of contents</summary>

- [Heading 1](#heading-1)
  - [Heading 2](#heading-2)

</details>

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

IMHO, this is too trivial to be a feature... I would suggest using this setting

```json
{
    "emmet.excludeLanguages": [],
    "emmet.includeLanguages": {
        "markdown": "html"
    }
}
```

You can type `details` and then press <kbd>Tab</kbd> to get `<details>|</details>`
