### ISSUE TITLE
用户代码片段生不生效的问题

### ISSUE THREAD

**Issue by MyAlphaGo** [yzhang-gh/vscode-markdown#610]
#### What is the problem?
用户代码片段时而生效，时而不生效。

我想知道什么原因会导致它不生效，这个问题真的太影响体验了

**Comment by MyAlphaGo** [comment]
希望尽快得到答案

**Comment by yzhang-gh** [comment]
报告问题的时候请尽量多地提供细节（预期行为如何，实际如何），毕竟大家都没有读心术

---

如果我没理解错的话你应该是指左下角菜单里面可以设置地那个 用户代码片段

在我这是正常的

![image](https://user-images.githubusercontent.com/7588612/73605500-02c6ee00-45da-11ea-9b5c-debe8ba25745.png)

另外有个类似的报告 #409，基本表明不是这个插件的问题
