### ISSUE TITLE
GitLab math not rendered

### ISSUE THREAD

**Issue by TriMoon** [yzhang-gh/vscode-markdown#612]
#### What is the problem?
When you use math inside nested blocks, it does not get rendered at all.

#### How can I reproduce it?
See correct output: [README.md#createinstance](https://gitlab.com/trimoon-inc/Arma3_DS/-/blob/36c48785adeae892e2c6651ccb1f50304358e833/README.md#createinstance)
For source see: [README.md#L143-148](https://gitlab.com/trimoon-inc/Arma3_DS/-/blob/36c48785adeae892e2c6651ccb1f50304358e833/README.md#L143-148)

#### Is there any error message in the console?
Not that i could see...

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This (math inside a code block) is a special syntax from the [GitLab Flavored Markdown](https://docs.gitlab.com/ee/user/markdown.html#math). So you can't expect it to work elsewhere (e.g. here in GitHub comments box)

**Comment by TriMoon** [comment]
Any other way to include math is also special syntax, yet this extension is able to show math.
It just borkes on this usage, because when you use the same syntax outside nested blocks it is displayed correctly.
So this is a bug of this extension's **intended** behavior :wink:

**Comment by yzhang-gh** [comment]
Well, there are still many different ways/dialects to _**define math environment**_,
e.g. `\(inline\)`/`\[display\]` (#552).

Currently, we only support `$inline$`/`$$dispaly$$`. You can see more about the rules [here](https://github.com/waylonflinn/markdown-it-katex#syntax).

**Comment by TriMoon** [comment]
> Currently, we only support `$inline$`/`$$dispaly$$`. You can see more about the rules [here](https://github.com/waylonflinn/markdown-it-katex#syntax).

Thanks then this extension is **useless** for use in development on git repos, because neither [github](https://guides.github.com/features/mastering-markdown/#GitHub-flavored-markdown) nor [gitlab](https://gitlab.com/help/user/markdown#math) recognizes the `$$` variant for blocks...

**Comment by yzhang-gh** [comment]
I don't get the point. GitHub doesn't support math at all 😳. You will see the same preview (without correct math rendering) on GitHub and inside VSCode.

This extension tries to align with the [CommonMark Spec](https://spec.commonmark.org/) + some really popular syntax (e.g. GitHub tables).

When it comes to the math environment, I would say `$$` and `\[dispaly\]` are more commonly recognized than the GitLab one. (See the [survey](https://github.com/cben/mathdown/wiki/math-in-markdown))

This can be a feature request which is to support GitLab math syntax. However, it always gets a lower priority than the `\[\]` one. Markdown has never been unified. You can find there are many [requests](https://github.com/yzhang-gh/vscode-markdown/issues?q=is%3Aissue+is%3Aopen+label%3A%22Markdown+dialect%22) for various dialects.

**Comment by TriMoon** [comment]
> I don't get the point. GitHub doesn't support math at all :flushed:. You will see the same preview (without correct math rendering) on GitHub and inside VSCode.

I stand corrected indeed, **GitLab** has better support.
> 
> This extension tries to align with the [CommonMark Spec](https://spec.commonmark.org/) + some really popular syntax (e.g. GitHub tables).

:clap: More [reason](https://spec.commonmark.org/0.29/#fenced-code-blocks) to support the <code>```math</code> version see [example 112](https://spec.commonmark.org/0.29/#example-112) ...

**Comment by yzhang-gh** [comment]
That is the example of "fenced code blocks", designed to show "source code".

---

Markdown code:
<pre>
```
**bold** _italic_
```
</pre>

Preview:
```
**bold** _italic_
```

---

Markdown code:
<pre>
```markdown
**bold** _italic_
```
</pre>
Preview:
```markdown
**bold** _italic_
```

---

Markdown code:
<pre>
```javascript
function foo() {
    return 0;
}
```
</pre>
Preview:
```javascript
function foo() {
    return 0;
}
```

---

**Then**, according to CommonMark

Markdown code
<pre>
```math
\alpha = \beta
```
</pre>
should renders
```math
\alpha = \beta
```
_with math syntax highlight_.

---

I am not saying I don't recognize the GitLab Flavored Markdown. But this extension doesn't aim to cover all Markdown dialects (unless popular enough or someone is willing to contribute).

**Comment by yzhang-gh** [comment]
This extension only supports basic math functionality. Please turn to Markdown+Math (which supports various math syntax) for more features (see [`README`](https://github.com/yzhang-gh/vscode-markdown#math)).
