### ISSUE TITLE
$\ce{N2 + 3H2 <=>T[ 高温、加压 ][催化剂] 2NH3}$ render wrong

### ISSUE THREAD

**Issue by wuyudi** [yzhang-gh/vscode-markdown#613]
#### What is the problem?

![image](https://user-images.githubusercontent.com/30024051/73910859-6dad4900-48a8-11ea-9ff5-7de8c638cf8c.png)

#### How can I reproduce it?

$\ce{N2 + 3H2 <=>T[ 高温、加压 ][催化剂] 2NH3}$

#### Is there any error message in the console?

nothing

**Comment by yzhang-gh** [comment]
奇怪，我发现我的电脑上所有数学公式都不能显示了。。。你的 VSCode 和插件版本是多少？

**Comment by wuyudi** [comment]
![image](https://user-images.githubusercontent.com/30024051/73912362-3b054f80-48ac-11ea-8028-14c1f82f23c7.png)
![image](https://user-images.githubusercontent.com/30024051/73912406-58d2b480-48ac-11ea-934f-54c750294b3e.png)

**Comment by yzhang-gh** [comment]
版本和你一样，我这暂时测试不了了。不过之后会更新一下 KaTeX 版本，可能就顺便解决了。

cc @balthild 说不定愿意帮忙验证一下

**Comment by balthild** [comment]
https://jsfiddle.net/0dq68rx2/

https://jsfiddle.net/8tayf5kp/

根据 package-lock.json，v2.7.0 里 katex 版本是 0.10.2，的确会渲染错误。改为 0.11.1 就没问题了。

**Comment by yzhang-gh** [comment]
感谢帮助

**Comment by yzhang-gh** [comment]
（开发版中解决了）
