### ISSUE TITLE
Disable path autocomplete

### ISSUE THREAD

**Issue by gouletjg** [yzhang-gh/vscode-markdown#614]
### What is the problem?

I use VSCode in a very large network drive and take notes in Markdown using this extension. VSCode will eat up RAM when I try to link to another file as it searches all directories for suitable files to link.  Eventually VSCode will crash as Windows runs out of ram to give it.

The process that is created is called "Rg", but only gets created when Markdown-All-In-One is enabled AND I attempt to link to another file (such as via `![]()` or `[]()`. Disabling the extension fixes the issue. The extension [Path Autocomplete](https://marketplace.visualstudio.com/items?itemName=ionutvmi.path-autocomplete) works flawlessly by only sowing results for the directory I am in. It does not search for other files.

Note; I really like the fact that it searches for files to link to when in much smaller directories.  If a toggle could be added to enable / disable this feature though, I would appreciate it for this particular use case.

#### How can I reproduce it?

In a directory with a LOT of files (on the order of hundreds of GB). Try to link to a file using `[]()`

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Can you tell me more about the directory with hundreds of GB files? (For example, we now have heuristic which is to exclude `node_modules` folders.)

A toggle can be the solution. But I think there might be better ways to deal with it.
(If you open such a big folder with VSCode, sooner or later there will/might be some problems. For example, [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree))

**Comment by gouletjg** [comment]
Almost all of it is text files. I did forget to mention one key point (which may work as a better fix). I have set VSCode NOT to search in sub-directories which contain most of the files (say, 99% of the directory size). Before I did this, if I pressed ctrl + p (quick open), the "Rg" process would start and crash VSCode (with or without this extension). 

Perhaps using the "Exclude" rules under Settings > Features > Search would be a better solution?

Example directory structure:
- Notes (small)
-- Markdown files
- Directory with a ton of other text files (ignored from search)
-- A whole bunch of text files!
- Another huge directory (ignored)
-- More text files!
- Directory with scripts (on search path, not huge)
-- Reasonably sized directory. Linking here would be useful, but I prefer VSCode not crashing

**Comment by yzhang-gh** [comment]
> Perhaps using the "Exclude" rules under Settings > Features > Search would be a better solution?

That's a good idea.

**Comment by yzhang-gh** [comment]
Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by gouletjg** [comment]
Dev build worked perfectly!  Thank you!
