### ISSUE TITLE
Cmd + Shift + ] switched between open tabs in vscode

### ISSUE THREAD

**Issue by virenv** [yzhang-gh/vscode-markdown#615]
Issue: Cmd + Shift + ] is a default command to switch between tabs on macs. This command is also listed as a command to increase the heading levels for this extension.

It is listed here: [Keyboard shortcuts](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#keyboard-shortcuts)

**Comment by yzhang-gh** [comment]
You can delete (or reassign) the keybindings as you wish (see [VSCode docs](https://code.visualstudio.com/docs/getstarted/keybindings)).

**Comment by virenv** [comment]
Will it be beneficial to have separate non conflicting keys? A user might just skip using that shortcut key.

**Comment by yzhang-gh** [comment]
The default keybindings are hard to choose as there almost always are conflicts.

For example, some agree to use Ctrl/Cmd + B to toggle bold style, but some do prefer its default VSCode behavior "toggle explorer panel".

**Comment by virenv** [comment]
Yes, I understand that it is a hard problem to get a fixed solution. I think, I got answer to my question. Thanks @yzhang-gh for looking at it.
