### ISSUE TITLE
A bug and a feature about KaTeX

### ISSUE THREAD

**Issue by Suyun514** [yzhang-gh/vscode-markdown#616]
1. 当处理需要 `$` 套 `$` 的数学公式时会有 bug，如 `$\ce{NaOH(aq,$\infty$)}$`。

正确的效果：![image](https://user-images.githubusercontent.com/52325399/74225908-8b3e4080-4cf6-11ea-8562-c7b4238d7524.png)；
`vscode-markdown` 中的效果：![image](https://user-images.githubusercontent.com/52325399/74225956-9beeb680-4cf6-11ea-826d-c58a57f1693e.png)。

2. 希望支持 `\(...\)` 包裹的行内公式，`\[...\]` 包裹的行间公式。

**Comment by yzhang-gh** [comment]
1. 不是很理解这个例子为什么要 `$` 套 `$`，`$\ce{NaOH(aq,\infty)}$` 似乎可以满足你需要的效果
   另外[开发版](https://github.com/yzhang-gh/vscode-markdown#latest-development-build)里更新了 KaTeX，对某些数学的语法可能有更好的支持
2. 这个和 #552 重复了

**Comment by Suyun514** [comment]
1. 我换一个例子：`$\ce{ZnS($c$)}$`。
这些例子来自 mhchem 的示例：https://mhchem.github.io/MathJax-mhchem/

**Comment by yzhang-gh** [comment]
嗯，把这个归到 #552 中
