### ISSUE TITLE
Cannot use Vietnamese keyboard in *.md file

### ISSUE THREAD

**Issue by NhokCrazy199** [yzhang-gh/vscode-markdown#617]
Since the new update, I have not been able to type Vietnamese characters in * .md files.
Currently I have to disable this plugin to be able to use.
I hope the author will fix this problem in the next versions.
Vietnamese keyboard inf at unikey.org

**Comment by yzhang-gh** [comment]
There is a really old issue (#41) about this.

I am not sure whether it is the same issue. But I suggest deleting the `onBackspaceKey` keybinding registered by this extension.

![image](https://user-images.githubusercontent.com/7588612/74419633-31b84c00-4e85-11ea-8440-65cc998bf89e.png)

**Comment by NhokCrazy199** [comment]
It is working, thanks!

**Comment by Lemmingh** [comment]
Duplicate of #200
