### ISSUE TITLE
Highlight Code Blocks

### ISSUE THREAD

**Issue by woojoo666** [yzhang-gh/vscode-markdown#619]
#### What is the problem?

Right now plain text code blocks don't have any special highlighting in the IDE, so it's hard to tell where the code blocks are:

![screenshot](https://i.imgur.com/pqS0R1x.png)

It would be nice to have some highlighting, kind of like in Sublime Text:

![screenshot](https://i.imgur.com/PulFQsX.png)

Maybe this can be an option in the settings. Or maybe it is only enabled for plain text code blocks?

**Comment by yzhang-gh** [comment]
It is because your theme doesn't support it.

![image](https://user-images.githubusercontent.com/7588612/74823789-42176d80-5342-11ea-9c1a-602db2a6c268.png)

![image](https://user-images.githubusercontent.com/7588612/74823820-4f345c80-5342-11ea-842e-7ea6d447034f.png)
