### ISSUE TITLE
Preview is too wide!

### ISSUE THREAD

**Issue by marktripney** [yzhang-gh/vscode-markdown#621]
#### What is the problem?
The preview is the full width of the editor. Might it be possible to limit the preview width to, for example, 80 chars, or to inherit the `wordWrapColumn` of the editor?

(Just a 'nice-to-have', love the extension and use it frequently - **thank you!**)

#### How can I reproduce it?
Preview .md file.

**Comment by yzhang-gh** [comment]
This preview tab is provided by VSCode itself. It can be opened side-by-side.

See https://code.visualstudio.com/docs/languages/markdown#_markdown-preview

**Comment by marktripney** [comment]
Perfect - thanks!
