### ISSUE TITLE
some confusion about \varnothing

### ISSUE THREAD

**Issue by wuyudi** [yzhang-gh/vscode-markdown#624]
#### What is the problem?

I have a habit of copying and pasting the Unicode rendered by KaTeX to the left. It works well at other symbols ( for example `\varphi`). But `\varnothing` seems a bit different.

![GIF1](https://user-images.githubusercontent.com/30024051/75423772-4a216f80-5937-11ea-8368-65eabd58b15c.gif)

#### How can I reproduce it?

`$\varnothing$` , and then copy and paste it to the left.

#### Is there any error message in the console?

no

It didn't bother me（I can just use `\varnothing`） , but I really want to know the reason ：）

**Comment by yzhang-gh** [comment]
Looks like KaTeX doesn't support the direct input of `\varnothing`

![image](https://user-images.githubusercontent.com/7588612/75424938-a064d180-597c-11ea-921c-2d80052f7b55.png)

I guess that is because `\varnothing` and `\emptyset` are using the same character but different fonts.
