### ISSUE TITLE
Markdown text coloring is cumbersome, possibility for enhancement?

### ISSUE THREAD

**Issue by earik87** [yzhang-gh/vscode-markdown#625]
#590 ## What is the problem?

I want to color the selected text in the markdown files. However, this is only possible with a extensive syntax. Such as following; 

My name is `<span style="color:RED ">Enis Arik</span>`

Is it possible to make this easier such as reducing the amount of syntax has been used?

**Comment by yzhang-gh** [comment]
This is about the specifications (i.e. the syntaxes) of Markdown. In detail, this extension supports [GFM](https://github.github.com/gfm/) (based on [CommonMark](https://spec.commonmark.org/)) + KaTeX for math.

You are looking for a Markdown dialect which introduces new syntax for your use case. (See [this](https://github.com/yzhang-gh/vscode-markdown/issues?q=is%3Aissue+is%3Aopen+label%3A%22Markdown+dialect%22) for a list of dialects.) AFAIK, there isn't a dialect having such a syntax.
