### ISSUE TITLE
How to add a blank line automatic. between "1. " and "2. "

### ISSUE THREAD

**Issue by kktt007** [yzhang-gh/vscode-markdown#626]
如题，怎么在有序列表中自动空一行。
目前是回车2次到下下行后，但是需要重新添加序号:
1. foo
<!blank line>
2. foo(2次回车到这里后，2. 要自己重新加，想请教是否已支持)

Ps:
发现了隐藏功能，shift + enter能从有序进入到对应的评级，不添加序号，这样添加无序就方便多了，请教这样的快捷绑定有说明吗，
thanks

**Comment by yzhang-gh** [comment]
> 怎么在有序列表中自动空一行

这个确实没想到好的解决办法。一个方法是第一次回车之后按 <kbd>ctrl+shift+enter</kbd>（在上方插入一行）

> 发现了隐藏功能，shift + enter 能从有序进入到对应的评级，不添加序号

这个是很早之前别人的建议，很久没人提，我自己都忘了 😂（平时基本是多按一次回车或者删除键来删除的）

**Comment by kktt007** [comment]
> 
> 
> > 怎么在有序列表中自动空一行
> 
> 这个确实没想到好的解决办法。一个方法是第一次回车之后按 ctrl+shift+enter（在上方插入一行）
> 
> > 发现了隐藏功能，shift + enter 能从有序进入到对应的评级，不添加序号
> 
> 这个是很早之前别人的建议，很久没人提，我自己都忘了 😂（平时基本是多按一次回车或者删除键来删除的）

非常感谢，当时也想到说回车加入一行，可以凑活，当时配置里默认有序多加一行，这是个好习惯，反正比我目前空行好的多，毕竟空行后，有序要自己加了。。。
(shift+enter这样的隐藏功能键还有吗，有其他的吗，我是自己按的看看的，终于方便点了)
![](https://img.vim-cn.com/ff/00d8a4ca9861f248a78b5fedd1efb2ac2950a7.png)

**Comment by yzhang-gh** [comment]
其实在插件的详情页可以看到的

![image](https://user-images.githubusercontent.com/7588612/75546734-36bff280-5a64-11ea-91b9-5b6f18bef2f3.png)

**Comment by kktt007** [comment]
> 
> 
> 其实在插件的详情页可以看到的
> 
> ![image](https://user-images.githubusercontent.com/7588612/75546734-36bff280-5a64-11ea-91b9-5b6f18bef2f3.png)

谢谢。

**Comment by yzhang-gh** [comment]
对了，之前忘记说了。推荐你换一个等宽字体（比如默认的 Consolas），现在这个字体上下对不齐。
如果需要中文也对齐的话可以选择 [Sarasa Mono SC](https://github.com/be5invis/Sarasa-Gothic/releases)。

**Comment by kktt007** [comment]
> 对了，之前忘记说了。推荐你换一个等宽字体（比如默认的 Consolas），现在这个字体上下对不齐。
> 如果需要中文也对齐的话可以选择 [Sarasa Mono SC](https://github.com/be5invis/Sarasa-Gothic/releases)。

非常感谢,你看我是截图没有对齐吗
目前windows用的是SF Pro Text 字体, 楷体, 
Linux用的英文是MesloLGM Nerd Font Mono, 中文是 '全字庫正楷體', '文泉驿微米黑'
英文基本是水果味的,中国字体就知道台湾和文泉的,您上面推荐的我也收藏啦,谢谢.如有更多推荐,非常感谢.放弃sublime就是字体不对齐~~
