### ISSUE TITLE
[bug] `$\Phi = \frac{dQ}{dt}$` does not render right.

### ISSUE THREAD

**Issue by treert** [yzhang-gh/vscode-markdown#627]
### What is the problem?
`$\Phi = \frac{dQ}{dt}$` does not render right,
![image](https://user-images.githubusercontent.com/4133961/75676449-31f97980-5cc4-11ea-83bc-41634da76121.png)

the right one is, ![image](https://user-images.githubusercontent.com/4133961/75676666-b1874880-5cc4-11ea-872d-e8d145324cac.png)
which can be fix by a ugly trick：`$\Phi = \frac{dQ}{dt}\\$`，add `\\`in the tail.

#### How can I reproduce it?

RT

#### Is there any error message in the console?
Nothing error.

**Comment by yzhang-gh** [comment]
Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

---

> ![image](https://user-images.githubusercontent.com/7588612/75690251-79d8ca80-5cdd-11ea-80b6-066c7774c46d.png)

🤣

**Comment by treert** [comment]
the last dev build is **Right**

**Comment by treert** [comment]
Find the reason, [markdown-it-attrs](https://www.npmjs.com/package/markdown-it-attrs) cause this bug.
