### ISSUE TITLE
How can I enable "toggle inline code" and "toggle code block" keyboard shortcuts?

### ISSUE THREAD

**Issue by sunknudsen** [yzhang-gh/vscode-markdown#628]
According to the [README](https://github.com/yzhang-gh/vscode-markdown#available-commands), `toggleCodeSpan` exists, but not `toggleCodeBlock`, even though it is the subject of a [merged PR](https://github.com/yzhang-gh/vscode-markdown/pull/551).

See https://github.com/yzhang-gh/vscode-markdown/blob/master/src/formatting.ts#L16

I’m using the following key bindings:

```json
{
  "key": "cmd+shift+k",
  "when": "editorTextFocus && !editorReadonly && editorLangId == markdown",
  "command": "markdown.extension.editing.toggleCodeSpan"
},
{
  "key": "cmd+alt+shift+k",
  "when": "editorTextFocus && !editorReadonly && editorLangId == markdown",
  "command": "markdown.extension.editing.toggleCodeBlock"
}
```

`toggleCodeSpan` works, but not `toggleCodeBlock` which throws the following error.

> command 'markdown.extension.editing.toggleCodeBlock' not found

Tried reinstalling plugin and restarting VSC a few times.

**Comment by yzhang-gh** [comment]
Just open the keybinding page (left bottom corner) and you can assign a shortcut to it.

![image](https://user-images.githubusercontent.com/7588612/75694461-86f8b800-5ce3-11ea-9278-46f5e9126302.png)

**Comment by sunknudsen** [comment]
Thanks for the follow up @yzhang-gh. Please see updated issue.

**Comment by sunknudsen** [comment]
@yzhang-gh These are all the available key bindings related to Markdown All in One. Do you know why `toggleCodeBlock` is not there?

![Screen Shot 2020-03-02 at 10 36 43 AM](https://user-images.githubusercontent.com/2117655/75702658-de673b80-5c83-11ea-86e2-a7bba6e1c207.png)

**Comment by yzhang-gh** [comment]
That's weird. I have no clue but you can try the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by sunknudsen** [comment]
@yzhang-gh Not sure what caused the issue, but `toggleCodeBlock` works now. Thanks for looking into it.
