### ISSUE TITLE
Double horizontal line becomes heading in TOC

### ISSUE THREAD

**Issue by anand-avinash** [yzhang-gh/vscode-markdown#629]
#### What is the problem?
The auto TOC generator turns one of the double horizontal line into a heading.

#### How can I reproduce it?
VSCode: 1.42.1
OS: Windows 10
Extension: Markdown All in One

Markdown snippet:
```md
# Table of contents
1. [Table of contents](#table-of-contents)
---
---

# head1
Some text is better than no text
## head2

---
---
```

Generated output (After pressing `ctrl+s`):
````md
# Table of contents
1. [Table of contents](#table-of-contents)
   1. [---](#hr)
2. [head1](#head1)
   1. [head2](#head2)
   2. [---](#hr-1)

---
---

# head1
Some text is better than no text
## head2

---
---
````
Expected output (after pressing `ctrl+s`):
````md
# Table of contents
1. [Table of contents](#table-of-contents)
2. [head1](#head1)
   1. [head2](#head2)

---
---

# head1
Some text is better than no text
## head2

---
---
````

#### Is there any error message in the console?
No.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
