### ISSUE TITLE
TOC is not getting updated in for "markdown.extension.toc.plaintext": true

### ISSUE THREAD

**Issue by anand-avinash** [yzhang-gh/vscode-markdown#630]
#### What is the problem?
The TOC is getting generated as expected when the value of `markdown.extension.toc.plaintext` is set `false`. However, after setting it `true`, the TOC is not getting updated at all. You can add other new headings, remove old headings, but the TOC will never be updated after pressing `ctrl+s`.

The value of `markdown.extension.toc.orderedList` has no effect on the observed behavior.

#### How can I reproduce it?
VSCode: 1.42.1
OS: Windows 10
Extension: Markdown All in One

I have the following settings for TOC generation:
````json
{
    "markdown.extension.toc.githubCompatibility": true,
    "markdown.extension.toc.plaintext": true,
    "markdown.extension.toc.updateOnSave": true
}
````

#### Is there any error message in the console?
No.

**Comment by yzhang-gh** [comment]
You need to recreate the TOC with command `create table of contents`. The extension lost tracking of the TOC when you changed `plaintext` to `true`.

**Comment by anand-avinash** [comment]
I tried your solution and it works. However, I am confused about what do you mean by `plaintext`. When I generated TOC with plaintext enabled, I got the TOC without hyperlink. What I thought of getting was unformatted text in TOC. For example, I created a heading in bold text `# **head1**`. Currently, it appears as `1. [**head1**](#head1)` in TOC. I had expected to get `1. [head1](#head1)` after enabling plaintext.

**Comment by yzhang-gh** [comment]
> When I generated TOC with plaintext enabled, I got the TOC without hyperlink.

You are right.

> What I thought of getting was unformatted text in TOC.

That's a good question 😂. I don't remember when the option was added (and named) but some people do prefer TOC without links.
