### ISSUE TITLE
Preserve relative paths to images

### ISSUE THREAD

**Issue by BernardZhao** [yzhang-gh/vscode-markdown#631]
#### What is the problem?
When printing markdown to HTML, my relative links to images are transformed into absolute links. It would be nice if they were preserved as relative links so that the files and HTML are portable together.

#### How can I reproduce it?
Run the `Print current document to HTML` command on a `.md` file with a relative link.

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment]
Please check the settings. I remember we have a toggle for that.

**Comment by BernardZhao** [comment]
Found it. Thanks!
