### ISSUE TITLE
format failed

### ISSUE THREAD

**Issue by Jason23347** [yzhang-gh/vscode-markdown#632]
Issue Type: <b>Bug</b>

The warning was "overlapping ranges are not allowed", and I cannot figure out where the problem is.
This is my file content:
## update

| method | url            | description     |
| ------ | -------------- | --------------- |
| GET    | /api/v1/event | get event list |

## delete

| method | url            | description     |
| ------ | -------------- | --------------- |
| GET    | /api/v1/event | get event list |

### return

Extension version: 2.7.0
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:50:36.977Z)
OS version: Linux x64 5.0.0-38-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) m3-7Y30 CPU @ 1.00GHz (4 x 2467)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|3.74GB (0.11GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by yzhang-gh** [comment]
It doesn't look like a problem with this extension. If you click on the upwards arrow in the warning message, you can see the source.

**Comment by Jason23347** [comment]
I'm afraid there was no arrow displayed...that's why I don't know what the problem is...

**Comment by yzhang-gh** [comment]
I mean

![image](https://user-images.githubusercontent.com/7588612/76145156-f1ce3880-60c1-11ea-9895-c894e774b400.png)

And please check what other Markdown extensions you have installed.

**Comment by Jason23347** [comment]
Unfortunately I have only one markdown extension(this one) installed,except a markdown theme kit.
Anyway, I haven't had this problem again these days, this issue should be closed.

**Comment by ThibaultUrien** [comment]
I encountered the same issue. I don't have any arrow either. I still think it is very likely to be related with this plugin in some ways as it only occure if I have this plugin installed and enabled.
This seem to be related with this vscode issue : https://github.com/Microsoft/vscode/issues/20757

**Comment by yzhang-gh** [comment]
@ThibaultUrien Can you provide your sample file and what steps I should do to reproduce the issue?
