### ISSUE TITLE
[Feature request] Support for markdown footnote.

### ISSUE THREAD

**Issue by hunterzju** [yzhang-gh/vscode-markdown#634]
#### What is the problem?
outstanding plugin, but sometimes, I need the markdown footnote function, it does not support.    
for example:
```
You can create footnotes like this[^footnote].

[^footnote]: Here is the *text* of the **footnote**.
```
The reference function will not show content, and if the reference is not available online, the reference will not work very well.    
Or if the reference can support such format:
```
This is [an example][id] reference-style link.

Then, anywhere in the document, you define your link label like this, on a line by itself:

[id]: http://example.com/  "Optional Title Here"
```
So that the "Optional Title Here" can be shown in the doc.

Thanks a lot!

**Comment by yzhang-gh** [comment]
Please see #212. It has been supported for a while.
