### ISSUE TITLE
"markdown.extension.tableFormatter.enabled": false  not respected

### ISSUE THREAD

**Issue by Dr-Irv** [yzhang-gh/vscode-markdown#640]
####  What is the problem?
If I have 
```json
"markdown.extension.tableFormatter.enabled": false
```
in `settings.json`, the settings is not respected

#### How can I reproduce it?
Create a markdown document with the following text:
```markdown
# Test of Markdown table formatting

| Col1 | Col2 | Longer Col 3 |
|------|------|--------------------------------------|
| abc | 123 | A simple line |
| def | 345 | A very long line that should be really long because we want it to wrap |
| ghi | 678 | A shorter line but a little longer |
```

Then hit Shift-Alt-F to format the document.  The table still gets reformatted:
```markdown
# Test of Markdown table formatting

| Col1 | Col2 | Longer Col 3                                                           |
| ---- | ---- | ---------------------------------------------------------------------- |
| abc  | 123  | A simple line                                                          |
| def  | 345  | A very long line that should be really long because we want it to wrap |
| ghi  | 678  | A shorter line but a little longer                                     |
```

My understanding is that with the setting being `false`, the table would _not_ get reformatted.

#### Is there any error message in the console?

No error message

**Comment by yzhang-gh** [comment]
The option works as expected on my laptop. If you disable `tableFormatter`, you will get

![image](https://user-images.githubusercontent.com/7588612/76777699-8da72500-67e3-11ea-807a-2d4e59f6394a.png)

when you press `alt+shift+f`.

Please check whether it is caused by other extensions.

**Comment by Dr-Irv** [comment]
You're right.  I had "prettier" installed and it was doing that.
