### ISSUE TITLE
Table breaks if TeX inside it has a '|'

### ISSUE THREAD

**Issue by shilangyu** [yzhang-gh/vscode-markdown#641]
#### What is the problem?

If a table uses TeX math and this TeX block has a `|` the formatter and previewer breaks

#### How can I reproduce it?

Paste this:

```
| $f(x)$        | $\int f(x) dx$ |
| ------------- | -------------- |
| $\frac{1}{x}$ | $\ln|x| + C$   |
```

If line 3 is used somewhere outside of the table, everything is fine

**Comment by yzhang-gh** [comment]
Thanks. Let's move to #318.
