### ISSUE TITLE
Use Relative Paths for Images when Printing to HTML

### ISSUE THREAD

**Issue by queenkjuul** [yzhang-gh/vscode-markdown#642]
Apologies if this is a VSCode thing and not the fault of the extension. Not sure if this is an issue or a feature request

#### What is the problem?
When printing markdown to HTML, images in the format `![alt](relative/path)` are converted to HTML tags containing absolute paths like `<img src="file:///full/path/to/relative/path>`

This causes issues when moving my files from my working folder to my site folder, as I have to go back in and manually alter the HTML files. 

#### How can I reproduce it?
Create a markdown file and include an image using an relative path such as `![](image.png)`. Print it to HTML. The HTML output will contain `<img src="file:///full/path/to/image.png>`

#### Is there any error message in the console?

None as I do not believe this is unexpected behavior?

**Comment by yzhang-gh** [comment]
Please check the "supported settings" section.

**Comment by queenkjuul** [comment]
I swore I looked up and down :/ my bad

**Comment by yzhang-gh** [comment]
😉
