### ISSUE TITLE
is it possible to format formula in markdown

### ISSUE THREAD

**Issue by wuyudi** [yzhang-gh/vscode-markdown#643]
#### What is the problem?

I found that in `$$  $$` environment , formula can't be formated. So, to get them formatted, I have to copy it to .tex , and then paste back. So is it possible to add this function?

**Comment by yzhang-gh** [comment]
I'm afraid not.

**Comment by yzhang-gh** [comment]
Because I haven't found a good formatter for math equations. To my memory, [latexindent](https://github.com/cmhughes/latexindent.pl) doesn't do a lot for math environments.
