### ISSUE TITLE
[Feature request] Extending TOC to other file types beside .md ?

### ISSUE THREAD

**Issue by neeoteh** [yzhang-gh/vscode-markdown#645]
This extension is great, can it be extended even more? TOC to other types beside markdown or to change the syntax highlighting to a different format than ,md while using the same TOC feature from markdown?
  For example jumping using TOC within .sh, .py, .java files would help a lot (even if # is considered comment in some).

 Thank you.

**Comment by yzhang-gh** [comment]
It is an interesting idea. However, I don't think it is a good feature for this extension.

People can make a standalone extension to do this and properly handle different languages.
Extending this extension to other file types may cause some unexpected side effects.
