### ISSUE TITLE
Is there any way to enable a markdown-it plugin in `print to html`?

### ISSUE THREAD

**Issue by 1354092549** [yzhang-gh/vscode-markdown#647]
#### What is the problem?
Is there any way to enable a markdown-it plugin in `print to html`?
I have written a plugin that helps embed mind map into markdown and enabled it in VS Code's built-in markdown preview (accroding to [Markdown Extension](https://code.visualstudio.com/api/extension-guides/markdown-extension)).
But when I use `print to html`, the plugin does not work at all.

Here is my source:
- [markdown-it-tinymind](https://github.com/1354092549/markdown-it-tinymind)
- [vscode-markdown-tinymind
](https://github.com/1354092549/vscode-markdown-tinymind)

#### How can I reproduce it?
Install my plugin, and open `Demo.md` in [Demo.zip](https://github.com/yzhang-gh/vscode-markdown/files/4433093/Demo.zip).
You will see the plugin working well with the preview window, but not working in `print to html`.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. This extension is also a Markdown extension (just like yours) that contributes to the VSCode's built-in one. The best solution would be VSCode itself supports the export of HTML.

For this extension('s HTML export feature), I hard-coded some markdown-it plugins that are used by VSCode, this extension, and some that are frequently requested.
