### ISSUE TITLE
Getting in Touch with the Author

### ISSUE THREAD

**Issue by msaaddev** [yzhang-gh/vscode-markdown#648]
Hey, @yzhang-gh! I want to get in touch with you with an amazing proposition but I couldn't find your email on your GitHub account. Can you please send me a blank email at mrsaadirfan@gmail.com so that I can get back to you. Thank you for your time. :)

**Comment by msaaddev** [comment]
I am now going to close this issue since it is not related to vscode-markdown. I hope you will see this message.

**Comment by yzhang-gh** [comment]
Hi, thanks for your interest. My email is yzhang.lifeAToutlook.com.

**Comment by msaaddev** [comment]
Thank you! I will email you shortly. :)
