### ISSUE TITLE
Support for customizable KaTex delimiter

### ISSUE THREAD

**Issue by ingun37** [yzhang-gh/vscode-markdown#651]
I personally think `$` makes bad delimiter for Tex in Markdown for various reasons. I wrote an article about it: [Stop using $ as delimiter for Tex in Markdown](https://dev.to/ingun37/stop-using-dollar-sign-as-delimiter-for-tex-24bf). The argument in the article is, in a nutshell, we should stop using `$` as delimiter because:

* Tex already uses `$` as delimiter for nested Tex e.g. `\text{In quaternion $i^2$, $j^2$, $k^2$, $ijk$ and $-1$ are all equal.}`
* `$`, or any single special character is used frequently in both programming and general writings so it's susceptible to conflicts with other syntaxes.

I think it's reasonable to use something long and unique for the delimiter (unless Markdown makes a new standard about it) like how Dev.to started supporting KaTex with delimiter of `{% katex %}...{% endkatex %}`.

Could you make it customizable?

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Actually there is never a widely accepted syntax for math in Markdown. Except for `$`, `\(\)` from TeX, there is also <code>$\`math\`$</code> from GitLab and more.

I would suggest [Markdown+Math](https://marketplace.visualstudio.com/items?itemName=goessner.mdmath) extension if you need dedicated math support. Please see #570 (also #552).
