### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by KubaMiszcz** [yzhang-gh/vscode-markdown#652]
- Issue Type: `Performance`
- Extension Name: `markdown-all-in-one`
- Extension Version: `2.7.0`
- OS Version: `Windows_NT x64 10.0.18363`
- VSCode version: `1.44.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`C:\Users\KubaMiszcz\yzhang.markdown-all-in-one-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by yzhang-gh** [comment]
> :warning: Make sure to **attach** this file from your *home*-directory:
> :warning:`C:\Users\KubaMiszcz\yzhang.markdown-all-in-one-unresponsive.cpuprofile.txt`

Feel free to reopen when you have more information.
