### ISSUE TITLE
Open Preview: a multiple-line blockquote is rendered as a single line

### ISSUE THREAD

**Issue by ssilva** [yzhang-gh/vscode-markdown#659]
#### What is the problem?

Expected behaviour: a multiple-line blockquote should be rendered as multiple lines (see the [GitHub Flavored Markdown Spec - example 206](https://github.github.com/gfm/#example-206))

Actual behaviour: a multiple-line blockquote is rendered as a single line

#### How can I reproduce it?
1. Create a file with the following contents:
    ```
    > Hello
    > World
    ```
1. Markdown: Open Preview

Result:
> Hello World
#### Is there any error message in the console?
No

**Comment by yzhang-gh** [comment]
You need to enable `markdown.preview.breaks`. (Note that it is provided by VSCode itself.)

**Comment by ssilva** [comment]
Ah, of course!
Thank you, sorry for the trouble!
