### ISSUE TITLE
formatter not working

### ISSUE THREAD

**Issue by HuuLane** [yzhang-gh/vscode-markdown#661]
#### What is the problem?

`Markdown All in One` works like a charm, I especially appreciate the formatter,

it was something like that `foo,bar` -> `for, bar`, but it's not working now.

#### How can I reproduce it?

I disabled all extensions in the workspace except the `Markdown All in One`, and 
 `format document` but nothing happened.

#### Is there any error message in the console?

Not at all

**Comment by yzhang-gh** [comment]
Thank you.

However, I cannot take the credit. This extension only formats GFM Table 😂. You probably have used another formatter extension.

**Comment by HuuLane** [comment]
Sorry, I made a mistake

**Comment by HuuLane** [comment]
You call the extension markdown all in one, so why not implement plain text formatter? Will you? 😂

**Comment by yzhang-gh** [comment]
Well, there is no consensus how a Markdown document should be formatted. (No unified code style)

From another perspective, there is [Prettier - Code formatter](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode) which provides formatters for all kinds of languages, including Markdown. It is more professional in terms of code formatting.
