### ISSUE TITLE
problem with code validity when printing markdown into html

### ISSUE THREAD

**Issue by iiic** [yzhang-gh/vscode-markdown#662]
When I'm printing markdown into html with this extension and have code snippets in markdown it creates invalid html5 code.

Because it's not possible to have div element as a child of code element

extension creates something like `<pre><code class="language-javascript"><div>…` .

It's possible to not place that div element into code ? Are there some directive or it's bug?

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

This extension copied the relevant code from VSCode which added the `div` tag.

https://github.com/microsoft/vscode/blob/5d9e099684d6ee34a434a2f6cdfab830ae96c111/extensions/markdown-language-features/src/markdownEngine.ts#L324-L339

Maybe you need to file an issue there.
