### ISSUE TITLE
Usage of styleByWrapping for inserting Hex-Codes

### ISSUE THREAD

**Issue by Pindar777** [yzhang-gh/vscode-markdown#663]
Hi there,

thanks for the great package!
I wonder how to write a user defined keymapping that makes use of your "styleByWrapping"-function like the integrated "markdown.extension.editing.toggleBold".

I seek to habe a short cut likae CTRL-Shift-A that takes the selected texts and adds/removes the "right" quotation marks: e.g. &bdquo;TEXT&ldquo;

Cheers

**Comment by yzhang-gh** [comment]
Thank you.

However, I am afraid it is not possible to call `styleByWrapping` outside the extension as it is a internal function.

A solution is to use VSCode's snippets although you will need two shortcuts for `add` and `remove` respectively.
https://code.visualstudio.com/docs/editor/userdefinedsnippets.
e.g. `"${TM_SELECTED_TEXT/[„“]//g}"` for removing quotations.

**Comment by Pindar777** [comment]
Thank you @yzhang-gh for your fast reply.
I try to get this running with the variable.

I thought I could be possible to make the styleByWrapping public, if the function would except two arguments "before" and "after"

This is how to use your toogle Bold in keybinding
    {
        "key": "ctrl+shift+a",
        "command": "markdown.extension.editing.toggleBold"
    }, 

Idea:
    {
        "key": "ctrl+shift+a",
        "command": "markdown.extension.editing.WrapBy"
        "args": {
            "strBefore":   ,
            "strAfter":
        }
    },

**Comment by yzhang-gh** [comment]
> I thought I could be possible to make the styleByWrapping public

Yes, just register it with VSCode like

https://github.com/yzhang-gh/vscode-markdown/blob/67fcde982a423dc990b5a5ccfba4f5f233a0ed56/src/formatting.ts#L12

However, are you editing Hex-codes in Markdown files? This extension is only activated for Markdown documents.

**Comment by Pindar777** [comment]
@yzhang-gh In deed, however I am in favor of a solution that only uses simple user defined changes in VSC since I wonder that an update of your extension would break the hack.

I'm writing rmd-Documents without formats bookdown, word and powerpoint. Sometime special characters are needed. Inserting and reverting "the right" quotation marks would come in very handy.

**Comment by yzhang-gh** [comment]
I mean if we add `commands.registerCommand('markdown.extension.editing._wrapBy', (before, after) => styleByWrapping(before, after))` (i.e. expose the function), your idea in https://github.com/yzhang-gh/vscode-markdown/issues/663#issuecomment-619343974 will work.

**Comment by Pindar777** [comment]
@yzhang-gh That would be pretty cool! I think that would fit perfectly.

**Comment by yzhang-gh** [comment]
Would you mind opening a PR? You don't even need to run it locally. The CI will generate a `.vsix` and you can then download it for testing.

**Comment by Pindar777** [comment]
@yzhang-gh I tried to to that with github desktop

`Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.`

I gonna try it now here online and check back

**Comment by Pindar777** [comment]
@yzhang-gh I now used VSC and checked out to the "debug" branch and pulled the new line in the formatting.ts file.

**Comment by yzhang-gh** [comment]
Oh, the debug branch is different. Alright, let me do it for you.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). Be sure to use the correct command/args names.

**Comment by Pindar777** [comment]
@yzhang-gh Sorry for the circumstances. Working with PR is quite new for me (but you've probably guessed that already, lol).

**Comment by Pindar777** [comment]
@yzhang-gh I installed from VSIX and used the keymapping as proposed. 

    {
        "key": "ctrl+shift+a", 
        "command": "markdown.extension.editing._wrapBy",
        "args": {
            "before": "&bdquo;",
            "after": "&lddquo;"
        }    
    },   

The result is

test + shortcut = [object Object]test[object Object]

the arguments seem to not find there way into the function.

**Comment by yzhang-gh** [comment]
I've checked it. It turned out that the `args` was not unpacked so `before` received

```
{
    "before": "&bdquo;",
    "after": "&lddquo;"
}
```

**Comment by yzhang-gh** [comment]
Should be okay now.

**Comment by Pindar777** [comment]
Hi @yzhang-gh ,
thank you very much - it works like a charm:

  {
        "key": "ctrl+shift+a", //insert special quotation marks via markdown all in one
        "command": "markdown.extension.editing._wrapBy",
        "args": {
           "before": "&bdquo;",
           "after": "&ldquo;"
        }   
    },  

Cheers
