### ISSUE TITLE
`Cannot read property 'uri' of undefined` when command without any workspace folder open

### ISSUE THREAD

**Issue by ganxy1028** [yzhang-gh/vscode-markdown#666]
![fail](https://user-images.githubusercontent.com/26629457/80366010-1c1ac600-88bb-11ea-8f48-20031f8dd3aa.png)
在工作区有文件夹的情况下一切正常，但是没有的情况下所有的command都出错，console里面为`Cannot read property 'uri' of undefined` 
在 python 扩展里也有这个问题，提了 https://github.com/microsoft/vscode-python/issues/11291 ，似乎是 `workspace.workspaceFolders[0].uri.fsPath`  的问题。不知这个是不是也是？
感谢处理

**Comment by yzhang-gh** [comment]
感谢。现在应该可以了。

**Comment by ganxy1028** [comment]
感谢
