### ISSUE TITLE
Links to other .md files don't properly convert when printing to HTML

### ISSUE THREAD

**Issue by lesha-co** [yzhang-gh/vscode-markdown#667]
#### What is the problem?
I want to create a multi-page document with links between pages, then "print" it to HTML, but I can't because links still are to .md files

#### How can I reproduce it?
"Print to HTML" this markdown:
```
[more info](more-info.md)
```
Resulting HTML will have link to .md instead to .html (assuming `more-info.md` has been printed as well)
```
<a href="more info.md">more info</a>
```

This is rather a feature request. Would be great to have an option "assume referenced .md files are printed to HTML when printing to HTML"

**Comment by lesha-co** [comment]
Wow, that was fast, looking forward to new release!

**Comment by yzhang-gh** [comment]
It is now the default behavior as I presume it is rare to link to raw `.md` files. Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by lesha-co** [comment]
Looks like it's working! Big thanks!
