### ISSUE TITLE
Adding $ \{ \} $ to autoClosingPairs for math

### ISSUE THREAD

**Issue by scaomath** [yzhang-gh/vscode-markdown#669]
In the `language-configuration.json` file, it is impossible to add things like`$ \{ \} $`, `$ \big( \big)$` to either autoClosingPairs or surroundingPairs. Vscode just says `\` is not a valid string 

I wonder if currently there is a workaround on this.

**Comment by yzhang-gh** [comment]
I don't think we can have multiple characters in those "pairs".

You can use [snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets) to do the similar thing.

**Comment by scaomath** [comment]
> You can use [snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets) to do the similar thing.

Alright, thanks. Here is my snippet to achieve that:
```
"Curly bracket": {
		"prefix": "@{",
		"body": "\\{${1:}\\\\}"
	},
```

To enable it, one has to toggle `editor.quickSuggestions` to be true in settings for `[markdown]`. I guess vscode disable suggestions for markdown by default since suggestions might mess up things.
