### ISSUE TITLE
option to use markdown preview with other file extensions than .md

### ISSUE THREAD

**Issue by aisbergde** [yzhang-gh/vscode-markdown#671]
#### Markdown Preview is only shown for files with extension .md

I want to use GhostText to edit browser content with Visual Studio Code to get an instant Markdown Preview. But the Ghosttext plugin creates local files with the extension .tmp and No Markdown Preview is shown.

I have no idea how to enable Markdown Preview on .tmp files

Is there an option or is it possible to implement an option to use the Plugin on other files?

#### How can I reproduce it?

Create a file without extenion .md (or create a new unsaved file) and try to preview

#### Is there any error message in the console?

no error, but no preview Window is shown.

**Comment by yzhang-gh** [comment]
Actually the preview is provided by VSCode itself, to which this extension adds more Markdown syntax support.

You can configure the `files.associations` option to enable Markdown extension for other file types.
(`"*.tmp": "markdown"`)

**Comment by aisbergde** [comment]
perfect and easy solution!
