### ISSUE TITLE
Keyboard Shortcuts: use [BracketLeft] and [BracketRight]

### ISSUE THREAD

**Issue by kzhui125** [yzhang-gh/vscode-markdown#672]
使用mac，发现中文输入法状态下，下面两个快捷键不生效了，需要切换为英文状态

Key | Command
-- | --
Ctrl/Cmd + Shift + ] | Toggle heading (uplevel)
Ctrl/Cmd + Shift + [ | Toggle heading (downlevel)

研究了一下，可以使用`[BracketLeft]`代替`[`，使用`[BracketRight]`代替`]`，这样中英文状态下都生效。

类似于：

```json
[
    {
        "key": "cmd+shift+[BracketLeft]",
        "command": "markdown.extension.c1"
    },
    {
        "key": "cmd+shift+[BracketRight]",
        "command": "markdown.extension.c2"
    },
]
```

**Comment by yzhang-gh** [comment]
似乎没看到其他人有这个问题。如果你那里不行的话随时可以在 VSCode 自带的快捷键设置里修改。

**Comment by kzhui125** [comment]
<img width="515" alt="1" src="https://user-images.githubusercontent.com/11925432/80912521-10724800-8d70-11ea-8199-6d56515341b7.png">

keyboard shortcuts没搜到Toggle heading的命令，是不是没加上去

**Comment by yzhang-gh** [comment]
你可以直接搜按键的名字，这几个命令是纯快捷键，要搜的话也可以搜 `heading`

**Comment by kzhui125** [comment]
手动修改之后可以了

```json
[
    {
        "key": "cmd+shift+[BracketLeft]",
        "command": "markdown.extension.editing.toggleHeadingDown"
    },
    {
        "key": "cmd+shift+[BracketRight]",
        "command": "markdown.extension.editing.toggleHeadingUp"
    }
]
```
