### ISSUE TITLE
HTML files that work offline

### ISSUE THREAD

**Issue by frostius** [yzhang-gh/vscode-markdown#673]
## Problem
HTML output currently includes links to remote stylesheets (markdown.css & highlight.css)
This prevents output from displaying correctly when offline

## Solution
a) Allow an option for the stylesheets to be embedded (meh)
b) Allow an option for the stylesheets to be local (my preference)
c) Allow an option to exclude external stylesheets (also good)

## Background
We document our source primarily thru jsdoc headers and a markdown file for each source file.  We include a javascript file in each markdown file that ties all of the markdown HTML files together thru a sidebar table of contents.  We'd like this to work well offline.  Embedding the CSS in each file would be less than ideal.  

---

Edited by @yzhang-gh
- [ ] option 1: embed all the CSS/JS files in the HTML (as done inside VSCode)
- [ ] option 2: do not include/link any CSS files (unless they are needed by Markdown dialects, e.g. math)

**Comment by yzhang-gh** [comment]
> a) Allow an option for the stylesheets to be embedded (easiest)

This is possibly the only feasible way as those CSS/JS files may come from many different places (e.g. user option `preview.styles`, other Markdown dialect plugins etc.)

https://github.com/yzhang-gh/vscode-markdown/blob/7a52ea8a71eebb7803d0c2fbba706beb2e55d02d/src/print.ts#L119-L126

**Comment by frostius** [comment]
maybe option c?
c) allow an option to exclude external stylesheets
This would allow me to simply create a local stylesheet that includes the markdown & highlight CSS

**Comment by yzhang-gh** [comment]
It is hard to tell which ones are "external".

If you have a local stylesheet, why not include it with `preview.styles` option? (They will be embedded in the HTML.)
So if you are online, the HTML looks right.
And if you are offline, the markdown & highlight CSS also take effect.

**Comment by frostius** [comment]
We have, in fact, worked around it by including a local stylesheet that 
supercedes the markdown & highlight stylesheets.   To avoid repeating 
the CSS in every file we don't actually want it embedded, especially as 
we don't want to have to regenerate the HTML if the CSS gets tweaked.

The problem with this approach is that w/o removing the unneeded 
stylesheets, we have to keep track of whats in them so we can be sure 
we're correctly overriding them so that the online/offline versions 
match.  Omitting them would solve this problem.

Of course, we could certainly build a tool to do all of this, but your 
extension has been great and easily solves all of our needs but for the 
offline issue.


------ Original Message ------

**Comment by yzhang-gh** [comment]
Alright, I kind of understand want you mean by option c.
What you want is a pure HTML without any stylesheet, is it right?
(In contrast, the current solution is to make sure you have the same preview within and outside VSCode)

**Comment by frostius** [comment]
Yes

**Comment by yzhang-gh** [comment]
What about `highlight.css`?

**Comment by frostius** [comment]
For option c? I had assumed you'd simply have an option to disable the
external stylesheets.  It's simple enough to have the highlight css in a
local file

**Comment by yzhang-gh** [comment]
I agree.

**Comment by Glucksistemi** [comment]
I would appreciate option to remove all the styles (or all non-user-defined styles) too

**Comment by yzhang-gh** [comment]
Thanks to @Glucksistemi. Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) (option `print.includeVscodeStylesheets`).
