### ISSUE TITLE
Add somehow commands from trfsigns library

### ISSUE THREAD

**Issue by FilipChoc** [yzhang-gh/vscode-markdown#674]
#### What is the problem?
Hello, 
Is there some way how to add _trfsigns library_ to markdown, that I could see the symbols in the preview. (Pdf is not the problem. I am using pandoc and this works just fine.)

I am using: VS CODE with extensions: Markdown all in one, Markdown+Math

The goal would be for example to display this in preview correctly:
$$f(t) \laplace \overline{f}(s)$$

Thanks for any help

**Comment by yzhang-gh** [comment]
Both this extension and Markdown+Math use [KaTeX](https://katex.org/) to render math expressions in the preview. So you probably need to open a feature request [there](https://github.com/KaTeX/KaTeX).
