### ISSUE TITLE
Weird TOC generation

### ISSUE THREAD

**Issue by artificial-aidan** [yzhang-gh/vscode-markdown#675]
#### What is the problem?

Depending on the contents of a markdown file the TOC can fail to generate. I've found a few cases that this happens. Was able to reproduce 1 with fake text.

#### How can I reproduce it?

This markdown generates a correct TOC:

<pre>
# H1

- [H1](#h1)
  - [H2](#h2)
    - [H3](#h3)
    - [test](#test)
      - [test2](#test2)
      - [test3](#test3)
    - [Test4](#test4)
    - [Test5](#test5)
    - [test22](#test22)
  - [H2](#h2-1)
    - [Test6](#test6)
    - [test7](#test7)
    - [test8](#test8)
    - [test9](#test9)
  - [test10](#test10)
  - [test11](#test11)
    - [test12](#test12)
    - [test13](#test13)
    - [test14](#test14)
    - [test15](#test15)
  - [test16](#test16)
    - [test17](#test17)
    - [test18](#test18)
  - [test19](#test19)
  - [test20](#test20)
    - [test21](#test21)

### H3

Testing

#### test2

Words

#### test3

Words

### Test4

Words

### Test5

```
word
```

### test22

words

## H2

words

### Test6

words

### test7

words

### test8

words

### test9

words

## test10

words

### test12

words

### test13

words

### test14

words

### test15

Words

## test16

words

### test17

words

### test18

words

## test19

```
words
```

### test21
</pre>

And this generates an incorrect TOC:

<pre>
# H1

- [H1](#h1)
  - [H2](#h2)
    - [H3](#h3)
    - [test](#test)
      - [test2](#test2)
      - [test3](#test3)
    - [Test4](#test4)
    - [Test5](#test5)
  - [test20](#test20)
    - [test21](#test21)

### H3

Testing

#### test2

Words

#### test3

Words

### Test4

Words

### Test5

```word```

### test22

words

## H2

words

### Test6

words

### test7

words

### test8

words

### test9

words

## test10

words

### test12

words

### test13

words

### test14

words

### test15

Words

## test16

words

### test17

words

### test18

words

## test19

```
words
```

### test21
</pre>

#### Is there any error message in the console?

No

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
