### ISSUE TITLE
Auto preview not respect markdown.preview.fontSize

### ISSUE THREAD

**Issue by verdimrc** [yzhang-gh/vscode-markdown#676]
#### What is the problem?

When `markdown.extension.preview.autoShowPreviewToSide` is enabled, left-clicking a `.md` file in the file explorer will automatically open a preview tab. However, the fonts in this preview tab does not seem to respect the size specified in `markdown.preview.fontSize`.

#### How can I reproduce it?

1. Set `markdown.extension.preview.autoShowPreviewToSide` to `True`, and `markdown.preview.fontSize=20` (note: use large font size to clearly see the effect).

2. Left-click `.md` file in the file explorer. The auto-opened preview tab still uses smaller font size.

As comparison, this produces the expected behavior:

1. Right-click a `.md` file in the file explorer, then choose *Open preview*. The font size is larger.

#### Is there any error message in the console?

None observed.

**Comment by yzhang-gh** [comment]
I checked and it worked as expected on my laptop.

Can you disable any other Markdown extensions and try again?

**Comment by verdimrc** [comment]
On a fresh vscode-1.45.0 installation, I still experienced the issue. The only extension installed is `Markdown All in One` version 2.8.0, and this is the `settings.json`:

```json
{
    "markdown.extension.toc.orderedList": true,
    "markdown.extension.preview.autoShowPreviewToSide": true,
    "markdown.preview.fontSize": 22
}
```

**Comment by yzhang-gh** [comment]
![font](https://user-images.githubusercontent.com/7588612/81466561-42b6f600-9205-11ea-97ad-be3ec37b3932.gif)

Maybe you can try the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) although there shouldn't be any change regarding this.
