### ISSUE TITLE
command 'markdown.extension.editing.toggleUnorderedList' not found

### ISSUE THREAD

**Issue by DrStrangepork** [yzhang-gh/vscode-markdown#677]
#### What is the problem?

When I highlight some text and hit Cmd+L, I get a popup in the lower-right "command 'markdown.extension.editing.toggleUnorderedList' not found"

#### How can I reproduce it?

highlight some text and hit Cmd+L (on a Mac)

**Comment by yzhang-gh** [comment]
Thanks for the feedback. However, this extension does not register with `cmd+l` at all. Can you investigate a little bit using VSCode's "keyboard shortcuts" page?
