### ISSUE TITLE
Cannot open preview, won't use user CSS (conflict with Spellright)

### ISSUE THREAD

**Issue by yadayadaydadaa** [yzhang-gh/vscode-markdown#679]
Since possibly a recent update the keybinding for the side-by-side preview complains `command 'markdown.extension.togglePreviewToSide' not found`. Same with other previewing bindings. However from the command palette the preview opens… almost fine:

The CSS is awful now, very low contrast. I tried to put a user CSS, but it is only *randomly* read. Half of the time I get the error `Could not load 'markdown.styles': (filename)`.

**Comment by yzhang-gh** [comment]
> Since possibly a recent update the keybinding for the side-by-side preview complains `command 'markdown.extension.togglePreviewToSide' not found`.

Seems to work well on my laptop

![key](https://user-images.githubusercontent.com/7588612/81487832-0b435a80-9294-11ea-86b7-56e7720346eb.gif)

> The CSS is awful now, very low contrast.

It might be because of your theme, or other Markdown preview extensions you installed.

> Half of the time I get the error `Could not load 'markdown.styles': (filename)`.

VSCode only allows within workspace `markdown.styles` links (and `https`?).

**Comment by yadayadaydadaa** [comment]
It's something very odd. It happens only in a specific workspace. I've tried reloading the window. Closing the windows and reopening the workspace. I've tried disabling potentially conflicting extensions (this workspace has Spell Right enabled, which generally just kills the computer, so is not universally enabled), but no. The preview will not be shown. There's nothing specific in the workspace configuration file.

**Comment by yzhang-gh** [comment]
Have you tried disabling all other extensions

![image](https://user-images.githubusercontent.com/7588612/81488374-72640d80-929a-11ea-81ea-ba808b247cf4.png)

**Comment by yadayadaydadaa** [comment]
I created a new workspace, started a new `.md` file, and opened the preview just fine.
I closed the preview, enabled Spell Right, and 🥁🥁 I get the error.

**Comment by yzhang-gh** [comment]
😅

**Comment by yzhang-gh** [comment]
Close
