### ISSUE TITLE
Overlapping ranges are not allowed!

### ISSUE THREAD

**Issue by asbjornu** [yzhang-gh/vscode-markdown#682]
#### What is the problem?

When trying to format [this markdown document](https://gist.githubusercontent.com/asbjornu/648c2f9f20321aad22217e16a68268ad/raw/dde438df6359c0b7a6a05ae86fdc058ab11cacc4/other-features.md), VS Code fails with the error message:

>Command 'Format Document' resulted in an error (Overlapping ranges are not allowed!)

<img width="448" alt="image" src="https://user-images.githubusercontent.com/12283/81700130-8d847800-9468-11ea-995a-b1957aa10816.png">

#### How can I reproduce it?

With a clean install of VS Code and only `yzhang.markdown-all-in-one` installed, invoking "Format Document" on [this markdown document](https://gist.githubusercontent.com/asbjornu/648c2f9f20321aad22217e16a68268ad/raw/dde438df6359c0b7a6a05ae86fdc058ab11cacc4/other-features.md) should result in the above error. 

#### Is there any error message in the console?

> Command 'Format Document' resulted in an error (Overlapping ranges are not allowed!)
`onDidChangeNotification @ notificationsAlerts.ts:40`

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/12283/81700490-fd92fe00-9468-11ea-8bcd-55bb67d4316b.png">

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

The reason is you have two identical tables.

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by yzhang-gh** [comment]
Be careful. There is a serious bug.

**Comment by yzhang-gh** [comment]
Resolved.

**Comment by asbjornu** [comment]
Awesome, thanks @yzhang-gh!
