### ISSUE TITLE
Table of Contents being automatically created within document and deleting code

### ISSUE THREAD

**Issue by coxjames** [yzhang-gh/vscode-markdown#683]
#### What is the problem?
I open a md file in VS Code and after the first save this extension automatically generates a TOC halfway through the document. It also deletes content where the TOC is inserted.

#### How can I reproduce it?
I can provide an example md document, which has the TOC inserted about 400 lines into the document by this extension.

**Comment by yzhang-gh** [comment]
You can disable `toc.updateOnSave` option to solve the problem.

It would be better if you can attach your example document (pack it as `.zip` file and then you can attach it in the comments) as it means this extension detects a TOC where it shouldn't.

**Comment by coxjames** [comment]
[UserGuide.zip](https://github.com/yzhang-gh/vscode-markdown/files/4625747/UserGuide.zip)
This document ends up with 2 TOCs, one at about line 100 and the other at line 800

**Comment by yzhang-gh** [comment]
Can you describe what content they were (before they are replaced by TOCs)?

**Comment by coxjames** [comment]
[UserGuide.zip](https://github.com/yzhang-gh/vscode-markdown/files/4625771/UserGuide.zip)
Sorry, I did not realise I sent the "after" file. The attached is the original before the TOC was inserted by the extension. 

They appear to be dot point lists with hyperlinks at the beginning - (from lines 101 and 741)

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

(It is a similar issue as #549. I've added a sanity check that a TOC list item shouldn't contain plaintext.)

**Comment by coxjames** [comment]
Thanks. Can I suggest that the auto update of the TOC be turned off by default as it is not obvious from your feature list that this is automated. Having an extension discretely editing content is not ideal.

**Comment by yzhang-gh** [comment]
> Having an extension discretely editing content is not ideal.

I totally agree. But this feature is quite mature now, and personally I would like more users to be benefited from this. I'm going to add a piece of description to the `README`.
