### ISSUE TITLE
Plantuml is exported to HTML as <pre> not embedded SVG

### ISSUE THREAD

**Issue by wino45** [yzhang-gh/vscode-markdown#684]
#### What is the problem?

The plantuml is not exported to html, but properly previewed. Math is working in both.

Can you just embed SVG in HTML export ?

#### How can I reproduce it?

<pre>
# Message Sequence Charts

```plantuml
@startuml
participant a as "gggg"
a->b: go
@enduml
```
</pre>

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment]
Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). The exported HTML now has the same result as in VSCode.

**Comment by wino45** [comment]
In 83 html export is not working.

console.ts:137 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'apply' of undefined
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
console.ts:137 [Extension Host] stack trace: TypeError: Cannot read property 'apply' of undefined	at f.use (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:1022645)	at Object.extendMarkdownIt (c:\Users\PiotrW\.vscode\extensions\jebbs.plantuml-2.13.9\out\src\extension.js:34:27)	at Object.extendMarkdownIt (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:307336)	at Object.newEngine (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:269336)	at processTicksAndRejections (internal/process/task_queues.js:85:5)	at async Object.getEngine (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:268330)	at async Object.render (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:269392)	at async d (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:1111383)
t.log @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:65 [[object Object]]Cannot read property 'apply' of undefined
$onExtensionRuntimeError @ mainThreadExtensionService.ts:65
_doInvokeHandler @ rpcProtocol.ts:402
_invokeHandler @ rpcProtocol.ts:387
_receiveRequest @ rpcProtocol.ts:303
_receiveOneMessage @ rpcProtocol.ts:230
(anonymous) @ rpcProtocol.ts:105
fire @ event.ts:587
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
(anonymous) @ ipc.net.ts:592
fire @ event.ts:587
acceptChunk @ ipc.net.ts:239
(anonymous) @ ipc.net.ts:200
t @ ipc.net.ts:28
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
mainThreadExtensionService.ts:66 TypeError: Cannot read property 'apply' of undefined
	at f.use (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:1022645)
	at Object.extendMarkdownIt (c:\Users\PiotrW\.vscode\extensions\jebbs.plantuml-2.13.9\out\src\extension.js:34:27)
	at Object.extendMarkdownIt (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:307336)
	at Object.newEngine (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:269336)
	at processTicksAndRejections (internal/process/task_queues.js:85:5)
	at async Object.getEngine (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:268330)
	at async Object.render (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:269392)
	at async d (c:\Users\PiotrW\.vscode\extensions\yzhang.markdown-all-in-one-2.8.0\dist\extension.js:1:1111383)

**Comment by yzhang-gh** [comment]
Thank you. May I ask which plantuml extension you are using?

**Comment by wino45** [comment]
Newest. Version 1.2020.9, Local Render

**Comment by yzhang-gh** [comment]
Well, I mean which plantuml extension/plugin in VSCode 😅.

**Comment by wino45** [comment]
Extenstion version is 2.13.9

**Comment by yzhang-gh** [comment]
It is a bit different from other Markdown plugins as it requires external programs. (I cannot preview it as I don't have PlantUML installed on my PC.)

cc @1354092549 do you have any idea?

**Comment by wino45** [comment]
You can try the remote rendering as described in "Notice 1" of [PlantUML](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml)

**Comment by 1354092549** [comment]
***This is a bug of [PlantUML Extension](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml) (jebbs.plantuml-2.13.9)***
The extension does not implement `extendMarkdownIt` properly.
When `extendMarkdownIt` is called, there always causes a error even through a renderer for PlantUML is actually added.
*VSCode's Markdown Previewer* will ignore this error while *Markdown All in One* will fail, so you can preview it normally but can't export it to html.

**Comment by 1354092549** [comment]
This bug has existed for three years (qjebbs/vscode-plantuml@6430f2257b6cace4e7f289d35c97d713b6d36e4a)
Related line: https://github.com/qjebbs/vscode-plantuml/blob/30d82c89ade704d0f4f19740b708b05d62728862/src/extension.ts#L54

**Comment by 1354092549** [comment]
By the way, PlantUML Extension will create a `<img>` instead of a `<svg>`.
```html
<body class="vscode-light">
    <h1 id="message-sequence-charts">Message Sequence Charts</h1>
    <img style="background-color:#FFF;" src="https://www.plantuml.com/plantuml/svg/0/SoWkIImgAStDuIe0qfd9cGM9UIKAYGg9nGfAwK2Wn9MeQvTafP2Up-MGcfS2KWW0">
</body>
```

**Comment by yzhang-gh** [comment]
@1354092549 Thanks a lot! So we just need to wait for the fix from PlantUML.

**Comment by yzhang-gh** [comment]
Looks like PlantUML has fixed it.

**Comment by UTPALBHATT** [comment]
```

```plantuml
@startuml
participant a as "gggg"
a->b: go
@enduml
```
```
is working fine for me in `.md` file.
