### ISSUE TITLE
Table formatting does not work properly when using Korean langauge.

### ISSUE THREAD

**Issue by esesem** [yzhang-gh/vscode-markdown#685]
#### What is the problem?
When I run table formatting using short cut Alt + Shift + F, it does not work properly when using Korean characters. Korean characters have 2-byte width, I think this is not adopted to extension.

Here is an example after running table formatting.

```
| Contents | Description |
| -------- | ----------- |
| 안녕하세요    | 아침 인사       |
| 감사합니다    | 감사의 표시 고마움  |
```

It should be;
```
| Contents   | Description        |
| ---------- | ------------------ |
| 안녕하세요 | 아침 인사          |
| 감사합니다 | 감사의 표시 고마움 |
```

#### How can I reproduce it?
Please set Korean characters as 2-byte width in table formatting.

#### Is there any error message in the console?
No error message.

**Comment by esesem** [comment]
#100

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by esesem** [comment]
Thank you for your response! I will test dev build.
