### ISSUE TITLE
feature request: automatic enumerate and re-enumerate headers

### ISSUE THREAD

**Issue by aisbergde** [yzhang-gh/vscode-markdown#687]
#### What is the problem?

I want to request an option to automatic enumerate and re-enumerate headers:

before
```
# header 1
text
## header 2
text
# header 3
text
```
after
```
# 1.  header 1
text
## 1.1  header 2
text
# 2.  header 3
text
```

this could be combinded with TOC features

maybe this could be useful:

https://github.com/A4Vision/enumerate-markdown

**Comment by yzhang-gh** [comment]
Please see #457.
