### ISSUE TITLE
handling dot (.) in heading number scheme

### ISSUE THREAD

**Issue by hellt** [yzhang-gh/vscode-markdown#689]
#### What is the problem?
If the heading has a dot separated number, the link to it is generated incorrectly.

#### How can I reproduce it?
Create a heading
```
# 1.1 test heading
```

Start typing a link in the md body, the dialog with the internal links will suggest the href to be `11-test-heading`, it should be `1-1-test-heading` instead.

![image](https://user-images.githubusercontent.com/5679861/82370583-1414f880-9a19-11ea-952c-697d39f38683.png)

**Comment by yzhang-gh** [comment]
Probably you didn't enable the `githubCompatibility` option. (Note it will be changed to `slugifyMode`) in the next release.

**Comment by hellt** [comment]
@yzhang-gh enabling this setting had no effect on this particular behavior =(

**Comment by yzhang-gh** [comment]
Alright, I just checked and GitHub/GitLab both generate anchors like `11-test-heading` rather than `1-1-test-heading`. Which software are you using? Do you confirm `1-1-test-heading` really works?

**Comment by hellt** [comment]
@yzhang-gh I am using [Hugo](https://gohugo.io/) which uses blackfriday markdown engine afaik

here is an example of the heading https://netdevops.me/2019/creating-a-bootstrap-based-front-end-for-your-simple-rest-service/#1-1-get-your-tool-a-web-interface

**Comment by yzhang-gh** [comment]
Thanks for the information. It looks like Hugo is using Goldmark now ([the official docs](https://gohugo.io/getting-started/configuration-markup/)), from where I have seen a default configuration `autoHeadingIDType: github`. There is also an option `plainIDAnchors: true` for blackFriday.

Can you please play around with those configurations and see whether it can be compatible with GitHub?

**Comment by hellt** [comment]
thanks @yzhang-gh !

```
plainIDAnchors = true
```
worked
