### ISSUE TITLE
please add mermaid support

### ISSUE THREAD

**Issue by Yensan** [yzhang-gh/vscode-markdown#69]
- VSCode Version: Code 1.19.0 (816be6780ca8bd0ab80314e11478c48c70d09383, 2017-12-14T12:06:43.492Z)
- OS Version: Windows_NT x64 6.1.7601

Extension|Author (truncated)|Version
---|---|---
markdown-all-in-one|yzh|0.11.2

mermaid is used to wirte within markdown for graphic info. But I find this plugin does not support it. please add it.

**Comment by neilsustc** [comment]
I think [Markdown Preview Mermaid Support](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-mermaid) might meet your need.

But in my view, mermaid is not too widely used is common Markdown context, I would like not to add it to this extension recently.

**Comment by Yensan** [comment]
ok.
I love using markdown to write code document, but markdown is lack of tools in visual info. So I use mermaid. 
Maybe Jupter Notebook is better.

**Comment by yzhang-gh** [comment]
Please see [v3.0.0](https://github.com/yzhang-gh/vscode-markdown/blob/master/CHANGELOG.md#300-2020524)
