### ISSUE TITLE
auto-numbering for preview, outline, toc

### ISSUE THREAD

**Issue by dulm** [yzhang-gh/vscode-markdown#690]
just like typora :  http://support.typora.io/Auto-Numbering/
it not change the src text.

not like   https://marketplace.visualstudio.com/items?itemName=legendmohe.markdown-index
it change the src text, and need to run every time.

other issues:
https://github.com/yzhang-gh/vscode-markdown/issues/457
https://github.com/yzhang-gh/vscode-markdown/issues/555

**Comment by yzhang-gh** [comment]
It looks like you can just add that CSS code (in above Typora link) to your `markdown.styles`.

**Comment by yzhang-gh** [comment]
Close as this is done by external CSS.

**Comment by roamerop** [comment]
> just like typora : http://support.typora.io/Auto-Numbering/
> it not change the src text.
> 
> not like https://marketplace.visualstudio.com/items?itemName=legendmohe.markdown-index
> it change the src text, and need to run every time.
> 
> other issues:
> #457
> #555

@dulm Do you find how to deal with it?
