### ISSUE TITLE
Print Theme Setting Non-functional

### ISSUE THREAD

**Issue by mpearon** [yzhang-gh/vscode-markdown#691]
#### What is the problem?
Print Theme is non-functional

#### How can I reproduce it?
Set print theme setting and generate HTML
```json
"markdown.extension.print.theme": "dark"
```

#### Is there any error message in the console?

No errors present.

**Comment by yzhang-gh** [comment]
Currently, this option only affects the _syntax highlight_ of fenced code blocks (#534).

The reason is that, by default, VSCode doesn't set a background color for the preview. The background color is inherited from the VSCode theme.

For now, you need to find a Markdown dark style file (CSS) and put it in `markdown.styles` option.

(related #686)

**Comment by mpearon** [comment]
Thank you for getting back to me!  I’ve tried this out and it appears to be working.

**Comment by tx8821** [comment]
This issue has incorrect working IMHO. Not that this particular setting ("markdown.extension.print.theme") is disfunctional, but the bigger issue is that BY DEFAULT the output should match VS Code theme, which it doesn't! The description of the extension in VS Code extension's page clearly states: "The exported HTML should look the same as inside VSCode." which is a big LIE.
When VS Code is in its dark theme mode, print generates white document! This should not even need a setting, this should be a default - to generate same HTML as what you see in VS Code preview window. Again - the description of the extension states: "The exported HTML should look the same as inside VSCode."

**Comment by yzhang-gh** [comment]
The description for sure can be made more accurate.

As for more exported HTML styling mismatch, let's move to #686.
