### ISSUE TITLE
 footnotes are rendered to wrong HTML when the link has spaced title.

### ISSUE THREAD

**Issue by elonzh** [yzhang-gh/vscode-markdown#692]
#### What is the problem?

footnotes are rendered to wrong HTML when the link has spaced title.

![image](https://user-images.githubusercontent.com/8749411/82639624-aeed1d00-9c3b-11ea-94d8-f6386edfed54.png)

#### How can I reproduce it?

```markdown
- footnote1[^1]
- footnote2[^2]

[^1]: [footnote1](http://example.com)
[^2]: [footnote 2](http://example.com)
```

#### Is there any error message in the console?

No

**Comment by yzhang-gh** [comment]
Are you using another Markdown extension? This is out of the scope of this extension.

**Comment by elonzh** [comment]
@yzhang-gh No,  `yzhang.markdown-all-in-one` is the only extension for markdown

**Comment by yzhang-gh** [comment]
Alright, the description is a bit misleading. When we talk about Markdown footnote, we usually mean the real footnotes at the end of the document.

![image](https://user-images.githubusercontent.com/7588612/82659617-8d039280-9c5b-11ea-81b4-bbb4ba9d9390.png)
<sub>https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes</sub>

What you are using is called [reference links](https://spec.commonmark.org/0.29/#reference-link) (where whitespaces do matter).
If you look at where `^1` points to, it isn't working as you expect (I guess).

![image](https://user-images.githubusercontent.com/7588612/82660233-904b4e00-9c5c-11ea-9ff3-c94d0f4b7a2d.png)

---

BTW, if you are going to use the footnote plugin mentioned above, you can also install the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) of this extension for compatibility.

**Comment by elonzh** [comment]
I tried `bierner.markdown-footnotes` and it works great! Thanks

**Comment by yzhang-gh** [comment]
Glad to hear that.
