### ISSUE TITLE
Is it possible to turn off border around `inline-code`?

### ISSUE THREAD

**Issue by nemosmithasf** [yzhang-gh/vscode-markdown#693]
The border around the back-ticked code is somewhat distracting. Is there a way to disable it?

![Screen Shot 2020-05-23 at 3 35 59 PM](https://user-images.githubusercontent.com/14184529/82739143-2f2e8380-9d0b-11ea-93fe-8e21ba53da09.png)

**Comment by yzhang-gh** [comment]
Please find out `markdown.extension.syntax.decorations` option.

**Comment by nemosmithasf** [comment]
I had tried that, but it didn't make a difference

![Screen Shot 2020-05-24 at 6 48 16 AM](https://user-images.githubusercontent.com/14184529/82752231-96d7e380-9d8a-11ea-9592-a083e08acb60.png)

**Comment by yzhang-gh** [comment]
Have you restarted VSCode?

**Comment by nemosmithasf** [comment]
strange, I thought I had, but it turns out I didn't.

Thanks for your help.

**Comment by yzhang-gh** [comment]
👌
