### ISSUE TITLE
SVG in exported HTML got wrong mime type

### ISSUE THREAD

**Issue by wino45** [yzhang-gh/vscode-markdown#694]
#### What is the problem?
SVG images have wrong mime type when exporting to HTML:
<img src="data:image/svg;base64
instead of :
<img src="data:image/svg+xml;base64

#### How can I reproduce it?
`
![Client procedure](./figure.svg)*Client procedure*
`
and export to HTML. Add "+xml" to fix it.

**Comment by yzhang-gh** [comment]
Thanks. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
