### ISSUE TITLE
Numbering doesn't restart at 1

### ISSUE THREAD

**Issue by ashtou** [yzhang-gh/vscode-markdown#695]
#### What is the problem?

- Thanks for the new update, but numbering doesn't work as expected, i.e. it does not restart at 1 for sub-headers

- Also, is there any command to remove the numbering?

#### How can I reproduce it?

if you try to add section numbers to the sections below, `head1-2-1` will get `1.2.2.` instead of `1.2.1.`
```
# head1

## head1-1

### head1-1-1

## head1-2

### head1-2-1
```

**Comment by yzhang-gh** [comment]
Many thanks. Didn't notice this serious bug. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). (There is also a new command to remove it.)

**Comment by ashtou** [comment]
Great, thanks!
