### ISSUE TITLE
Loss of keyboard control when trying to close the split panel preview 

### ISSUE THREAD

**Issue by saveriomiroddi** [yzhang-gh/vscode-markdown#696]
#### What is the problem?

Sometimes, say, 30% of the times, when I try to close the split panel preview (the one activated by `Ctrl+K, V`), if I tap `Ctrl+W` on the right panel, I lose control of the keyboard (anything I can tap doesn't have any effect), and the panel doesn't close.

In order to close the panel then, I have to either click on the close (X) button with the mouse, or to click on the mouse with some panel, so that the cursor reappears, and the keyboard works again.

#### How can I reproduce it?

I can't stably reproduce it. I think it happens around 30% of the times. Trying it repeatedly triggers the issue (at least, on my system - an Ubuntu 20.04).

One way to reproduce it most, but not always, is:

- Open a Markdown file
- Tap Ctrl+K, V
- Tap Ctrl+1
- Tap Ctrl+2
- Tap Ctrl+W

at this point, when the bug reproduces, the panel won't close, and tapping any key on the keyboard won't have any effect.

#### Is there any error message in the console?

No, nothing.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. I tried and couldn't reproduce it on my Windows machine.

Can you disable this extension and then see whether you still have this issue?

**Comment by saveriomiroddi** [comment]
> Thanks for the feedback. I tried and couldn't reproduce it on my Windows machine.
> 
> Can you disable this extension and then see whether you still have this issue?

Interesting. It's not a problem of the plugin; it happens also with the plugin disabled (I thought the split screen was a functionality of the plugin). I'll report this to the VSC team.

Thanks, anyway!
