### ISSUE TITLE
TOC not generating properly using headers

### ISSUE THREAD

**Issue by ssbob** [yzhang-gh/vscode-markdown#699]
#### What is the problem?
Generating a TOC and it's not picking up some of the nested headers (4th header level). Problem exists in VSCode Mac (latest) with your package (latest, 3.0). I even tried your Atom version, same issue. 

#### How can I reproduce it?
Build a nested structure as follows:

H1
----H2
------H3
---------H4
---------H4.1
---------H4.2
---------H4.3
---------H4.4

When the TOC is created, and updated, H4.3, H4.4 are skipped, yet in VSCode I can see them just fine in the outline. I have played with the levels setting (1..6 and set it to 1..9 thinking it was a limitation) but that has not addressed it.

**Comment by yzhang-gh** [comment]
Can you provide a minimal reproducing example (text snippet)? I guess you have fenced code blocks between H4.2 and H4.3.

<img src="https://user-images.githubusercontent.com/7588612/82865480-65f9d900-9f59-11ea-8769-cf106edf87e8.png" alt="699" width="368px">

**Comment by ssbob** [comment]
Sure, let me know if this helps:

# Heading 1

## Heading 2

### Heading 3

#### Heading 4

```
code
block
```

Lorem ipsum dolor sit amet, nusquam intellegam te vel, iriure tractatos similique at usu. At eius dictas per, commodo eruditi dolorum et per. An audiam oporteat per. Ne prodesset argumentum.

#### Heading 4.1

```
code
block
```

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

- unordered element 1

- unordered element 2

- unordered element 3

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

#### Heading 4.2

```
code
block
```

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

- unordered element 1

#### Heading 4.3

```
code
block
```

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

- unordered element 1

- unordered element 2

- unordered element 3

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

```
code
block
```

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

#### Heading 4.4

```
code
block
```

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

```
code
block
````

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

- unordered element 1

- unordered element 2

- unordered element 3

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

- unordered element 1

- unordered element 2

- unordered element 3

Facer regione facilis ad quo, ne mundi possim nam. Omnium dolores efficiendi an duo, apeirian conclusionemque eu sea. His novum audire ea. Usu ipsum saepe assueverit an, te eos philosophia complectitur.

### Heading 3.1

**Comment by yzhang-gh** [comment]
It looks just right on my PC.

<img src="https://user-images.githubusercontent.com/7588612/82922807-aafb2b00-9fac-11ea-9724-2c6f246b7fd9.png" alt="699" width="402px">

**Comment by ssbob** [comment]
I just tested it on my system, and you are correct. So it has to be something in my text that is causing the interpreter to not understand the sequence of sections/headers. Let me try to copy things section by section and see if I can find the culprit. 

Thanks

**Comment by ssbob** [comment]
Something interesting, if I remove the code block from 4.2, then 4.3 and 4.4 show up. However, if I add back a blank code block, then it removes 4.3 and 4.4. I am using the following syntax 

```json {.line-numbers}
stuff
stuff
stuff
```

If I remove the {.line-numbers}, and stick with just json, then it's fine. Any thoughts?

**Comment by yzhang-gh** [comment]
Alright, we didn't allow `{` in the <code>```</code> line.

Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by ssbob** [comment]
Ah ok that would explain it, I tried your dev build (3.0.0-2) and it is doing the same thing. Will hang on and wait for the next release. I can live without line numbers.

**Comment by yzhang-gh** [comment]
Thanks. This time it should be really fixed.

**Comment by ssbob** [comment]
Works! Thanks for the updates.
