### ISSUE TITLE
checkTaskList on hightlight

### ISSUE THREAD

**Issue by lyspooner** [yzhang-gh/vscode-markdown#700]
#### What is the problem?
When highlighting, checkTaskList (alt+c) doesn't behave as I would expect. It ticks the line with the cursor but no highlighting.

#### How can I reproduce it?
Create 3 todo lines:
```
- [ ] a
- [ ] a
- [ ] a

```

Place your cursor at the beginning and highlight 2 lines (Hold Shift, Down, Down, Release Shift). Now tap (alt+c). All 3 lines will get ticked. This is counter to my intuition. Especially considering if you tap (alt+x) you will now cut only the top 2 lines and leave the third checked line. 

I recommend having it behave like cut and copy. If there is no highlighting then it acts on the line. If there is highlighting then it acts on the highlighted text. 

#### Is there any error message in the console?
N/A

**Comment by yzhang-gh** [comment]
> I recommend having it behave like cut and copy. If there is no highlighting then it acts on the line. If there is highlighting then it acts on the highlighted text.

Makes sense. Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by lyspooner** [comment]
I couldn't figure out how to download the dev build.

**Comment by yzhang-gh** [comment]
The autotests failed so there was no `.vsix` packaged. Now it is fixed and please check it again.

**Comment by lyspooner** [comment]
Looks good. Thank you :D
