### ISSUE TITLE
Duplication of the heder numbers

### ISSUE THREAD

**Issue by mpostol** [yzhang-gh/vscode-markdown#701]
#### What is the problem?

If the number of the subsections is 10+ operation `ass/update section numbers` doesn't remove old numbers

#### How can I reproduce it?

Add many (10+) subsections on the level `###`  and execute the command `add/update section numbers`

#### Is there any error message in the console?

Not sure.

**Comment by yzhang-gh** [comment]
Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
