### ISSUE TITLE
cant get "Markdown All in One: Remove section numbers"

### ISSUE THREAD

**Issue by dongshen** [yzhang-gh/vscode-markdown#702]
#### What is the problem?
After Ctr+Shift+P, I cant get "Markdown All in One: Remove section numbers"

And try remove this and reinstall , but still the same.

**Comment by yzhang-gh** [comment]
Please download the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) as some users may have downloaded an obsolete version.

**Comment by dongshen** [comment]
done！
