### ISSUE TITLE
Add feature that support section numbering start at level2 of headings

### ISSUE THREAD

**Issue by scjmjy** [yzhang-gh/vscode-markdown#708]
This isn't a bug,but a new feature request.
Now, TOC already has a support for changing levels.
![image](https://user-images.githubusercontent.com/3145541/83279188-51db0380-a207-11ea-9ccb-d065967837e8.png)

But I found that section numbering has no support for changing levels.
Many users treat level1 header to be article title,  so they want to numbering headers from level2.

**Comment by yzhang-gh** [comment]
Thanks. Let's track this at #555.
