### ISSUE TITLE
The picture in the board will write a clip to the current specified directory

### ISSUE THREAD

**Issue by januwA** [yzhang-gh/vscode-markdown#710]
hi, I want to directly use `ctrl + v` to directly put the pictures in the pasteboard into a folder in the current directory when writing markdown. This function is very cool. Is there any way to achieve it?

**Comment by yzhang-gh** [comment]
I know there are some extensions offering this feature, e.g. [Paste Image](https://marketplace.visualstudio.com/items?itemName=mushan.vscode-paste-image).

**Comment by januwA** [comment]
This is what I want, thank you very much
