### ISSUE TITLE
Feature request: Set level for section numbering

### ISSUE THREAD

**Issue by akshaybabloo** [yzhang-gh/vscode-markdown#718]
Currently, when using the section numbering, it is not possible to set the level of numbering like how we can do it with TOC - `"markdown.extension.toc.levels": "2..6"`.

It would be nice to have this feature to ignore, say, `#` and start numbering from `## 1.`.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Now the section numbering is aligned with the real TOC. (If you set `toc.levels` to `2..6`, then the numbering also starts with level 2.) Please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

See more at https://github.com/yzhang-gh/vscode-markdown/issues/555#issuecomment-636283040.
