### ISSUE TITLE
Incompatibility to jupyter / python extension (blank screen)

### ISSUE THREAD

**Issue by progmem64** [yzhang-gh/vscode-markdown#719]
#### What is the problem?
Most of the time when I open a jupyter notebook in VSCode the screen is blank and it will not render. Works fine again as soon as I disable the vscode-markdown extension.

#### How can I reproduce it?
Install vscode-markdown and open a jupyter notebook.

vscode-markdown: 3.0.0
python-extension: 2020.5.80290
macOS: 10.15.5
python: 3.7.7 (conda) + deps
code: 
```
Version: 1.45.1
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:33:47.663Z (3 wks ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
```

**Comment by yzhang-gh** [comment]
It sounds weird as I cannot imagine why they conflict.

Just checked and it works well on my PC.

<img src="https://user-images.githubusercontent.com/7588612/83949767-246e0580-a858-11ea-88d0-fcce5aa4cd2e.gif" alt="Jupiter" width="661px">

Did you see any error message from the console? And what if you only enable this extension and the Python one?

**Comment by progmem64** [comment]
I could not reproduce the issue on another system, so I fully reset and reinstalled VSCode + Extensions and can no longer reproduce the issue.
Sorry for the inconvenience. Apparently, something was buggy with the install itself.

**Comment by yzhang-gh** [comment]
No worries.
