### ISSUE TITLE
TOC broken when combined with Try .NET

### ISSUE THREAD

**Issue by Anil86** [yzhang-gh/vscode-markdown#722]
#### What is the problem?
Many headings in TOC are missed when using code-snippet format of [Try .NET](https://github.com/dotnet/try).

````markdown
```cs --region "InlineData" --source-file ./../../Learn_xUnit.Test/InlineDataShould.cs --project ./../../Learn_xUnit.Test/Learn_xUnit.Test.csproj
```
````

#### How can I reproduce it?
* Create Markdown file
* Add few headings
* Randomly add code snippet as shown above to different headings
* Create TOC

#### Is there any error message in the console?

AFAIK I can't see any.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. There was an issue detecting fenced code blocks. It should already be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
