### ISSUE TITLE
Extension takes some time to load

### ISSUE THREAD

**Issue by anishmittal2020** [yzhang-gh/vscode-markdown#725]
Really appreciate the extension and its quite useful.

#### What is the problem?

Extension takes a few seconds for the first time usage after fresh opening of VScode. We get error: Enter key is not found. And we have to wait approximately 30 seconds for it to be working.

#### Questions

There are a lot of features of this extensions that I don't use. For instance, I only use this for List Editing and for keyboard shortcuts for bold, italic, too etc. 

Do you think the extension would load faster, if the end user could specify which features they want to use (in `settings.json`)?

There are other markdown extensions, which don't have the issue of startup lag. May be it will be useful to disable those features which cause the excessive startup lag (and missing enter key)!

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

> Extension takes a few seconds for the first time usage after fresh opening of VScode. We get error: Enter key is not found. And we have to wait approximately 30 seconds for it to be working.

Yes, that is the VSCode mechanism. From my personal experience, it takes ~3 seconds to get activated on my laptop and usually less than 1 second on my desktop PC.
I'm superized that it can be 30 seconds 😲.
- How many VSCode extensions do you have?
- In addition, you can follow the [VSCode's performance guide](https://github.com/microsoft/vscode/wiki/Performance-Issues#profile-the-running-extensions) to see which extension/functionality causes this lag. (This will be really helpful as we don't need to add toggle for every small feature we have.)

Before that, you can try some settings we already provided (`syntax.decorations` and `tableFormatter.enabled`).

**Comment by anishmittal2020** [comment]
@yzhang-gh I have tried the settings that you shared (syntax.decorations and tableFormatter.enabled). I have been using it for over 10 days and I find that it is working great. I don't have those lag problem.

**Comment by yzhang-gh** [comment]
👍
