### ISSUE TITLE
`line-through` syntax decoration fails to display in large Markdown files 

### ISSUE THREAD

**Issue by quanticle** [yzhang-gh/vscode-markdown#727]
#### What is the problem?

The `line-through` syntax decoration for the `~~strikethrough~~` syntax fails to display on large markdown files (files with more than around 1600 lines of text). 

#### How can I reproduce it?

I have created a [large markdown file](https://gist.githubusercontent.com/quanticle/7be19a638f20bb55686f3d154f28fd4e/raw/3f2fc3faeb54a83424cc189bd9dd91161f5524a7/large_markdown.md), which should reproduce the problem. It was created by copy/pasting [this](https://github.com/mxstbr/markdown-test-file/blob/master/TEST.md) Markdown syntax test page repeatedly.

#### Is there any error message in the console?

I only see these two error messages:
```
[Violation] 'setTimeout' handler took 74ms
[Violation] Forced reflow while executing JavaScript took 69ms
```
but I'm not sure if they have anything to do with the problem.

**Comment by quanticle** [comment]
In `utils.ts`, the `isFileTooLarge` function has a hardcoded upper limit of 50kB. Would it be possible to make this upper limit configurable? It looks like that is what is preventing the strikethrough syntax decoration from rendering on large files.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It is by design as syntax decorations may cause performance issues on large files. https://github.com/yzhang-gh/vscode-markdown/issues/578#issuecomment-567081263.

> Would it be possible to make this upper limit configurable?

It is doable, although I don't think it is needed for most users. Probably you can fork this repository and change it on your side. GitHub Actions will package a `.vsix` for you just like the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by quanticle** [comment]
I created a PR (#728) which adds a knob to configure the file size. It's a small change, and one that I think might be useful to other users. Please let me know what you think.

**Comment by yzhang-gh** [comment]
Thanks for your contribution. I've made a few changes. It should be available in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) now.

**Comment by quanticle** [comment]
Great! Thank you for fixing up my change. I can use the dev build for now, but when do you think the changes will be pushed to stable?

**Comment by yzhang-gh** [comment]
Probably this weekend 😉.
