### ISSUE TITLE
"Backtick" quote (code) is not highlighted

### ISSUE THREAD

**Issue by Solybum** [yzhang-gh/vscode-markdown#729]
#### What is the problem?
In VSCode markdown preview, text surrounded by "backticks" is highlighted, but when exporting to HTML the resulting \<code\> element is not.

#### How can I reproduce it?
- Create a new markdown file
- Add any text surrounded by backticks, for example: \`Test\`
- Use the command Print current document to HTML

#### Is there any error message in the console?

No

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Let's track this at #686.

**Comment by Solybum** [comment]
Thanks, I did search for it but didn't think about "inline"...
