### ISSUE TITLE
Missing HTML <a> tag when generationg table of content

### ISSUE THREAD

**Issue by mozram** [yzhang-gh/vscode-markdown#730]
#### What is the problem?
Bitbucket markdown relies on <a> tag for jumping through the ToC.

#### How can I reproduce it?
For example in markdown:
```text
- [1. Introduction](#1-introduction)

<a name="1-introduction"></a>
# 1. Introduction
```

Currently the extension does not generate the a-tag, causing the ToC hyperlink not working in Bitbucket.

#### Is there any error message in the console?
No

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Please refer to #703.

In short, it is an issue of Bitbucket. Of course we can provide a **workaround** (as you said, `<a>` tags), but I would suggest someone make a standalone plugin for Bitbucket.
