### ISSUE TITLE
Can't open image file if the file name contains space if enable Img To Base64 option

### ISSUE THREAD

**Issue by yah01** [yzhang-gh/vscode-markdown#731]
#### What is the problem?
Can't open image file if the file name contains space if enable Img To Base64 option

#### How can I reproduce it?
write a markdown file:
```![](channel%20example.svg)```

and make sure there is a image file with name "channel example.svg".

try to print it to HTML

#### Is there any error message in the console?

无法读取文件 my\path\channel%20example.svg, 已使用图像路径而不是 base64 编码

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
