### ISSUE TITLE
Invalid auto-generated links to headers with LaTeX

### ISSUE THREAD

**Issue by jerry-sky** [yzhang-gh/vscode-markdown#732]
#### What is the problem?

Invalid auto-generated links to headers with some LaTeX markup.

#### How can I reproduce it?

The example document below clearly shows the issue.

```md
# Test Document

## Header with some $\LaTeX$

Some content

## Other header without LaTeX

Auto-generated links:

- a link [to a header with some $\LaTeX$](#header-with-some-math-xmlnshttpwwww3org1998mathmathmlsemanticsmrowmtextlatexmtextmrowannotation-encodingapplicationx-texlatexannotationsemanticsmathlatex)
- a link [to a header without LaTeX](#other-header-without-latex)
```

As you can see the auto-generated link to the header *with some LaTeX in it* is not valid (does not work after clicking on it).\
Instead of `#header-with-some-math-xmlnshttpwwww3org1998mathmathmlsemanticsmrowmtextlatexmtextmrowannotation-encodingapplicationx-texlatexannotationsemanticsmathlatex` the expected value should be `#header-with-some-latex`.

This issue also appears when a ToC for the document is generated.

#### Is there any error message in the console?

There isn't.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by jerry-sky** [comment]
@yzhang-gh 
Unfortunately, the build failed so I can't download the _Latest Development Build_.

**Comment by yzhang-gh** [comment]
Should be good now 😅.

**Comment by jerry-sky** [comment]
No problem, thanks for the effort! :)
