### ISSUE TITLE
text cursor invisible when editing task list

### ISSUE THREAD

**Issue by we-taper** [yzhang-gh/vscode-markdown#733]
#### What is the problem?

It is difficult to see the text cursor when editing task list. For example:

![gif](https://i.gyazo.com/download/01aecd52fbd4c6d089a7e3148b54f81b.gif?_ga=2.67049128.723083590.1593078009-741511812.1593078009)

#### How can I reproduce it?

As shown above. The theme is `Light (Visual Studio)`.

I think it will be great to change the default color for tasklist to grey.

**Comment by yzhang-gh** [comment]
哈哈哈，为啥不直接戳我.

看起来和这个插件没关系，应该是别的插件把它变黑了（猜测你用了 TODO 这种功能的插件）

<img src="https://user-images.githubusercontent.com/7588612/85705494-d8560880-b713-11ea-9267-4d3987baead2.png" alt="theme" width="516px">

安利你一个主题 [GitHub Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme)

再安利你一个[插件](https://marketplace.visualstudio.com/items?itemName=yzhang.dictionary-completion)，用这个[开发版](https://github.com/yzhang-gh/vscode-dic-completion/actions/runs/147315122)（Python 也能用哦😏）

**Comment by we-taper** [comment]
I thought many people had the same problem.

In the end I found out this is caused by the [TODO tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree) plugin. Disable that should work.
