### ISSUE TITLE
Inline code block outline is too dark on light background

### ISSUE THREAD

**Issue by nyanpasu64** [yzhang-gh/vscode-markdown#734]
#### What is the problem?

If "Syntax: Decorations" are enabled, and you pick a light theme, then inline code blocks have too dark of an outline around them.

#### How can I reproduce it?

- Set `"markdown.extension.syntax.decorations": true`.
- Set `"workbench.colorTheme": "Default Light+"` (switch to light editor color theme).

Screenshot:

![vscode-markdown code blocks](https://user-images.githubusercontent.com/913957/85708517-1cf08e00-b699-11ea-97db-2f03d20dc93e.png)

**Comment by yzhang-gh** [comment]
Thanks for the feedback. The color was picked based on a dark theme I was using, although I switched to a light one recently.

We now have the API to know the theme kind (https://github.com/microsoft/vscode/issues/32813#issuecomment-617843228) but picking a proper color is still challenging as there are many different themes.

**Comment by nyanpasu64** [comment]
Does vscode's extension or theme engine let you pick the color by blending 10-20% of the foreground color into the background color (linearly interpolating between them) in linear or sRGB-gamma color space?

**Comment by yzhang-gh** [comment]
That's a good idea, although we cannot access the theme color yet.

**Comment by Lemmingh** [comment]
I don't think we really need the actual color value. **Color reference sounds enough** in this case.

What about `editor.selectionBackground`?

**Comment by yzhang-gh** [comment]
I roughly know that VS Code now provides ThemeColor APIs? As for which color to use, we can play around with it and then decide.

**Comment by Lemmingh** [comment]
> VS Code now provides ThemeColor APIs?

Emmm ... No. The `ThemeColor` class has **NOT** been changed. It still only acts as a reference to workbench color, and the VS Code team seems unwilling to expose the actual value inside.

---

> play around

I only tested *selection colors* and *word highlight colors* with the built-in **Light**, **Dark**, and **Monokai** themes, and the following looked good to me:

* `editor.selectionBackground`
* `editor.wordHighlightStrongBackground`

Thinking `selectionBackground` is usually brighter, I suggested it.

I'm on VS Code 1.51.0, on Windows, with a calibrated 100% sRGB display.

**Comment by yzhang-gh** [comment]
👍

**Comment by Lemmingh** [comment]
Let's try it?
https://github.com/yzhang-gh/vscode-markdown/actions?query=workflow%3ACI+branch%3Aadd%2Fdecoration-color

**Comment by yzhang-gh** [comment]
Nice work!

Just to add a few screenshots

**GitHub Light**
![image](https://user-images.githubusercontent.com/7588612/98656033-285c0180-237b-11eb-8a20-14b84fda56e0.png)

**GitHub Dark**
![image](https://user-images.githubusercontent.com/7588612/98656102-3dd12b80-237b-11eb-8d47-6309bac82a2b.png)

Actually, I don't have a strong preference on the colors. So looks good to me.

**Comment by Lemmingh** [comment]
If nothing is wrong, I will push to `master` at **2020-11-15**T**12:00**Z.
