### ISSUE TITLE
Convert inline link to reference link

### ISSUE THREAD

**Issue by yumetodo** [yzhang-gh/vscode-markdown#736]
# Abstruct

Markdown provides multiple way to create link.

example1:

````markdown
[foo](http://example.com) [bar] [hoge](http://example.com)

```markdown
[foo] [bar](http://example.com) [hoge]
```
````

example2:

````markdown
[foo] [bar] [hoge]

```markdown
[foo] [bar](http://example.com) [hoge]
```

[foo]: http://example.com
[hoge]: http://example.com
````

I propose to add the ability to convert link syntax from example1 to example2.

# Background

`grep` cannot be used for this case because grep cannot recognize markdown code block or code syntax.

ref(Japanese): https://qiitadon.com/web/statuses/104419328868979420

**Comment by yzhang-gh** [comment]
Thanks for the suggestion. Would like to see if anyone want to help.

**Comment by Lemmingh** [comment]
Duplicate of #260

**Comment by yzhang-gh** [comment]
Thanks. Then let's track it at #260.
