### ISSUE TITLE
Table formatting shortcut doesn't work in macOS

### ISSUE THREAD

**Issue by onewildgamer** [yzhang-gh/vscode-markdown#738]
#### What is the problem?
In macOS `opt+shift+f` or `ctrl+shift+I` `cmd+shift+I` are not working, can someone tell me the shortcut for the table formatting in macOS?

#### How can I reproduce it?
Install VS Code in macOS (Mojave) and install the plugin vscode-markdown. Try to format a table like lines with pipes.

**Comment by yzhang-gh** [comment]
It should be

<img src="https://user-images.githubusercontent.com/7588612/86103237-175ad400-baef-11ea-90cf-c3a553240ec7.png" alt="key" width="325px">

https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf

If it doesn't work for you, you may also check whether the text is in valid Table syntax.

**Comment by onewildgamer** [comment]
Thank you, the table format format was wrong. Sorry to bother.
