### ISSUE TITLE
Description of `Feature Contribution` in Visual Studio Code Extension page seems broken

### ISSUE THREAD

**Issue by iodar** [yzhang-gh/vscode-markdown#739]
#### What is the problem?

Description of tab `Feature Contribution` in Visual Studio Code extension page seems broken.

#### How can I reproduce it?

Open extension in Visual Studio Code.

![image](https://user-images.githubusercontent.com/47027105/86237918-eafd9100-bb9c-11ea-86f2-3ba8c56ac0f0.png)

#### Visual Studio Code Version
```
Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:20.174Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It is because we use these `%placeholder%`s to do localization (dates back to #240). I am not sure whether there is a better way now. But it doesn't seem to be a big problem (as you can see the description in the Settings UI).

**Comment by iodar** [comment]
Thank you for the advice with the description in the Settings UI @yzhang-gh. I did not think about this when I was creating this issue. Should I close this issue then since there is an workaround or should I leave it open?

**Comment by yzhang-gh** [comment]
Let's just leave it open.

**Comment by iodar** [comment]
Interestingly it works when I build the extension from source and install it with `Install from VSIX`. It also works with the latest build from GitHub which I have installed the same way.

![markdown-vscode](https://user-images.githubusercontent.com/47027105/86289850-b0bbe000-bbec-11ea-8eb9-c0a9184b51c6.png)

**Comment by yzhang-gh** [comment]
😮 That's weird. They are still `%...%` on my PC.

**Comment by iodar** [comment]
Oh I'm sorry. I forgot to mention that the second screenshot was taken on my linux machine. I've updated my comment above by adding information about the my vscode version and my os.

**Comment by yzhang-gh** [comment]
Thanks for the information 👍. I would say let it go. We haven't seen many people complaining about it yet 😅.

**Comment by Lemmingh** [comment]
microsoft/vscode#54111

**Comment by yzhang-gh** [comment]
@Lemmingh Thanks.
