### ISSUE TITLE
Autocomplete latex deletes initial backslash

### ISSUE THREAD

**Issue by ljarin** [yzhang-gh/vscode-markdown#740]
#### What is the problem?

When I tab-complete a latex function inside a `$$` block, it often strips the initial backslash that I need for latex. How can I prevent this? e.g. It goes from `\mathbf` to `mathbf{}`

#### How can I reproduce it?
See above. I worry maybe it's some other extension interfering though.

#### Is there any error message in the console?

no

**Comment by yzhang-gh** [comment]
It is complicate (there are so many different usages of `tab`).

I am using `emmet.triggerExpansionOnTab: true` and it becomes `$\<mathbf></mathbf>$`. If I disable that option, the outcome is <code>$\mathbf &nbsp;$</code> 😑. So I always use `enter` key to accept a completion.

**Comment by ljarin** [comment]
I just tested it, and I get the same behavior with enter or with clicking on the word.
Hm anyway it's probably something else interfering; feel free to close

**Comment by yzhang-gh** [comment]
Thanks for the update. You can disable some extensions to see whether it makes any difference.

**Comment by ljarin** [comment]
https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes It was an extension called Markdown Notes, if anyone finds this in the future
