### ISSUE TITLE
Proper TOCs that don't modify the source document

### ISSUE THREAD

**Issue by yadayadaydadaa** [yzhang-gh/vscode-markdown#741]
I wonder if it would be possible to support [markdown-it-toc-done-right](https://www.npmjs.com/package/markdown-it-toc-done-right) for TOCs instead/in addition to the current document-modifying approach?

**Comment by yzhang-gh** [comment]
It adds extra syntax (e.g. `[[TOC]]` or whatever) to the commonly used Markdown. You need a standalone Markdown extension to do this.

Take "Markdown Footnotes" as an example (it adds additional Markdown syntax for footnotes), you can install [Markdown Footnotes](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-footnotes) which uses [`markdown-it-footnote`](https://www.npmjs.com/package/markdown-it-footnote).

This extension is compatible with them.

**Comment by yzhang-gh** [comment]
Just use [Markdown AutoTOC](https://marketplace.visualstudio.com/items?itemName=wibblemonkey.markdown-auto-toc) along with this extension.
