### ISSUE TITLE
Ignore title on table of contents

### ISSUE THREAD

**Issue by tiagoporto** [yzhang-gh/vscode-markdown#743]
Congrats, this is an amazing and helpful extension.

I'd like to understand if is possible ignore some title on the generated TOC.

My file is

```md
# Title

## Table of contents
- [Title](#title)

## Subtitle1
## Subtitle2
```

When I generate the automatic TOC, this is the generated code

```md
# Title

## Table of contents
- [Title](#title)
  - [Table of contents](#table-of-contents)
  - [Subtitle1](#subtitle1)
  - [Subtitle2](#subtitle2)
```

Is there an way to ignore `#title` and `#table-of-contents` and list only the next titles?

Thank you

**Comment by yzhang-gh** [comment]
There are several ways (please see [`README`](https://github.com/yzhang-gh/vscode-markdown#table-of-contents)).

**Comment by tiagoporto** [comment]
@yzhang-gh thank you

`omittedFromToc` supports a glob path?

Example
```
"markdown.extension.toc.omittedFromToc": {
  // Use a path relative to your workspace.
  "**/*.md": [
      "# Introduction",
      "## Also omitted",
  ] 
}
```

**Comment by yzhang-gh** [comment]
> `omittedFromToc` supports a glob path?

Not yet.
