### ISSUE TITLE
`git pull` does not trigger updated render of the preview

### ISSUE THREAD

**Issue by Joelbear5** [yzhang-gh/vscode-markdown#744]
#### What is the problem?
`git pull` when there are updates to the README.md while the preview is open does not trigger a re-render of the preview until changes are made locally .

#### How can I reproduce it?
Checkout a branch with a `README.md` file.
Update the `README.md` on that branch on another computer or directly online in git, commit and push changes.
Run `git pull` locally and README.md file will update, however the Preview README.md will not update.
Add a space character or make any change, and the preview will render updates.

#### Is there any error message in the console?
No

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Actually this is controlled by VSCode ('s built-in Markdown extension). You can file an issue there (VSCode repository).
