### ISSUE TITLE
Possible to completely hide markdown decorations?

### ISSUE THREAD

**Issue by sinewave** [yzhang-gh/vscode-markdown#746]
#### What is the problem?
I enjoy writing in markdown but would prefer to not see the markdown decorations when not editing that word/text and ideally never see them... similar to how Notion handles it i.e. they act more as a shortcut to add formatting

I tried disabling the "Add syntax decorations..." checkbox but that didn’t seem to do anything or I'm misunderstanding what that's supposed to do.

Is there any way to achieve this with this extension or theming?

Thx

**Comment by yzhang-gh** [comment]
> I tried disabling the "Add syntax decorations..." checkbox but that didn’t seem to do anything or I'm misunderstanding what that's supposed to do.

Did you restart VSCode? Which decorations are you still seeing?

> Is there any way to achieve this with this extension or theming?

There was an attempt called "plain theme" #185. However, the conclusion is it should be done by the theme author. (It is very hard for non-theme extension.)

**Comment by sinewave** [comment]
Yea, tried restarting. Here's an example of what I'm seeing... I'm assuming the decorations refer to the asterisk/hashes/etc that markdown adds?

<img width="1503" alt="markdown decorations" src="https://user-images.githubusercontent.com/84384/86873525-51018100-c093-11ea-879b-19987e1eb977.png">

**Comment by yzhang-gh** [comment]
Uh, it has nothing to do with this extension, you can check by disabling this extension. It is the syntax highlight of the theme.

**Comment by sinewave** [comment]
Ah, do you know if there is a way to remove the markdown decorations by using a different theme or some other way/setting? 

I'm using the default light theme and don't have any other extensions enabled.

**Comment by yzhang-gh** [comment]
Well, it (as in your screenshot) is not called decoration, it is syntax highlight, you can even see it here

```markdown
# Heading

**bold** and _italic_
```

If you change VSCode's theme, you can see each theme has its own "highlight" (font weight, color etc.). Probably you can try [GitHub Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme).

---

Wait, you want to hide `*`? You cannot hide it in "source code" mode. This is not a WYSIWYG editor (yet).

The best someone can do is to dim `*`, `_` etc., just like the "plain theme" I mentioned above. AFAIK, there is no such a theme aimed for this.

**Comment by sinewave** [comment]
Yea, that’s what I was after although I assumed it wasn’t possible but then got confused by that setting as i didn’t quite understand what decorations are 😬

Thx for replying! I’ll try to explore minimizing the effect of the syntax highlighting through themes.
