### ISSUE TITLE
Converting multiple md files to html

### ISSUE THREAD

**Issue by Lamboluk** [yzhang-gh/vscode-markdown#747]
Hello everyone,

I use the extension in Visual Studio Code an it works fine. But I'm looking for a way to convert for example 200 md files to html but that 200 files I have to open file by file. Has someone a better way to convert the markdown files fast to html?                        I do not like pandoc and other converters because it's not so a beautiful output at this all-in-one converter.
So I'm happy to continue using this extension.
Thanks for helping!!!

I appreciate it.

**Comment by yzhang-gh** [comment]
Currently we cannot do this (batch export). Would like to know more about your file structure as I assume you don't put 200 Markdown files in a single folder and won't want to have 200 more HTML files in the same one (related #594).

**Comment by Lamboluk** [comment]
> Currently we cannot do this (batch export). Would like to know more about your file structure as I assume you don't put 200 Markdown files in a single folder and won't want to have 200 more HTML files in the same one (related #594).

It is for a documentation for a product. So each product has it's own documentation.

**Comment by Lamboluk** [comment]
> Currently we cannot do this (batch export). Would like to know more about your file structure as I assume you don't put 200 Markdown files in a single folder and won't want to have 200 more HTML files in the same one (related #594).

Is there a possibility to run the extension without visual studio code for example on cmd?

**Comment by yzhang-gh** [comment]
I'm afraid not.

**Comment by Lamboluk** [comment]
> I'm afraid not.

That's annoying. But thanks for you help anyway!

**Comment by yzhang-gh** [comment]
It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build). I've added a new command "Print documents to HTML". Please check it out.
