### ISSUE TITLE
Would you please make the command Cril + Shift + ] in the demo easier to recognize?

### ISSUE THREAD

**Issue by ruichima** [yzhang-gh/vscode-markdown#748]
I am new to this extension. Thank you for building such a helpful extension!

I think it was my problem, but it consufed me some time: it seems that the keyboard shortcut `Cril + Shift + ]` looks like `Cril + Shift + J` in [this demo](https://github.com/yzhang-gh/vscode-markdown/raw/master/images/gifs/section-numbers.gif). So... would you please make the command easier to recognize? Or type it in README.md?

Thank you for your reading.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Actually there is some description in the [Keyboard Shortcuts](https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts-1) section.

As for the GIF, feel free to make a new one (if you really want 😅). I would recommend software ScreenToGif, font Consolas and [GitHub Theme](https://marketplace.visualstudio.com/items?itemName=GitHub.github-vscode-theme) light 😉.

**Comment by ruichima** [comment]
Thank you for your replyment! I should have read the manual more carefully... By the way, thank you for your suggestions on making gif : )
