### ISSUE TITLE
Feature Request: Drag and Drop filename from sidebar to document as a link

### ISSUE THREAD

**Issue by AceTheWiz** [yzhang-gh/vscode-markdown#749]
#### What is the need?
I want to be able to Drag and Drop a filename, from sidebar, to a markdown document as a link.

**Comment by yzhang-gh** [comment]
It seems that we cannot do this with extension.

**Comment by AceTheWiz** [comment]
That is sad :(
Thanks

**Comment by Lemmingh** [comment]
VS Code now has an API proposal called "TextEditorDrop": <https://github.com/microsoft/vscode/issues/142990>

See the initial draft at: <https://github.com/microsoft/vscode/commit/bfc026b97a1c28d8288aa2510c066d03e5bcde54>

**Comment by cxcorp** [comment]
This feature is included in [VS Code 1.70](https://code.visualstudio.com/updates/v1_70#_drop-into-editor-api).

1. Start dragging image from Explorer sidebar onto open markdown editor
2. After you've started dragging the image, hold down Shift
3. Release image onto editor

![](https://code.visualstudio.com/assets/updates/1_70/api-drop.gif)
