### ISSUE TITLE
python3 syntax highlighting currently not working

### ISSUE THREAD

**Issue by parkershamblin** [yzhang-gh/vscode-markdown#750]
#### What is the problem?
Code blocks that are marked with python3 are not highlighted.
![image](https://user-images.githubusercontent.com/53675680/87243541-c7d8aa00-c404-11ea-8d00-e0b9acbed520.png)

#### How can I reproduce it?
Here is the markdown of a random Leetcode problem: https://gist.github.com/parkershamblin/bde8ad0db5f1e78a68dc11c98b59d06a  After downloading it and opening it up in vscode try running the command: 
Markdown: Print current document to HTML 

The resulting html page should look like the one shown above.

#### Additional details
If you edit the markdown and change "python3" to "python" in front of the code blocks you will get syntax highlighting and the resulting html page will look like this.
![image](https://user-images.githubusercontent.com/53675680/87243569-1128f980-c405-11ea-9a9c-1aa9d1995aa4.png)
This is my current solution. However, you can see that the syntax highlighting is not 100% accurate with this approach (i.e. type hinting not being supported).

**Comment by yzhang-gh** [comment]
This is handled by VSCode's built-in Markdown extension
(https://github.com/microsoft/vscode/blob/eed137ff2ef7d6b96aa9a7b41307b4c21cda4627/extensions/markdown-language-features/src/markdownEngine.ts#L326-L335)
which uses `highlight.js` that doesn't seem to support `python3`.

**Comment by Lemmingh** [comment]
IIRC, it's called [**syntax highlighting for embedded languages**](https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#embedded-languages). The highlighting engine detects embedded languages in parent file, and redirect them to proper extensions that support the language.

So far, **scope redirection for code blocks in Markdown is provided by VS Code's built-in** [`vscode.markdown` extension](https://github.com/microsoft/vscode/tree/master/extensions/markdown-basics). Sadly, it provides `python` (`meta.embedded.block.python` scope) but not `python3`. You can look up its TM grammars (`syntaxes/markdown.tmLanguage.json`) and contribution (`package.json`) to confirm this.

Additionally, I did a *quick search* in Marketplace, but cannot find any extension that contributes to `python3`. **Those that provides syntax highlighting for Python 3 contribute grammars to language `python`.**

Wow, I have no idea how to solve this problem.

**Comment by Lemmingh** [comment]
Oops, sorry for the noise.

I though you were talking highlighting in editor.

**Comment by yzhang-gh** [comment]
@Lemmingh Thanks for the input 😉.

**Comment by parkershamblin** [comment]
> This is handled by VSCode's built-in Markdown extension
> (https://github.com/microsoft/vscode/blob/eed137ff2ef7d6b96aa9a7b41307b4c21cda4627/extensions/markdown-language-features/src/markdownEngine.ts#L326-L335)
> which uses `highlight.js` that doesn't seem to support `python3`.

Thank you for the quick follow up. Yes, I actually tried installing highlight.js on my own to see if I could fix the problem but as you mentioned it doesn't look like highlight.js doesn't support python3 syntax highlighting right now.

**Comment by yzhang-gh** [comment]
Hope VSCode will adopt a better syntax highlighter in the future.

**Comment by Lemmingh** [comment]
highlightjs/highlight.js#2633
