### ISSUE TITLE
Enter and Backspace (Delete on Mac) keys do not work

### ISSUE THREAD

**Issue by manastalukdar** [yzhang-gh/vscode-markdown#751]
#### What is the problem?

Enter and Backspace (Delete on Mac) keys does not work with latest version of extension. Disabling the extension allows both keys to work as expected.

This is not a delay issue as reported [earlier](https://github.com/yzhang-gh/vscode-markdown/issues/335).

#### How can I reproduce it?

Open a markdown file in VSCode. Hit Enter or Backspace (Delete on Mac) keys. Nothing happens. Disable extension. Keys work again.

#### Is there any error message in the console?

Yes, but nothing that looks relevant.

### VSCode

```
Version: 1.48.0-insider (user setup)
Commit: c828a5339bca7222fd8f56ab98361a98f736d185
Date: 2020-07-14T05:39:53.264Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19041
```

### Extension

3.1.0

### OS

Windows 10 and MacOS (Darwin x64 19.5.0)

**Comment by yzhang-gh** [comment]
Thanks. But I cannot reproduce here. Probably you can check what if you disable all other extensions (except for this one).

<img src="https://user-images.githubusercontent.com/7588612/87495449-09c35380-c684-11ea-8aed-a986b8960832.gif" alt="nothing" width="457px">

**Comment by manastalukdar** [comment]
@yzhang-gh , is the failure to reproduce with VS Code Insiders?

**Comment by manastalukdar** [comment]
I wonder if this is related: https://github.com/microsoft/vscode/issues/102180. I am seeing the same errors in developer tools console.

**Comment by manastalukdar** [comment]
Workaround: Start VS Code explicitly as Administrator on Windows. (sudo on *nix oses)

**Comment by yzhang-gh** [comment]
> @yzhang-gh , is the failure to reproduce with latest VS Code Insiders?

I'm using the stable build. Then let's wait for more information.

**Comment by apeltzer** [comment]
Using 1.47.1 and can confirm the same behaviour.

**Comment by apeltzer** [comment]
<img width="638" alt="Bildschirmfoto 2020-07-16 um 15 52 54" src="https://user-images.githubusercontent.com/2359510/87679401-6a35bc00-c77c-11ea-95f8-7e7030c5f198.png">

**Comment by yzhang-gh** [comment]
@apeltzer Thanks for the information. Please see https://github.com/yzhang-gh/vscode-markdown#faq if you have seen that warning. Not sure whether yours is the same issue as this one.

**Comment by apeltzer** [comment]
A wipe and reinstall solved it for me at least 👍

**Comment by manastalukdar** [comment]
Issue resolved with latest version of Insiders:

```
Version: 1.48.0-insider
Commit: 5e5fa3edde19d38ac512d65ccefe2a12ecab025a
Date: 2020-07-16T13:10:40.625Z
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Darwin x64 19.5.0
```

**Comment by yzhang-gh** [comment]
Thanks for the update.
