### ISSUE TITLE
Feature request: Aligning Lists

### ISSUE THREAD

**Issue by nomad101** [yzhang-gh/vscode-markdown#752]
#### What is the problem?

Align markdown list

#### How can I reproduce it?

At the moment, if you have a list and the text wraps, the words on the next line don't left align . For example, ideally, the new line words ('particular', 'if', 'full') align with the word 'Civility' (as you would see in preview view). 

![Screenshot2](https://user-images.githubusercontent.com/27806124/87521199-f57b5880-c67b-11ea-8c06-c19dfd327e76.png)

 It would be great if this was possible in the editor view. It will make reading lists easier on the eye (and especially for long lists). 

Thanks for producing this great extension.

**Comment by yzhang-gh** [comment]
Please check out option `editor.wrappingIndent`.

**Comment by nomad101** [comment]
Thanks for the quick reply.

I did try that. But the problem is, when selecting `editor.wrappingIndent` to indent, it also applies it all paragraphs in a document (which look ugly), and not only to lists. 

Also, in a list it indents to the right of the first word, and doesn't align with it.

**Comment by yzhang-gh** [comment]
Text wrapping is handled by the editor (VSCode itself). Extensions have no control over it.

> Also, in a list it indents to the right of the first word, and doesn't align with it.

The indentation size should be the same as shown in the right bottom corner. Change it to `Spaces: 2` and they will be aligned, although that doesn't work for ordered lists.

**Comment by nomad101** [comment]
What you suggest for lists does work, though it also applies to (messes up) regular paragraphs. 

As you've helpfully pointed out, it's an issue with the editor. 

Thanks again for your help.

**Comment by yzhang-gh** [comment]
Thanks. Close as we have no way to do it on this (extension) side.
