### ISSUE TITLE
suggestion : Add an option to higlight double quoted strings : i.e. "double quoted string"

### ISSUE THREAD

**Issue by serge-hulne** [yzhang-gh/vscode-markdown#755]
#### What is the problem?
This is a suggestion / request:

Would it be possible to add an option for higlighting double quoted strings : 

i.e. "double quoted string"

It would help me to distinguish between text and dialogs (delimited by double quotes), because I'm using this plugin to write a novel. 

Thank your for this excellent plugin!
-

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Actually this has nothing to do with Markdown syntax. You can use another extension [Highlight](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight) with regex `(".*?")`.

**Comment by serge-hulne** [comment]
Thank you!

Where do put this regex (in what file?)

**Comment by yzhang-gh** [comment]
There is a "user settings" file. You can open it with this command (you need to first open the VSCode command palette with `ctrl+shift+p`)

<img src="https://user-images.githubusercontent.com/7588612/87960440-e155b200-cae6-11ea-8f56-c9ab8b8b4496.png" width="388px">

Be sure to also check out the instruction https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-highlight#settings

**Comment by serge-hulne** [comment]
Super!

Thank you very much!
:-)
