### ISSUE TITLE
Superscript and subscript symbols cannot be previewed

### ISSUE THREAD

**Issue by Linya0o** [yzhang-gh/vscode-markdown#756]
I tried to use ~~ and ^^ to type subscripts and subscripts, but it didn't work.
Although using HTML and latax can also be solved

**Comment by Lemmingh** [comment]
Perhaps you're talking about [Pandoc’s Markdown](https://pandoc.org/MANUAL.html#superscripts-and-subscripts) or **R Markdown**.

Might be related to
#618
https://github.com/yzhang-gh/vscode-markdown/issues/623#issuecomment-591730714

**Comment by yzhang-gh** [comment]
@Lemmingh Thanks for the input.

@Linya0o We don't support those syntaxes by default. I've added [an explanation](https://github.com/yzhang-gh/vscode-markdown#faq) about which syntax is supported. Please check it out.

**Comment by yzhang-gh** [comment]
Can be solved by other extensions (e.g., [Markdown Superscript](https://marketplace.visualstudio.com/items?itemName=DevHawk.markdown-sup)).
