### ISSUE TITLE
Allow ability to have omitted header per project, rather than a VSCode settings

### ISSUE THREAD

**Issue by D-Marc1** [yzhang-gh/vscode-markdown#760]
#### What is the problem?

You currently can only omit headers via changing VSCode settings, but it would be nice to have a per project file for this plugin like how there's an `.eslintrc.js` for each project. This way, the same settings for removed headers can be shared among multiple developers.

**Comment by yzhang-gh** [comment]
Have you tried [workspace-level settings](https://code.visualstudio.com/docs/getstarted/settings)?

**Comment by D-Marc1** [comment]
But would it be possible to have the settings version controlled for each project? That's what I like about `.eslintrc.js` for instance.

**Comment by yzhang-gh** [comment]
We don't have such a feature as this extension is not something like Javascript. It only works for Markdown _inside VSCode_.

> That's what I like about `.eslintrc.js` for instance.

VSCode stores workspace-level settings in `.vscode/settings.json` (in the current folder). To me it is the same result as you expect.

**Comment by D-Marc1** [comment]
@yzhang-gh I agree. Thanks for the replies. I misunderstood what workspace settings do.
