### ISSUE TITLE
Toggle math environment for different formula delimiters

### ISSUE THREAD

**Issue by javioustlj** [yzhang-gh/vscode-markdown#766]
#### What is the problem?
I'd like to use brackets as formula delimiters. However default delimiters in this extension is dollars.
Could you please add a new configuration button that users could choose their prefer delimeter when toggle math environment just by type Ctrl + M?

Thank you very much

#### How can I reproduce it?
NA

#### Is there any error message in the console?

NA

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

The fact is we haven't support `\[\]` math environment yet. Probably you can define your own snippet, for example, `\[$1\]$0`. See https://code.visualstudio.com/docs/editor/userdefinedsnippets#_assign-keybindings-to-snippets.

**Comment by javioustlj** [comment]
Do you have any plan to support \\[\\] math environment?

**Comment by yzhang-gh** [comment]
I would suggest using the "Markdown+Math" extension as it is quite mature (see https://github.com/yzhang-gh/vscode-markdown#math).

**Comment by javioustlj** [comment]
Markdown+Math is excellent to deal with markdown math. However, it doesn't support for auto completion with math. So when I disable in markdown all in one, there won't be auto completion with math.

**Comment by yzhang-gh** [comment]
The intellisense is not disabled. It is just because we also don't provide completions inside `\[\]` now (#552).

**Comment by javioustlj** [comment]
Will trace this issue in #552
