### ISSUE TITLE
Printing Batch folder to HTML doesn't work

### ISSUE THREAD

**Issue by leomoty** [yzhang-gh/vscode-markdown#769]
#### What is the problem?

command 'markdown.extension.printToHtmlBatch' not found

#### How can I reproduce it?

Try to batch print a folder

#### Is there any error message in the console?

```
Error: command 'markdown.extension.printToHtmlBatch' not found
    at u._tryExecuteCommand (workbench.desktop.main.js:sourcemap:3331)
    at workbench.desktop.main.js:sourcemap:3331
    at async t (workbench.desktop.main.js:sourcemap:4333)
onDidNotificationChange @ workbench.desktop.main.js:sourcemap:2720
```

**Comment by yzhang-gh** [comment]
Thanks. It looks like you hadn't open a Markdown file before executed this command.

**Comment by leomoty** [comment]
Interesting, I didn't even notice that, will retry with a markdown file open for now. Thanks for the quick fix too.
