### ISSUE TITLE
Markdown element with 'omit in toc' comment is deleted from the source file not just TOC

### ISSUE THREAD

**Issue by shashijeevan** [yzhang-gh/vscode-markdown#770]
#### What is the problem?
I have added TOC under a separate chapter name (Table of Contents). I wanted to hide this chapter under TOC listing using the 'omit in toc' feature. After saving the markdown file the Chapter is getting deleted from the source Markdown file. It was not supposed to be deleted from the source but only hide it in the generated output.

#### How can I reproduce it?

Here is the detailed sample. 

Step 1:
Create a Markdown file with the following content

```
# Table of Contents

<!-- TOC -->

- [Table of Contents](#table-of-contents)
- [Chapter 1](#chapter-1)
- [Chapter 2](#chapter-2)

<!-- /TOC -->

# Chapter 1

# Chapter 2
```
========
Step 2:
Add the text to omit the Chapter name in the TOC listing and save the file

```
# Table of Contents <!-- omit in toc -->

<!-- TOC -->

- [Table of Contents](#table-of-contents)
- [Chapter 1](#chapter-1)
- [Chapter 2](#chapter-2)

<!-- /TOC -->

# Chapter 1

# Chapter 2
```

========
Step 3:
Notice the markdown source file content.
You will see that the "Table of Contents" chapter is deleted in the source markdown file. Following is the content after save

```
<!-- TOC -->

- [Chapter 1](#chapter-1)
- [Chapter 2](#chapter-2)

<!-- /TOC -->

# Chapter 1

# Chapter 2
```

Expected:
It was only supposed to hide "Table of Contents " chapter in the TOC listing and NOT delete from the markdown source file

#### Is there any error message in the console?

No

**Comment by yzhang-gh** [comment]
Thanks for the detailed report.

However, it looks like you are also using other Markdown TOC extensions. (This extension doesn't need `<!-- TOC -->` style comment.)

<img src="https://user-images.githubusercontent.com/7588612/89113679-b126ef80-d4a6-11ea-881b-c2e6c5ace4c3.gif" width="457px" alt="GIF">

**Comment by shashijeevan** [comment]
Thanks for the clarification. I had the other plugin also installed. After removing it, the omit option is working fine.

**Comment by yzhang-gh** [comment]
Thanks for the update.
