### ISSUE TITLE
Syntax highlighting bug: "[" should be white.

### ISSUE THREAD

**Issue by minaminao** [yzhang-gh/vscode-markdown#771]
#### What is the problem?
This may have already been reported, but the syntax highlighting of the links doesn't seem to be working well.

Syntax highlight:
![image](https://user-images.githubusercontent.com/20497787/89117118-307fe780-d4d6-11ea-8875-07d5c61ace0c.png)
Actually:
![image](https://user-images.githubusercontent.com/20497787/89117122-3aa1e600-d4d6-11ea-9871-b6725dad9a97.png)

The color of `[` should be white.

**Comment by minaminao** [comment]
I'm sorry. It was a mistake to report them individually as this happened even with this extension turned off.

**Comment by yzhang-gh** [comment]
You can open an issue [here](https://github.com/microsoft/vscode-markdown-tm-grammar).

**Comment by minaminao** [comment]
Thank you!
