### ISSUE TITLE
Markdown dropdowns automatically collapse in preview when being edited

### ISSUE THREAD

**Issue by DAmNRelentless** [yzhang-gh/vscode-markdown#772]
#### What is the problem?
If you have a markdown preview open which includes a dropdown menu that is currently expanded, it will automatically collapse once it's edited.
That's kinda annoying if you want to make changes to it and you need to manually expand the menu each time you edit something on it.

#### How can I reproduce it?
1. open up a markdown file and create a dropdown menu like this:
```
<details>
    <summary>
        Testing Purpose
    </summary>

*Details*:
- test

*Info*:
- more test
</details>
```
2. open up the markdown preview and expand the dropdown menu
3. edit anything within the markdown file
4. the menu automatically collapses and you need to reopen it

#### Is there any error message in the console?

No

#### Versions
VSCode: v1.47.3
Markdown AiO: v3.2.0

**Comment by yzhang-gh** [comment]
I think it has nothing to do with this extension. And probably we cannot change the behavior on extension side. Consider open an issue in the VSCode main repository. (VSCode has built-in Markdown support.)

**Comment by DAmNRelentless** [comment]
You are right. This also happens without the extension. Thanks for letting me know. I referenced this issue in the issue of the official repository.

**Comment by Lemmingh** [comment]
It appears that VS Code regenerates the whole built-in webview for preview every time there is a change in the editor. I guess it might take a long time before they can improve it.

---

Here is a workaround:

Set `open` attribute to keep `<details>` expanded by default.

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Creating_an_open_disclosure_box

**Comment by DAmNRelentless** [comment]
Thanks for this! Well it has enough votes to be in the backlog for Microsoft. We'll see.
