### ISSUE TITLE
Extreme lag for large file (about 250KB, ~10K lines)

### ISSUE THREAD

**Issue by whlinaa** [yzhang-gh/vscode-markdown#773]
#### What is the problem?
When pressing "enter" or "delete", it takes more than 1 or 2 seconds to do

I really love this extension, but the extreme lag renders it unusable for large markdown file. I truly hope this can be fixed. Thank you very much!

**Comment by yzhang-gh** [comment]
Thanks for the feedback. This extension automatically disables some features (e.g. syntax decorations) if the file is larger than 50KB.

- Can you check whether the syntax decorations have been disabled as expected? For example,
  ```
  ~~strikethrough~~ `code`
  ```
- Have you tried to disable all other extensions except for this one? Some extensions are known to probably conflict with this extension.
- Otherwise please can you provide a dummy large file so that I can test on my side.

**Comment by whlinaa** [comment]
Thank you for your response. Yes, the syntax decorations have been disabled for my markdown file, which is 250KB.

May I have your email address for sending the markdown file to you?

I really appreciate your effort to help, thank you!

**Comment by yzhang-gh** [comment]
Sure, just send it to yzhang.lifeAToutlook.com

**Comment by whlinaa** [comment]
I have just sent it to you. Thank you!

**Comment by yzhang-gh** [comment]
Thanks. However, it seems to work well on my desktop computer 😳.

<img src="https://user-images.githubusercontent.com/7588612/89301329-2ad3fe80-d69c-11ea-9d18-e119111b11f5.gif" width="612px" alt="GIF">

---

> * Have you tried to disable all other extensions except for this one? Some extensions are known to probably conflict with this extension.

You can easily do this with this button

<img src="https://user-images.githubusercontent.com/7588612/89301848-b483cc00-d69c-11ea-9d98-977db765c92e.png" alt="PNG" width="524px">

**Comment by whlinaa** [comment]
Thank you so much for your prompt testing and info.

I tried to disable my extensions, and indeed the culprit is Bracket Pair Colorizer (https://marketplace.visualstudio.com/items?itemName=CoenraadS.bracket-pair-colorizer). After disabling it, I experience no lag. 

Truly thankful for your help! I really appreciate it. Thank you!

**Comment by yzhang-gh** [comment]
That makes sense as that extension also needs to scan the whole document.
