### ISSUE TITLE
Toggle list from style '1.' to '1)' fails for list items '10.' and higher

### ISSUE THREAD

**Issue by mauvity** [yzhang-gh/vscode-markdown#776]
#### What is the problem?

Toggle list from style '1.' to '1)' fails for list items '10.' and higher. (I am trying to remove bullets from a large list.)

#### How can I reproduce it?

1. Create any list with 10 or more items
2. Use the 'Toggle list' command to cycle through list styles
3. When cycling from style '1.' to '1)', item '10.' will incorrectly change to '- 10.', i.e. fail to convert to '10)'

#### Is there any error message in the console?

No

Thank you :)

**Comment by yzhang-gh** [comment]
Thanks. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by Chiramisu** [comment]
Ah, I also noticed this just now actually. Good to know it's fixed already. Great work @yzhang-gh ! 🎉
