### ISSUE TITLE
togglePreviewToSide key doesn't behave like toggle

### ISSUE THREAD

**Issue by Technik-J** [yzhang-gh/vscode-markdown#778]
The key binding `markdown.extension.togglePreviewToSide` only opens preview to the side, but not closing it, so it doesn't behave like toggle.

**Comment by yzhang-gh** [comment]
Thanks for the feedback. I just checked and you are right `togglePreviewToSide` doesn't work as expected (although `togglePreview` does work).

This is a really old feature and I remember there were some technical problems (the preview pane is quite different from the normal editor tab). Probably VSCode has provided new APIs? I'm not sure. It would be great if someone can help.

https://github.com/yzhang-gh/vscode-markdown/blob/062cf59c4380e46574460e73c6b286e4fc338218/src/preview.ts#L28-L35
