### ISSUE TITLE
[linux] Nothing is working (arch)

### ISSUE THREAD

**Issue by NicTanghe** [yzhang-gh/vscode-markdown#781]
#### What is the problem?
Nothing works. even after reinstall and reboot

*pasting link on selected text does not work

*When I enter Ctrl+shift+i I get the error there is no formatter for multimarkdown files installed
and the "install  Formatter" button doesn't point to anywhere existing. i even installed pandoc which did nothing then i installed the pandoc formatter and that did nothing

*ctrl+v returns the error ''markdown.extention.togglePreview' not found  but wnt away after installing some formatters; like MarkdownTqble Formatter markdown Formatter and pandoc formatter

#### How can I reproduce it?
Boot  up a vm with instantos.
Install your plugin.
Try using it

#### Is there any error message in the console?

There is no formatter for 'multimarkdown' files installed.

**Comment by yzhang-gh** [comment]
This extension doesn't support multimarkdown. You can use command `change language mode` to tell VSCode to treat multimarkdown as markdown. Also setting `files.associations` may be useful.

**Comment by NicTanghe** [comment]
but then how does it handle math ?

Annyway i later just switch to using hugo learn annyway.
