### ISSUE TITLE
Unable to have the Table of Contents just show Heading levels 1 & 2

### ISSUE THREAD

**Issue by mccarthyp-snet** [yzhang-gh/vscode-markdown#783]
#### What is the problem?

`"markdown.extension.toc.levels": "1..2"` doesn't work

#### Is there any error message in the console?

No.

**Comment by yzhang-gh** [comment]
<img src="https://user-images.githubusercontent.com/7588612/90324352-44305100-dfa0-11ea-8410-cf9cce4f4d0c.gif" width="597px" alt="toc.levels">

**Comment by schaveyt** [comment]
This bug is present for me

**Comment by yzhang-gh** [comment]
Obviously I cannot reproduce this. Please provide a minimal (not-)working example.

**Comment by schaveyt** [comment]
So figured out what I was encountering.

1. I had created a document way back in April using the version of the tool available back then. 
   1.  Back then the behavior of the tool was such that if I set the toc.level user setting to 1..4, it effected both the TOC and is did NOT apply the numbered headings to heading levels above 4. This was actually what I desired
1. Some version later, a change seems to be made that only the TOC honored the TOC.level setting
1. In addition, that previous version would insert numbered headings of format "1.2.3". However the newer version seems to be expecting "1.2.3." with the period at the end. When I run the option I will get "### 1.2.3. 1.2.3 My Heading". I really need to lock extension versions.

To resolve all of this, I concluded must append  to any heading greater than 4 and add a period to the number format.

**Comment by yzhang-gh** [comment]
Thanks for the information.

As for the trailing dots of numbered headings, please see #714. In short, the trailing dots make sure we won't accidentally break headings starting with numbers. But we may add an option in the future, depending on the feedback.
