### ISSUE TITLE
Feature Suggestion: Paste image URL by uploading to Github Asset API

### ISSUE THREAD

**Issue by nchandran3** [yzhang-gh/vscode-markdown#784]
In Github web editor, if you paste an image, it will automatically upload it to the Github Assets API, and return the link. 

It would be great for Markdown All In One to do this as well, if the user has provided authentication information. I find myself having a window open just to generate these links and copy and pasting them into my Markdown documents, but I think it could easily be integrated into the extension itself and placed under a configuration option. 

For example, this is an example of the request made when pasting an image into a form in Github: 
![image](https://user-images.githubusercontent.com/3078212/90550951-a767e200-e15e-11ea-884f-7ee1461fb65b.png)

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

From my view, it is too specific to GitHub rather than general Markdown. I would suggest someone make a standalone extension which generates images links (no matter GitHub or GitLab etc.).
