### ISSUE TITLE
auto completion treat `- - -` as list

### ISSUE THREAD

**Issue by NewUserHa** [yzhang-gh/vscode-markdown#785]
#### What is the problem?
input: `- - -` then `enter`
output:
```
- - -
- 
```

any fix or option to change this behavior?

thanks!

ps: this also happens in `vscode-docs-authoring` extension. https://github.com/microsoft/vscode-docs-authoring/issues/725

**Comment by yzhang-gh** [comment]
Thanks for the feedback. It should be fixed in the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
