### ISSUE TITLE
markdown.extension.checkTaskList shortcut conflicts with character 'ç' on mac

### ISSUE THREAD

**Issue by marcelo-fanatee** [yzhang-gh/vscode-markdown#786]
#### What is the problem?
markdown.extension.checkTaskList has a shortcut `option + c` that wont let you type the character `ç`

#### How can I reproduce it?
press `option + c` expecting to type `ç` but nothing happens or if in a task list the task gets marked instead

#### Is there any error message in the console?
not an error

#### suggestion
make it available to toggle the shortcut on and off
or make it available to change the shortcut

**Comment by yzhang-gh** [comment]
Please see https://github.com/yzhang-gh/vscode-markdown/issues/320#issuecomment-437922097.

**Comment by marcelo-fanatee** [comment]
thank you, sorry for the inconvenience, i failed on my search.
