### ISSUE TITLE
Suggestion: Don't treat Article Title as a section

### ISSUE THREAD

**Issue by VDerGoW** [yzhang-gh/vscode-markdown#790]
**Suggestion: Don't treat Article Title as a section.**

Maybe section numbers should start from the first `#` symbol rather than `===` symbol.

Before run `Add/Update section numbers`: 

![image](https://user-images.githubusercontent.com/11539008/91020181-ba7a2680-e624-11ea-8b26-26844f9f7297.png)

After run `Add/Update section numbers`:

![image](https://user-images.githubusercontent.com/11539008/91020838-90753400-e625-11ea-99dc-e5eab41d0a14.png)

Thanks for the extension(*^_^*)

**Comment by yzhang-gh** [comment]
Currently the section numbering is expected to align with the TOC (in other words, if a heading shows up in the TOC, it will be considered in the numbering).

Probably you can try

```markdown
<!-- omit in toc -->
A Heading
===

Some text
```

Then it should disappear from both TOC and numbering.

**Comment by VDerGoW** [comment]
It works, Thank you!
