### ISSUE TITLE
LaTeX math delimiters `\(...\)`, `\[...\]` do not trigger auto-completion.

### ISSUE THREAD

**Issue by chaichontat** [yzhang-gh/vscode-markdown#793]
#### What is the problem?

Like the title states, auto-completion only works in a TeX environment (`$...$`), like the one in #387. However, [some](https://tex.stackexchange.com/questions/510/are-and-preferable-to-dollar-signs-for-math-mode) users might use LaTeX environment syntaxes `\(...\)`, `\[...\]`.

#### How can I reproduce it?
```markdown
This $works$.
This one \(does not\).
```
This is VSCode 1.48.1, Markdown All in One 3.2.0.

I believe that this might be intentional but would you consider adding support for `\(...\)` as well? Thank you for this wonderful package!

**Comment by Lemmingh** [comment]
#552
#531

**Comment by yzhang-gh** [comment]
Thanks. Let's track this at #552.
