### ISSUE TITLE
indent not obey the settings in bullets

### ISSUE THREAD

**Issue by orionlee** [yzhang-gh/vscode-markdown#795]
#### What is the problem? / How can I reproduce it?

In a markdown file with indent set to be 4 spaces, after I enable the extension, in writing a (unordered) list, when I press tab, it'd indent with 2 spaces instead. 

- Disabling the extension resolved the issue.
- Indent with regular (non-bullet list) text, or numbered list has no problem. 

Extension version: v3.2.0

Animation illustrating it. Thanks for building the tool.

![vscode-md-all-in-one-indent-bug](https://user-images.githubusercontent.com/250644/91326482-3f765480-e779-11ea-8ccc-544733a83dd0.gif)

**Comment by yzhang-gh** [comment]
Thanks. Option `list.indentationSize` may help.

**Comment by orionlee** [comment]
Thanks! Setting the indentation to inherit resolves the issue. 

I was looking for indent size as 2 in the settings and missed it. 
The default, adaptive, seems to be counter intuitive.

**Comment by yzhang-gh** [comment]
> I was looking for indent size as 2 in the settings and missed it.
> The default, adaptive, seems to be counter intuitive.

`adaptive` allows ordered lists to have 3-space indentation. Some would prefer this as it has "better" alignment.
