### ISSUE TITLE
Add vscode-markdown command to convert selected text into collapsible section

### ISSUE THREAD

**Issue by subodh-dharma** [yzhang-gh/vscode-markdown#799]
#### What is the problem?
Add a new vscode command to convert selected text into a collapsible section.

#### How can I reproduce it?

Feature doesn't exists

#### Is there any error message in the console?
No Error

#### Feature Request Details

Given a text section, a vscode command can be used to convert a text area to a collapsible area. For e.g.

To convert the following text in markdown syntax

> #### Hidden Block
> 
> ```bash
> > echo "hello world!"
> ```

to the collapsible section, we need to surround this text with the following tags which enable the above text to be rendered as collapsible section

> &lt;details>
> &lt;summary>Expand&lt;/summary>
> &lt;p>
> 
> #### Hidden Block
> 
> ```bash
> > echo "hello world!"
> ```
> 
> &lt;/p>
> &lt;/details>

which is rendered as follows:

<details><summary>Expand</summary>
<p>

#### Hidden Block

```bash
> echo "hello world!"
```

</p>
</details>

A vscode command similar to generate Table of Contents can be useful [TOC Command](https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one#table-of-contents)

**Comment by yzhang-gh** [comment]
This can be easily done by defining a [user snippet](https://code.visualstudio.com/docs/editor/userdefinedsnippets) (with `TM_SELECTED_TEXT` variable).

**Comment by tfga** [comment]
Just for the record:

```json
{
    "key": "alt+c",
    "command": "editor.action.insertSnippet",
    "when": "editorLangId == 'markdown'",
    "args": {
        "snippet": "<details>\n\t<summary>$0</summary>\n\n$TM_SELECTED_TEXT\n</details>"
    }
}
```

Add this to your `~/.config/Code/User/keybindings.json`

**Comment by tfga** [comment]
@Lemmingh Why did you remove the `\t`?

**Comment by Lemmingh** [comment]
For **compatibility**. I suggest not to use tabs in a Markdown document.

Your snippet inserts two *Type 6 HTML block*. Tab is usually harmless here.

However, please consider the following cases. Though we might never encounter them, they do exist.

* Mixing spaces (U+0020) and tabs (U+0009) can confuse editors. A guy, who mainly use spaces, may be surprised, when running this snippet without careful check.
* Some linters hate mixing spaces and tabs.
* Some tools reserve all the ASCII control characters. There was a source control system, whose built-in diff tool takes tabs as markers.
* CommonMark regards each leading tab as 4 spaces in most cases. A guy, who do not set tab size to 4, may be visually surprised when tabs exist in a document.

**Comment by tfga** [comment]
VSCode doesn't insert `\t` in this case: it inserts spaces.  
FYI.
