### ISSUE TITLE
cann't convert images to base64 when printing to HTML when images have Chinese name.

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [yzhang-gh/vscode-markdown#800]
Issue Type: <b>Bug</b>

Unable to read file /home/wuxinyu/Documents/Github/Physics/第九章振动/images/%E5%9E%82%E7%9B%B4%E6%96%B9%E5%90%91%E5%90%8C%E9%A2%91%E7%8E%87%E7%AE%80%E8%B0%90%E6%8C%AF%E5%8A%A8%E5%90%88%E6%88%90.png, . Reverting to image paths instead of base64 encoding. (/home/wuxinyu/Documents/Github/Physics/第九章振动/summary.md)

Extension version: 3.3.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-42-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4089)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.42GB (7.87GB free)|
|Process Argv|--no-sandbox --unity-launch /home/wuxinyu/Desktop/Physics.code-workspace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by yzhang-gh** [comment]
Thanks. Let's track this at #436.
