### ISSUE TITLE
cann't print to html with a dark theme.

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [yzhang-gh/vscode-markdown#801]
Issue Type: <b>Bug</b>

**I opened html file with Google Chrome, but it is light theme.**

**My setting in vscode:**
{
    "window.zoomLevel": 1,
    "editor.suggestSelection": "first",
    "vsintellicode.modify.editor.suggestSelection": "automaticallyOverrodeDefaultValue",
    "markdown.extension.print.absoluteImgPath": false,
    "markdown.extension.math.enabled": false,
    "explorer.confirmDelete": false,
    "files.autoSave": "onFocusChange",
    "MarkdownPaste.path": "./images/",
    "julia.enableTelemetry": true,
    "markdown-preview-enhanced.enableExtendedTableSyntax": true,
    "markdown-preview-enhanced.enableScriptExecution": true,
    "markdown-preview-enhanced.chromePath": "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
    "markdown-preview-enhanced.HTML5EmbedIsAllowedHttp": true,
    "markdown-preview-enhanced.HTML5EmbedUseLinkSyntax": true,
    "markdown-preview-enhanced.imageFolderPath": "/images",
    "markdown-preview-enhanced.previewTheme": "one-dark.css",
    "terminal.integrated.cursorStyle": "line",
    "[markdown]": {
        "editor.wordWrap": "on",
        "editor.quickSuggestions": {
            "other": true,
            "comments": false,
            "strings": false,
        }
    },
    "julia.enableCrashReporter": true,
    "C_Cpp.default.intelliSenseMode": "gcc-x64",
    "kite.showWelcomeNotificationOnStartup": false,
    "git.enableSmartCommit": true,
    "git.confirmSync": false,
    "markdown.extension.orderedList.autoRenumber": false,
    "markdown.extension.preview.autoShowPreviewToSide": true,
    "markdown.extension.syntax.decorationFileSizeLimit": 5000000,
    "editor.suggest.localityBonus": true,
    "editor.suggest.maxVisibleSuggestions": 15,
    "editor.suggest.shareSuggestSelections": true,
    "editor.suggest.showWords": false,
    "python.diagnostics.sourceMapsEnabled": true,
    "C_Cpp.errorSquiggles": "Enabled",
    "python.terminal.executeInFileDir": true,
    "python.analysis.memory.keepLibraryAst": true,
    "python.analysis.memory.keepLibraryLocalVariables": true,
    "vsintellicode.features.python.deepLearning": "enabled",
    "python.analysis.cachingLevel": "System",
    "python.analysis.diagnosticPublishDelay": 100,
    "python.languageServer": "Pylance",
    "python.analysis.typeCheckingMode": "basic",
    "C_Cpp.default.cStandard": "c11",
    "C_Cpp.default.cppStandard": "c++17",
    "C_Cpp.updateChannel": "Insiders",
    "julia.executablePath": "/home/wuxinyu/Programs/julia-1.5.0/bin/julia",
    "arduino.path": "/home/wuxinyu/Programs/arduino-1.8.13",
    "python.formatting.provider": "yapf",
    "editor.formatOnPaste": true,
    "editor.formatOnSave": true,
    "editor.formatOnType": true,
    "workbench.iconTheme": "vscode-icons",
    "markdown.extension.toc.levels": "1..3",
    "markdown.extension.print.imgToBase64": true,
    "markdown.extension.tableFormatter.normalizeIndentation": true,
    "markdown.extension.print.theme": "dark",
    "markdown.preview.fontSize": 18
}

Extension version: 3.3.0
VS Code version: Code 1.48.2 (a0479759d6e9ea56afa657e454193f72aef85bd0, 2020-08-25T10:56:10.074Z)
OS version: Linux x64 5.4.0-45-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 4060)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.42GB (11.80GB free)|
|Process Argv|--no-sandbox --unity-launch /home/wuxinyu/Desktop/Physics.code-workspace|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by Lemmingh** [comment]
https://github.com/yzhang-gh/vscode-markdown/issues/691#issuecomment-631847117

**Comment by yzhang-gh** [comment]
That's true. Let's follow #691.
