### ISSUE TITLE
`orderedList.autoRenumber` setting is ignored when adding items

### ISSUE THREAD

**Issue by Domiii** [yzhang-gh/vscode-markdown#803]
#### What is the problem?

`markdown.extension.orderedList.autoRenumber` setting is ignored.

Numbers still increase when pressing enter and going to the next item.

In this example, I had a list with `1. a` and `1. b` (which renders with correct ordering).
When pressing enter after `b`, it increases the next line by 1, ending up in broken list ordering `1 -> 1 -> 2`:

![image](https://user-images.githubusercontent.com/282899/92306871-0c2b9500-efc5-11ea-934a-d69220c301f3.png)

#### How can I reproduce it?

1. Set `markdown.extension.orderedList.autoRenumber` to `false`
1. Reload Window (just to be safe)
1. Go to settings and check that it is actually set to `false`
1. Edit an ordered list and see: numbers still going up when pressing enter and going to the next item

**Comment by yzhang-gh** [comment]
Thanks. You are looking for another configuration `orderedList.marker`, which controls what marker to add, while `orderedList.autoRenumber` means renumbering all list items below it.

**Comment by Domiii** [comment]
Hi @yzhang-gh, and thank you for your speedy reply!

What marker do I want? I want `1`, and it already is `1` isn't it? It gives me `2`, but I want `1`?

**Comment by yzhang-gh** [comment]
<img src="https://user-images.githubusercontent.com/7588612/92329760-4c117b80-f09c-11ea-9dd8-2ac098f93bd2.png" width="440px" alt="marker">

**Comment by Domiii** [comment]
That fixes it! Thanks!

**Comment by yzhang-gh** [comment]
😉
