### ISSUE TITLE
Adjust Math Equation Font Size in Output

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [yzhang-gh/vscode-markdown#805]
#### What is the problem?

The font size in rendered KaTeX equation is always a bit larger than the normal text. It would be better to slightly adjust this to make documents look better.

#### How can I reproduce it?

Simply type a math equation in md file and look at the preview.

#### Is there any error message in the console?

This is not an error.

**Comment by yzhang-gh** [comment]
Thanks.

This is the [outcome of KaTeX](https://github.com/KaTeX/KaTeX/issues/329). You can add a personal CSS

```css
.katex {
    font-size: 1em !important;
}
```

with the VSCode option `markdown.styles`.

As it may cause some problems, I don't think it is a good idea to change it in this extension. Of course we can make it controlled by an option, but we need to see how many people request this.

**Comment by Yue-Zhengyuan** [comment]
Thanks! But I still have problem in using the personal CSS. I created a file `katex.css` containing only the lines you suggested, and add the path to the css file by editing `settings.json`:

```
"markdown.styles": [
    "path/to/the/file/katex.css"
],
```

 However, VS Code says 

```
Could not load 'markdown.styles': path/to/the/file/katex.css
```

What else should I do?

**Comment by yzhang-gh** [comment]
VSCode is pretty strict with this (for security reasons). The setting description is

> A list of URLs or local paths to CSS style sheets to use from the markdown preview. **Relative paths are interpreted relative to the folder open in the explorer. If there is no open folder, they are interpreted relative to the location of the markdown file.** All '\' need to be written as '\\'.

And to my knowledge, you can only use relative paths or `https` urls.
