### ISSUE TITLE
[Bug] Can't type Vietnamese text properly in markdown file

### ISSUE THREAD

**Issue by longgt** [yzhang-gh/vscode-markdown#806]
#### What is the problem?

If this extension was enabled, when typing special characters in Vietnamese such as

 * ê (ee)
 * ô (oo)
 * í (is)
 * ì (if)

it'll be reverted to normal characters (e, o, i, i...)

If disabled this extension then restart VS Code, special Vietnamese character will be displayed properly as typing.

#### How can I reproduce it?

Same as the following steps:

https://github.com/microsoft/vscode/issues/1168#issuecomment-174469544

#### Is there any error message in the console?

No

#### Other information

 * Version: 3.3.0
 * OS: Windows 10 64 bit
 * VS Code: 1.48.2

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Please see https://github.com/yzhang-gh/vscode-markdown/issues/617#issuecomment-585629661 and #41.

**Comment by longgt** [comment]
As you mentioned, it's duplicated of #41 
I've tried to change this setting and it worked like a charm.
Thanks.
