### ISSUE TITLE
Auto-generated links to headers with special characters

### ISSUE THREAD

**Issue by jerry-sky** [yzhang-gh/vscode-markdown#807]
#### What is the problem?

Incorrectly generated links to headers containing some non-alphanumeric characters.

#### How can I reproduce it?

1. Create a new Markdown document in VS Code with the extension enabled.
2. Paste the following content:

```md
# Test Document

## “Header with quotation marks”

## ‘Header with alternative quotation marks’

## „Die Kopfzeile“

## «Nagłówek z alternatywnymi cudzysłowami»

## Normal Header

[link](#<!-- cursor right here -->)

```
3. With the cursor placed in the spot marked above pick auto-generated link to one of the headers.

The issue comes up only with headers that use non-English quotation marks e.g. quotation marks used in German („Die Kopfzeile“) or Polish («Nagłówek…»). You can pick the auto-generated link to one of the headers that use non-English quotation marks, but after interacting with them (CTRL + Left Click) to navigate to that part of the document nothing happens. This issue is not present when dealing with links to other headers however (those that only use English quotation marks such as `“”` and `‘’`)

It appears that when the Markdown-to-HTML converter renders the IDs of the headers, the English quotation marks are treated just like the typewriter quotation marks (`""` and `''`) — they are ignored when generating the header’s slug.\
Apparently, the non-English quotation marks (such as `„` or `«`) are treated like letters and when you fix the link manually (in above example it would be `[link](#„die-kopfzeile“)`) it does work as intended — you can navigate to that part of the document using this link.

Additionally, with the header in German both of the following fixes work:
- `[link](#„die-kopfzeile“)`
- `[link](#„die-kopfzeile)`

as the beginning quotation mark `„` does not overlap with one of the English ones — the other one `“` does overlap (English ones are `“` and `”`)

I would not be surprised if there are some issues like that related to other *special* characters.

#### Is there any error message in the console?

There isn’t.

**Comment by yzhang-gh** [comment]
Thanks. Have you tried `toc.slugifyMode` option? The Markdown-to-HTML converters are different at different places/software. Feel free to tell me if there is any mismatch.

**Comment by jerry-sky** [comment]
Ah, I see the problem. VS Code creates a different slug from the one that GitHub would generate (GitHub omits both English and non-English quotation marks while VS Code encodes them like in a URL). In that case it would be wise to use the one that GitHub uses, as that’s where I keep my repositories.

However, now the issue of not being able to navigate in VS Code still stands — how to force VS Code to use GitHub-style slugs?\
I can’t find a way to change that in VS Code. Is that possible?\
This issue is persistent in both editor and in preview tabs.

**Comment by yzhang-gh** [comment]
I'm afraid we cannot change how VSCode generates slugs (for preview inside VSCode).

If I remember correctly, the TOC works well even if you are using GitHub-style slugs. That's because VSCode has used some tricks. But your issue here is about the normal links (not TOC) and no wonder they don't work... I think we can only rely on VSCode team to solve this.

**Comment by jerry-sky** [comment]
Unfortunately, TOCs in my documents do not work both in preview and editor tabs.

But yeah, it turned out to be an *Upstream* issue.

Should I create a separate issue in the VS Code main repository?

**Comment by yzhang-gh** [comment]
Of course you can. I guess there are similar issues already reported in the main repository.

I'm closing the issue here. Feel free to comment again if you get some new information.

**Comment by jerry-sky** [comment]
*– New Empiric Evidence –*

Apart from using your extension in VS Code I’m currently working on a simple static website that displays some of my Markdown notes and I was looking for a way to convert them into HTML documents. However, I’ve run into an issue when choosing the slugify function for the script that does the conversion to HTML.

*sigh*

There is no consensus even on how just *one* slug style looks like. The [package I have used](https://github.com/Flet/github-slugger) does not accurately converts to GitHub-styled slugs (it lets `«»` slip through while the *actual* GitHub markdown converter doesn’t).\
My solution for to this was to *steal* [the solution you have used](https://github.com/yzhang-gh/vscode-markdown/blob/master/src/util.ts#L187) as it matches (at least to my empiric evidence) the *actual* Markdown rendered documents as seen on GitHub.

So, I guess, someone has to establish what slugify function the GitHub Markdown-to-HTML converter uses.

**Comment by yzhang-gh** [comment]
The solution in this extension should be identical to the GitHub's _in theory_ (it is a "translation" as GitHub seems to be using Ruby in the backend).
