### ISSUE TITLE
How to use \label and \ref in latex environment?

### ISSUE THREAD

**Issue by littlesulley** [yzhang-gh/vscode-markdown#810]
By far it does not seem to support the \label{} as well as the \ref{} command, say
![image](https://user-images.githubusercontent.com/35071593/92671140-1690ba80-f348-11ea-8725-d38da9933b74.png)
which produces
![image](https://user-images.githubusercontent.com/35071593/92671155-1db7c880-f348-11ea-8722-8f2d8023b18f.png)

How can i use them, or if not, will you support it in the future?
Thanks a lot!

**Comment by yzhang-gh** [comment]
The math support is based on [KaTeX](https://katex.org/) which doesn't seem to support `\label` command.

Maybe you can try out the Markdown+Math extension (see [here](https://github.com/yzhang-gh/vscode-markdown#math)).

**Comment by littlesulley** [comment]
OK thank you very much, i'll try it!

**Comment by hanshantong** [comment]
@littlesulley Hello, I also can't use "\label" in my markdown file in VS Code equiped with "markdown All in one, markdown math". But I can use "\label{}" in typora editor. Do you have any solutions for VS Code?
