### ISSUE TITLE
Tab size ignored when editing lists

### ISSUE THREAD

**Issue by Domiii** [yzhang-gh/vscode-markdown#812]
#### What is the problem?

Tab size ignored when editing lists.

This is quite a deal breaker. Hoping to see this fixed soon :)

#### How can I reproduce it?

1. Set tab size to something that is not 2 (usually I use 3 for markdown)
1. Start a list
1. Add a second item to the list
1. Hit `tab` on that second item to make it a nested item
1. -> Only moves 2 spaces

Screenshots:

Before: ![image](https://user-images.githubusercontent.com/282899/93014626-19f4a200-f5e5-11ea-8f2e-17418f29d64f.png)

After: ![image](https://user-images.githubusercontent.com/282899/93014643-3c86bb00-f5e5-11ea-9099-06c9894da94c.png)

#### Is there any error message in the console?

Nothing.

**Comment by yzhang-gh** [comment]
It is expected to press tab in the beginning of _the list item_ but not _that line_.

#### Demo in the `README`

![demo](https://github.com/yzhang-gh/vscode-markdown/raw/master/images/gifs/tab-backspace.gif)

**Comment by Lemmingh** [comment]
@Domiii
Perhaps you're looking for `markdown.extension.list.indentationSize` setting?

---

Note that there is *actually* **no** concept of "tab size" in CommonMark. See <https://spec.commonmark.org/0.29/#list-items>, especially **Example 264** to **267** under “The rules for sublists”.

So if you decide to set `indentationSize` to `inherit`, be careful.
Good luck.

**Comment by Domiii** [comment]
> It is expected to press tab in the beginning of _the list item_ but not _that line_.

Doesn't matter if I tab in or before the line, it always only goes 2 spaces, instead of my configured 3.

**Comment by Domiii** [comment]
> @Domiii
> Perhaps you're looking for `markdown.extension.list.indentationSize` setting?

Ok, I see what you mean now. Your extension enforces the spec and that's probably a good thing.

(arguably the stupidest spec of them all... who thought it would be a good idea to have context-sensitive tab sizes!?)

However, maybe overriding VSCode default behavior might warrant some explanation to the user?

**Comment by yzhang-gh** [comment]
> (arguably the stupidest spec of them all... who thought it would be a good idea to have context-sensitive tab sizes!?)

We did have argued (#155, #241) a lot on this topic 🤣.
