### ISSUE TITLE
Debt: add a FAQ about performance issues

### ISSUE THREAD

**Issue by yzhang-gh** [yzhang-gh/vscode-markdown#818]
#816, #815 etc.

**Comment by Lemmingh** [comment]
What about building debug package on CI?

It's not very difficult. But I'd like to first discuss how to introduce the job.

| Step               | Release | Debug | PR  |
| ------------------ | ------- | ----- | --- |
| Checkout           | Do      | Do    | Do  |
| Set debug manifest | -       | Do    | -   |
| Build `^`          | Do      | Do    | Do  |
| Test               | Do      | -     | Do  |
| Upload VSIX        | Do      | Do    | -   |

* Release: Build release package.
* Debug: Build debug package.
* PR: Triggered by PR.

`^`: Build commands are a little bit different.

As shown above, these three jobs have steps in common, so it's possible to merge some by `strategy`.

I prefer to put Release and Debug together, and create a separate workflow for PR.

What's your opinion?

**Comment by yzhang-gh** [comment]
> What about building debug package on CI?

Brilliant!

Not sure whether we should call it "release" build, probably "latest"/"preview"/"dev"?

**Comment by Lemmingh** [comment]
> whether we should call it "release" build

My "release" and "debug" referred to build mode. 😅
That is:

* Release: `webpack --mode production`
* Debug: `tsc -p ./`

**Comment by yzhang-gh** [comment]
👌

**Comment by Lemmingh** [comment]
I have a new idea about building **debug** package:

Run webpack in `development` mode.

```diff
-"vscode:prepublish": "webpack --mode production",
+"vscode:prepublish": "webpack --mode development",
```

In this way:

* There is **no gap** between production and debug packages. Thus, we can get more precise profile results.
* We only need to modify `package.json`.
* We can build both packages in just **one** job run easily, with no need of matrix workflow.

(Note: As mentioned somewhere, I finally decided to use word "**production**" instead of "release".)

**Comment by yzhang-gh** [comment]
I haven't tried `webpack --mode development` before. If in this mode we can see the function name from the CPU profile, I think it is good.

**Comment by Lemmingh** [comment]
> see the function name from the CPU profile

Yes.

In `development` mode, webpack preserves all module names, function names, and comments.

Although wrappers introduced by webpack also appear in call tree, I guess it's not a big problem.

**Comment by yzhang-gh** [comment]
It has been 2.5 months since our last update. I am going to do this and publish a new version in this weekend.

**Comment by yzhang-gh** [comment]
v3.4.0 🚀

**Comment by Lemmingh** [comment]
So, the `debug` branch is no longer needed. We can delete it safely.
