### ISSUE TITLE
Table of Contents with image fails to ignore it

### ISSUE THREAD

**Issue by marvson** [yzhang-gh/vscode-markdown#819]
#### What is the problem?

When there is an image like `![Image](link-to-image.png)` in a heading, the table of content's link doesn't work.  It instead generates a link like:  `[!Image My title here](#img-srcimagepng-altimagelink-to-image)` that just doesn't point to anything. I'm using the version 3.3.0. It may be related to #792

#### How can I reproduce it?

Put an image inline in a heading and generate the table of contents, the link generated doesn't work.

#### Is there any error message in the console?

No error on devtools related to this.

**Comment by Lemmingh** [comment]
Thank you for your input.

2a23bea4075079aba7192a2558ee68f8bec90056, which is still under review, already fixed the problem.

When it gets merged, you can try our dev build.

**Comment by Lemmingh** [comment]
https://github.com/yzhang-gh/vscode-markdown/issues/792#issuecomment-693525399
