### ISSUE TITLE
Request support for Typographer mode

### ISSUE THREAD

**Issue by rdhar** [yzhang-gh/vscode-markdown#823]
Hi, huge thanks for sharing this extension as it makes any sort of long-form writing in VS Code a breeze!

This is a question more than anything, so do feel free to let me know if this is in the wrong place and I'd be happy to move it elsewhere.

#### Summary

Would it be possible to support "typographer" mode in order to replace certain symbols for more aesthetic variants?

#### Steps

As a live comparison, head to the [markdown-it demo page](https://markdown-it.github.io/) and un/tick the typographer checkbox to view the difference. I've listed some of the most common examples below:

|Name|Markdown|Typographer|
|:--|:-:|:-:|
|Left single quote|`'`|`‘`|
|Left double quote|`"`|`“`|
|Right single quote|`'`|`’`|
|Right double quote|`"`|`”`|
|Ellipsis|`...`|…|
|En-dash|`--`|–|
|Em-dash|`---`|—|
|Copyright|`(c)`|©|
|Trademark|`(tm)`|™|

It'd be ideal to add a config setting such that Typographer replacements are done on-the-fly.

Thank you for your time.

**Comment by rdhar** [comment]
Fair enough, thanks for pointing me in the right direction. Will log a request there with link back for additional context.

Thanks once again for your response.

**Comment by rdhar** [comment]
Hey @yzhang-gh (and heads-up for anyone else interested), I've raised this request: **https://github.com/microsoft/vscode/issues/107328**.

Would like to encourage everyone who'd like this feature to 👍 the request on that thread, thank you!

**Comment by yzhang-gh** [comment]
Thanks. Upvoted 👍
