### ISSUE TITLE
Image Size

### ISSUE THREAD

**Issue by dmitryt** [yzhang-gh/vscode-markdown#825]
#### What is the problem?

Is it possible to provide width/height for inserted image? Something like that https://gist.github.com/uupaa/f77d2bcf4dc7a294d109

#### How can I reproduce it?
N/A

#### Is there any error message in the console?
N/A

**Comment by yzhang-gh** [comment]
In short, it is not possible with pure Markdown syntax (at least on GitHub, as shown in the above link).

You need a `markdown-it` plugin (e.g. [this one](https://www.npmjs.com/package/markdown-it-imsize)) to extend the Markdown syntax. (Also see this [FAQ](https://github.com/yzhang-gh/vscode-markdown#q-which-markdown-syntax-is-supported).)

**Comment by dmitryt** [comment]
Thanks for such a quick answer. Closing the issue then
