### ISSUE TITLE
Table of contents problem

### ISSUE THREAD

**Issue by kzhui125** [yzhang-gh/vscode-markdown#827]
<img width="308" alt="1" src="https://user-images.githubusercontent.com/11925432/94518385-67674500-025c-11eb-9be9-357b1929060c.png">

链接跳转不生效了。

click to header not working.

```md
# title

- [title](#title)
  - [1. test](#1dot-test)
  - [2.test](#2dottest)

## 1. test

## 2.test

```

**Comment by yzhang-gh** [comment]
可能需要把 `slugifyMode` 设置成 `vscode`（我默认理解你是指 VSCode 的预览里有问题）。如果还是不行可以尝试一下[开发版](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by kzhui125** [comment]
键盘按ctrl / command，鼠标点击#title，可以正常跳转

但是鼠标点击带dot的，没反应

不是预览模式 @yzhang-gh

**Comment by yzhang-gh** [comment]
Ctrl 加点击这个是 VSCode 提供的功能，和这个插件没有关系

**Comment by kzhui125** [comment]
意思是生成的链接有问题，不要加dot：

https://stackoverflow.com/a/51226139/4822506

```
# title

- [title](#title)
  - [1. test](#1-test)
  - [2.test](#2test)

## 1. test

## 2.test

```

**Comment by yzhang-gh** [comment]
![image](https://user-images.githubusercontent.com/7588612/94523401-b49ae500-0263-11eb-89fc-1013029295fb.png)

我这本来就没有 `dot` 😳。你是不是还用了别的 Markdown 插件？

**Comment by kzhui125** [comment]
果然是的

https://marketplace.visualstudio.com/items?itemName=kortina.vscode-markdown-notes

禁用之后好了。。。

Thanks
