### ISSUE TITLE
Markdown Intellisense with multiple identical labels shows non-unique anchors

### ISSUE THREAD

**Issue by gmccullo** [yzhang-gh/vscode-markdown#831]
## Problem

See screenshot. Each "item" should have a unique anchor value: "item", "item-1", "item-2" etc. Intellisense just shows the "item" multiple times. The table of contents was generated with an extension just to show how the links should be; it's not relevant to the issue.

Note: the behavior is the same with editor.wordBasedSuggestions on or off. 

![image](https://user-images.githubusercontent.com/26315643/95422442-a1f96d80-093f-11eb-8e9b-60b0e7995939.png)

## How to reproduce

Just make a file that looks like the screenshot. And try to make an internal link to one of the item headers.

```
# item

# item

# item

[link]()
```

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

---

https://github.com/yzhang-gh/vscode-markdown/blob/8b09452402e6b7200f65dc63a4c94343f8813393/src/completion.ts#L522
