### ISSUE TITLE
Please add shortcut to sorround inline `code`

### ISSUE THREAD

**Issue by tifDev** [yzhang-gh/vscode-markdown#835]
I want to trigger an inline comment via shotcut.
Currently I have:

```
    "key": "alt+c",
    "command": "editor.action.insertSnippet",
    "when": "editorTextFocus && editorLangId == markdown",
    "args": {
      "snippet": "`$TM_SELECTED_TEXT`"
    }

```
But I need to always select the string to comment and I want the way this plugin does: it automatically detects the near string and puts it between the "`". 

How can I achieve this? Is this possible to be implemented?

**Note**: I've changed alt+c (c = comment) to trigger inline comment and alt+x (x = put an X into checklist) to trigger `markdown.extension.checkTaskList`.

**Comment by Lemmingh** [comment]
> Currently I have

VS Code already defines this pair:
https://github.com/microsoft/vscode/blob/c13678f258248b38570ef08311047d29d40d9c45/extensions/markdown-basics/language-configuration.json#L39

So theoretically, you do not need to create such a snippet again. Just select the text, and then press <kbd>`</kbd> should work.

What went wrong?

---

> automatically detects the near string and puts it between the "`".

Could you please explain it in **more detail**? It would be great if you provide some **examples**.

**Comment by tifDev** [comment]
> automatically detects the near string and puts it between the "`".

Here is an example, when the cursor is somewhere in the string, if I hit ctrl+b it automatically puts it between ** but when I do the same with my shortcut for alt+c it does this:

![image](https://user-images.githubusercontent.com/39730484/96339916-738e3780-108f-11eb-884a-5a466a199d6a.png)

How can I fix this? I want the same behaviour as putting in bold where I don't need to select the string always to put it between the characters.

**Comment by Lemmingh** [comment]
I see.

We've provided a command called `markdown.extension.editing.toggleCodeSpan`, which should meets your need.
https://github.com/yzhang-gh/vscode-markdown/blob/3037848b96033584b19abb599f8a5f54332f30fe/src/formatting.ts#L10

You can **assign a key binding to it**.

**Comment by yzhang-gh** [comment]
@Lemmingh Thanks.

We also have another undocumented feature (a public command `markdown.extension.editing._wrapBy`, see https://github.com/yzhang-gh/vscode-markdown/issues/663#issuecomment-619343974) for more complex cases.

**Comment by tifDev** [comment]
Yes it's this. Thank you both :)
