### ISSUE TITLE
Toc not displayed

### ISSUE THREAD

**Issue by Kyridiculous2** [yzhang-gh/vscode-markdown#838]
<!--

## Problem
No TOC is displayed

## Error message in the console
<!--
 INFO Setting search error: XHR timeout: 5000ms
extensionsViews.ts:288 Error querying extensions gallery Canceled
(anonymous) @ extensionsViews.ts:280
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/cvda.DESKTOP-BIRAVCC/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/cvda.DESKTOP-BIRAVCC/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/tas-client-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/cvda.DESKTOP-BIRAVCC/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map:

**Comment by Kyridiculous2** [comment]
## Problem
No TOC is displayed

## How to reproduce

## Error message in the console

 INFO Setting search error: XHR timeout: 5000ms
extensionsViews.ts:288 Error querying extensions gallery Canceled
(anonymous) @ extensionsViews.ts:280
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/cvda.DESKTOP-BIRAVCC/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/semver-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/cvda.DESKTOP-BIRAVCC/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/tas-client-umd.js.map: 
DevTools failed to load SourceMap: Could not load content for file:///C:/Users/cvda.DESKTOP-BIRAVCC/AppData/Local/Programs/Microsoft%20VS%20Code/resources/app/out/vs/code/electron-browser/workbench/main.js.map:

**Comment by yzhang-gh** [comment]
Please provide more information about how to reproduce the problem. What is the text? What is expected?

**Comment by Kyridiculous2** [comment]
![image](https://user-images.githubusercontent.com/26832000/96991873-b2266500-155b-11eb-8ce5-e12507ecc97d.png)
As the image indicates, there is no toc displayed as expected== 
how can I mannualy insert a toc?

**Comment by yzhang-gh** [comment]
You need to use the "Markdown All in One: Create Table of Contents" command through [VSCode command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette).

**Comment by Kyridiculous2** [comment]
OK  I got it， thx for your help. I just didn't find that on your extension page previously.
