### ISSUE TITLE
Support Multi-line table formatting

### ISSUE THREAD

**Issue by xuld** [yzhang-gh/vscode-markdown#840]
## Problem
Backslash at end of table row merges with  line content below, which is implemented by [markdown-it-multimd-table](https://www.npmjs.com/package/markdown-it-multimd-table#multiline-optional).

```md
|   Markdown   | Rendered HTML |
|--------------|---------------|
|    *Italic*  | *Italic*      | \
|              |               |
|    - Item 1  | - Item 1      | \
|    - Item 2  | - Item 2      |
|    ```python | ```python       \
|    .1 + .2   | .1 + .2         \
|    ```       | ```           |
```

But the markdown formatter cannot recognize it correctly, and after formatting, it changes to:
```md
| Markdown                      | Rendered HTML     |
| ----------------------------- | ----------------- |
| *Italic*                      | *Italic*          | \ |
|                               |                   |
| - Item 1                      | - Item 1          | \ |
| - Item 2                      | - Item 2          |
| ```python | ```python       \ |
| .1 + .2                       | .1 + .2         \ |
| ```       | ```               |
```

It's simple to fix by checking the end of table row.

The same issue goes for cell merging.

**Comment by Lemmingh** [comment]
It's interesting, but **forbidden by the [GFM Spec](https://github.github.com/gfm/#tables-extension-)**:

> Block-level elements cannot be inserted in a table.

Not sure what to do.

**Comment by yzhang-gh** [comment]
As far as I see from your example, it is not easy to support this syntax.

I would suggest using plain HTML for complex tables/layouts rather than adding more and more rules to Markdown.

**Comment by Lemmingh** [comment]
This [multi-line table](https://www.npmjs.com/package/markdown-it-multimd-table#multiline-optional) is **incompatible** with [GFM table](https://github.github.com/gfm/#tables-extension-).

In a GFM table, the last U+007C (`|`) is optional. Thus, if a line ends with a U+005C (`\`), the `\` must be **literal**.

However, in a "multi-line table", the trailing `\` is part of the **syntax**.

---

**As long as we support GFM, it is not possible to handle the "multi-line table".**

Sorry.
