### ISSUE TITLE
$\sqrt{x}$ can't be renderered properly

### ISSUE THREAD

**Issue by m1stm4o** [yzhang-gh/vscode-markdown#843]
## Problem
What went wrong?

Can't get the proper result for "$\sqrt{x}$" if there are no characters behind it.
See the picture below.  
<img width="262" alt="pic" src="https://user-images.githubusercontent.com/16450904/98462486-af7c6e80-21ef-11eb-9c47-9e3c0c77b2a9.png">

Additional info, I tested the same code 
in http://waylonflinn.github.io/markdown-it-katex/, and got the correct result.

<img width="106" alt="pic2" src="https://user-images.githubusercontent.com/16450904/98462572-2d407a00-21f0-11eb-8f33-9693198de98f.png">

Expected behavior?  
Get the proper rendered result.

Your environment (if necessary)?
Markdown All in One 3.3.0

## How to reproduce

Copy the following code to any markdown file and preview.

```
$\sqrt{x}$

$\sqrt{x}$a

$\sqrt{x}$  
n

${\sqrt{x}}$

$\sqrt{{x}}$
```

**Comment by yzhang-gh** [comment]
I also cannot reproduce this issue. Please check whether you have other Markdown and Math extensions installed.

**Comment by m1stm4o** [comment]
Sorry, I found that it's the extension "vscode-markdown-markmap" causing this problem, after I disabled the extension, the problem is gone, sorry for bothering you:sweat_smile:
