### ISSUE TITLE
Disable syntax decoration only for code span

### ISSUE THREAD

**Issue by werunom** [yzhang-gh/vscode-markdown#845]
## Proposal

At present, adding/removing syntax decoration works for both `strikethrough` and `code span`. Can this enabling/disabling be individualised? 

With this, users (like me) who do not want syntax decoration for code-span can disable only that without losing out on decoration for strikethrough.

**Comment by yzhang-gh** [comment]
Thanks. Please see https://github.com/yzhang-gh/vscode-markdown/issues/757#issuecomment-662951920.

**Comment by werunom** [comment]
@yzhang-gh --- Thanks for pointing me to the related thread. I use HIGHLIGHT extension. 

A minor clarification. under `"highlight.regexes"` (in `settings.json`), I use the regex you suggested `(~~.+?~~)`. But within the block, what I have to give to get the strikethrough text decoration?

```
"highlight.regexes": {
        "(~~.+?~~)": [
            {
                ????
            },
        ],
}
```
Thanks for your help :)

**Comment by werunom** [comment]
Got it. 

```
        "(~~.+?~~)": [
            {
                "textDecoration": "line-through"
            },
            {}
        ],
```

**Comment by yzhang-gh** [comment]
👍
