### ISSUE TITLE
Invalid syntax in settings.json

### ISSUE THREAD

**Issue by hudcap** [yzhang-gh/vscode-markdown#847]
## Problem

I'm seeing syntax errors all over my settings.json (see pics below)
Also, it seems like some settings are missing. Honestly, I'm a little lost, so please forgive me if this was my error, but I've never seen this before and it seems like the extension was just updated.

![image](https://user-images.githubusercontent.com/4990645/99432392-1679e180-28da-11eb-84df-e62f99b87255.png)
![image](https://user-images.githubusercontent.com/4990645/99432622-69539900-28da-11eb-82e9-0c291ae249dd.png)
![image](https://user-images.githubusercontent.com/4990645/99432680-7bcdd280-28da-11eb-8cb2-27cd5d1e7070.png)

## How to reproduce
I'm not really sure... I was trying to edit a completely unrelated setting and all these errors popped up when the file opened.

## Error message in the console

I don't see anything related.

**Comment by Lemmingh** [comment]
You should **report this issue to VS Code**.

Obviously, the legacy Settings Editor does not support [`markdownEnumDescriptions`](https://code.visualstudio.com/api/references/contribution-points#Configuration-property-schema) well.

Thank you.
