### ISSUE TITLE
Fenced code blocks in LaTeX can not trigger syntax highlighting in the preview

### ISSUE THREAD

**Issue by gaochenyi** [yzhang-gh/vscode-markdown#849]
## Problem

Hi,

I find a strange behavior and didn't find a solution with Google.

Fenced code blocks in `LaTeX` trigger syntax highlighting in the editor tab, but don't trigger syntax highlighting in the preview tab.
However, it is reverse for `TeX`: fenced code blocks in `TeX` trigger syntax highlighting in the preview tab, but don't trigger syntax highlighting in the editor tab.

The expected behavior: syntax highlighting could be enabled both in the editor tab and the preview tab for at least one language.

## How to reproduce

Use following code to reproduce this behavior. The screenshot is also posted below.

    ```tex
    \TeX
    ```

    ```latex
    \TeX
    ```

![Screen Shot 2020-11-20 at 15 49 53](https://user-images.githubusercontent.com/32761974/99775602-855d7180-2b4a-11eb-96e2-b2c6571622bd.png)

**Comment by Lemmingh** [comment]
https://lemmingh.github.io/vscode-markdown-docs/decisions/syntax-highlighting-for-fenced-code-blocks.html

**Comment by Lemmingh** [comment]
VS Code's preview is still using [highlight.js 9.15.10](https://github.com/highlightjs/highlight.js/tree/9.15.10), which does not support `latex`.

https://github.com/microsoft/vscode/blob/69de6464ceef070df04d28514a006ad184c0fd65/extensions/markdown-language-features/package.json#L327

Updating to the latest version 10 can [solve the problem](https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md).

**Please report it to VS Code.**

Thank you.

**Comment by Lemmingh** [comment]
As for the highlighting **in editor**.

VS code still does not provide [built-in support](https://github.com/microsoft/vscode-markdown-tm-grammar/blob/b7bd5df45abf8b0e774598801f266e29b476b1d3/build.js).

It should come from **other extensions**, for example, LaTeX Workshop provides `latex`:

https://github.com/James-Yu/LaTeX-Workshop/blob/79b83ed768c284584c640327b0498f00c348fa01/package.json#L205-L214
https://github.com/James-Yu/LaTeX-Workshop/blob/79b83ed768c284584c640327b0498f00c348fa01/syntax/latexblock.json

**Comment by gaochenyi** [comment]
> VS Code's preview is still using [highlight.js 9.15.10](https://github.com/highlightjs/highlight.js/tree/9.15.10), which does not support `latex`.
> 
> https://github.com/microsoft/vscode/blob/69de6464ceef070df04d28514a006ad184c0fd65/extensions/markdown-language-features/package.json#L327
> 
> Updating to the latest version 10 can [solve the problem](https://github.com/highlightjs/highlight.js/blob/master/SUPPORTED_LANGUAGES.md).
> 
> **Please report it to VS Code.**
> 
> Thank you.

Thanks, I have raised [an issue to the upstream](https://github.com/microsoft/vscode/issues/111024).
