### ISSUE TITLE
imgToBase64 not working on Traditional Chinese filename

### ISSUE THREAD

**Issue by chencyu** [yzhang-gh/vscode-markdown#850]
## Problem

I write a line contain:

```Markdown
Img ![img](res/繁體中文圖片.png)
```

It show correctly in preview mode

But when I use command `Markdown All in One: Print current document to HTML`, 
then it notify me:
```
Unable to read file <path-to-dir>\res\%E7%B9%81%E9%AB%94%E4%B8%AD%E6%96%87%E5%9C%96%E7%89%87.png, . Reverting to image paths instead of base64 encoding. (<path-to-dir>\Test.md)
```

By the way, it seems ok the path contain Chinese but not for filename.

## How to reproduce

Make a image file with Chinese filename, and link it locally in markdown file.
Then use command `Markdown All in One: Print current document to HTML`

## Error message in the console

no any associated error message in console.

**Comment by yzhang-gh** [comment]
Thanks.

It is a known issue (#436). As I recall, there is something wrong with the `fs.readFileSync`. Let's track this issue there.
