### ISSUE TITLE
Markdown Preview Enhanced 右键无法使用

### ISSUE THREAD

**Issue by inerve** [yzhang-gh/vscode-markdown#851]
## Problem

hi 作者你好，看名字是华人，所以就不用英文了哈。我是一名 Markdown All in One 的重度用户，自从上次更新之后，配合 https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced Markdown Preview Enhanced 使用时出现了问题。

在MD的预览界面，右键失效了，导致无法将markdown 导出为 PDF 或 DOC（使用pandoc实现）

这个功能对我来说非常重要，麻烦作者抽空修正一下~

**Comment by yzhang-gh** [comment]
我没理解你这个描述。Markdown Preview Enhanced 用的是它自己的 Preview 界面 (Webview)，和 VS Code 自带的无关。

你有测试过禁用 Markdown All in One 之后是什么效果吗？个人认为很可能与我们无关

**Comment by inerve** [comment]
> 我没理解你这个描述。Markdown Preview Enhanced 用的是它自己的 Preview 界面 (Webview)，和 VS Code 自带的无关。
> 
> 你有测试过禁用 Markdown All in One 之后是什么效果吗？个人认为很可能与我们无关

你好，确实如你所描述。

禁用了 Markdown All in One 之后，Markdown Preview Enhanced 界面的右键依旧无法使用。因为 Preview 插件没有更新记录，所以判断是 All in One 的问题，打扰啦，感谢回复。

**Comment by 1jt** [comment]
请问最后怎么解决的
