### ISSUE TITLE
Heading section numbers larger than 99 are not correctly updated

### ISSUE THREAD

**Issue by CHEN-Jing194** [yzhang-gh/vscode-markdown#852]
If update section number repeatedly, sections which their section number larger than 100 will be added with section number repeatedly.

**Comment by yzhang-gh** [comment]
Please provide a piece of code to reproduce the issue.

**Comment by CHEN-Jing194** [comment]
> Please provide a piece of code to reproduce the issue.
![animations](https://user-images.githubusercontent.com/49305655/100312005-1077b500-2fec-11eb-9e06-8ce818509681.gif)

**Comment by yzhang-gh** [comment]
Thanks.

Interesting, I presumed there wouldn't be more than 99 (consecutive) sections...

But now you can have up to 999 of them! (Please use the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build))

**Comment by Lemmingh** [comment]
@yzhang-gh
You omitted `removeSectionNumbers()`.

---

BTW, this issue is somehow related to ordered lists. Then, if performance permits, what about aligning with the Spec?

> An ordered list marker is a sequence of 1–9 arabic digits (`0-9`), followed by ...

**Comment by yzhang-gh** [comment]
Good catch.

I changed it to `{1,9}` (although IMO, it has nothing to do with ordered lists (as we cannot have them in the headings)).

**Comment by Lemmingh** [comment]
But we have `markdown.extension.toc.orderedList`. 😏

---

Verified on my machine. Performance appears acceptable.

In a document with ~3000 lines and **1000 headings**, the four commands (**Add/Update section numbers**, **Remove section numbers**, **Create Table of Contents**, **Update Table of Contents**) can respond **within 1 second**.

In a document with ~40000 lines and **17000 headings**, they need **less than 20 seconds**.

**Comment by yzhang-gh** [comment]
> But we have `markdown.extension.toc.orderedList`. 😏

Aha, never used it though 🤣.

> Performance appears acceptable.

👍

**Comment by yzhang-gh** [comment]
released in v3.4.2
