### ISSUE TITLE
Preview issue in unordered lists

### ISSUE THREAD

**Issue by p-mng** [yzhang-gh/vscode-markdown#854]
## Problem

If an indented sub-item without content is inserted in an unordered list, the item above it is formatted as a heading in the preview.

## How to reproduce

Create an unordered list as shown in the following photo

Normal behaviour:

![Normal](https://user-images.githubusercontent.com/65464529/100342910-f1265b00-2fde-11eb-9dd9-ffbb07ab9784.png)

Abnormal behaviour:

![Bugged](https://user-images.githubusercontent.com/65464529/100342958-04392b00-2fdf-11eb-9266-74c81518db66.png)

Tested with v3.4.0 in VS Code on Arch Linux

I'm not sure what causes this issue and apologize if this is the intended behaviour

## Error message in the console

None

**Comment by Lemmingh** [comment]
https://spec.commonmark.org/0.29/#example-270

**Comment by p-mng** [comment]
Thanks for the hint! Closing since this is not a problem with the project
