### ISSUE TITLE
Uninstall does not remove entries from Ctrl-Shift-P menu

### ISSUE THREAD

**Issue by maiku41** [yzhang-gh/vscode-markdown#863]
## Problem

After uninstalling and restarting, command menu (Ctl-Shift-P) still contains entries for Markdown All In One.  Selecting any of the entries results in an error.

## How to reproduce
Install extension.  Uninstall extension.  Restart VSCode.  Type Ctl-Shift-P.

## Error message in the console

Command 'Markdown All in One: Toggle code span' resulted in an error (Running the contributed command: 'markdown.extension.editing.toggleCodeSpan' failed.)

**Comment by Lemmingh** [comment]
Is there anything in your [**user `keybindings.json`**](https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization)?

Did you **completely** reloaded VS Code? Please close **all** VS Code instances (if on macOS, remember to Control-click the Dock icon and select Quit at last), then restart it. In some rare cases, you need to reload VS Code twice to uninstall an extension.

**Comment by maiku41** [comment]
Looks like "reload twice" was the key.

Thanks!

**Comment by maiku41** [comment]
Worked after reloading VS Code twice.
