### ISSUE TITLE
TOC not working

### ISSUE THREAD

**Issue by efie45** [yzhang-gh/vscode-markdown#864]
## Problem

When trying to add a TOC into a markdown document I get something like the following added onto a single line instead:

```
<!-- TOC -->autoauto- [Postman Resources and Tips](#postman-resources-and-tips)auto    - [Automatic Authorization Before Requests](#automatic-authorization-before-requests)auto- [Shared Servers](#shared-servers)auto <!-- /TOC -->
```
It shows up exactly like this in markdown preview, and if I convert the document to another format like .pdf for example.

Version information for VSCode standard where this is happening:

Version: 1.51.1
Commit: e5a624b788d92b8d34d1392e4c4d9789406efe8f
Date: 2020-11-11T01:11:34.018Z (4 wks ago)
Electron: 9.3.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Also behaving the same way on VSCode-Insiders

Version: 1.52.0-insider
Commit: 6f933020e8dd4ea046eae2bcfc59a18edf2bc517
Date: 2020-12-08T15:37:39.271Z (2 days ago)
Electron: 9.3.5
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by yzhang-gh** [comment]
It doesn't look like a TOC created by this extension. Please check which command you are using. (For this extension, it is "Markdown All in One: Create Table of Contents".)

**Comment by efie45** [comment]
Yeah you're right actually. I thought I had disabled the other extension I tried first but I must not have reloaded VSCode. Thank you.
