### ISSUE TITLE
Want more default macros (upgrade KaTeX version)

### ISSUE THREAD

**Issue by fly1026** [yzhang-gh/vscode-markdown#866]
## Proposal

Please update the KaTeX version.

The latest KaTeX v0.12.0 has a bit more various predefined macros than KaTeX v0.11.0 the current vscode-markdown uses.
I know "markdown.extension.katex.macros" can help, but adding all the macros by hand is deranging.

## References

https://github.com/KaTeX/KaTeX/releases/tag/v0.12.0

**Comment by yzhang-gh** [comment]
Please check out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by fly1026** [comment]
Thanks.
