### ISSUE TITLE
Wrong TOC text for headings end with `#`

### ISSUE THREAD

**Issue by Tai-Zhou** [yzhang-gh/vscode-markdown#867]
## Problem

I failed to create a ToC with the same title for the section name "C#", every '#' is lost from head 1 to 6 (but the links work well).

<img width="196" alt="Screenshot" src="https://user-images.githubusercontent.com/21986946/102049566-11964800-3e1c-11eb-9930-48ece9884cf5.png">

I've tried all the "Slugify Mode" and "Plaintext" but didn't fix this problem. I may need help to config properly.

## How to reproduce

Create ToC for

``` markdown
# C#
## C#
### C#
#### C#
##### C#
###### C#
```

## Error message in the console

There is no error shown.

**Comment by Lemmingh** [comment]
There's a chance that we cannot distinguish *literal U+0023* from *closed-style ATX marker*.

https://github.com/yzhang-gh/vscode-markdown/blob/1d1eca9ceb8c47b417dcca5d00597bc520f008e2/src/toc.ts#L379

**Comment by Lemmingh** [comment]
To fix it, we need to pass <https://spec.commonmark.org/0.29/#example-46>

**Comment by yzhang-gh** [comment]
Please check out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

**Comment by Tai-Zhou** [comment]
Fixed! Thank you for the great extension!

**Comment by yzhang-gh** [comment]
released in v3.4.2
