### ISSUE TITLE
Auto completion didn't work (Answer: need to open a folder rather than a single file)

### ISSUE THREAD

**Issue by Neptune10000** [yzhang-gh/vscode-markdown#876]
## How to reproduce
Auto complection didn't work
I am kind of confuse of how to use auto complection for images.
Am I need to set Completion: Root? But it seems didn't work even if I set it to the path of *.md file.

https://user-images.githubusercontent.com/20330348/103464842-d7acc780-4d71-11eb-9956-800d004973e9.mov

**Comment by yzhang-gh** [comment]
I guess you opened a single Markdown file rather than a folder?

![image](https://user-images.githubusercontent.com/7588612/103465669-11cd9780-4d79-11eb-9284-5e0ad8f76ad7.png)

**Comment by Neptune10000** [comment]
Great. Than it worked 😂
Thank you!

**Comment by yzhang-gh** [comment]
😉
