### ISSUE TITLE
Add an option to disable all key bindings

### ISSUE THREAD

**Issue by robsonpeixoto** [yzhang-gh/vscode-markdown#878]
## Proposal
Has something like `"gitlens.keymap": "none"` to disable all keymaps.

**Comment by yzhang-gh** [comment]
Can you specify which (set) of keybindings you would like to disable? There are many keybindings serving (quite) different features.

**Comment by Lemmingh** [comment]
I prefer to introduce some `markdown.extension.*.enabled` settings to control **each feature and corresponding key bindings**, just like #872.

---

GitLens contributes a configuration key (setting) [`gitlens.keymap`](https://github.com/eamodio/vscode-gitlens/blob/3509a3a247ee7b799c92334874088dd7e8764149/README.md#keyboard-shortcut-settings-), and a bunch of [`gitlens:` contexts](https://github.com/eamodio/vscode-gitlens/blob/3509a3a247ee7b799c92334874088dd7e8764149/src/constants.ts#L28-L56).

Then, it combines them in `when` clause to control key bindings.

Note that VS Code provides the `config.` context to reference configuration keys.

**Comment by robsonpeixoto** [comment]
I'm disabling these keybindings:
```
    {
        "key": "alt+c",
        "command": "-markdown.extension.checkTaskList",
        "when": "editorTextFocus && editorLangId == 'markdown'"
    },
    {
        "key": "cmd+b",
        "command": "-markdown.extension.editing.toggleBold",
        "when": "editorTextFocus && !editorReadonly && editorLangId == 'markdown'"
    }
```
