### ISSUE TITLE
Make Whitespaces at Line Ends Visible

### ISSUE THREAD

**Issue by Daniel-Chin** [yzhang-gh/vscode-markdown#881]
## Proposal

Make double whitespaces at line ends visible. So like use a symbol to represent them, or overlay a symbol on top.  
In other words, match for '\x20\x20\n'.  
This will bring great user experience, especially when the user gets used to this kind of visual interaction.

**Comment by yzhang-gh** [comment]
Thanks for the suggestion. I have been using another highlight extension to do this (visualizing the trailing double whitespace). So I'd like to see this feature. (Probably we include it in the existing "syntax decorations".)

**Comment by Lemmingh** [comment]
VS Code's

* `editor.renderWhitespace`
* `editor.renderControlCharacters`

should meet you need.

**Comment by yzhang-gh** [comment]
Didn't notice VS Code provides a `trailing` option for `editor.renderWhitespace` now. But extra decoration can still be helpful because the whitespace is somehow too dim to notice (its color and style/glyph are not designed for this).

**Comment by Lemmingh** [comment]
Then, what about

```json
{
    "markdown.extension.theming.decoration.renderTrailingWhitespace": true,
    "markdown.extension.theming.color.editor.trailingWhitespace.background": "#00AA00"
}
```

Or, define the **color** under `contributes.colors`?

```json
{
    "id": "markdown.extension.editor.trailingWhitespace.background",
    "description": "Background color of trailing whitespace characters in the Markdown editor.",
    "defaults": {
        "dark": "diffEditor.insertedTextBackground",
        "light": "diffEditor.insertedTextBackground",
        "highContrast": "#9BB955"
    }
}
```

Anyway, they must be **scoped to `application`** to minimize the complexity of resolving conflicts, since a color theme can contribute `editorWhitespace.foreground` to control the color of whitespace characters.

**Comment by yzhang-gh** [comment]
Probably we need to try a few different styles so that we pick a relatively good one. My immediate thought is to add a highlighted symbol `↵` (that is why I prefer to use decoration rather than only colors).

**Comment by Lemmingh** [comment]
I definitely understand [your idea](https://github.com/yzhang-gh/vscode-markdown/issues/881#issuecomment-756667895), and I am also in favor of editor decoration.

Below is the proto I created yesterday, which looks good to me. Thinking it's too complex and far from production-ready, I posted [an extremely simplified piece above](https://github.com/yzhang-gh/vscode-markdown/issues/881#issuecomment-757089928).

## `extension.ts`

```typescript
"use strict";

import * as vscode from "vscode";

//#region Decoration

const colors = {
	"editor.formattingMark.foreground": new vscode.ThemeColor("markdown.extension.editor.formattingMark.foreground"),
	"editor.trailingSpace.background": new vscode.ThemeColor("markdown.extension.editor.trailingSpace.background"),
} as const;

type FontIcon =
	| "link"
	| "pilcrow"
	| "reversedPilcrow"
	;

const fontIcons: Readonly<Record<FontIcon, vscode.ThemableDecorationAttachmentRenderOptions>> = {
	"link": {
		contentText: "\u{1F517}\u{FE0E}",
		color: colors["editor.formattingMark.foreground"],
	},
	"pilcrow": {
		contentText: "¶",
		color: colors["editor.formattingMark.foreground"],
	},
	"reversedPilcrow": {
		contentText: "⁋",
		color: colors["editor.formattingMark.foreground"],
	},
};

type DecorationClass =
	| "hardLineBreak"
	| "paragraph"
	| "trailingSpace"
	;

const decorationStyles: Readonly<Record<DecorationClass, vscode.DecorationRenderOptions>> = {
	"hardLineBreak": {
		after: fontIcons.reversedPilcrow,
	},
	"paragraph": {
		after: fontIcons.pilcrow,
	},
	"trailingSpace": {
		backgroundColor: colors["editor.trailingSpace.background"],
	},
};

// DecorationClass -> Configuration key
const decorationClassConfigMap: Readonly<Record<DecorationClass, string>> = {
	"hardLineBreak": "markdown.extension.theming.decoration.renderHardLineBreak",
	"paragraph": "markdown.extension.theming.decoration.renderParagraph",
	"trailingSpace": "markdown.extension.theming.decoration.renderTrailingSpace",
};

// Decoration type instances currently in use. Dynamically updated.
const decorationHandles = new Map<DecorationClass, vscode.TextEditorDecorationType>([
	["trailingSpace", vscode.window.createTextEditorDecorationType(decorationStyles.trailingSpace)],
	["hardLineBreak", vscode.window.createTextEditorDecorationType({
		backgroundColor: colors["editor.trailingSpace.background"],
		after: fontIcons.reversedPilcrow,
		before: fontIcons.link, // test
	})],
]);

const decorationWorkers: Readonly<Record<DecorationClass, (document: vscode.TextDocument, editor: vscode.TextEditor) => unknown>> = {
	"hardLineBreak": (document: vscode.TextDocument, editor: vscode.TextEditor) => {
		const targetRanges: vscode.Range[] = [];

		for (let i = 0; i < document.lineCount; i++) {
			const line = document.lineAt(i);
			const trailingSpaceLength = line.text.match(/ {2,}$/)?.[0].length;

			if (trailingSpaceLength) {
				targetRanges.push(
					line.range.with(new vscode.Position(i, line.text.length - trailingSpaceLength))
				);
			}
		}

		editor.setDecorations(decorationHandles.get("hardLineBreak")!, targetRanges);
	},
	"paragraph": () => { },
	"trailingSpace": () => { },
};

function updateDecoration(document: vscode.TextDocument): void {
	const editor = vscode.window.activeTextEditor;

	if (!(editor && editor.document === document)) {
		return;
	}

	const target = "hardLineBreak"; // test

	if (vscode.workspace.getConfiguration().get<boolean>(decorationClassConfigMap[target])) {
		if (!decorationHandles.has(target)) {
			decorationHandles.set(target, vscode.window.createTextEditorDecorationType(decorationStyles[target]));
		}

		decorationWorkers[target](document, editor);
	} else {
		decorationHandles.get(target)?.dispose();
		decorationHandles.delete(target);
	}
}

//#endregion Decoration

export function activate(context: vscode.ExtensionContext) {
	console.log('"Playground" is now active!');

	const disposable = [
		vscode.commands.registerCommand("playground.start", () => {
			vscode.window.showInformationMessage('"Playground" is activated!');

			vscode.workspace.onDidChangeTextDocument((e) => updateDecoration(e.document));
		}),
	];

	context.subscriptions.push(...disposable);
}

export function deactivate() { }
```

## `package.json` "contributes"

```json
{
	"colors": [
		{
			"id": "markdown.extension.editor.formattingMark.foreground",
			"description": "Color of formatting marks (paragraphs, hard line breaks, links, etc.) in the Markdown editor.",
			"defaults": {
				"dark": "editorWhitespace.foreground",
				"light": "editorWhitespace.foreground",
				"highContrast": "diffEditor.insertedTextBorder"
			}
		},
		{
			"id": "markdown.extension.editor.trailingSpace.background",
			"description": "Background color of trailing space (U+0020) characters in the Markdown editor.",
			"defaults": {
				"dark": "diffEditor.diagonalFill",
				"light": "diffEditor.diagonalFill",
				"highContrast": "editorWhitespace.foreground"
			}
		}
	],
	"configuration": {
		"title": "Lemming's Playground",
		"properties": {
			"markdown.extension.theming.decoration.renderHardLineBreak": {
				"type": "boolean",
				"default": true,
				"scope": "application"
			}
		}
	},
	"commands": [
		{
			"command": "playground.start",
			"title": "Start Playground ;)"
		}
	]
}
```

**Comment by yzhang-gh** [comment]
That will be great 👍. Do you have any screenshots?

Additionally, do you think it would be better to call it a "[soft return](https://en.wikipedia.org/wiki/Line_wrap_and_word_wrap#Soft_and_hard_returns)"? Just like in Word

![image](https://user-images.githubusercontent.com/7588612/104115924-51831900-534f-11eb-9aed-0ba208bd59d5.png)

**Comment by Lemmingh** [comment]
![2021-01-10_demo](https://user-images.githubusercontent.com/43396014/104119196-d75f8e00-5368-11eb-8a69-2a6756094946.png)

---

> do you think it would be better to call it a "soft return"?

No. I'd like to stick to CommonMark's terms.

**Comment by yzhang-gh** [comment]
Thanks.

I like it that the marker is placed after the whitespace. But I guess we can remove the background color (for whitespace). It looks out of place (distractive).

What is the meaning of reversed pilcrow `⁋`? I haven't seen it before and I can only find this
https://www.quora.com/What-is-the-proper-use-of-a-reverse-pilcrow

> stick to CommonMark's terms.

Interesting (although to me it is a bit counter-intuitive). Anyway, I'm fine with this 👌.

**Comment by Lemmingh** [comment]
> we can remove the background color (for whitespace)

Not a problem. **Each decoration is controlled by a corresponding setting.** We can keep all default to `false`, and let users choose their favorite combination.

---

> What is the meaning of reversed pilcrow

I didn't pay much attention, just found it by cross-reference.

As you've noted, the **Reversed Pilcrow Sign** (U+204B) appears to be designed for RTL.

---

Then, let's **pick some new symbols**.

What was your plan with these arrows? Use them as in Microsoft Word?

* `↵` (U+21B5) Downwards Arrow with Corner Leftwards
* `↓` (U+2193) Downwards Arrow

**Comment by yzhang-gh** [comment]
> What was your plan with these arrows? Use them as in Microsoft Word?

Users will feel familiar when they see it (`↵`), otherwise we need some good reasons why we choose a different one.

**Comment by Lemmingh** [comment]
> Users will feel familiar

Make sense.

* `¶` for [**paragraph**](https://spec.commonmark.org/0.29/#paragraphs).
* `↵` for [**hard line break**](https://spec.commonmark.org/0.29/#hard-line-breaks).

I'm a bit hesitant. See the table below.

---

I installed **Arabic** and **Hebrew** language pack to reveal complex script support in Word.
Interestingly, the paragraph mark is always **pilcrow** (¶) in **Office 365 Version 2012 for Windows**, even if the paragraph direction is RTL.

Besides, the appearance of formatting marks depends on the **preferred authoring language**.

| Mark              | Others | East Asian |
| ----------------- | ------ | ------------- |
| Paragraph         | ¶      | ↵ / ↳         |
| Manual line break | ↵ / ↳  | ↓             |

**Comment by yzhang-gh** [comment]
> Besides, the appearance of formatting marks depends on the **preferred authoring language**.

That's interesting. No wonder why I have a feeling that I have seen `↵` for paragraphs.

I guess we can adopt `¶`-`↵` first (it will be good enough to use) and I doubt whether there will be many people aware of this difference. The pain point is to provide a visual hint for hard line break which is hard to notice. The rest is just the icing on the cake.
