### ISSUE TITLE
Generated Markdown for TOC has too little indentation

### ISSUE THREAD

**Issue by ComFreek** [yzhang-gh/vscode-markdown#899]
## Problem

The TOC generation/update produces "invalid" Markdown syntax (too little indentation) when >= 10 headers are present.

Example:
```
1. [1](#1)
2. [2](#2)
3. [3](#3)
4. [4](#4)
5. [5](#5)
6. [6](#6)
7. [7](#7)
8. [8](#8)
9. [9](#9)
10. [A](#a)
   1. [A.1](#a1)
   2. [A.2](#a2)

# 1
# 2
# 3
# 4
# 5
# 6
# 7
# 8
# 9
# A

## A.1
## A.2
```

Concretely, exactly one space is missing for each A.1 and A.2:

```
10. [A](#a)
   1. [A.1](#a1)
   2. [A.2](#a2)
```
The outcome is that the TOC gets misrendered.
(Note, that in general the number of spaces grows with each magnitude, e.g. for >= 1000 headers, we need three spaces in the subheaders for the >=1000-th headers.)

I am using the latest nightly version as of today (2021-02-11), namely <https://github.com/yzhang-gh/vscode-markdown/actions/runs/515444847>.

## Error message in the console

None

**Comment by yzhang-gh** [comment]
Thanks. Please see [#543](https://github.com/yzhang-gh/vscode-markdown/issues/543#issuecomment-547738217).
