### ISSUE TITLE
second hyperlink in header line is errantly recreated in Table of Contents

### ISSUE THREAD

**Issue by jtmoon79** [yzhang-gh/vscode-markdown#908]
Using _Markdown All in One_ version v3.4.0.

## Problem

Adding an additional hyperlink in a header line causes the printed to Table Of Contents entry with a raw markdown hyperlink.

## How to reproduce

Given the following markdown with two markdown hyperlinks within the header

    # my header1 [link1](http://www.link1.com) [link2](http://www.link2.com)

    hello

Save this in a `.md` file.
From the Command Pallette, run  _Markdown All in One: Create Table of Contents_.  The `link2` is a raw markdown hyperlink

    # my header1 [link1](http://www.link1.com) [link2](http://www.link2.com)

    - [# my header1 link1 [link2](http://www.link2.com)](#-my-header1-link1-link2)

    hello

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Can you please try out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build)? I cannot remember when but it should already be fixed 😅.

**Comment by Lemmingh** [comment]
First, #877

<https://github.com/yzhang-gh/vscode-markdown/blob/882842507032fd575d07bc4604de22b95bd1ffea/src/toc.ts#L632>

Finally, #890

<https://github.com/yzhang-gh/vscode-markdown/blob/51ed4fb04bd1ae70924e5518e33e3b8adb67adda/src/toc.ts#L452-L478>
