### ISSUE TITLE
Create table of contents based on files in a directory

### ISSUE THREAD

**Issue by johnjago** [yzhang-gh/vscode-markdown#912]
## Proposal

There are many plugins for creating a table of contents from headers in a single file. As far as I understand, this plugin has such a feature. However, what I'm looking for is the ability to create a table of contents based on multiple Markdown files in a directory.

For example, if we have the files

```
home.md
docs/
  one.md
  two.md
```

Then creation of a table of contents based on the files would look something like

```markdown
# Table of contents
- [One](one.md)
- [Two](two.md)
```

The title used in the table of contents would be pulled from the first largest heading in the file. This could also have additional options such as nesting all the headings within each file, under each file's entry in the table of contents.

## References

If something like this already exists, let me know! :slightly_smiling_face:

**Comment by yzhang-gh** [comment]
Thanks for the feedback. Let's track this issue at #814.
