### ISSUE TITLE
may I change h1 h2 .... h5 font size, thanks

### ISSUE THREAD

**Issue by iterateself** [yzhang-gh/vscode-markdown#918]
## Proposal

may I change h1 h2 ... h5 font size.

the h5 header font size is too small, it's smaller than normal font size.

![](http://images.iterate.site/blog/image/20210321/gXKjNF98MOtt.png)

thanks.

**Comment by yzhang-gh** [comment]
To do so you need some CSS knowledge. You can have a look at the VS Code [official documentation](https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css) for Markdown.

**Comment by iterateself** [comment]
thank you very much, solved.
