### ISSUE TITLE
Support workspace env variables.

### ISSUE THREAD

**Issue by littleclown** [yzhang-gh/vscode-markdown#919]
## Proposal

I want to use some path aliases to reference the resources in the vscode workspace with absolute paths instead of the unstable relative paths. 

For example, I have two files located at `~/workspace/. resource/image/a.png` and `~/workspace/doc/A/B/C/D/e.md` respectively,
then I want to use`<VSCODE_WORKSPACE>/.resource/image/a.png` instead of `../../../../../../../.resource/image/a.png` to reference the image asset in the `e.md`.

The relative paths are unstabled, because in the follow-up work, I may move the path of these two files at any time, if I use a relative path, the reference may become invalid and what's worse is that it will be hard to correct it . But if I can use an absolute path, it's easy to modify the reference path of the resource file by replacing it globally.

**Comment by yzhang-gh** [comment]
Do you mean you would like to write something like `<WS_ENV>` in the Markdown file and it will be replaced (in the background) before previewing? It changes the syntax of Markdown and looks more like a markdown-it extension (see [here](https://github.com/yzhang-gh/vscode-markdown#q-which-markdown-syntax-is-supported)).

**Comment by Lemmingh** [comment]
Seems not strongly related to the syntax, but, um, a combination of several other issues.

There are indeed some interesting discussions at VuePress.

**Comment by littleclown** [comment]
@yzhang-gh hey, thank you for such a quick response!

Yes, I want to perform variable injection only before the preview, and only want to change the rendering result without affecting the source code. 

I think it is possible to replace variables before being executed by the markdown parser or renderer. Or how do I find the corresponding markdown-it extension (like you mentioned) and how to use it?

**Comment by yzhang-gh** [comment]
> I think it is possible to replace variables before being executed by the markdown parser or renderer.

The Markdown preview is provided by VS Code itself and we cannot preprocess the document. That's why we need a markdown-it extension.

> how do I find the corresponding markdown-it extension

I'm afraid there isn't any markdown-it extension that meets your need. Actually, it makes more sense to
- use Markdown files with `<WS_ENV>` as source files
- write a user script (`.ps1`, `.py` etc.) that performs the replacement and produces the final Markdown files.

because it is just a replacement and doesn't matter it is Markdown or something else.

**Comment by littleclown** [comment]
> I'm afraid there isn't any markdown-it extension that meets your need. Actually, it makes more sense to
> 
> * use Markdown files with `<WS_ENV>` as source files
> * write a user script (`.ps1`, `.py` etc.) that performs the replacement and produces the final Markdown files.
> 
> because it is just a replacement and doesn't matter it is Markdown or something else.

Um, thanks for the advice, but I don't think this can solve my problem. If I do the replacement directly, it is equivalent to using a relative path from the beginning, which is still difficult to fix the path reference invalidation issues caused by the file migration that may happened in the future.

> The relative paths are unstabled, because in the follow-up work, I may move the path of these two files at any time, if I use a relative path, the reference may become invalid and what's worse is that it will be hard to correct it . But if I can use an absolute path, it's easy to modify the reference path of the resource file by replacing it globally.

**Comment by yzhang-gh** [comment]
I meant a build system. You always work on the `src` files (with `<WS_ENV>`) and use a script to produce an `out`/`dist(ribution)` folder for preview. Otherwise you need to write a markdown-it extension. I don't think there will be a ready-to-use one as most of the users don't need it.

**Comment by littleclown** [comment]
Okay, I see what you mean! But this is a little bit troublesome for me, anyway, thanks for your suggestion.
