### ISSUE TITLE
Checkbox collector

### ISSUE THREAD

**Issue by Eoors** [yzhang-gh/vscode-markdown#921]
## Proposal

You can create checkboxes all over a md file, and I would like to collect all of them under one header, like a "ToDo list" header.
It would go through on the whole file and collect all the available checkboxes and list them together. It could help to track the open and closed task all over the file within one section.\
The ticking of the checkbox would work bi-directional, so it does not matter where you tick a checkbox it would be reflected at both location. In can run by using a command, like when we are creating a content. 
Optionally it can show, from which chapter/section the checkbox is coming from.

**Comment by yzhang-gh** [comment]
It sounds too much for Markdown itself. Usually it is a single direction from Markdown to HTML.

The checkboxes are introduced by GitHub (Flavored Markdown) and only work on GitHub. (You cannot tick a checkbox in the VS Code preview tab.)

According to your description, I think [Todo Tree](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree#markdown-support) may meet your need.

**Comment by Eoors** [comment]
Thank you for the quick response. I would not apply it on the preview mode, only in the raw md file. However the suggested extension is working properly in the vs code view! Thanks for the hint, I have not found that one so far :)
