### ISSUE TITLE
Cannot render Katex when VS Code Jupyter notebook is running

### ISSUE THREAD

**Issue by TINGWEIJING** [yzhang-gh/vscode-markdown#923]
## Problem
Katex does not render when there is a Jupyter notebook opened.

![image](https://user-images.githubusercontent.com/55592054/112459265-9c320000-8d98-11eb-89aa-00cf309d4203.png)

## How to reproduce
1. Open any markdown file
2. Open any Jupyter notebook file (.ipynb) in VS Code
3. Try some Katex syntax

## Error message in the console

![image](https://user-images.githubusercontent.com/55592054/112459453-d00d2580-8d98-11eb-8dcc-976d01c7428c.png)

**Comment by yzhang-gh** [comment]
It looks all right on my PC

![image](https://user-images.githubusercontent.com/7588612/112465472-bcb18880-8d9f-11eb-93eb-b52a0434c0d2.png)

And from the screenshot above I cannot see any error message which is related to this extension. Can you try again, e.g., with a clean folder?

**Comment by Lemmingh** [comment]
@TINGWEIJING

You are running **Markdown Preview Enhanced**, which processes math with **its own renderer**.

It's out of our control. **Please consult MPE's documentation**:
<https://shd101wyy.github.io/markdown-preview-enhanced/#/math>

**Comment by yzhang-gh** [comment]
It looks to be the VS Code's built-in preview tab (according to the title) 🤔 Did MPE change it?

**Comment by Lemmingh** [comment]
MPE has its own webview, and its icon is different from VS Code's.

**Judging from the icon of the panel, it should be MPE.**

**Comment by TINGWEIJING** [comment]
I am so sorry.
I was confused with the extension.
