### ISSUE TITLE
Surround selections with quotes

### ISSUE THREAD

**Issue by jasper-zanjani** [yzhang-gh/vscode-markdown#924]
## Proposal

Currently, the extension supports surround with parentheses `(` `)`, square brackets `[` `]`, and backtick.

Selection surround support should also be extended to curly brace `{` `}`, single quote `'`, and double quote `"`.

**Comment by yzhang-gh** [comment]
This is provided by VS Code ('s built-in Markdown support) so we have no good way to change it 😓
https://github.com/microsoft/vscode/blob/700ee37a240d3789dbc093f9e32758f2295ea694/extensions/markdown-basics/language-configuration.json#L36-L42

Related #846 (autoclosing) while this one is "surrounding".

**Comment by jasper-zanjani** [comment]
I submitted [#119982](https://github.com/microsoft/vscode/issues/119982) upstream

**Comment by yzhang-gh** [comment]
I hope so.

**Comment by Lemmingh** [comment]
This was raised there many years ago, but was rejected with "as designed". Not sure whether they can change their minds this time.

**Comment by yzhang-gh** [comment]
Has been fixed by VS Code.
