### ISSUE TITLE
Ability to Easily Toggle a Task List Item

### ISSUE THREAD

**Issue by K4LCIFER** [yzhang-gh/vscode-markdown#925]
## Proposal

It would be really nice to be able to just click or double click (maybe with a keyboard modifier like `<ALT>` for example) a task list item to have it get checked. In addition to this, in the preview pane, a single click on a task list checkbox should toggle it.
Before click or double click:
```markdown
- [ ] item
```
After click or double click
```markdown
- [X] item
```

**Comment by yzhang-gh** [comment]
Due to the limitation of VS Code APIs, it is (almost) impossible to have these features (double-click events, backward edit).

I would suggest using the keyboard shortcut [alt+c](https://github.com/yzhang-gh/vscode-markdown#keyboard-shortcuts) to toggle checkboxes.

**Comment by mrienstra** [comment]
`shd101wyy.markdown-preview-enhanced` ([Marketplace](https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced); [GitHub](https://github.com/shd101wyy/vscode-markdown-preview-enhanced)) has this capability. It relies on `@shd101wyy/mume`, the relevant method is here:
https://github.com/shd101wyy/mume/blob/d1904b9/src/webview.ts#L1278-L1315

---

Here's some clues as to how VS Code handles clicks in the preview webview:

`extensions/markdown-language-features/preview-src/index.ts`:
- [L228-L282](https://github.com/microsoft/vscode/blob/9883eb4a62e920d3fab3a1d2e56c3f25e44a887c/extensions/markdown-language-features/preview-src/index.ts#L228-L282)

`extensions/markdown-language-features/src/preview/preview.ts`:
- [L167-L200](https://github.com/microsoft/vscode/blob/9883eb4a62e920d3fab3a1d2e56c3f25e44a887c/extensions/markdown-language-features/src/preview/preview.ts#L167-L200)
- [L351-L377](https://github.com/microsoft/vscode/blob/9883eb4a62e920d3fab3a1d2e56c3f25e44a887c/extensions/markdown-language-features/src/preview/preview.ts#L351-L377)

---

[`markdown-it-task-lists`](https://github.com/revin/markdown-it-task-lists#usage) (used by this repo) has an `enabled: true` option, which will need to be set if a click-to-toggle feature is added.

**Comment by yzhang-gh** [comment]
Thanks for the information. We only _extend_ the VS Code's built-in Markdown preview rather than provide a standalone one like in the Markdown Preview Enhanced extension. That's why I said there is no available API as we do not want to re-implement it.
