### ISSUE TITLE
indenting the list a list of items with `tab` goes wrong

### ISSUE THREAD

**Issue by nt4f04uNd** [yzhang-gh/vscode-markdown#926]
## Problem

as titled

## How to reproduce

1. have a list of items

```md
1.
2.
3.
```

2. middle mouse all at the beginning (starting from any item, except the 1.)
3. press `tab`

you can see on video what happens (i press `tab` -> `ctrl+z` -> `ctrl+z`)

## Error message in the console

none

https://user-images.githubusercontent.com/39104740/113353836-f148b580-9346-11eb-81f8-395404a4a413.mp4

**Comment by Lemmingh** [comment]
Thank you for your report, but
**what went wrong?**

Looks like you're talking about <https://github.com/yzhang-gh/vscode-markdown/issues/829#issuecomment-702502662>.

**Comment by nt4f04uNd** [comment]
i see this is a duplicate, but could you explain how is that an expected behavior? they simply do not support vscode built-in capability of multi cursor

**Comment by yzhang-gh** [comment]
Please check out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build) 👌

**Comment by Lemmingh** [comment]
> [could you explain how is that an expected behavior?](https://github.com/yzhang-gh/vscode-markdown/issues/926#issuecomment-812563909)

I mean it's too **hard** to figure out **what you were expecting** from [that description](https://github.com/yzhang-gh/vscode-markdown/issues/926#issue-848788226).
