### ISSUE TITLE
markdown render equation of different height in fraction (denominator)

### ISSUE THREAD

**Issue by sirlis** [yzhang-gh/vscode-markdown#927]
See the below figure. Both `sqrt` have the same structure at the denominator. The first `sqrt` is lower than the second one. because there is a `x_ik` in it instead of `x_qk`. (`q` is taller than `i`). This makes it less comfortable to view.

preview:
![image](https://user-images.githubusercontent.com/12960298/113376204-c04a9e00-93a3-11eb-8a75-9eb7a7117f17.png)

=======Steps to Reproduce:
1. open a markdown file.
2. type the following equation
```
$$
sim_c(\boldsymbol x_i,\boldsymbol x_q) = cos(\boldsymbol x_i,\boldsymbol x_q)=\frac{\boldsymbol x_i\cdot \boldsymbol x_q}{\vert\vert\boldsymbol x_i\vert\vert\vert\cdot\vert\boldsymbol x_q\vert\vert} = \frac{\sum_{k=1}^n x_{ik}x_{qk}}{\sqrt{\sum_{k=1}^n x_{ik}^2} \sqrt{\sum_{k=1}^n x_{qk}^2}}
$$
```
3. see the render result

**Comment by yzhang-gh** [comment]
This is rendered by [KaTeX](https://github.com/KaTeX/KaTeX), which is out of our control.

![image](https://user-images.githubusercontent.com/7588612/113379308-bd53ab80-93ab-11eb-95f3-ce2d1f2664ed.png)

**Comment by sirlis** [comment]
> This is rendered by [KaTeX](https://github.com/KaTeX/KaTeX), which is out of our control.
> 
> ![image](https://user-images.githubusercontent.com/7588612/113379308-bd53ab80-93ab-11eb-95f3-ce2d1f2664ed.png)

Thank you.
