### ISSUE TITLE
Extension conflicts with python debugging

### ISSUE THREAD

**Issue by Yajo** [yzhang-gh/vscode-markdown#928]
## Problem

I had a problem with https://github.com/microsoft/vscode-python: it doesn't start debugging my python files.

I ran [extension bisect](https://code.visualstudio.com/blogs/2021/02/16/extension-bisect) and it detected vscode-markdown as the guilty one.

My environment is Fedora 34 Silverblue, working in a [doodba](https://github.com/Tecnativa/doodba) project (based on docker-compose).

## How to reproduce

Well, this is a big project, but you can more or less reproduce it with:

2. Make sure you have docker installed with all its dependencies and configurations. It's not straightforward, check https://docs.docker.com/engine/install/.
3. Install [pipx](https://pipxproject.github.io/pipx/)
4.  Run:

        python3 -m pip install --user pipx
        pipx install docker-compose
        pipx install invoke
        pipx ensurepath
        git clone https://github.com/Yajo/doodba-devel.git -b 12.0 doodba-devel-12.0
        cd doodba-devel-12.0
        invoke img-pull img-build --pull git-aggregate resetdb start
        code doodba.doodba-devel-12.0.code-workspace

    That should let you with a VSCode open, with an environment pretty close to what I'm using.
1. Install both python and markdown all in one extensions.
2. Go to the debugging panel
3. Choose "Start Odoo and debug Python"
4. Hit "start debugging"

5. One task will start, you can check that in the task counter in the status bar. Once it's finished, the debugger should connect within about 20 seconds. I've been waiting for 15 minutes and still not connected.
6. Disable markdown all in one.
7. Reload.
8. Retry.
9. Connects fine.

## Error message in the console

[-1617792584696.log](https://github.com/yzhang-gh/vscode-markdown/files/6270969/-1617792584696.log)

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

According to the log file, there is a conspicuous `kortina.vscode-markdown-notes-0.0.24`. Can you check again with that one disabled? (This name looks so familiar https://github.com/yzhang-gh/vscode-markdown/issues/855#issuecomment-773376295)

**Comment by Yajo** [comment]
I disabled that extension, enabled markdown all-in-one, reloaded window and tried again. The problem still happens, so it seems the guilty one is still markdown all-in-one. 😅

**Comment by yzhang-gh** [comment]
Interesting. The problem is there isn't any error message and I cannot even think of any possible reason. Before we have some clues you can just keep this extension disabled.

**Comment by Lemmingh** [comment]
The log file that you provided (`-1617792584696.log`) said:

Line 25:

```log
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:626  WARN UNRESPONSIVE extension host, 'kortina.vscode-markdown-notes' took 36% of 5360.051ms, saved PROFILE here: 'file:///tmp/exthost-4cd16a.cpuprofile' Array(17)
```

Line 636, 639, 642:

```log
/usr/share/code/resources/app/out/vs/workbench/workbench.desktop.main.js:626  WARN UNRESPONSIVE extension host, 'foam.foam-vscode' took 97% of 23123.118ms, saved PROFILE here: 'file:///tmp/exthost-f465d3.cpuprofile' Array(10)
```

And [**Foam for VSCode** (`foam.foam-vscode`)](https://marketplace.visualstudio.com/items?itemName=foam.foam-vscode) also contributes a markdown-it plugin:
<https://github.com/foambubble/foam/blob/531bdab2504c6bf72a42920b1743c0eadee88316/packages/foam-vscode/package.json#L35>

---

So would you please **disable `foam.foam-vscode`**, and try again?

If the problem still exists, please feel free to [attach a CPU profile](https://markdown-all-in-one.github.io/docs/contributing/performance-issue.html#how-to-report).

**Comment by Yajo** [comment]
OK, disabling Foam and enabling markdown-all-in-one makes debugging work again. The debugger takes about 10 extra seconds to connect, but works at least.

**Comment by Lemmingh** [comment]
Thank you.

---

I also checked the source of `foam.foam-vscode`:
<https://github.com/foambubble/foam/blob/531bdab2504c6bf72a42920b1743c0eadee88316/packages/foam-vscode/src/features/preview-navigation.ts>

**It appears to be very very slow in large workspaces due to the complex resolution strategy of wikilink.**

Then this case should be substantially the same as <https://github.com/yzhang-gh/vscode-markdown/issues/855#issuecomment-773933432>.

---

I guess there is no way to make things better in the foreseeable future, unless we figure out how to get rid of unexpected impacts from external code.

**If needed, you can just disable our product.**

**Comment by Yajo** [comment]
> The debugger takes about 10 extra seconds to connect

I double-checked today. It seems the other day, when I posted this, I was doing some other tasks in parallel that were actually guilty of this slowdown.

Indeed I confirm that disabling Foam makes all work as before. I'll open them an issue.

Thanks for your help and time, and sorry for the confusion.
