### ISSUE TITLE
Extension issue: backspace unavailable to delete while img path autocompleting using the '\'

### ISSUE THREAD

**Issue by xlq57913** [yzhang-gh/vscode-markdown#930]
- Issue Type: `Bug`
- Extension Name: `markdown-all-in-one`
- Extension Version: `3.4.0`
- OS Version: `Darwin x64 20.3.0`
- VS Code version: `1.55.1`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 139,
		"activateCallTime": 8,
		"activateResolvedTime": 15,
		"activationReason": {
			"startup": false,
			"extensionId": {
				"value": "yzhang.markdown-all-in-one",
				"_lower": "yzhang.markdown-all-in-one"
			},
			"activationEvent": "onLanguage:markdown"
		}
	},
	"runtimeErrors": []
}
```

**Comment by yzhang-gh** [comment]
It would be better if you can provide more information (e.g., how to reproduce this issue, what result is expected)

**Comment by yzhang-gh** [comment]
Closing as there isn't enough information for this.
