### ISSUE TITLE
Badges are broken in github/marketplace

### ISSUE THREAD

**Issue by Tyriar** [yzhang-gh/vscode-markdown#932]
vscode

![image](https://user-images.githubusercontent.com/2193314/114420602-51bacc80-9b69-11eb-87cc-b3bb654d105f.png)

github

![image](https://user-images.githubusercontent.com/2193314/114420617-541d2680-9b69-11eb-8b2e-0118f8304dca.png)

marketplace

![image](https://user-images.githubusercontent.com/2193314/114420650-5a130780-9b69-11eb-8ac2-8a42cdbe1e0e.png)

**Comment by yzhang-gh** [comment]
Thank you.

These badges are hosted by [shields.io](https://shields.io/), which runs into problems now 🤔. (I guess many open-source badges are affected)

![image](https://user-images.githubusercontent.com/7588612/114423389-ba498e00-9be9-11eb-9dac-e9e135d3bc3c.png)

**Comment by Lemmingh** [comment]
According to <https://metrics.shields.io/d/aESRBSjmz/services?orgId=1&from=1618236000000&to=1618246800000>,
there appeared to be downtime on `shields.io` from **2021-04-12T15:12:00Z** to **2021-04-12T16:35:00Z**.
They've recovered now.

Thank you.
