### ISSUE TITLE
How to specify the markdown default editor?

### ISSUE THREAD

**Issue by ziqiangxu** [yzhang-gh/vscode-markdown#938]
## Problem

I am not used to the `*Markdown Edit*` provided by this plugin `**Markdown All in one**`. 

If I want to use the built in Editor which is called `*Text Editor*`, I must right click the title of this file which is under editing, and select *`Reopen Editor with ...`* to switch to `*Text Editor*`.
![图片](https://user-images.githubusercontent.com/18530271/115953341-745fc480-a51d-11eb-85f7-491893082b40.png)

So if any way can I config the *`Text Editor`* which is built in as the default editor?
![图片](https://user-images.githubusercontent.com/18530271/115953134-3615d580-a51c-11eb-95b8-b86e36b91610.png)

**Comment by yzhang-gh** [comment]
The `Markdown Edit` is not a part of this extension. You may need to check what other extensions you have installed.

**Comment by ziqiangxu** [comment]
> The `Markdown Edit` is not a part of this extension. You may need to check what other extensions you have installed.
> 
> It is this one I guess: [vscode all markdown](https://marketplace.visualstudio.com/items?itemName=TobiasTao.vscode-md).

Oh yes, you are right. The `Markdown Edit` absolutely be a part of [vscode all markdown](https://marketplace.visualstudio.com/items?itemName=TobiasTao.vscode-md). Thank you！
