### ISSUE TITLE
如何使用katex.macros得到代码提示？

### ISSUE THREAD

**Issue by yfzhao20** [yzhang-gh/vscode-markdown#939]
## Help wanted

我想用’setting.json‘文件中的`markdown.extension.katex.macros`创建片段获得提示，如同我输入`\frac`并按下tab键后，会自动出现`\frac{}{}`，并且光标会出现在第一个花括号中。**我知道通过用户代码片段可以完成这一点，但是我想通过macros来完成，这样这些快捷输入就只能在数学公式环境中被触发。**
当前的macros，例如：
```
markdown.extension.katex.macros:{
"\\iii":"\\mathrm{i}"
}
```
结果是输入`\i`，会有`\iii`的提示，按下tab后，上屏的仍然是`\iii`。这样会带来坏处，就是其他编辑器不认识这个记号，即使是我用vscode的插件markdown preview enhanced他也不认识。

我需要修改哪里，才能使我按下tab后显示的是`\mathrm{i}`？

还是说这样的功能并不能实现？

**Comment by yzhang-gh** [comment]
这与宏的功能是冲突的，宏就是为了引入（直接使用） `\iii` 函数从而不需要写 `\mathrm`

如你所说，这个需求完全正是用户代码片段（只不过加上限制：只想在数学环境中触发），这就超出了这个插件的范畴

**Comment by yfzhao20** [comment]
> 这与宏的功能是冲突的，宏就是为了引入（直接使用） `\iii` 函数从而不需要写 `\mathrm`
> 
> 如你所说，这个需求完全正是用户代码片段（只不过加上限制：只想在数学环境中触发），这就超出了这个插件的范畴


所以这是不是意味着能够触发的macro已经在katex源文件中设定好了🤔

另外请问一下，vscode有没有办法限制其触发环境？

**Comment by yzhang-gh** [comment]
>> 这与宏的功能是冲突的，宏就是为了引入（直接使用） `\iii` 函数从而不需要写 `\mathrm`
>
> 所以这是不是意味着能够触发的 macro 已经在 katex 源文件中设定好了🤔

是指如果定义的是 `\iii` 就**只应该**补全 `\iii`，而不应该补全成 `\mathrm`，否则就不叫宏了

> 另外请问一下，vscode 有没有办法限制其触发环境？

从现状来说应该没办法，自带的 user snippets 功能并不考虑当前的上下文语法。
要达到你的需求的话只能单独写一个插件实现 [completionProvider](https://code.visualstudio.com/api/language-extensions/programmatic-language-features#show-code-completion-proposals)，设定触发字符，判断触发条件，读取你定义的 snippet（并不能称为宏），提供补全。

**Comment by yfzhao20** [comment]
了解了，谢谢！
