### ISSUE TITLE
Issue with triggering comment in math environment

### ISSUE THREAD

**Issue by warpmatrix** [yzhang-gh/vscode-markdown#941]
## Problem

- What went wrong: If I trigger comment in math environment ($$...$$) by typing <kbd>Ctrl</kbd>+<kbd>/</kbd>, the line will be wrapped by the comment in html style, which is `<!-- -->`, and the comment will be showed in the preview.
- Expected behavior: However, it ought to be wrapped by the comment in latex style I guess, which is `%` at the beginning of the line.
- Your environment: The extension version is 3.4.0 with all settings default.

I notice that behaviors in math environment is different from normal environment. For example,  an "itemize" environment doesn't be triggered in math environment. So the issue above can be fixed? Although it is a trivial issues, it will be handier if the issue is fixed.

## How to reproduce

Here is an example:

```md
$$
<!-- html\ comment\ by\ typing\ ctrl+/ -->
% latex comment
$$
```

![preview](https://user-images.githubusercontent.com/43591111/116573595-87203200-a93f-11eb-952b-20b1a1a6a63d.jpg)

Besides, it seems nothing suspicious in the console.

**Comment by yzhang-gh** [comment]
It looks like `embeddedLanguages` can help with this. But we still have a problem: KaTeX is not LaTeX so we shouldn't mark it as LaTeX.

https://github.com/yzhang-gh/vscode-markdown/issues/846#issuecomment-733586401

cc @Lemmingh
