### ISSUE TITLE
The word `restore` in comments corrupts the syntax highlighting of code blocks

### ISSUE THREAD

**Issue by matrix-ranger** [yzhang-gh/vscode-markdown#950]
If you write the word `restore` in comments of a code block, then the syntax highlighting becomes a chaos after this word. This occurs for code blocks of any language.

<img width="219" alt="image" src="https://user-images.githubusercontent.com/48684632/117691331-5c12c980-b1ee-11eb-81d8-dba19c8c7072.png">

**Comment by yzhang-gh** [comment]
The syntax highlight is provided by VS Code ('s built-in extension). You may open an issue in the VS Code main repository.

**Comment by matrix-ranger** [comment]
Sure. I opened an issue there. https://github.com/microsoft/vscode/issues/123489

**Comment by yzhang-gh** [comment]
Thanks.
