### ISSUE TITLE
Extension 'Markdown All in One' Cannot format <document> statusbar error message with GFM formatting disabled

### ISSUE THREAD

**Issue by d0rf3n** [yzhang-gh/vscode-markdown#952]
Could be related to https://github.com/yzhang-gh/vscode-markdown/issues/317 and https://github.com/prettier/prettier-vscode/issues/421, but it's not actually anything that doesn't work in this case. Just an unessecary error.

## Problem

![image](https://user-images.githubusercontent.com/5390970/118118105-c42efe80-b3ec-11eb-8a1e-e43676f3a283.png) shows up in the statusbar when formtting the document with GFM formatting disabled. Enabling it or uninstalling Prettier stop the message from showing. All other formatting works even though the message is shown all the time.

I know that MAiO doesn't do any other formatting, but still the error.

## How to reproduce

Have Prettier and Markdown All in One installed.
Disable markdown GFM formatting in MAiO.

Format file on save or manually.

Message is shown in statusbar.

A simple empty .md file with these settings works for me to reproduce.

## Error message in the console

Couldn't find any relevant outputs anywhere.

**Comment by yzhang-gh** [comment]
I cannot reproduce this issue on my PC (`tableFormatter` is disabled and VS Code is reloaded)

![952](https://user-images.githubusercontent.com/7588612/118119910-a9c34800-b421-11eb-8cb4-b4353a050a9a.gif)

It looks like VS Code still uses MAiO to format the document in your case. I remember there is a way (in VS Code) to select one when there are multiple formatters available. Probably there is something wrong with the cached choice.

**Comment by d0rf3n** [comment]
Is gfm table formatting disabled in markdown all in one using `markdown.extension.tableFormatter.enabled`?

My tables don't format on save or manually with just prettier.

**Comment by d0rf3n** [comment]
I'll try some more when I got time. Maybe a fresh install.

**Comment by yzhang-gh** [comment]
You can try to set Prettier as the default formatter for Markdown.
See https://code.visualstudio.com/updates/v1_33#_default-formatter-selection

Should be something similar to
```json
"[javascript]": {
  "editor.defaultFormatter": "HookyQR.beautify"
}
```

**Comment by d0rf3n** [comment]
That was it, The default formatter was set to markdown all in one, which broke when disabling the table formatter.

Should this happen?

Anyhow this solved the issue for me. Can't remeber setting that myself, but perhaps I did.

You can close this if you don't think it is relevant for any further work.

Thanks for the help! Keep up the good work!

**Comment by yzhang-gh** [comment]
😉
