### ISSUE TITLE
\ket not showing properly

### ISSUE THREAD

**Issue by NeoFantom** [yzhang-gh/vscode-markdown#953]
My vscode now can't compile `\ket` command, it just shows a red `\ket` original command in the compiled md preview. Why is that? I thought KaTeX supported this command?
![image](https://user-images.githubusercontent.com/38828722/118983430-03da8500-b9af-11eb-9376-62bafcafa952.png)

**Comment by NeoFantom** [comment]
Is this because I did not install some dependent packages such as KaTeX? I really do not understand how this works, e.g. do I need to manually install KaTeX

**Comment by yzhang-gh** [comment]
Thanks for the feedback. I guess it is because we are using an older version of KaTeX. You can check out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).

#943

**Comment by NeoFantom** [comment]
> Thanks for the feedback. I guess it is because we are using an older version of KaTeX. You can check out the [dev build](https://github.com/yzhang-gh/vscode-markdown#latest-development-build).
> 
> #943

I really cannot understand how to download dev build from the link you offered, don't understand GitHub workflows. Can you give me some guidance?

**Comment by yzhang-gh** [comment]
It happens that the dependabot made a PR 3 days ago so the latest GitHub action didn't make a dev build 😅

Just go to https://github.com/yzhang-gh/vscode-markdown/actions/runs/873932957 (the second latest one) and download the artifacts.

**Comment by NeoFantom** [comment]
Any plan when to make this latest dev build official?

**Comment by yzhang-gh** [comment]
We still have some work to do but it won't be long, I guess. (#966)
