### ISSUE TITLE
Dollar enclose

### ISSUE THREAD

**Issue by irvnriir** [yzhang-gh/vscode-markdown#963]
## Problem
Why to hell .

![Screenshot](https://user-images.githubusercontent.com/13949704/121455364-d5d7d780-c993-11eb-8be0-75fa402115b6.png)

**Comment by yzhang-gh** [comment]
Not sure what you want to ask. It is called [math](https://github.com/yzhang-gh/vscode-markdown#math) environment. You can disable `markdown.extension.math.enabled` if you don't need it.

**Comment by irvnriir** [comment]
what specification defines that ? a tag selection is very inconvenient (`$<<variable name>>` in many languages, and `<<number>>$` for Currency) . thanks for the setting, it solved my issue .

**Comment by yzhang-gh** [comment]
It is a popular syntax extension to Markdown (inspired by LaTeX I believe). You can find more information at #955 if curious.
