### ISSUE TITLE
Markdown+Math macros affected by this extension ...

### ISSUE THREAD

**Issue by goessner** [yzhang-gh/vscode-markdown#967]
... as is reproducable by 

https://github.com/goessner/mdmath/issues/114

After disabeling your extension, Markdown+Math works as expected.

I would be glad, if you have a short look into this ... might be possibly a name collision ... thanks

--
sg

**Comment by Lemmingh** [comment]
Thank you for reporting.

From the original issue <https://github.com/goessner/mdmath/issues/114#issuecomment-863528298>:

```
"markdown.extension.math.enabled": false, //<- This fixes the macro issue
```

So, it's expected behavior.

As documented, setting `math.enabled` to `false` stops **Markdown All in One** from processing math rendering.

**Comment by Lemmingh** [comment]
Well, the collision:

`math_block` and `math_inline`

<https://github.com/yzhang-gh/markdown-it-katex/blob/c77efb25e3e5eb3367b45077cc7c1473908fedc1/index.js#L195-L196>
<https://github.com/goessner/markdown-it-texmath/blob/61e637f2155801f7a5bf61acac492d5365368036/texmath.js#L225>

---

I do not think any change to `markdown-it-katex` or `markdown-it-texmath` could or should land.

When multiple markdown-it plugins with the same goal are loaded at the same time, the result is mostly unpredictable.

The product of #570 is practical and sufficient:

> Be sure to disable `math.enabled` option of this extension.

---

BTW, you might be interested in <https://github.com/microsoft/vscode/issues/124783>. Fortunately, they also have a `math.enabled` option.

**Comment by yzhang-gh** [comment]
@goessner Thanks for reaching out.

As @Lemmingh said, it is expected as the document (math blocks) should not be processed by two extensions at the same time. We already provided a `math.enabled` option on our side. So I don't think there are other changes needed.

**Comment by Lemmingh** [comment]
@goessner
<https://markdown-all-in-one.github.io/docs/guide/compatibility.html> now has a dedicated explanation. You can reference it in your FAQ.
