### ISSUE TITLE
Enable extension for virtual workspaces

### ISSUE THREAD

**Issue by plof27** [yzhang-gh/vscode-markdown#971]
## Proposal
Previously, Markdown All in One worked like a charm with virutal workspaces like [Microsoft's Live Share extension](https://marketplace.visualstudio.com/items?itemName=MS-vsliveshare.vsliveshare). With the recent April 2021 update, the extension no longer works because it hasn't been "activated" for virtual workspaces.

![image](https://user-images.githubusercontent.com/8202612/123525782-df05bb80-d698-11eb-8653-4444cdcc2a22.png)

**Comment by Lemmingh** [comment]
Duplicate of #948
