### ISSUE TITLE
spacings are off

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [yzhang-gh/vscode-markdown#973]
the markdown preview is hard to read. new lines and headers are not well spaced. 
it's all too compressed. How do I change it?

**Comment by yzhang-gh** [comment]
You can choose a Markdown preview style extension (e.g. [Markdown Preview GitHub Styling](https://marketplace.visualstudio.com/items?itemName=bierner.markdown-preview-github-styles)).

Or you can use your own style files, which require some knowledge about CSS.

Please see the VS Code's docs for details:
https://code.visualstudio.com/docs/languages/markdown#_extending-the-markdown-preview

**Comment by hp8wvvvgnj6asjm7** [comment]
thanks =)
