### ISSUE TITLE
"... (command 'markdown.extension.toc.create' not found)" et.al.

### ISSUE THREAD

**Issue by ethzero** [yzhang-gh/vscode-markdown#975]
## Problem
**What went wrong?**
When accessing any of the Markdown All In One commands, 'command not found' is returned.

**Expected behavior?**
Commands are found :)

## How to reproduce
* CTRL+ALT+P 
* Markdown All in One: Create Table of Contents
... or any Markdown All in One command.

## Error message in the console
No reported console issues.

## Screenshot
<img src="https://user-images.githubusercontent.com/357538/123956024-28f4e700-d9a2-11eb-8d7b-84dbbc445134.png" width="75%">

## Attempted resolutions
* Followed FAQ advise, as per 'Q: Error "command 'markdown.extension.onXXXKey' not found"'
* Disable/Enable extension
* Uninstall/Re-install extension
* Downgraded extension

**Comment by ethzero** [comment]
Answerign by own 'issue'.

Apparently one language profile was overriding another, in this case the NGINX extension (with somewhat similar highlighting) was overriding Markdown for the file README.md.txt:
```
    "files.associations": {
        "*.md.txt": "markdown",
        "**/nginx/*/*": "NGINX"
    },
```

I guess the extension functions are not loaded if the file type does match. Shame the error looks like the entire extension is broken rather than a more useful "This isn't a Markdown file!".

**Comment by yzhang-gh** [comment]
Thanks.

> I guess the extension functions are not loaded if the file type does match. Shame the error looks like the entire extension is broken rather than a more useful "This isn't a Markdown file!".

You are right. But it is kind of strange as the "Create TOC" command should have not appeared in the command palette if this extension was loaded.

**Comment by Lemmingh** [comment]
Commands do appear in the Command Palette as soon as an extension is enabled.

The `enablement` property can generally hide/dim commands when they are supposed to be unavailable.

🤔 Not sure whether I discussed it with you before. If I did, I should have asked for help because the clause for `enablement` confused me.

**Comment by yzhang-gh** [comment]
https://code.visualstudio.com/api/extension-guides/command#enablement-of-commands

Looks like we do need `enablement` ("Editor and explorer context menus render enablement/disablement items while the Command Palette filters them.")

**Comment by Lemmingh** [comment]
Yes, we need, to avoid confusion.

The problem is I have seen many contexts, such as `editorLangId` and `resourceLangId`. I'm not sure how to combine them in the `enablement` clause.

**Comment by yzhang-gh** [comment]
It looks that the `editorLangId` is specific to an editor, while `resourceLangId` can be also applied to the Explorer (context menu). I think we can just go for `editorLangId` here. (We don't have to care too much about the potential corner cases which are very rare.)
