### ISSUE TITLE
onBackspace error

### ISSUE THREAD

**Issue by fredgrott** [yzhang-gh/vscode-markdown#976]
The latest stable build and VSCODEInsiders 1.58.0 produce the onBackspace error.

The workaround is to install the latest dev build.

and the fix works as planned no onbackspace errors and do not have delete key shortcut bindings etc

**Comment by Lemmingh** [comment]
Would you please describe the procedure in more detail？

I cannot reproduce it, and guess it's caused by the delay of extension loading, just like previous similar reports.

## My environment

VS Code:

```
Version: 1.58.0-insider (system setup)
Commit: 57930758db9e2c83f59b9ee1851400bd16192d32
Date: 2021-06-30T05:14:00.370Z
Electron: 12.0.12
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043
```

Markdown All in One:

3.4.0 (stable)
