### ISSUE TITLE
Auto completion in math causes `\` to disappear

### ISSUE THREAD

**Issue by dualer** [yzhang-gh/vscode-markdown#980]
## Problem

当使用`\`触发自动补全, 例如`\alp`, 会出现候选词, 选择其中任意候选词, 例如`\alpha`, `\`会缺失, 开始我以为是和`Markdown+Math`插件冲突了, 但是我将该插件`disable`后, 问题仍然存在. 

环境: win10
## How to reproduce
![Video_20210712103121 mp4_20210712_105402](https://user-images.githubusercontent.com/85242539/125235573-41a3bc00-e315-11eb-9d46-25033742e1ac.gif)

## Error message in the console

无

**Comment by Lemmingh** [comment]
可以提供更详细的复现步骤吗？比如文档上下文，键入过程。

按照你现在的描述，我实现了无法触发 completion。😂

**Comment by dualer** [comment]
> 可以提供更详细的复现步骤吗？比如文档上下文，键入过程。
> 
> 按照你现在的描述，我实现了无法触发 completion。😂

突然又可以了, 这个不用上下文吧, 比如想键入$\alpha$, 输入`$\alp$`后, 应该第一个候选词就是`\alpha`, 然后回车就行了. 不清楚怎么回事, 经常会有这种问题, 选择候选词后, 会丢失掉前面的`\`, 但等段时间后突然又没问题了.

**Comment by yzhang-gh** [comment]
> 按照你现在的描述，我实现了无法触发 completion。😂

目前应该只能在输入 `\` 时触发补全，中途不行。印象里之前有人想修改一下，但是造成了其它问题，就不了了之了

**Comment by dualer** [comment]
现在又出现这个问题了, 我录了屏
![Video_20210712103121 mp4_20210712_105402](https://user-images.githubusercontent.com/85242539/125224610-87a25500-e300-11eb-960b-b6391fa323eb.gif)

**Comment by yzhang-gh** [comment]
怀疑是你还用了其它的补全插件有冲突，比如 IntelliCode

**Comment by dualer** [comment]
> 怀疑是你还用了其它的补全插件有冲突，比如 IntelliCode

是的. 我把Markdown Notes插件关了，就没问题了，这个插件似乎调用了IntelliCode引擎
