### ISSUE TITLE
auto-number math equations

### ISSUE THREAD

**Issue by dualer** [yzhang-gh/vscode-markdown#984]
## Proposal

是否能增加方程自动计数的功能? 例如像[链接](https://stackoverflow.com/questions/52939909/how-can-i-auto-number-math-equations-in-rmarkdown)中这样.

**Comment by yzhang-gh** [comment]
参见 #904。简而言之，这需要添加额外的语法，KaTeX 目前做不到，而对于本插件来说太超范围了。
