### ISSUE TITLE
Inserts into html: From extension vscode.markdown-math

### ISSUE THREAD

**Issue by tik9** [yzhang-gh/vscode-markdown#986]
Everytime I `convert a md file` to html with `Markdown all in one` I get on top of the html: `/* From extension vscode.markdown-math */` followed by css starting with `@font-face{font-family:KaTeX`. How can I avoid it?

**Comment by yzhang-gh** [comment]
https://code.visualstudio.com/updates/v1_58#_math-formula-rendering-in-the-markdown-preview

`vscode.markdown-math` is a new VS Code _built-in_ extension introduced in v1.58. You can set `"markdown.math.enabled": false` to disable this feature.

Note that this extension also provides basic math support, but we only include related CSS if there is any valid math block in your document.

**Comment by tik9** [comment]
ok, I have no math block in my [text](https://github.com/tik9/tik9.github.io/blob/master/README.md), but the extension is there on [Line 8](https://github.com/tik9/tik9.github.io/blob/master/README.html#L8).

**Comment by yzhang-gh** [comment]
Not sure whether the above configuration solves your problem. You can also totally disable it with

<img src="https://user-images.githubusercontent.com/7588612/125751139-a882fcf1-0fe6-4f04-85fc-aaabf0c3ad45.png" width="365" alt="disable markdown-math">
