### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by clydebaron2000** [yzhang-gh/vscode-markdown#989]
- Issue Type: `Bug`
- Extension Name: `markdown-all-in-one`
- Extension Version: `3.4.0`
- OS Version: `Windows_NT x64 10.0.19042`
- VS Code version: `1.58.2`

:warning: We have written the needed data into your clipboard. Please paste! :warning:
```json 
{
	"messages": [],
	"activationTimes": {
		"codeLoadingTime": 46,
		"activateCallTime": 21,
		"activateResolvedTime": 0,
		"activationReason": {
			"startup": true,
			"extensionId": {
				"value": "yzhang.markdown-all-in-one",
				"_lower": "yzhang.markdown-all-in-one"
			},
			"activationEvent": "workspaceContains:README.md"
		}
	},
	"runtimeErrors": []
}
```

**Comment by yzhang-gh** [comment]
Please provide more information (e.g., what is the problem; how to reproduce it)
