### ISSUE TITLE
lineHeight setting doesn't apply in task's list

### ISSUE THREAD

**Issue by csalv5** [yzhang-gh/vscode-markdown#99]
vscode-markdown task list ignores "markdown.preview.lineHeight" setting. 

Steps:
- Set "markdown.preview.lineHeight" to another value
- Task list's line height is unaware of this change.

EDIT: the list must be separated by an newline, for example: 
```
- [ ] one 
- [ ] two

- [ ] new task
```
Is there any error message in the console?
No.

**Comment by Lemmingh** [comment]
I can't make heads or tails of your description.

I guess you were facing **the restriction of the CSS Box Model**.

---

You example compiles to

```html
<ul class="contains-task-list">
    <li class="task-list-item code-line" data-line="0">
        <p data-line="0" class="code-line"><input class="task-list-item-checkbox" disabled="" type="checkbox"> one</p>
    </li>
    <li class="task-list-item code-line" data-line="1">
        <p data-line="1" class="code-line"><input class="task-list-item-checkbox" disabled="" type="checkbox"> two</p>
    </li>
    <li class="task-list-item code-line" data-line="3">
        <p data-line="3" class="code-line"><input class="task-list-item-checkbox" disabled="" type="checkbox"> new task</p>
    </li>
</ul>
```

Notice those `<input type="checkbox">` elements.
https://developer.mozilla.org/en-US/docs/Learn/Forms/Property_compatibility_table_for_form_controls
