### ISSUE TITLE
Can't type unicode character

### ISSUE THREAD

**Issue by tynguyen2k1** [yzhang-gh/vscode-markdown#990]
## Problem

Can't type unicode character:

https://user-images.githubusercontent.com/64082226/125995942-8299ea5e-4e95-44a4-a1db-80ecfb999615.mp4

## How to reproduce
I'm not sure. It happens when I try to type unicode character.

## Error message in the console

No error message in the console.

**Comment by yzhang-gh** [comment]
Thanks for the feedback.

Please see https://github.com/yzhang-gh/vscode-markdown/issues/617#issuecomment-585629661 and #41.
