### ISSUE TITLE
Toggle/Disable Real-time/Live Markdown Preview Updating

### ISSUE THREAD

**Issue by FruitSausage** [yzhang-gh/vscode-markdown#991]
Is there a feature to toggle real-time preview updating, or better to only update on save like LaTeX?  For long files full of KaTeX math, real-time preview updating can significantly slow down the editor.  I have tried regularly closing/reopening the preview as a workaround, but this steals focus from the editor.

**Comment by Lemmingh** [comment]
No. I'm sorry.

The preview is from VS Code. They only listen to changes:
<https://github.com/microsoft/vscode/blob/54a2e15f6bf459a07e7da4178074ed143e2e251c/extensions/markdown-language-features/src/features/preview.ts#L154-L162>

But this sounds reasonable. What about opening an issue at their repo?
<https://github.com/microsoft/vscode/labels/markdown>

**Comment by FruitSausage** [comment]
Thanks for linking the exact code.

I've opened an issue here:
https://github.com/microsoft/vscode/issues/129252

**Comment by yzhang-gh** [comment]
Thanks

**Comment by FruitSausage** [comment]
After updating VSCode earlier to 1.60, I also encountered this issue:

https://github.com/yzhang-gh/vscode-markdown/issues/1010

which made me realize having both the built-in math renderer and Markdown All in One's running at the same time was the cause of a lot of the preview update slowness I've been having.  Disabling the built-in preview extension as mentioned here:

https://github.com/yzhang-gh/vscode-markdown/issues/1008

fixed the syntax highlighting and improved the preview speed.  I see the issues with having both renderers running at the same time is mentioned here:

https://markdown-all-in-one.github.io/docs/guide/compatibility.html#rendering-for-math-in-the-markdown-preview

but @Lemmingh @yzhang-gh would it be possible to mention the conflict on the extension marketplace page?

**Comment by yzhang-gh** [comment]
We were planning a major update (v3.5.0) but I won't have enough time until the end of this year.

Probably we can make a patch (v3.4.1) including only fixes for several issues (e.g. #1010).

**Comment by Lemmingh** [comment]
I'll mention the docs in the README.

Let's move the discussion about release to #966
