### ISSUE TITLE
Ignore from TOC

### ISSUE THREAD

**Issue by ridvanaltun** [yzhang-gh/vscode-markdown#994]
## Proposal

I think we need ability to ignore some titles from auto inserted TOC.

**Comment by yzhang-gh** [comment]
Please check out [Three ways to control which headings are present in the TOC](https://github.com/yzhang-gh/vscode-markdown#table-of-contents).

**Comment by ridvanaltun** [comment]
> Please check out [Three ways to control which headings are present in the TOC](https://github.com/yzhang-gh/vscode-markdown#table-of-contents).

It is what I am looking for, thanks.
