### ISSUE TITLE
Config option to never include first level one header in the TOC

### ISSUE THREAD

**Issue by majkinetor** [yzhang-gh/vscode-markdown#997]
## Proposal

Markdown documents often have first header as the name of the document, then all other subheaders are under it. This leads to TOC that is always completely under the the first header which looks bad so one always needs to put `omit in toc` above first header.  

100% of my documents are like this:

```
<!-- omit in ToC -->
# Document title

## section 1

## section 2

### section 2.1
...
...
```

It would be great to have this is an option, disabled by default.

* [ ] Never include first _level one_ header in the TOC<br>

In situation when one has this option enabled and still wants to include it in the ToC, the one can ad hoc use `<h1>title</h1>` instead of changing options. This is what I use now sometimes instead of `<!-- omit in ToC -->` when I can't remember its spelling :) The problem with h1 is that other team members are confused why this header is differently treated or can even revert it, but as ad-hoc temporary solution is perfectly OK.

**Comment by yzhang-gh** [comment]
Please check out `markdown.extension.toc.levels` (which can also be configured per folder).

**Comment by majkinetor** [comment]
Thats it, I set it to 2..6 and it works OK. 
I misunderstood that option. Thanks a lot.
