### ISSUE TITLE
默认快捷键冲突解决优化

### ISSUE THREAD

**Issue by heartacker** [yzhang-gh/vscode-markdown#999]
## Proposal
https://github.com/yzhang-gh/vscode-markdown/issues/995 
经过讨论之后，发现大家还是更加喜欢未选中就直接可以触发 **加粗** _斜体_ 等。
这就和快捷键冲突。`ctrl+b` 和`ctrl+i`
今天还发现还有一个快捷键是冲突的。
`ctrl+m` 和触发公式环境

![image](https://user-images.githubusercontent.com/1876302/130319095-bd9179f2-a149-4658-a278-4ca85e94e53b.png)

## References

还发现，可以用`alt+s` 触发删除。

那么为么解决快捷键冲突问题，我们是否可以将快捷键做以下更正，以减少快捷键冲突。
`ctrl+b`-->`alt+b` bold

`ctrl+i`-->`alt+i` italic

`ctrl+m`-->`alt+m` math

`alt+s` ok   

另外，还可以添加
 `alt+l` togglelist
`alt+~ ` togglecode block

使用alt 键都不会 和默认键盘冲突

**Comment by yzhang-gh** [comment]
还是如之前所说，没有一个让所有人都满意的设置（总会有冲突的）

选择目前的 `ctrl` 类快捷键的理由很充足，例如这和其它非常多编辑器相同 (Word, Typora and almost any editor you can think of)，甚至 GitHub 评论框，更不论要考虑如此多用户的历史习惯

而且 `alt` 也并不是不会产生冲突，比如 https://github.com/yzhang-gh/vscode-markdown/issues/404

对于一个百万级用户量的插件，`ctrl+b` 尚且只有 15 个 👍，应该不难推测目前快捷键的 <正 / 中立 vs. 反> 支持者比例吧

（暂且关闭这个 issue，让大家分流到 `ctrl+b` 和 `ctrl+i` 或者 `ctrl+m` 各自的 issue 中投票）
